import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { Href, router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, SafeAreaView, Share, StyleSheet, Text, View } from 'react-native';
import { CATALOGUE_NAMES, MUSLIM_NAMES, VERIFIED_NAMES } from '../../features/muslim-names/data';
import type { NameGender } from '../../features/muslim-names/types';
import { ChoiceChip, EditorialPill, ScreenHeader, StatusPill, prenomTheme } from '../../features/muslim-names/ui';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';

function pick(pool:number[],except?:number){if(!pool.length)return 0;if(pool.length===1)return pool[0];let x=pool[Math.floor(Math.random()*pool.length)];while(x===except)x=pool[Math.floor(Math.random()*pool.length)];return x;}
export default function DiscoverScreen(){
  const [verifiedOnly,setVerifiedOnly]=useState(true);
  const initial=useMemo(()=>{const first=VERIFIED_NAMES[Math.floor(Math.random()*VERIFIED_NAMES.length)];return MUSLIM_NAMES.findIndex(x=>x.id===first.id);},[]);const [index,setIndex]=useState(initial);const [gender,setGender]=useState<'all'|NameGender>('all');const item=MUSLIM_NAMES[index];
  const poolIndexes=(g=gender,verified=verifiedOnly)=>MUSLIM_NAMES.map((x,i)=>({x,i})).filter(({x})=>(g==='all'||x.gender===g)&&(!verified||x.editorialLevel!=='catalogue')).map(({i})=>i);
  const shuffle=()=>setIndex(pick(poolIndexes(),index));
  const setG=(g:'all'|NameGender)=>{setGender(g);setIndex(pick(poolIndexes(g,verifiedOnly)));};
  const setQuality=(verified:boolean)=>{setVerifiedOnly(verified);setIndex(pick(poolIndexes(gender,verified)));};
  const share=()=>Share.share({message:`${item.name}${item.arabic?` — ${item.arabic}`:''}\n${item.meaning}\n\nDécouvert dans OUMMAH`});
  return <LinearGradient colors={[colors.background,colors.backgroundSecondary,colors.background]} style={styles.screen}><SafeAreaView style={styles.safe}><ScreenHeader title="Surprends-moi" onBack={()=>router.back()}/><View style={styles.content}>
    <Text style={styles.eyebrow}>DÉCOUVERTE</Text><Text style={styles.title}>Un prénom, au hasard</Text><Text style={styles.subtitle}>Laissez-vous surprendre, puis ouvrez la fiche si un prénom attire votre attention.</Text>
    <View style={styles.filters}><ChoiceChip label="Tous" active={gender==='all'} onPress={()=>setG('all')}/><ChoiceChip label="Garçons" active={gender==='boy'} onPress={()=>setG('boy')}/><ChoiceChip label="Filles" active={gender==='girl'} onPress={()=>setG('girl')}/></View>{CATALOGUE_NAMES.length?<View style={styles.filters}><ChoiceChip label="Fiches vérifiées" icon="shield-checkmark-outline" active={verifiedOnly} onPress={()=>setQuality(true)}/><ChoiceChip label="Inclure le catalogue" icon="library-outline" active={!verifiedOnly} onPress={()=>setQuality(false)}/></View>:null}
    <View style={[styles.card,{borderColor:item.gender==='boy'?'rgba(110,181,255,.55)':'rgba(242,166,199,.55)',backgroundColor:item.gender==='boy'?'rgba(86,155,235,.08)':'rgba(231,126,174,.08)'}]}><View style={styles.spark}><Ionicons name="sparkles" size={18} color={colors.goldLight}/></View>{item.arabic?<Text style={styles.arabic}>{item.arabic}</Text>:null}<Text style={styles.name}>{item.name}</Text><Text style={styles.translit}>{item.transliteration}</Text>{item.editorialLevel==='catalogue'?<EditorialPill item={item}/>:<StatusPill status={item.status}/>}<View style={styles.line}/><Text style={styles.meaning}>{item.meaning}</Text><Text style={styles.origin}>{item.origin.join(' · ')}</Text></View>
    <Pressable onPress={shuffle} style={styles.primary}><Ionicons name="shuffle" size={18} color={colors.background}/><Text style={styles.primaryText}>Un autre prénom</Text></Pressable>
    <View style={styles.secondaryRow}><Pressable onPress={()=>router.push(`/prenoms/${item.id}` as Href)} style={styles.secondary}><Ionicons name="document-text-outline" size={17} color={colors.goldLight}/><Text style={styles.secondaryText}>Voir la fiche</Text></Pressable><Pressable onPress={()=>void share()} style={styles.secondary}><Ionicons name="share-outline" size={17} color={colors.goldLight}/><Text style={styles.secondaryText}>Partager</Text></Pressable></View>
    <Text style={styles.disclaimer}>La découverte aléatoire ne classe pas les prénoms par mérite. Consultez la fiche pour comprendre le statut et les nuances.</Text>
  </View></SafeAreaView></LinearGradient>;
}
const styles=StyleSheet.create({screen:{flex:1},safe:{flex:1},content:{flex:1,padding:16,paddingBottom:28},eyebrow:{color:colors.goldLight,fontFamily:typography.sans,fontSize:9,fontWeight:'800',letterSpacing:1.4},title:{marginTop:5,color:colors.text,fontFamily:typography.sans,fontSize:25,fontWeight:'800'},subtitle:{marginTop:5,color:colors.textSecondary,fontFamily:typography.sans,fontSize:11.5,lineHeight:18},filters:{marginTop:16,flexDirection:'row',gap:8,flexWrap:'wrap'},card:{marginTop:18,flex:1,minHeight:350,maxHeight:470,padding:24,borderRadius:30,borderWidth:1,borderColor:prenomTheme.borderGold,backgroundColor:prenomTheme.cardStrong,alignItems:'center',justifyContent:'center'},spark:{position:'absolute',top:18,right:18,width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:prenomTheme.goldWash},arabic:{color:colors.goldLight,fontFamily:typography.arabic,fontSize:48,lineHeight:68,textAlign:'center'},name:{marginTop:8,color:colors.text,fontFamily:typography.sans,fontSize:29,fontWeight:'800'},translit:{marginTop:4,marginBottom:13,color:colors.textMuted,fontFamily:typography.sans,fontSize:11.5},line:{marginVertical:17,width:54,height:1,backgroundColor:colors.borderSoft},meaning:{maxWidth:290,color:colors.textSecondary,fontFamily:typography.sans,fontSize:14,lineHeight:21,textAlign:'center'},origin:{marginTop:8,color:colors.textMuted,fontFamily:typography.sans,fontSize:9.5},primary:{marginTop:14,minHeight:52,borderRadius:17,backgroundColor:colors.goldLight,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},primaryText:{color:colors.background,fontFamily:typography.sans,fontSize:12,fontWeight:'900'},secondaryRow:{marginTop:9,flexDirection:'row',gap:9},secondary:{flex:1,minHeight:48,borderRadius:16,borderWidth:1,borderColor:colors.borderSoft,backgroundColor:prenomTheme.card,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},secondaryText:{color:colors.text,fontFamily:typography.sans,fontSize:11,fontWeight:'700'},disclaimer:{marginTop:12,color:colors.textMuted,fontFamily:typography.sans,fontSize:9.5,lineHeight:14,textAlign:'center'}});
