import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { categoryById, topicById } from "../../features/fiqh/fiqhData";
import { colors } from "../../theme/colors";

export default function FiqhCategory() {
  const { categoryId } = useLocalSearchParams<{ categoryId: string }>();
  const category = categoryById.get(categoryId);
  const [selectedId, setSelectedId] = useState("");
  if (!category) return <SafeAreaView style={s.screen}><Text style={s.text}>Catégorie introuvable.</Text></SafeAreaView>;
  const chapters = category.chapters ?? [];
  if (!chapters.length) return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => router.back()}><Text style={s.back}>‹ Retour</Text></Pressable><Text style={s.kicker}>CATÉGORIE</Text><Text style={s.title}>{category.title}</Text><Text style={s.intro}>{category.summary}</Text>{category.topicIds.map((id) => { const topic = topicById.get(id); return <Pressable key={id} onPress={() => router.push(`/fiqh/topic/${id}`)} style={s.row}><View style={s.rowCopy}><Text style={s.rowTitle}>{topic?.title ?? id}</Text>{topic ? <Text style={s.rowText}>{topic.summary}</Text> : null}</View><Ionicons name="chevron-forward" size={19} color={colors.goldLight} /></Pressable>; })}</ScrollView></SafeAreaView>;
  const activeId = selectedId || chapters[0].id;
  const activeChapter = chapters.find((chapter) => chapter.id === activeId)!;
  return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => router.back()}><Text style={s.back}>‹ Retour</Text></Pressable><Text style={s.kicker}>LIVRE DE FIQH</Text><Text style={s.title}>{category.title}</Text><Text style={s.arabic}>{category.arabicTitle}</Text><Text style={s.intro}>Un parcours progressif pour étudier les notions documentées de la prière.</Text><Text style={s.count}>{category.topicIds.length} sujets · {chapters.length} chapitres</Text><Text style={s.sectionTitle}>Table des matières</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rail}>{chapters.map((chapter, index) => { const active = chapter.id === activeId; return <Pressable key={chapter.id} onPress={() => setSelectedId(chapter.id)} style={[s.chapter, active && s.chapterActive]}><Text style={s.number}>{String(index + 1).padStart(2, "0")}</Text><Text style={s.chapterTitle}>{chapter.title}</Text><Text style={s.chapterCount}>{chapter.topicIds.length} sujet{chapter.topicIds.length > 1 ? "s" : ""}</Text><Ionicons name="arrow-forward" size={16} color={colors.goldLight} /></Pressable>; })}</ScrollView><Text style={s.activeLabel}>Chapitre sélectionné : {activeChapter.title}</Text><View style={s.preview}><Text style={s.previewKicker}>CHAPITRE {String(chapters.indexOf(activeChapter) + 1).padStart(2, "0")}</Text><Text style={s.previewTitle}>{activeChapter.title}</Text>{activeChapter.topicIds.map((id) => { const topic = topicById.get(id); return topic ? <Pressable key={id} onPress={() => router.push({ pathname: "/fiqh/topic/[topicId]", params: { topicId: id, chapter: activeChapter.id } })} style={s.previewRow}><Text style={s.rowTitle}>{topic.title}</Text><Ionicons name="chevron-forward" size={18} color={colors.goldLight} /></Pressable> : null; })}<Pressable onPress={() => router.push({ pathname: "/fiqh/chapter/[chapterId]", params: { chapterId: activeChapter.id } })} style={s.openButton}><Text style={s.openText}>Ouvrir le chapitre</Text><Ionicons name="arrow-forward" size={16} color={colors.goldLight} /></Pressable></View></ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: 22, paddingBottom: 60 }, back: { color: colors.goldLight, fontSize: 18, marginBottom: 27 }, kicker: { color: colors.goldLight, fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { color: colors.text, fontSize: 34, fontWeight: "800", marginTop: 7 }, arabic: { color: colors.goldLight, fontSize: 25, marginTop: 4 }, intro: { color: colors.textSecondary, fontSize: 16, lineHeight: 24, marginTop: 12 }, count: { color: colors.textMuted, fontSize: 13, marginTop: 10 }, sectionTitle: { color: colors.goldLight, fontSize: 14, fontWeight: "800", letterSpacing: 1, marginTop: 28, marginBottom: 10 }, rail: { gap: 10, paddingRight: 38, paddingBottom: 4 }, chapter: { width: 180, minHeight: 132, padding: 15, borderRadius: 17, backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.goldDark }, chapterActive: { borderColor: colors.goldLight, backgroundColor: colors.surface }, number: { color: colors.goldLight, fontSize: 12, fontWeight: "800" }, chapterTitle: { color: colors.text, fontSize: 18, fontWeight: "800", marginTop: 16 }, chapterCount: { color: colors.textSecondary, fontSize: 13, marginTop: 7, marginBottom: 10 }, activeLabel: { color: colors.textSecondary, fontSize: 13, marginTop: 12 }, preview: { marginTop: 10, padding: 17, borderRadius: 17, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderSoft }, previewKicker: { color: colors.goldLight, fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, previewTitle: { color: colors.text, fontSize: 24, fontWeight: "800", marginTop: 6, marginBottom: 8 }, previewRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 12, borderTopWidth: 1, borderTopColor: colors.borderSoft }, openButton: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 12, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.borderSoft }, openText: { color: colors.goldLight, fontSize: 14, fontWeight: "800" }, row: { flexDirection: "row", alignItems: "center", paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: colors.borderSoft }, rowCopy: { flex: 1 }, rowTitle: { color: colors.text, fontSize: 17, fontWeight: "700" }, rowText: { color: colors.textSecondary, fontSize: 13, marginTop: 4 }, text: { color: colors.text } });
