export const AL_FATIHA_WORDS = [
  "بِسْمِ",
  "اللَّهِ",
  "الرَّحْمَٰنِ",
  "الرَّحِيمِ",
  "الْحَمْدُ",
  "لِلَّهِ",
  "رَبِّ",
  "الْعَالَمِينَ",
  "الرَّحْمَٰنِ",
  "الرَّحِيمِ",
  "مَالِكِ",
  "يَوْمِ",
  "الدِّينِ",
  "إِيَّاكَ",
  "نَعْبُدُ",
  "وَإِيَّاكَ",
  "نَسْتَعِينُ",
  "اهْدِنَا",
  "الصِّرَاطَ",
  "الْمُسْتَقِيمَ",
  "صِرَاطَ",
  "الَّذِينَ",
  "أَنْعَمْتَ",
  "عَلَيْهِمْ",
  "غَيْرِ",
  "الْمَغْضُوبِ",
  "عَلَيْهِمْ",
  "وَلَا",
  "الضَّالِّينَ",
] as const;

export const AL_FATIHA_VERSES = [
  AL_FATIHA_WORDS.slice(0, 4),
  AL_FATIHA_WORDS.slice(4, 8),
  AL_FATIHA_WORDS.slice(8, 10),
  AL_FATIHA_WORDS.slice(10, 13),
  AL_FATIHA_WORDS.slice(13, 17),
  AL_FATIHA_WORDS.slice(17, 20),
  AL_FATIHA_WORDS.slice(20, 29),
] as const;
