-- OUMMAH Hadith source identity.
-- source_hadith_id is copied only from an official source. It is never generated
-- by OUMMAH and is not the internal Hadith identifier.

alter table public.hadiths
  add column if not exists source_hadith_id text;

alter table public.hadiths
  drop constraint if exists hadiths_source_hadith_id_requires_version;
alter table public.hadiths
  add constraint hadiths_source_hadith_id_requires_version
  check (source_hadith_id is null or source_version_id is not null);

-- The source identity is unique only within a documentary source version.
-- NULL source_hadith_id values are intentionally excluded from this index.
create unique index if not exists hadiths_source_version_source_hadith_id_key
  on public.hadiths(source_version_id, source_hadith_id)
  where source_hadith_id is not null;

create or replace function public.prevent_hadith_source_hadith_id_change()
returns trigger
language plpgsql
as $$
declare
  justification text;
  evidence text;
begin
  if old.source_hadith_id is not null
     and new.source_hadith_id is distinct from old.source_hadith_id then
    raise exception 'source_hadith_id is immutable once documented';
  end if;

  if old.source_hadith_id is null and new.source_hadith_id is not null then
    justification := nullif(btrim(current_setting('hadith.source_hadith_id_justification', true)), '');
    evidence := nullif(btrim(current_setting('hadith.source_hadith_id_evidence', true)), '');

    if justification is null or evidence is null then
      raise exception 'Adding source_hadith_id requires documentary justification and evidence';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists hadith_source_hadith_id_immutable on public.hadiths;
create trigger hadith_source_hadith_id_immutable
before update of source_hadith_id on public.hadiths
for each row execute function public.prevent_hadith_source_hadith_id_change();

comment on column public.hadiths.source_hadith_id is
  'Stable identifier supplied by the official source, nullable, never generated by OUMMAH, and immutable after documentary assignment.';
