-- OUMMAH — surveillance automatique des alertes
-- Exécution horaire avec pg_cron et push critique via pg_net.

create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

create table if not exists public.admin_alert_settings (
  alert_type text primary key,
  enabled boolean not null default true,
  critical_push_enabled boolean not null default true,
  label text not null,
  description text not null,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_alert_monitor_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running'
    check (status in ('running', 'success', 'failed')),
  open_alerts_before integer not null default 0,
  open_alerts_after integer not null default 0,
  new_critical_alerts integer not null default 0,
  push_requests_sent integer not null default 0,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists admin_alert_monitor_runs_started_idx
on public.admin_alert_monitor_runs(started_at desc);

alter table public.admin_alert_settings enable row level security;
alter table public.admin_alert_monitor_runs enable row level security;

revoke all on public.admin_alert_settings from anon, authenticated;
revoke all on public.admin_alert_monitor_runs from anon, authenticated;

alter table public.admin_system_alerts
  add column if not exists push_notified_at timestamptz;

insert into public.admin_alert_settings (
  alert_type,
  enabled,
  critical_push_enabled,
  label,
  description
)
values
  (
    'revenuecat_webhook_silent',
    true,
    true,
    'Webhook RevenueCat silencieux',
    'Alerte lorsqu’aucun événement RevenueCat Production n’est reçu depuis plus de 24 heures.'
  ),
  (
    'revenuecat_unlinked_subscription',
    true,
    true,
    'Abonnement non relié',
    'Alerte lorsqu’un abonnement Production n’est associé à aucun compte OUMMAH.'
  ),
  (
    'revenuecat_refund',
    true,
    false,
    'Remboursement RevenueCat',
    'Alerte lorsqu’un remboursement Production est reçu.'
  ),
  (
    'revenuecat_billing_issue',
    true,
    true,
    'Incident de paiement',
    'Alerte lorsqu’un abonnement actif rencontre un incident de paiement.'
  ),
  (
    'wasil_consumption_spike',
    true,
    true,
    'Consommation Wasil anormale',
    'Alerte lorsqu’un utilisateur pose un volume inhabituel de questions Wasil.'
  ),
  (
    'manual_premium_expiring',
    true,
    false,
    'Premium manuel bientôt expiré',
    'Alerte sept jours avant l’expiration d’un Premium offert.'
  ),
  (
    'wasil_zero_credit',
    true,
    false,
    'Utilisateur à zéro crédit',
    'Alerte lorsqu’un utilisateur actif atteint un solde Wasil nul.'
  )
on conflict (alert_type)
do update set
  label = excluded.label,
  description = excluded.description;

create or replace function public.admin_alert_type_enabled(
  p_alert_type text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select setting.enabled
      from public.admin_alert_settings setting
      where setting.alert_type = p_alert_type
    ),
    true
  );
$$;

create or replace function public.admin_alert_setting_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.admin_alert_type_enabled(new.alert_type) then
    return null;
  end if;

  return new;
end;
$$;

drop trigger if exists admin_alert_setting_guard_trigger
on public.admin_system_alerts;

create trigger admin_alert_setting_guard_trigger
before insert or update
on public.admin_system_alerts
for each row
execute function public.admin_alert_setting_guard();

-- Autorise le cron PostgreSQL à exécuter le moteur.
create or replace function public.admin_refresh_system_alerts()
returns void
language plpgsql
security definer
set search_path = public, auth
as $function$
declare
  row_data record;
  last_production_event timestamptz;
begin
  if not public.is_oummah_admin()
    and current_user not in ('postgres', 'service_role')
  then
    raise exception 'ADMIN_FORBIDDEN';
  end if;

  if to_regclass('public.revenuecat_webhook_events') is not null then
    select max(received_at)
    into last_production_event
    from public.revenuecat_webhook_events
    where environment = 'PRODUCTION'
      and event_type <> 'TEST';

    if last_production_event is not null
      and last_production_event < now() - interval '24 hours'
    then
      perform public.admin_upsert_detected_alert(
        'revenuecat_webhook_silent',
        'revenuecat:webhook:production-silent',
        'warning',
        'Webhook RevenueCat silencieux',
        'Aucun événement RevenueCat Production reçu depuis plus de 24 heures.',
        jsonb_build_object(
          'last_production_event', last_production_event
        )
      );
    end if;
  end if;

  if to_regclass('public.revenuecat_customer_subscriptions') is not null then
    for row_data in
      select
        app_user_id,
        product_id,
        store,
        expiration_at,
        latest_event_type
      from public.revenuecat_customer_subscriptions
      where user_id is null
        and environment = 'PRODUCTION'
        and latest_event_type <> 'TEST'
    loop
      perform public.admin_upsert_detected_alert(
        'revenuecat_unlinked_subscription',
        'revenuecat:unlinked:' || row_data.app_user_id || ':' || row_data.product_id,
        'critical',
        'Abonnement Production non relié',
        'Un abonnement RevenueCat Production n’est associé à aucun compte OUMMAH.',
        jsonb_build_object(
          'app_user_id', row_data.app_user_id,
          'product_id', row_data.product_id,
          'store', row_data.store,
          'expiration_at', row_data.expiration_at,
          'latest_event_type', row_data.latest_event_type
        )
      );
    end loop;

    for row_data in
      select
        app_user_id,
        product_id,
        user_id,
        billing_issue_detected_at,
        expiration_at
      from public.revenuecat_customer_subscriptions
      where environment = 'PRODUCTION'
        and latest_event_type <> 'TEST'
        and active = true
        and billing_issue_detected_at is not null
    loop
      perform public.admin_upsert_detected_alert(
        'revenuecat_billing_issue',
        'revenuecat:billing:' || row_data.app_user_id || ':' || row_data.product_id,
        'critical',
        'Incident de paiement RevenueCat',
        'Un abonnement actif rencontre un incident de paiement.',
        jsonb_build_object(
          'app_user_id', row_data.app_user_id,
          'product_id', row_data.product_id,
          'user_id', row_data.user_id,
          'billing_issue_detected_at', row_data.billing_issue_detected_at,
          'expiration_at', row_data.expiration_at
        )
      );
    end loop;
  end if;

  if to_regclass('public.revenuecat_webhook_events') is not null then
    for row_data in
      select
        event_id,
        app_user_id,
        product_id,
        price_usd,
        currency,
        received_at
      from public.revenuecat_webhook_events
      where environment = 'PRODUCTION'
        and event_type = 'REFUND'
        and received_at >= now() - interval '30 days'
    loop
      perform public.admin_upsert_detected_alert(
        'revenuecat_refund',
        'revenuecat:refund:' || row_data.event_id,
        'warning',
        'Remboursement RevenueCat reçu',
        'Un achat ou abonnement RevenueCat a été remboursé.',
        jsonb_build_object(
          'event_id', row_data.event_id,
          'app_user_id', row_data.app_user_id,
          'product_id', row_data.product_id,
          'price_usd', row_data.price_usd,
          'currency', row_data.currency,
          'received_at', row_data.received_at
        )
      );
    end loop;
  end if;

  if to_regclass('public.analytics_events') is not null then
    for row_data in
      select
        analytics.user_id,
        account.email,
        count(*) filter (
          where analytics.created_at >= now() - interval '10 minutes'
        )::integer as questions_10m,
        count(*) filter (
          where analytics.created_at >= now() - interval '1 hour'
        )::integer as questions_1h,
        count(*) filter (
          where analytics.created_at >= now() - interval '24 hours'
        )::integer as questions_24h
      from public.analytics_events analytics
      left join auth.users account on account.id = analytics.user_id
      where analytics.event_name = 'wasil_question'
        and analytics.created_at >= now() - interval '24 hours'
      group by analytics.user_id, account.email
      having
        count(*) filter (
          where analytics.created_at >= now() - interval '10 minutes'
        ) >= 12
        or count(*) filter (
          where analytics.created_at >= now() - interval '1 hour'
        ) >= 35
        or count(*) >= 150
    loop
      perform public.admin_upsert_detected_alert(
        'wasil_consumption_spike',
        'wasil:spike:' || row_data.user_id::text || ':'
          || to_char(now() at time zone 'UTC', 'YYYY-MM-DD'),
        case
          when row_data.questions_10m >= 20
            or row_data.questions_1h >= 60
            or row_data.questions_24h >= 250
          then 'critical'::public.admin_alert_severity
          else 'warning'::public.admin_alert_severity
        end,
        'Consommation Wasil anormale',
        'Un utilisateur présente une fréquence de questions Wasil inhabituelle.',
        jsonb_build_object(
          'user_id', row_data.user_id,
          'email', row_data.email,
          'questions_10m', row_data.questions_10m,
          'questions_1h', row_data.questions_1h,
          'questions_24h', row_data.questions_24h
        )
      );
    end loop;
  end if;

  if to_regclass('public.premium_manual_grants') is not null then
    for row_data in
      select
        grant_row.user_id,
        account.email,
        grant_row.ends_at
      from public.premium_manual_grants grant_row
      left join auth.users account on account.id = grant_row.user_id
      where grant_row.active = true
        and grant_row.ends_at > now()
        and grant_row.ends_at <= now() + interval '7 days'
    loop
      perform public.admin_upsert_detected_alert(
        'manual_premium_expiring',
        'premium:expiring:' || row_data.user_id::text || ':'
          || row_data.ends_at::date::text,
        'info',
        'Premium manuel bientôt expiré',
        'Un accès Premium offert arrive à expiration sous 7 jours.',
        jsonb_build_object(
          'user_id', row_data.user_id,
          'email', row_data.email,
          'ends_at', row_data.ends_at
        )
      );
    end loop;
  end if;

  if to_regclass('public.wasil_wallets') is not null then
    for row_data in
      select
        wallet.user_id,
        account.email,
        wallet.total_spent,
        wallet.updated_at
      from public.wasil_wallets wallet
      left join auth.users account on account.id = wallet.user_id
      where wallet.balance = 0
        and wallet.total_spent > 0
        and wallet.updated_at >= now() - interval '7 days'
      order by wallet.updated_at desc
      limit 100
    loop
      perform public.admin_upsert_detected_alert(
        'wasil_zero_credit',
        'wasil:zero-credit:' || row_data.user_id::text || ':'
          || row_data.updated_at::date::text,
        'info',
        'Utilisateur à zéro crédit Wasil',
        'Un utilisateur ayant déjà consommé des crédits vient d’atteindre un solde nul.',
        jsonb_build_object(
          'user_id', row_data.user_id,
          'email', row_data.email,
          'total_spent', row_data.total_spent,
          'wallet_updated_at', row_data.updated_at
        )
      );
    end loop;
  end if;
end;
$function$;

create or replace function public.admin_push_new_critical_alerts()
returns integer
language plpgsql
security definer
set search_path = public, auth, net
as $$
declare
  messages jsonb;
  alerts_to_mark uuid[];
  request_id bigint;
begin
  if to_regclass('public.user_push_tokens') is null
    or to_regclass('public.oummah_admin_users') is null
  then
    return 0;
  end if;

  select
    jsonb_agg(
      jsonb_build_object(
        'to', token.expo_push_token,
        'title', 'Alerte critique OUMMAH',
        'body', alert_row.title,
        'sound', 'default',
        'channelId', 'oummah-admin',
        'data', jsonb_build_object(
          'route', '/admin/alerts',
          'alertId', alert_row.id
        )
      )
    ),
    array_agg(distinct alert_row.id)
  into messages, alerts_to_mark
  from public.admin_system_alerts alert_row
  join public.admin_alert_settings setting
    on setting.alert_type = alert_row.alert_type
  cross join public.user_push_tokens token
  join public.oummah_admin_users admin_user
    on admin_user.user_id = token.user_id
  where alert_row.status = 'open'
    and alert_row.severity = 'critical'
    and alert_row.push_notified_at is null
    and setting.enabled = true
    and setting.critical_push_enabled = true
    and token.enabled = true;

  if messages is null or jsonb_array_length(messages) = 0 then
    return 0;
  end if;

  select net.http_post(
    url := 'https://exp.host/--/api/v2/push/send',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Accept', 'application/json'
    ),
    body := messages,
    timeout_milliseconds := 10000
  )
  into request_id;

  update public.admin_system_alerts
  set
    push_notified_at = now(),
    updated_at = now()
  where id = any(alerts_to_mark);

  return jsonb_array_length(messages);
end;
$$;

create or replace function public.run_admin_alert_monitor()
returns void
language plpgsql
security definer
set search_path = public, auth, net
as $$
declare
  run_id bigint;
  before_count integer;
  after_count integer;
  critical_before integer;
  critical_after integer;
  push_count integer := 0;
begin
  select count(*)
  into before_count
  from public.admin_system_alerts
  where status = 'open';

  select count(*)
  into critical_before
  from public.admin_system_alerts
  where status = 'open'
    and severity = 'critical';

  insert into public.admin_alert_monitor_runs (
    status,
    open_alerts_before
  )
  values (
    'running',
    before_count
  )
  returning id into run_id;

  begin
    perform public.admin_refresh_system_alerts();

    select count(*)
    into after_count
    from public.admin_system_alerts
    where status = 'open';

    select count(*)
    into critical_after
    from public.admin_system_alerts
    where status = 'open'
      and severity = 'critical';

    push_count := public.admin_push_new_critical_alerts();

    update public.admin_alert_monitor_runs
    set
      status = 'success',
      finished_at = now(),
      open_alerts_after = after_count,
      new_critical_alerts = greatest(critical_after - critical_before, 0),
      push_requests_sent = push_count
    where id = run_id;
  exception
    when others then
      update public.admin_alert_monitor_runs
      set
        status = 'failed',
        finished_at = now(),
        error_message = sqlerrm
      where id = run_id;

      raise;
  end;
end;
$$;

create or replace function public.admin_run_alert_monitor_now()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_oummah_admin() then
    raise exception 'ADMIN_FORBIDDEN';
  end if;

  perform public.run_admin_alert_monitor();
end;
$$;

create or replace function public.admin_get_alert_monitor_health()
returns jsonb
language plpgsql
security definer
set search_path = public, auth, cron
as $$
declare
  last_run public.admin_alert_monitor_runs%rowtype;
  last_success_at timestamptz;
  last_failure_at timestamptz;
  cron_enabled boolean := false;
  cron_schedule text;
  calculated_status text;
begin
  if not public.is_oummah_admin() then
    raise exception 'ADMIN_FORBIDDEN';
  end if;

  select *
  into last_run
  from public.admin_alert_monitor_runs
  order by started_at desc
  limit 1;

  select max(finished_at)
  into last_success_at
  from public.admin_alert_monitor_runs
  where status = 'success';

  select max(finished_at)
  into last_failure_at
  from public.admin_alert_monitor_runs
  where status = 'failed';

  select
    job.active,
    job.schedule
  into cron_enabled, cron_schedule
  from cron.job job
  where job.jobname = 'oummah-admin-alert-monitor-hourly'
  limit 1;

  calculated_status :=
    case
      when last_run.id is null then 'never_run'
      when last_run.status = 'failed' then 'critical'
      when last_run.started_at < now() - interval '2 hours' then 'critical'
      when coalesce(cron_enabled, false) = false then 'warning'
      else 'healthy'
    end;

  return jsonb_build_object(
    'status', calculated_status,
    'last_run_at', last_run.started_at,
    'last_success_at', last_success_at,
    'last_failure_at', last_failure_at,
    'last_error', last_run.error_message,
    'cron_enabled', coalesce(cron_enabled, false),
    'cron_schedule', cron_schedule,
    'runs_24h', (
      select count(*)
      from public.admin_alert_monitor_runs
      where started_at >= now() - interval '24 hours'
    ),
    'failures_24h', (
      select count(*)
      from public.admin_alert_monitor_runs
      where started_at >= now() - interval '24 hours'
        and status = 'failed'
    )
  );
end;
$$;

create or replace function public.admin_list_alert_settings()
returns table (
  alert_type text,
  enabled boolean,
  critical_push_enabled boolean,
  label text,
  description text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_oummah_admin() then
    raise exception 'ADMIN_FORBIDDEN';
  end if;

  return query
  select
    setting.alert_type,
    setting.enabled,
    setting.critical_push_enabled,
    setting.label,
    setting.description,
    setting.updated_at
  from public.admin_alert_settings setting
  order by setting.label asc;
end;
$$;

create or replace function public.admin_update_alert_setting(
  p_alert_type text,
  p_enabled boolean,
  p_critical_push_enabled boolean
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_oummah_admin() then
    raise exception 'ADMIN_FORBIDDEN';
  end if;

  update public.admin_alert_settings
  set
    enabled = p_enabled,
    critical_push_enabled =
      case when p_enabled then p_critical_push_enabled else false end,
    updated_by = auth.uid(),
    updated_at = now()
  where alert_type = p_alert_type;

  if not found then
    raise exception 'ADMIN_ALERT_SETTING_NOT_FOUND';
  end if;

  if not p_enabled then
    update public.admin_system_alerts
    set
      status = 'ignored',
      ignored_at = now(),
      handled_by = auth.uid(),
      handling_note = 'Type d’alerte désactivé',
      updated_at = now()
    where alert_type = p_alert_type
      and status = 'open';
  end if;
end;
$$;

-- Remplace proprement l'ancien job s'il existe.
do $$
declare
  existing_job_id bigint;
begin
  select jobid
  into existing_job_id
  from cron.job
  where jobname = 'oummah-admin-alert-monitor-hourly'
  limit 1;

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;
end
$$;

select cron.schedule(
  'oummah-admin-alert-monitor-hourly',
  '0 * * * *',
  $cron$select public.run_admin_alert_monitor();$cron$
);

revoke all on function public.admin_alert_type_enabled(text) from public;
revoke all on function public.admin_push_new_critical_alerts() from public;
revoke all on function public.run_admin_alert_monitor() from public;
revoke all on function public.admin_run_alert_monitor_now() from public;
revoke all on function public.admin_get_alert_monitor_health() from public;
revoke all on function public.admin_list_alert_settings() from public;
revoke all on function public.admin_update_alert_setting(
  text,
  boolean,
  boolean
) from public;

grant execute on function public.admin_run_alert_monitor_now()
to authenticated;
grant execute on function public.admin_get_alert_monitor_health()
to authenticated;
grant execute on function public.admin_list_alert_settings()
to authenticated;
grant execute on function public.admin_update_alert_setting(
  text,
  boolean,
  boolean
) to authenticated;

-- Premier contrôle immédiat pour initialiser la santé du moteur.
select public.run_admin_alert_monitor();

notify pgrst, 'reload schema';
