-- OUMMAH — statistiques avancées fiables
-- L'activité est collectée à partir de l'installation de cette version.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid()
    references auth.users(id) on delete cascade,
  event_name text not null
    check (event_name in ('screen_view', 'wasil_question', 'app_open')),
  module text not null
    check (
      module in (
        'home',
        'quran',
        'audio',
        'hadith',
        'dua',
        'dhikr',
        'mosques',
        'qibla',
        'goals',
        'calendar',
        'profile',
        'wasil',
        'premium',
        'other'
      )
    ),
  route text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_idx
on public.analytics_events(created_at desc);

create index if not exists analytics_events_user_created_idx
on public.analytics_events(user_id, created_at desc);

create index if not exists analytics_events_module_created_idx
on public.analytics_events(module, created_at desc);

alter table public.analytics_events enable row level security;

drop policy if exists "Users can insert their analytics events"
on public.analytics_events;

create policy "Users can insert their analytics events"
on public.analytics_events
for insert
to authenticated
with check (
  user_id = auth.uid()
  and created_at <= now() + interval '5 minutes'
);

grant insert on public.analytics_events to authenticated;
revoke select, update, delete on public.analytics_events
from anon, authenticated;

create or replace function public.admin_get_analytics(
  p_days integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  safe_days integer;
  overview_value jsonb;
  daily_value jsonb;
  modules_value jsonb;
begin
  if not public.is_oummah_admin() then
    raise exception 'ADMIN_FORBIDDEN';
  end if;

  safe_days := least(greatest(coalesce(p_days, 30), 7), 90);

  select jsonb_build_object(
    'users_total', (
      select count(*)
      from auth.users
    ),
    'new_users_today', (
      select count(*)
      from auth.users
      where created_at >= date_trunc('day', now())
    ),
    'active_1d', (
      select count(distinct user_id)
      from public.analytics_events
      where created_at >= now() - interval '1 day'
    ),
    'active_7d', (
      select count(distinct user_id)
      from public.analytics_events
      where created_at >= now() - interval '7 days'
    ),
    'active_30d', (
      select count(distinct user_id)
      from public.analytics_events
      where created_at >= now() - interval '30 days'
    ),
    'wasil_1d', (
      select count(*)
      from public.analytics_events
      where event_name = 'wasil_question'
        and created_at >= now() - interval '1 day'
    ),
    'wasil_7d', (
      select count(*)
      from public.analytics_events
      where event_name = 'wasil_question'
        and created_at >= now() - interval '7 days'
    ),
    'wasil_30d', (
      select count(*)
      from public.analytics_events
      where event_name = 'wasil_question'
        and created_at >= now() - interval '30 days'
    ),
    'credits_spent_lifetime', (
      select coalesce(sum(total_spent), 0)
      from public.wasil_wallets
    )
  )
  into overview_value;

  with days as (
    select generate_series(
      date_trunc('day', now()) - make_interval(days => safe_days - 1),
      date_trunc('day', now()),
      interval '1 day'
    )::date as day
  ),
  aggregate_events as (
    select
      created_at::date as day,
      count(distinct user_id) as active_users,
      count(*) filter (
        where event_name = 'screen_view'
      ) as screen_views,
      count(*) filter (
        where event_name = 'wasil_question'
      ) as wasil_questions
    from public.analytics_events
    where created_at >=
      date_trunc('day', now()) - make_interval(days => safe_days - 1)
    group by created_at::date
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'day', days.day,
        'active_users', coalesce(events.active_users, 0),
        'screen_views', coalesce(events.screen_views, 0),
        'wasil_questions', coalesce(events.wasil_questions, 0)
      )
      order by days.day asc
    ),
    '[]'::jsonb
  )
  into daily_value
  from days
  left join aggregate_events events
    on events.day = days.day;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'module', ranked.module,
        'opens', ranked.opens,
        'unique_users', ranked.unique_users
      )
      order by ranked.opens desc
    ),
    '[]'::jsonb
  )
  into modules_value
  from (
    select
      module,
      count(*) filter (
        where event_name = 'screen_view'
      ) as opens,
      count(distinct user_id) as unique_users
    from public.analytics_events
    where created_at >= now() - make_interval(days => safe_days)
    group by module
    having count(*) filter (
      where event_name = 'screen_view'
    ) > 0
    order by opens desc
    limit 20
  ) ranked;

  return jsonb_build_object(
    'overview', overview_value,
    'daily', daily_value,
    'modules', modules_value
  );
end;
$$;

revoke all on function public.admin_get_analytics(integer) from public;
grant execute on function public.admin_get_analytics(integer)
to authenticated;

notify pgrst, 'reload schema';
