export type NameGender = "male" | "female";
export type NameEntry = { id: string; name: string; arabic?: string; gender: NameGender; meaning: string; origin: string; tags?: string[] };

type Seed = [string, string, string, string, string?, string[]?];
const male: Seed[] = [
  ["Adam","آدم","Homme, être humain","Arabe / coranique","Adam"],["Adel","عادل","Juste, équitable","Arabe"],["Ahmad","أحمد","Le plus digne de louanges","Arabe / coranique"],["Ali","علي","Élevé, noble","Arabe / islamique"],["Amin","أمين","Digne de confiance","Arabe"],["Anas","أنس","Affection, amitié","Arabe"],["Ayman","أيمن","Béni, fortuné","Arabe"],["Bilal","بلال","Eau, fraîcheur","Arabe / islamique"],["Dawud","داود","Bien-aimé","Arabe / coranique","Dawud"],["Faris","فارس","Cavalier, chevalier","Arabe"],["Hamza","حمزة","Fort, ferme","Arabe / islamique"],["Hassan","حسن","Beau, bon","Arabe / islamique"],["Hatem","حاتم","Juge, généreux","Arabe"],["Ibrahim","إبراهيم","Nom d’un prophète","Arabe / coranique","Ibrahim"],["Idris","إدريس","Nom d’un prophète","Arabe / coranique","Idris"],["Ilyas","إلياس","Nom d’un prophète","Arabe / coranique","Ilyas"],["Imran","عمران","Prospérité, construction","Arabe / coranique"],["Isa","عيسى","Nom d’un prophète","Arabe / coranique","Isa"],["Ismail","إسماعيل","Dieu entend","Arabe / coranique","Ismail"],["Jalil","جليل","Majestueux, noble","Arabe"],["Karim","كريم","Généreux, noble","Arabe / coranique"],["Khalil","خليل","Ami intime","Arabe"],["Malik","مالك","Roi, maître","Arabe"],["Marwan","مروان","Pierre dure, silex","Arabe"],["Moussa","موسى","Nom d’un prophète","Arabe / coranique","Moussa"],["Mustapha","مصطفى","Choisi, élu","Arabe"],["Nabil","نبيل","Noble, distingué","Arabe"],["Nadir","نادر","Rare, précieux","Arabe"],["Nuh","نوح","Nom d’un prophète","Arabe / coranique","Nuh"],["Omar","عمر","Vie, longévité","Arabe / islamique"],["Rayan","ريان","Abreuvé, luxuriant","Arabe / islamique"],["Said","سعيد","Heureux, chanceux","Arabe"],["Salim","سليم","Sain, paisible","Arabe"],["Sami","سامي","Élevé, sublime","Arabe"],["Sofyan","سفيان","Rapide, léger","Arabe"],["Souleyman","سليمان","Homme de paix","Arabe / coranique","Souleyman"],["Taha","طه","Nom mentionné dans le Coran","Arabe / coranique","Taha"],["Yacine","يس","Nom mentionné dans le Coran","Arabe / coranique","Yacine"],["Yahya","يحيى","Il vit, vivant","Arabe / coranique","Yahya"],["Yassir","ياسر","Aisé, facile","Arabe"],["Younes","يونس","Nom d’un prophète","Arabe / coranique","Younes"],["Yusuf","يوسف","Dieu ajoutera","Arabe / coranique","Yusuf"],["Zakaria","زكريا","Dieu s’est souvenu","Arabe / coranique","Zakaria"],["Zayd","زيد","Croissance, abondance","Arabe / islamique"],["Zayn","زين","Beauté, grâce","Arabe"]
];
const female: Seed[] = [
  ["Aaliyah","عالية","Élevée, noble","Arabe"],["Aïcha","عائشة","Vivante, pleine de vie","Arabe / islamique"],["Amina","آمنة","En sécurité, paisible","Arabe"],["Aya","آية","Signe, verset","Arabe / coranique"],["Basma","بسمة","Sourire","Arabe"],["Bouchra","بشرى","Bonne nouvelle","Arabe / coranique"],["Dalia","دالية","Vigne, branche","Arabe"],["Dounia","دنيا","Monde, vie présente","Arabe"],["Duaa","دعاء","Invocation","Arabe"],["Farah","فرح","Joie","Arabe"],["Hafsa","حفصة","Jeune lionne","Arabe / islamique"],["Hana","هناء","Bonheur, félicité","Arabe"],["Hiba","هبة","Don, cadeau","Arabe"],["Hind","هند","Nom arabe ancien","Arabe"],["Imane","إيمان","Foi","Arabe"],["Inaya","عناية","Soin, attention","Arabe"],["Jana","جنى","Récolte, fruit du paradis","Arabe / coranique"],["Jasmine","ياسمين","Jasmin","Arabe"],["Kawtar","كوثر","Abondance","Arabe / coranique"],["Khadija","خديجة","Nom arabe ancien","Arabe / islamique"],["Lamia","لامية","Aux lèvres délicates","Arabe"],["Leïla","ليلى","Nuit","Arabe"],["Lina","لينة","Tendre, délicate","Arabe / coranique"],["Mariam","مريم","Nom d’une femme honorée dans le Coran","Arabe / coranique","Mariam"],["Maya","مايا","Nom traditionnel, sens variable","Arabe"],["Nadia","نادية","Rosée, généreuse","Arabe"],["Nour","نور","Lumière","Arabe / coranique"],["Rania","رانيا","Celle qui regarde avec attention","Arabe"],["Rim","ريم","Gazelle blanche","Arabe"],["Safiya","صفية","Pure, choisie","Arabe / islamique"],["Salma","سلمى","Paisible, saine","Arabe"],["Samia","سامية","Élevée, sublime","Arabe"],["Sara","سارة","Princesse, joie","Arabe / coranique"],["Siham","سهام","Flèches","Arabe"],["Soumaya","سمية","Élevée, distinguée","Arabe / islamique"],["Tasnim","تسنيم","Source du paradis","Arabe / coranique"],["Warda","وردة","Rose","Arabe"],["Yasmin","ياسمين","Jasmin","Arabe"],["Zahra","زهراء","Fleurie, lumineuse","Arabe"],["Zaynab","زينب","Nom arabe traditionnel","Arabe / islamique"]
];
const toEntry = (gender: NameGender, [name, arabic, meaning, origin, tag]: Seed): NameEntry => ({ id: `${gender}-${name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")}`, name, arabic, gender, meaning, origin, tags: tag ? [tag] : undefined });
export const NAMES: readonly NameEntry[] = [...male.map((x) => toEntry("male", x)), ...female.map((x) => toEntry("female", x))].sort((a,b) => a.name.localeCompare(b.name, "fr"));
export const getName = (id: string) => NAMES.find((entry) => entry.id === id);
