import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";

import { COMPANIONS } from "../../features/companions/companionsData";
import type { CompanionCalloutKind } from "../../features/companions/companionsTypes";
import { colors } from "../../theme/colors";
import { typography } from "../../theme/typography";

const CALLOUT_LABELS: Record<CompanionCalloutKind, string> = { AUTHENTIC_HADITH: "HADITH AUTHENTIQUE", PROPHET_WORD: "PAROLE DU PROPHÈTE ﷺ", ESTABLISHED_FACT: "FAIT LARGEMENT ÉTABLI", HISTORICAL_MARKER: "REPÈRE HISTORIQUE", SOURCE_NOTE: "À PROPOS DE CE RÉCIT", DISPUTED_ACCOUNT: "DIVERGENCE DES SOURCES" };

export default function CompanionDetailScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>();
  const companion = COMPANIONS.find((item) => item.id === id);
  if (!companion) return <SafeAreaView style={styles.safe}><Text style={styles.missing}>Biographie introuvable.</Text></SafeAreaView>;
  return <LinearGradient colors={[colors.background, colors.backgroundSecondary, colors.background]} style={styles.screen}><SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="chevron-back" size={23} color={colors.text} /></Pressable><Text style={styles.headerTitle}>Biographie</Text><View style={styles.spacer} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.kicker}>LES COMPAGNONS · الصحابة</Text><Text style={styles.title}>{companion.name}</Text><Text style={styles.arabic}>{companion.arabicName}</Text><Text style={styles.summary}>{companion.summary}</Text><View style={styles.rule} />{companion.periods.map((period, index) => <View key={period.id} style={styles.period}><View style={styles.rail}><View style={styles.dot} />{index < companion.periods.length - 1 ? <View style={styles.line} /> : null}</View><View style={styles.periodBody}><Text style={styles.periodTitle}>{period.title}</Text>{period.dateLabel ? <Text style={styles.date}>{period.dateLabel}</Text> : null}{period.paragraphs.map((paragraph) => <Text key={paragraph} style={styles.paragraph}>{paragraph}</Text>)}{period.callouts?.map((callout) => <View key={callout.text} style={styles.callout}><Text style={styles.calloutLabel}>{CALLOUT_LABELS[callout.kind]}</Text><Text style={styles.calloutText}>{callout.text}</Text>{callout.source ? <Text style={styles.source}>{callout.source.label} · {callout.source.reference}{callout.source.grade ? ` · ${callout.source.grade}` : ""}</Text> : null}</View>)}{period.sources?.map((source) => <Text key={source.reference} style={styles.source}>Source · {source.label} — {source.reference}{source.grade ? ` (${source.grade})` : ""}</Text>)}</View></View>)}</ScrollView></SafeAreaView></LinearGradient>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, safe: { flex: 1 }, header: { minHeight: 74, paddingHorizontal: 16, flexDirection: "row", alignItems: "center" }, back: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.borderSoft, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,.04)" }, spacer: { width: 44 }, headerTitle: { flex: 1, textAlign: "center", color: colors.text, fontFamily: typography.serifSemibold, fontSize: 22 }, content: { padding: 18, paddingBottom: 70 }, kicker: { color: colors.goldLight, fontFamily: typography.sans, fontSize: 10, fontWeight: "900", letterSpacing: 1.3 }, title: { marginTop: 9, color: colors.text, fontFamily: typography.serifSemibold, fontSize: 31, lineHeight: 37 }, arabic: { marginTop: 5, color: colors.goldLight, fontFamily: typography.arabic, fontSize: 25 }, summary: { marginTop: 13, color: colors.textSecondary, fontFamily: typography.sans, fontSize: 15, lineHeight: 23 }, rule: { height: 1, marginVertical: 22, backgroundColor: "rgba(227,181,90,.24)" }, period: { flexDirection: "row", gap: 13 }, rail: { width: 15, alignItems: "center" }, dot: { width: 10, height: 10, marginTop: 7, borderRadius: 5, backgroundColor: colors.goldLight, shadowColor: colors.goldLight, shadowOpacity: .35, shadowRadius: 7 }, line: { width: 1, flex: 1, marginTop: 7, backgroundColor: "rgba(227,181,90,.28)" }, periodBody: { flex: 1, paddingBottom: 24 }, periodTitle: { color: colors.text, fontFamily: typography.serifSemibold, fontSize: 22, lineHeight: 28 }, date: { marginTop: 4, color: colors.goldLight, fontFamily: typography.sans, fontSize: 10, fontWeight: "800" }, paragraph: { marginTop: 12, color: colors.textSecondary, fontFamily: typography.sans, fontSize: 15, lineHeight: 24 }, callout: { marginTop: 15, padding: 13, borderRadius: 16, borderWidth: 1, borderColor: "rgba(227,181,90,.28)", backgroundColor: "rgba(227,181,90,.07)" }, calloutLabel: { color: colors.goldLight, fontFamily: typography.sans, fontSize: 9, fontWeight: "900", letterSpacing: 1 }, calloutText: { marginTop: 6, color: colors.textSecondary, fontFamily: typography.sans, fontSize: 13, lineHeight: 20 }, source: { marginTop: 8, color: colors.textMuted, fontFamily: typography.sans, fontSize: 10.5, lineHeight: 16 }, missing: { margin: 30, color: colors.text },
});
