import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import type { Href } from "expo-router";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import HadithScreenHeader from "../../features/hadith/presentation/HadithScreenHeader";
import { activateHadithProgram, dueHadithReviews, HADITH_PROGRAM_TEMPLATES, loadHadithLearningState, type HadithLearningState } from "../../features/hadith/services/hadithLearningService";
import { colors } from "../../theme/colors";
import { typography } from "../../theme/typography";

export default function HadithLearningScreen() {
  const [state, setState] = useState<HadithLearningState>();
  useFocusEffect(useCallback(() => { let active = true; void loadHadithLearningState().then((value) => active && setState(value)); return () => { active = false; }; }, []));
  const due = state ? dueHadithReviews(state) : [];
  const choose = async (template: (typeof HADITH_PROGRAM_TEMPLATES)[number]) => { const next = await activateHadithProgram(template); setState(next); };
  return <LinearGradient colors={["#080713", "#120A1D", "#080713"]} style={styles.screen}><SafeAreaView edges={["top"]} style={styles.safe}><View style={styles.header}><HadithScreenHeader title="Apprentissage" subtitle="Lire · comprendre · mémoriser · réviser" /></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.hero}><LinearGradient colors={["#533256", "#20152E"]} style={StyleSheet.absoluteFill} /><Text style={styles.heroKicker}>VOTRE PARCOURS</Text><Text style={styles.heroTitle}>{state?.activeProgram?.title ?? "Choisissez votre rythme"}</Text><Text style={styles.heroText}>{state?.activeProgram?.description ?? "Un programme simple qui s’adapte à votre quotidien."}</Text><View style={styles.stats}><Stat value={state?.streak ?? 0} label="jours" /><Stat value={state?.memorizedIds.length ?? 0} label="mémorisés" /><Stat value={due.length} label="à réviser" /></View>{state?.activeProgram ? <Pressable onPress={() => router.push("/hadith/learning/session" as Href)} style={styles.primary}><Ionicons name="play" size={17} color="#1B1321" /><Text style={styles.primaryText}>{due.length ? "Commencer mes révisions" : "Continuer le programme"}</Text></Pressable> : null}</View>
    <Text style={styles.sectionTitle}>Programmes</Text><View style={styles.programs}>{HADITH_PROGRAM_TEMPLATES.map((template) => { const active = state?.activeProgram?.id === template.id; return <Pressable key={template.id} onPress={() => choose(template)} style={[styles.program, active && styles.programActive]}><View style={styles.programIcon}><Ionicons name={template.id === "nawawi" ? "library-outline" : template.id === "character" ? "heart-outline" : "calendar-outline"} size={21} color={colors.goldLight} /></View><View style={styles.programCopy}><Text style={styles.programTitle}>{template.title}</Text><Text style={styles.programText}>{template.description}</Text><Text style={styles.programMeta}>{template.targetCount} hadiths · {template.cadence === "daily" ? "quotidien" : "rythme souple"}</Text></View>{active ? <Ionicons name="checkmark-circle" size={22} color="#75D1A0" /> : <Ionicons name="chevron-forward" size={17} color={colors.textMuted} />}</Pressable>; })}</View>
    <View style={styles.method}><Text style={styles.methodTitle}>Répétition espacée OUMMAH</Text><Text style={styles.methodText}>Après chaque révision, indiquez votre aisance. Le prochain rappel est automatiquement ajusté : 10 minutes, 1 jour, 3 jours, 7 jours puis davantage.</Text></View>
  </ScrollView></SafeAreaView></LinearGradient>;
}
function Stat({ value, label }: { value: number; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, safe: { flex: 1 }, header: { paddingHorizontal: 18 }, content: { padding: 18, paddingTop: 13, paddingBottom: 110 }, hero: { minHeight: 270, borderRadius: 29, overflow: "hidden", padding: 21, borderWidth: 1, borderColor: "rgba(238,200,120,0.28)" }, heroKicker: { color: colors.goldLight, fontFamily: typography.sans, fontWeight: "800", fontSize: 9, letterSpacing: 1.5 }, heroTitle: { color: colors.text, fontFamily: typography.serifSemibold, fontSize: 28, marginTop: 7 }, heroText: { color: colors.textSecondary, fontFamily: typography.sans, fontSize: 12, lineHeight: 18, marginTop: 5 }, stats: { flexDirection: "row", gap: 8, marginTop: 20 }, stat: { flex: 1, padding: 11, borderRadius: 16, backgroundColor: "rgba(9,7,19,0.32)" }, statValue: { color: colors.text, fontFamily: typography.serifSemibold, fontSize: 21 }, statLabel: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 9 }, primary: { marginTop: 20, height: 47, borderRadius: 16, backgroundColor: colors.goldLight, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, primaryText: { color: "#1B1321", fontFamily: typography.sans, fontSize: 11.5, fontWeight: "800" }, sectionTitle: { color: colors.text, fontFamily: typography.serifMedium, fontSize: 22, marginTop: 27, marginBottom: 12 }, programs: { gap: 9 }, program: { minHeight: 91, padding: 14, borderRadius: 21, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "rgba(28,19,41,0.84)", borderWidth: 1, borderColor: "rgba(139,91,160,0.18)" }, programActive: { borderColor: "rgba(117,209,160,0.38)", backgroundColor: "rgba(42,49,48,0.72)" }, programIcon: { width: 43, height: 43, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(227,181,90,0.1)" }, programCopy: { flex: 1 }, programTitle: { color: colors.text, fontFamily: typography.serifMedium, fontSize: 17 }, programText: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 10, marginTop: 2 }, programMeta: { color: colors.goldLight, fontFamily: typography.sans, fontSize: 9, marginTop: 5 }, method: { marginTop: 22, padding: 17, borderRadius: 21, backgroundColor: "rgba(93,70,128,0.11)" }, methodTitle: { color: "#D7B9E5", fontFamily: typography.sans, fontSize: 11.5, fontWeight: "700" }, methodText: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 10.5, lineHeight: 16, marginTop: 5 } });

