import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { submitBoycottCandidate } from '../../features/boycott/data/BoycottRepository';
import { BOYCOTT_CATEGORY_LABELS, type BoycottCategory } from '../../features/boycott/domain/BoycottEntity';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';

const categories = Object.entries(BOYCOTT_CATEGORY_LABELS) as Array<[BoycottCategory,string]>;
export default function BoycottAddScreen(){
 const params=useLocalSearchParams<{barcode?:string;name?:string;brand?:string}>();
 const [name,setName]=useState(params.name ?? ''); const [brand,setBrand]=useState(params.brand ?? ''); const [barcode,setBarcode]=useState(params.barcode ?? ''); const [sourceUrl,setSourceUrl]=useState(''); const [note,setNote]=useState(''); const [category,setCategory]=useState<BoycottCategory>('food'); const [saving,setSaving]=useState(false);
 async function save(){ if(!name.trim()){Alert.alert('Nom requis','Indique le nom du produit ou de l’entreprise.');return;} setSaving(true); try{await submitBoycottCandidate({name,brand,barcode,sourceUrl,note,category}); Alert.alert('Envoyé','Merci. La proposition restera invisible jusqu’à validation par un admin OUMMAH.',[{text:'OK',onPress:()=>router.back()}]);}catch{Alert.alert('Erreur','Impossible d’envoyer la proposition pour le moment.');}finally{setSaving(false);} }
 return <LinearGradient colors={['#090713','#120A1D','#090713']} style={styles.screen}><SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.headerButton}><Ionicons name="arrow-back" size={21} color={colors.goldLight}/></Pressable><Text style={styles.headerTitle}>Proposer</Text><View style={styles.headerButton}/></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Ajouter un produit ou une entreprise</Text><Text style={styles.subtitle}>Aucune proposition ne devient publique automatiquement. Un admin vérifie le lien et les sources avant publication.</Text>
 {([['Nom *',name,setName,'Ex. KFC'],['Marque / groupe',brand,setBrand,'Ex. Yum! Brands'],['Code-barres',barcode,setBarcode,'EAN / UPC si disponible'],['Source',sourceUrl,setSourceUrl,'https://…'],['Note',note,setNote,'Ce que vous avez trouvé…']] as const).map(([label,value,setter,placeholder])=><View key={label} style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={setter} placeholder={placeholder} placeholderTextColor="#736B7A" style={[styles.input,label==='Note'&&styles.note]} multiline={label==='Note'} keyboardType={label==='Code-barres'?'number-pad':label==='Source'?'url':'default'} autoCapitalize={label==='Source'?'none':'sentences'}/></View>)}
 <Text style={styles.label}>Catégorie</Text><View style={styles.categories}>{categories.map(([key,label])=><Pressable key={key} onPress={()=>setCategory(key)} style={[styles.chip,category===key&&styles.chipActive]}><Text style={[styles.chipText,category===key&&styles.chipTextActive]}>{label}</Text></Pressable>)}</View>
 <Pressable disabled={saving} onPress={()=>void save()} style={[styles.submit,saving&&{opacity:.6}]}><Text style={styles.submitText}>{saving?'Envoi…':'Envoyer pour validation'}</Text><Ionicons name="shield-checkmark-outline" size={19} color="#17111C"/></Pressable></ScrollView></SafeAreaView></LinearGradient>;
}
const styles=StyleSheet.create({screen:{flex:1},safe:{flex:1},header:{height:58,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerButton:{width:42,height:42,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,0.045)',borderWidth:1,borderColor:'rgba(255,255,255,0.07)'},headerTitle:{color:colors.text,fontFamily:typography.serifSemibold,fontSize:22},content:{padding:16,paddingBottom:44},title:{color:colors.text,fontFamily:typography.serifSemibold,fontSize:28,lineHeight:32},subtitle:{marginTop:7,marginBottom:16,color:colors.textMuted,fontFamily:typography.sans,fontSize:12.5,lineHeight:18},field:{marginBottom:13},label:{marginBottom:6,color:colors.textSecondary,fontFamily:typography.sans,fontSize:11.5,fontWeight:'700'},input:{minHeight:54,borderRadius:19,paddingHorizontal:14,color:colors.text,fontFamily:typography.sans,fontSize:14.5,backgroundColor:'rgba(24,17,34,0.9)',borderWidth:1,borderColor:'rgba(255,255,255,0.07)'},note:{minHeight:96,paddingTop:14,textAlignVertical:'top'},categories:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:15,backgroundColor:'rgba(255,255,255,0.04)',borderWidth:1,borderColor:'rgba(255,255,255,0.07)'},chipActive:{backgroundColor:colors.goldLight,borderColor:colors.goldLight},chipText:{color:colors.textSecondary,fontFamily:typography.sans,fontSize:10.5,fontWeight:'700'},chipTextActive:{color:'#17111C'},submit:{marginTop:22,minHeight:57,borderRadius:20,backgroundColor:colors.goldLight,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},submitText:{color:'#17111C',fontFamily:typography.sans,fontSize:14,fontWeight:'800'}});
