import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { FiqhDifferenceCard } from "../../../features/fiqh/components/FiqhDifferenceCard";
import { FiqhPersonalCaseNotice } from "../../../features/fiqh/components/FiqhPersonalCaseNotice";
import { FiqhSection } from "../../../features/fiqh/components/FiqhSection";
import { FiqhSourceCard } from "../../../features/fiqh/components/FiqhSourceCard";
import { categoryById, chapterById, topicById } from "../../../features/fiqh/fiqhData";
import { saveFiqhProgress } from "../../../features/fiqh/fiqhStorage";
import { colors } from "../../../theme/colors";

export default function FiqhTopic() {
  const { topicId, chapter: chapterParam } = useLocalSearchParams<{ topicId: string; chapter?: string }>();
  const topic = topicById.get(topicId);
  const [openQuestion, setOpenQuestion] = useState<string | null>(null);
  useEffect(() => { if (topic) void saveFiqhProgress({ lastTopicId: topic.id, lastCategoryId: topic.categoryId }); }, [topic]);
  if (!topic) return <SafeAreaView style={s.screen}><Text style={s.text}>Sujet introuvable.</Text></SafeAreaView>;
  if (topic.publicationStatus === "coming_soon" || topic.publicationStatus === "blocked") return <SafeAreaView style={s.screen}><View style={s.content}><Pressable onPress={() => router.back()}><Text style={s.back}>‹ Retour</Text></Pressable><Text style={s.title}>{topic.title}</Text><Text style={s.summary}>Bientôt disponible.</Text></View></SafeAreaView>;
  const content = topic.content;
  const chapter = (chapterParam ? chapterById.get(chapterParam) : undefined) ?? Array.from(chapterById.values()).find((item) => item.topicIds.includes(topic.id));
  const category = categoryById.get(topic.categoryId);
  const index = chapter?.topicIds.indexOf(topic.id) ?? -1;
  const previousId = index > 0 ? chapter?.topicIds[index - 1] : undefined;
  const nextId = chapter && index >= 0 && index < chapter.topicIds.length - 1 ? chapter.topicIds[index + 1] : undefined;
  const previous = previousId ? topicById.get(previousId) : undefined;
  const next = nextId ? topicById.get(nextId) : undefined;
  const established = content?.ceQuiEstEtabli?.map((claim) => claim.text) ?? topic.established;
  const practice = content?.pratique?.map((claim) => claim.text) ?? topic.howTo;
  const teachings = content?.enseignements?.map((claim) => claim.text) ?? topic.takeaway;
  const knowledge = [...(content?.limites ?? []), ...(content?.divergences?.map((claim) => claim.text) ?? []), ...(content?.casPersonnel ? [content.casPersonnel] : [])];
  return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => router.back()}><Text style={s.back}>‹ Retour</Text></Pressable>{chapter ? <Text style={s.breadcrumb} numberOfLines={1} ellipsizeMode="tail">{category?.title ?? topic.categoryId} › {chapter.title} › {topic.title}</Text> : null}<Text style={s.title}>{topic.title}</Text>{topic.arabicTerm ? <Text style={s.arabic}>{topic.arabicTerm}</Text> : null}<Text style={s.summary}>{content?.introduction ?? topic.summary}</Text><FiqhSection title="DÉFINITION" items={(content?.definition ?? []).map((claim) => claim.text)} /><FiqhSection title="CE QUI EST ÉTABLI" items={established} /><FiqhSection title="COMMENT CELA SE PRATIQUE" items={practice} /><FiqhSection title="ENSEIGNEMENTS" items={teachings} /><FiqhSection title="CONDITIONS" items={topic.conditions} /><FiqhSection title="CE QUI ANNULE / INVALIDE" items={topic.invalidators} /><FiqhSection title="ERREURS FRÉQUENTES" items={topic.commonMistakes} /><FiqhSection title="CAS PARTICULIERS" items={topic.specialCases} />{topic.differences.map((difference) => <FiqhDifferenceCard key={difference.question} difference={difference} />)}<FiqhSection title="À SAVOIR" items={knowledge} />{content?.questions?.length ? <View style={s.faq}><Text style={s.faqTitle}>QUESTIONS FRÉQUENTES</Text>{content.questions.map((question) => <View key={question.id} style={s.faqItem}><Pressable onPress={() => setOpenQuestion(openQuestion === question.id ? null : question.id)} style={s.questionButton}><Text style={s.question} numberOfLines={2}>{question.question}</Text><Text style={s.toggle}>{openQuestion === question.id ? "−" : "+"}</Text></Pressable>{openQuestion === question.id ? question.answer.map((claim, claimIndex) => <Text key={`${question.id}-${claimIndex}`} style={s.answer}>{claim.text}</Text>) : null}</View>)}</View> : null}{topic.sensitive ? <FiqhPersonalCaseNotice /> : null}<FiqhSourceCard ids={topic.sourceIds} />{chapter ? <View style={s.navigation}>{previousId ? <Pressable onPress={() => router.replace({ pathname: "/fiqh/topic/[topicId]", params: { topicId: previousId, chapter: chapter.id } })} style={s.navButton}><Text style={s.nav} numberOfLines={2}>‹ {previous?.title}</Text></Pressable> : <View style={s.navButton} />}{nextId ? <Pressable onPress={() => router.replace({ pathname: "/fiqh/topic/[topicId]", params: { topicId: nextId, chapter: chapter.id } })} style={[s.navButton, s.navRight]}><Text style={s.nav} numberOfLines={2}> {next?.title} ›</Text></Pressable> : <Pressable onPress={() => router.push({ pathname: "/fiqh/chapter/[chapterId]", params: { chapterId: chapter.id } })} style={[s.navButton, s.navRight]}><Text style={s.nav}>Chapitre ›</Text></Pressable>}</View> : null}</ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: 22, paddingBottom: 70 }, back: { color: colors.goldLight, fontSize: 18, marginBottom: 16 }, breadcrumb: { color: colors.textMuted, fontSize: 13, marginBottom: 16 }, title: { color: colors.text, fontSize: 34, lineHeight: 40, fontWeight: "800", marginTop: 8 }, arabic: { color: colors.goldLight, fontSize: 26, marginTop: 4 }, summary: { color: colors.textSecondary, fontSize: 17, lineHeight: 25, marginTop: 12 }, faq: { marginTop: 22 }, faqTitle: { color: colors.goldLight, fontSize: 14, fontWeight: "800", letterSpacing: 1 }, faqItem: { marginTop: 10, padding: 14, borderRadius: 14, backgroundColor: colors.surfaceAlt }, questionButton: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, question: { color: colors.text, fontSize: 16, fontWeight: "700", flex: 1 }, toggle: { color: colors.goldLight, fontSize: 22, lineHeight: 24 }, answer: { color: colors.textSecondary, fontSize: 15, lineHeight: 23, marginTop: 12 }, navigation: { flexDirection: "row", justifyContent: "space-between", marginTop: 28, paddingTop: 18, borderTopWidth: 1, borderTopColor: colors.borderSoft }, navButton: { width: "47%", minHeight: 42, justifyContent: "center" }, navRight: { alignItems: "flex-end" }, nav: { color: colors.goldLight, fontSize: 14, lineHeight: 20, fontWeight: "700", textAlign: "left" }, text: { color: colors.text } });
