import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { HADITH_THEMES } from "../../features/hadith/domain/HadithTheme";
import HadithScreenHeader from "../../features/hadith/presentation/HadithScreenHeader";
import { downloadHadithPack, loadHadithOfflinePacks, removeHadithOfflinePack, type HadithOfflinePack } from "../../features/hadith/services/hadithOfflineService";
import { colors } from "../../theme/colors";
import { typography } from "../../theme/typography";

export default function HadithOfflineScreen() {
  const [packs, setPacks] = useState<HadithOfflinePack[]>([]); const [downloading, setDownloading] = useState<string>(); const [progress, setProgress] = useState(0);
  useEffect(() => { void loadHadithOfflinePacks().then(setPacks); }, []);
  const download = async (id: string, label: string, query: string) => { setDownloading(id); setProgress(0); try { await downloadHadithPack(id, label, query, 20, setProgress); setPacks(await loadHadithOfflinePacks()); } catch { Alert.alert("Téléchargement interrompu", "Vérifiez votre connexion puis réessayez."); } finally { setDownloading(undefined); } };
  const installed = new Set(packs.map((pack) => pack.id));
  return <LinearGradient colors={["#080713", "#120A1D", "#080713"]} style={styles.screen}><SafeAreaView edges={["top"]} style={styles.safe}><View style={styles.header}><HadithScreenHeader title="Hors ligne" subtitle="Emportez vos lectures avec vous" /></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.hero}><Ionicons name="cloud-done-outline" size={29} color="#75D1A0" /><View style={{ flex: 1 }}><Text style={styles.heroTitle}>{packs.reduce((sum, pack) => sum + pack.hadithIds.length, 0)} fiches disponibles</Text><Text style={styles.heroText}>Arabe, traduction, explication et références restent consultables sans réseau.</Text></View></View><Text style={styles.section}>Packs thématiques</Text>{HADITH_THEMES.slice(0, 10).map((theme) => { const active = installed.has(theme.id); const busy = downloading === theme.id; return <View key={theme.id} style={styles.pack}><View style={[styles.icon, { backgroundColor: `${theme.color}20` }]}><Ionicons name={theme.icon as never} size={20} color={theme.color} /></View><View style={styles.copy}><Text style={styles.title}>{theme.label}</Text><Text style={styles.meta}>{active ? `${packs.find((pack) => pack.id === theme.id)?.hadithIds.length ?? 0} fiches enregistrées` : "Jusqu’à 20 fiches référencées"}</Text>{busy ? <View style={styles.track}><View style={[styles.fill, { width: `${Math.round(progress * 100)}%` }]} /></View> : null}</View><Pressable disabled={Boolean(downloading)} onPress={() => active ? void removeHadithOfflinePack(theme.id).then(setPacks) : download(theme.id, theme.label, theme.query)} style={[styles.download, active && styles.downloadActive]}><Ionicons name={busy ? "hourglass-outline" : active ? "checkmark" : "download-outline"} size={18} color={active ? "#75D1A0" : colors.goldLight} /></Pressable></View>; })}<Text style={styles.note}>Le retrait d’un pack enlève son suivi de téléchargement. Une fiche également favorite ou déjà consultée peut rester dans le cache de sécurité.</Text></ScrollView></SafeAreaView></LinearGradient>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, safe: { flex: 1 }, header: { paddingHorizontal: 18 }, content: { padding: 18, paddingTop: 14, paddingBottom: 110 }, hero: { padding: 18, borderRadius: 22, backgroundColor: "rgba(59,124,91,0.11)", borderWidth: 1, borderColor: "rgba(117,209,160,0.18)", flexDirection: "row", alignItems: "center", gap: 12 }, heroTitle: { color: "#A2E3BF", fontFamily: typography.serifMedium, fontSize: 18 }, heroText: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 10.5, lineHeight: 15, marginTop: 3 }, section: { color: colors.text, fontFamily: typography.serifMedium, fontSize: 21, marginTop: 27, marginBottom: 11 }, pack: { minHeight: 73, padding: 12, marginBottom: 8, borderRadius: 19, backgroundColor: "rgba(28,19,41,0.82)", flexDirection: "row", alignItems: "center", gap: 11 }, icon: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center" }, copy: { flex: 1 }, title: { color: colors.text, fontFamily: typography.serifMedium, fontSize: 16 }, meta: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 9.5, marginTop: 2 }, download: { width: 39, height: 39, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(227,181,90,0.09)" }, downloadActive: { backgroundColor: "rgba(117,209,160,0.09)" }, track: { height: 3, borderRadius: 2, backgroundColor: "rgba(255,255,255,0.08)", marginTop: 7, overflow: "hidden" }, fill: { height: 3, backgroundColor: colors.goldLight }, note: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 9.5, lineHeight: 15, textAlign: "center", marginTop: 18 } });
