import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import type { Href } from "expo-router";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import HadithScreenHeader from "../../features/hadith/presentation/HadithScreenHeader";
import { createPersonalHadithList, deletePersonalHadithList, loadPersonalHadithLists, removeHadithFromPersonalList, type PersonalHadithList } from "../../features/hadith/services/hadithListService";
import { colors } from "../../theme/colors";
import { typography } from "../../theme/typography";

const COLORS = ["#B8874B", "#6E8F82", "#8B6DA1", "#A66666", "#637F9E"];
export default function HadithListsScreen() {
  const [lists, setLists] = useState<PersonalHadithList[]>([]); const [visible, setVisible] = useState(false); const [name, setName] = useState(""); const [color, setColor] = useState(COLORS[0]);
  const reload = useCallback(() => { void loadPersonalHadithLists().then(setLists); }, []); useFocusEffect(reload);
  const create = async () => { if (!name.trim()) return; await createPersonalHadithList(name, color); setName(""); setVisible(false); reload(); };
  const removeList = (list: PersonalHadithList) => Alert.alert("Supprimer la liste ?", `« ${list.name} » sera supprimée, sans effacer les hadiths de la source.`, [{ text: "Annuler", style: "cancel" }, { text: "Supprimer", style: "destructive", onPress: () => void deletePersonalHadithList(list.id).then(setLists) }]);
  return <LinearGradient colors={["#080713", "#120A1D", "#080713"]} style={styles.screen}><SafeAreaView edges={["top"]} style={styles.safe}><View style={styles.header}><HadithScreenHeader title="Mes listes" subtitle="Votre bibliothèque personnelle" right={<Pressable onPress={() => setVisible(true)} style={styles.add}><Ionicons name="add" size={22} color={colors.goldLight} /></Pressable>} /></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>{!lists.length ? <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="albums-outline" size={31} color={colors.goldLight} /></View><Text style={styles.emptyTitle}>Créez votre première collection</Text><Text style={styles.emptyText}>Patience, mariage, à mémoriser, pour mes enfants… classez librement ce qui vous a marqué.</Text><Pressable onPress={() => setVisible(true)} style={styles.primary}><Text style={styles.primaryText}>Créer une liste</Text></Pressable></View> : lists.map((list) => <View key={list.id} style={styles.listCard}><View style={styles.listHeader}><View style={[styles.listIcon, { backgroundColor: `${list.color}22` }]}><Ionicons name="bookmark" size={20} color={list.color} /></View><View style={styles.listCopy}><Text style={styles.listTitle}>{list.name}</Text><Text style={styles.listMeta}>{list.hadiths.length} hadith{list.hadiths.length > 1 ? "s" : ""}</Text></View><Pressable onPress={() => removeList(list)} hitSlop={8}><Ionicons name="ellipsis-horizontal" size={20} color={colors.textMuted} /></Pressable></View>{list.hadiths.slice(0, 5).map((item) => <Pressable key={item.id} onPress={() => router.push(`/hadith/${item.id}` as Href)} style={styles.hadith}><View style={[styles.dot, { backgroundColor: list.color }]} /><View style={{ flex: 1 }}><Text numberOfLines={2} style={styles.hadithTitle}>{item.title}</Text><Text numberOfLines={1} style={styles.hadithMeta}>{item.grade} · {item.reference}</Text></View><Pressable onPress={() => void removeHadithFromPersonalList(list.id, item.id).then(setLists)} hitSlop={8}><Ionicons name="close" size={17} color={colors.textMuted} /></Pressable></Pressable>)}{!list.hadiths.length ? <Text style={styles.listEmpty}>Ajoutez un hadith depuis sa fiche détaillée.</Text> : null}</View>)}</ScrollView>
    <Modal visible={visible} transparent animationType="fade" onRequestClose={() => setVisible(false)}><View style={styles.backdrop}><Pressable style={StyleSheet.absoluteFill} onPress={() => setVisible(false)} /><View style={styles.modal}><Text style={styles.modalTitle}>Nouvelle liste</Text><TextInput value={name} onChangeText={setName} autoFocus placeholder="Ex. À mémoriser" placeholderTextColor={colors.textMuted} style={styles.input} /><Text style={styles.colorLabel}>COULEUR</Text><View style={styles.colors}>{COLORS.map((item) => <Pressable key={item} onPress={() => setColor(item)} style={[styles.color, { backgroundColor: item }, color === item && styles.colorActive]} />)}</View><Pressable onPress={create} style={[styles.primary, !name.trim() && { opacity: 0.45 }]}><Text style={styles.primaryText}>Créer la liste</Text></Pressable></View></View></Modal>
  </SafeAreaView></LinearGradient>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, safe: { flex: 1 }, header: { paddingHorizontal: 18 }, add: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(35,23,49,0.94)" }, content: { padding: 18, paddingTop: 14, paddingBottom: 110, gap: 11 }, empty: { paddingTop: 85, alignItems: "center" }, emptyIcon: { width: 68, height: 68, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(227,181,90,0.1)" }, emptyTitle: { color: colors.text, fontFamily: typography.serifMedium, fontSize: 23, marginTop: 18 }, emptyText: { maxWidth: 300, color: colors.textMuted, fontFamily: typography.sans, fontSize: 11.5, lineHeight: 18, textAlign: "center", marginTop: 7 }, primary: { minWidth: 160, height: 47, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: colors.goldLight, marginTop: 20 }, primaryText: { color: "#1A1220", fontFamily: typography.sans, fontSize: 11.5, fontWeight: "800" }, listCard: { borderRadius: 24, padding: 16, backgroundColor: "rgba(29,20,42,0.9)", borderWidth: 1, borderColor: "rgba(140,91,161,0.19)" }, listHeader: { flexDirection: "row", alignItems: "center", gap: 11 }, listIcon: { width: 43, height: 43, borderRadius: 15, alignItems: "center", justifyContent: "center" }, listCopy: { flex: 1 }, listTitle: { color: colors.text, fontFamily: typography.serifMedium, fontSize: 18 }, listMeta: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 9.5, marginTop: 2 }, hadith: { minHeight: 63, paddingTop: 13, marginTop: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(255,255,255,0.08)", flexDirection: "row", alignItems: "center", gap: 9 }, dot: { width: 6, height: 6, borderRadius: 3 }, hadithTitle: { color: colors.textSecondary, fontFamily: typography.serifMedium, fontSize: 14.5 }, hadithMeta: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 9, marginTop: 3 }, listEmpty: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 10.5, marginTop: 15 }, backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.62)" }, modal: { padding: 22, paddingBottom: 35, borderTopLeftRadius: 30, borderTopRightRadius: 30, backgroundColor: "#171024" }, modalTitle: { color: colors.text, fontFamily: typography.serifSemibold, fontSize: 25 }, input: { height: 51, borderRadius: 16, paddingHorizontal: 15, color: colors.text, fontFamily: typography.sans, marginTop: 18, backgroundColor: "rgba(255,255,255,0.05)", borderWidth: 1, borderColor: "rgba(227,181,90,0.2)" }, colorLabel: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 9, fontWeight: "800", letterSpacing: 1, marginTop: 18 }, colors: { flexDirection: "row", gap: 12, marginTop: 10 }, color: { width: 31, height: 31, borderRadius: 12 }, colorActive: { borderWidth: 3, borderColor: "#FFF" } });

