import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import * as Sharing from "expo-sharing";
import { useLocalSearchParams } from "expo-router";
import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { captureRef } from "react-native-view-shot";
import { hadithRepository } from "../../features/hadith/data/hadithRepository";
import type { Hadith } from "../../features/hadith/domain/Hadith";
import HadithScreenHeader from "../../features/hadith/presentation/HadithScreenHeader";
import { shareHadithText, type HadithShareContent } from "../../features/hadith/services/hadithShareService";
import { colors } from "../../theme/colors";
import { typography } from "../../theme/typography";

type Format = "square" | "story";
export default function HadithShareScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [hadith, setHadith] = useState<Hadith | null>(null); const [content, setContent] = useState<HadithShareContent>("both"); const [format, setFormat] = useState<Format>("square"); const [sharing, setSharing] = useState(false); const cardRef = useRef<View>(null);
  useEffect(() => { if (id) void hadithRepository.get(id).then(setHadith); }, [id]);
  const shareImage = async () => { if (!cardRef.current || !hadith) return; setSharing(true); try { const uri = await captureRef(cardRef, { format: "png", quality: 1, result: "tmpfile" }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "image/png", dialogTitle: "Partager ce hadith" }); else await shareHadithText(hadith, content, true); } catch { Alert.alert("Partage indisponible", "Le texte peut toujours être copié ou partagé depuis la fiche."); } finally { setSharing(false); } };
  return <LinearGradient colors={["#080713", "#120A1D", "#080713"]} style={styles.screen}><SafeAreaView edges={["top"]} style={styles.safe}><View style={styles.header}><HadithScreenHeader title="Créer une carte" subtitle="La référence reste lisible sur chaque partage" /></View>{!hadith ? <View style={styles.center}><ActivityIndicator color={colors.goldLight} /></View> : <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View ref={cardRef} collapsable={false} style={[styles.card, format === "story" && styles.cardStory]}><LinearGradient colors={["#3A2347", "#171022", "#090711"]} style={StyleSheet.absoluteFill} /><View style={styles.emblem}><Text style={styles.emblemText}>ﷺ</Text></View>{content !== "french" && hadith.arabic ? <Text numberOfLines={format === "square" ? 5 : 9} style={styles.arabic}>{hadith.arabic}</Text> : null}{content !== "arabic" ? <Text numberOfLines={format === "square" ? 7 : 12} style={styles.french}>{hadith.french}</Text> : null}<View style={styles.cardFooter}><Text style={styles.reference}>{hadith.grade} · {hadith.reference}</Text><Text style={styles.source}>HADEETHENC · OUMMAH</Text></View></View><Text style={styles.label}>CONTENU</Text><View style={styles.options}>{(["arabic", "french", "both"] as HadithShareContent[]).map((item) => <Pressable key={item} onPress={() => setContent(item)} style={[styles.option, content === item && styles.optionActive]}><Text style={[styles.optionText, content === item && styles.optionTextActive]}>{item === "arabic" ? "Arabe" : item === "french" ? "Traduction" : "Les deux"}</Text></Pressable>)}</View><Text style={styles.label}>FORMAT</Text><View style={styles.options}>{(["square", "story"] as Format[]).map((item) => <Pressable key={item} onPress={() => setFormat(item)} style={[styles.option, format === item && styles.optionActive]}><Ionicons name={item === "square" ? "square-outline" : "phone-portrait-outline"} size={15} color={format === item ? colors.goldLight : colors.textMuted} /><Text style={[styles.optionText, format === item && styles.optionTextActive]}>{item === "square" ? "Carré" : "Story"}</Text></Pressable>)}</View><View style={styles.sourceToggle}><View><Text style={styles.toggleTitle}>Référence complète incluse</Text><Text style={styles.toggleText}>Authenticité, référence et source restent toujours visibles.</Text></View><Ionicons name="shield-checkmark" size={23} color="#75D1A0" /></View><Pressable onPress={shareImage} style={styles.primary}>{sharing ? <ActivityIndicator color="#1A1220" /> : <><Ionicons name="share-social" size={18} color="#1A1220" /><Text style={styles.primaryText}>Partager l’image</Text></>}</Pressable></ScrollView>}</SafeAreaView></LinearGradient>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, safe: { flex: 1 }, header: { paddingHorizontal: 18 }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, content: { padding: 18, paddingTop: 14, paddingBottom: 110, alignItems: "center" }, card: { width: 330, aspectRatio: 1, borderRadius: 0, overflow: "hidden", padding: 25, justifyContent: "center", borderWidth: 1, borderColor: "rgba(227,181,90,0.34)" }, cardStory: { aspectRatio: 9 / 16, paddingVertical: 38 }, emblem: { position: "absolute", top: 20, right: 20, width: 39, height: 39, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(227,181,90,0.12)" }, emblemText: { color: colors.goldLight, fontFamily: typography.arabic, fontSize: 18 }, arabic: { color: "#FFF6E7", fontFamily: "UthmanicHafs", fontSize: 20, lineHeight: 34, textAlign: "right", writingDirection: "rtl", marginBottom: 15 }, french: { color: colors.text, fontFamily: typography.serif, fontSize: 16, lineHeight: 22 }, cardFooter: { position: "absolute", left: 25, right: 25, bottom: 20, paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(255,255,255,0.16)" }, reference: { color: "#C8BFD0", fontFamily: typography.sans, fontSize: 8.5 }, source: { color: colors.goldLight, fontFamily: typography.sans, fontSize: 7.5, fontWeight: "800", letterSpacing: 1.2, marginTop: 4 }, label: { alignSelf: "stretch", color: colors.textMuted, fontFamily: typography.sans, fontSize: 9, fontWeight: "800", letterSpacing: 1.2, marginTop: 20, marginBottom: 8 }, options: { alignSelf: "stretch", flexDirection: "row", gap: 7 }, option: { flex: 1, height: 42, borderRadius: 14, flexDirection: "row", gap: 5, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.04)", borderWidth: 1, borderColor: "rgba(255,255,255,0.07)" }, optionActive: { backgroundColor: "rgba(227,181,90,0.1)", borderColor: "rgba(227,181,90,0.32)" }, optionText: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 10 }, optionTextActive: { color: colors.goldLight, fontWeight: "700" }, sourceToggle: { alignSelf: "stretch", marginTop: 18, padding: 14, borderRadius: 17, flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "rgba(255,255,255,0.035)" }, toggleTitle: { color: colors.text, fontFamily: typography.sans, fontSize: 11.5, fontWeight: "700" }, toggleText: { color: colors.textMuted, fontFamily: typography.sans, fontSize: 9, marginTop: 2 }, primary: { alignSelf: "stretch", height: 50, borderRadius: 17, marginTop: 18, backgroundColor: colors.goldLight, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, primaryText: { color: "#1A1220", fontFamily: typography.sans, fontSize: 12, fontWeight: "800" } });
