import type { MuslimName } from './types';

export const ABD_ALLAH_NAMES: MuslimName[] = [
  {
    id: 'abd-ar-rahim',
    gender: 'boy',
    name: 'Abd ar-Raḥīm',
    arabic: 'عبد الرحيم',
    transliteration: 'Abd ar-Raḥīm',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Ar-Raḥīm, traduit ici par « Le Très Miséricordieux ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Ar-Raḥīm.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-malik',
    gender: 'boy',
    name: 'Abd al-Malik',
    arabic: 'عبد الملك',
    transliteration: 'Abd al-Malik',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Malik, traduit ici par « Le Souverain ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Malik.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-quddus',
    gender: 'boy',
    name: 'Abd al-Quddūs',
    arabic: 'عبد القدوس',
    transliteration: 'Abd al-Quddūs',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Quddūs, traduit ici par « Le Très Saint ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Quddūs.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-as-salam',
    gender: 'boy',
    name: 'Abd as-Salām',
    arabic: 'عبد السلام',
    transliteration: 'Abd as-Salām',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin As-Salām, traduit ici par « La Source de paix, Le Parfait ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est As-Salām.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mumin',
    gender: 'boy',
    name: 'Abd al-Mu’min',
    arabic: 'عبد المؤمن',
    transliteration: 'Abd al-Mu’min',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mu’min, traduit ici par « Celui qui accorde la sécurité ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mu’min.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muhaymin',
    gender: 'boy',
    name: 'Abd al-Muhaymin',
    arabic: 'عبد المهيمن',
    transliteration: 'Abd al-Muhaymin',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muhaymin, traduit ici par « Le Protecteur, Le Gardien ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muhaymin.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-aziz',
    gender: 'boy',
    name: 'Abd al-‘Azīz',
    arabic: 'عبد العزيز',
    transliteration: 'Abd al-‘Azīz',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-‘Azīz, traduit ici par « Le Tout-Puissant ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-‘Azīz.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-jabbar',
    gender: 'boy',
    name: 'Abd al-Jabbār',
    arabic: 'عبد الجبار',
    transliteration: 'Abd al-Jabbār',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Jabbār, traduit ici par « Le Contraignant, Celui qui restaure ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Jabbār.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mutakabbir',
    gender: 'boy',
    name: 'Abd al-Mutakabbir',
    arabic: 'عبد المتكبر',
    transliteration: 'Abd al-Mutakabbir',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mutakabbir, traduit ici par « Le Suprême, Le Majestueux ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mutakabbir.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-khaliq',
    gender: 'boy',
    name: 'Abd al-Khāliq',
    arabic: 'عبد الخالق',
    transliteration: 'Abd al-Khāliq',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Khāliq, traduit ici par « Le Créateur ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Khāliq.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-bari',
    gender: 'boy',
    name: 'Abd al-Bāri’',
    arabic: 'عبد البارئ',
    transliteration: 'Abd al-Bāri’',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Bāri’, traduit ici par « Celui qui donne l’existence ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Bāri’.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-musawwir',
    gender: 'boy',
    name: 'Abd al-Muṣawwir',
    arabic: 'عبد المصور',
    transliteration: 'Abd al-Muṣawwir',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muṣawwir, traduit ici par « Celui qui façonne les formes ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muṣawwir.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-ghaffar',
    gender: 'boy',
    name: 'Abd al-Ghaffār',
    arabic: 'عبد الغفار',
    transliteration: 'Abd al-Ghaffār',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ghaffār, traduit ici par « Celui qui pardonne sans cesse ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ghaffār.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-qahhar',
    gender: 'boy',
    name: 'Abd al-Qahhār',
    arabic: 'عبد القهار',
    transliteration: 'Abd al-Qahhār',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Qahhār, traduit ici par « Le Dominateur suprême ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Qahhār.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-wahhab',
    gender: 'boy',
    name: 'Abd al-Wahhāb',
    arabic: 'عبد الوهاب',
    transliteration: 'Abd al-Wahhāb',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Wahhāb, traduit ici par « Le Grand Donateur ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Wahhāb.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-ar-razzaq',
    gender: 'boy',
    name: 'Abd ar-Razzāq',
    arabic: 'عبد الرزاق',
    transliteration: 'Abd ar-Razzāq',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Ar-Razzāq, traduit ici par « Le Pourvoyeur ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Ar-Razzāq.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-fattah',
    gender: 'boy',
    name: 'Abd al-Fattāḥ',
    arabic: 'عبد الفتاح',
    transliteration: 'Abd al-Fattāḥ',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Fattāḥ, traduit ici par « Celui qui ouvre et accorde la victoire ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Fattāḥ.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-alim',
    gender: 'boy',
    name: 'Abd al-‘Alīm',
    arabic: 'عبد العليم',
    transliteration: 'Abd al-‘Alīm',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-‘Alīm, traduit ici par « L’Omniscient ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-‘Alīm.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-qabid',
    gender: 'boy',
    name: 'Abd al-Qābiḍ',
    arabic: 'عبد القابض',
    transliteration: 'Abd al-Qābiḍ',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Qābiḍ, traduit ici par « Celui qui retient ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Qābiḍ.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-basit',
    gender: 'boy',
    name: 'Abd al-Bāsiṭ',
    arabic: 'عبد الباسط',
    transliteration: 'Abd al-Bāsiṭ',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Bāsiṭ, traduit ici par « Celui qui étend ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Bāsiṭ.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-khafid',
    gender: 'boy',
    name: 'Abd al-Khāfiḍ',
    arabic: 'عبد الخافض',
    transliteration: 'Abd al-Khāfiḍ',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Khāfiḍ, traduit ici par « Celui qui abaisse ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Khāfiḍ.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-ar-rafi',
    gender: 'boy',
    name: 'Abd ar-Rāfi’',
    arabic: 'عبد الرافع',
    transliteration: 'Abd ar-Rāfi’',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Ar-Rāfi’, traduit ici par « Celui qui élève ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Ar-Rāfi’.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muizz',
    gender: 'boy',
    name: 'Abd al-Mu‘izz',
    arabic: 'عبد المعز',
    transliteration: 'Abd al-Mu‘izz',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mu‘izz, traduit ici par « Celui qui honore ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mu‘izz.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mudhill',
    gender: 'boy',
    name: 'Abd al-Mudhill',
    arabic: 'عبد ٱلمذل',
    transliteration: 'Abd al-Mudhill',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mudhill, traduit ici par « Celui qui humilie ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mudhill.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-as-sami',
    gender: 'boy',
    name: 'Abd as-Samī‘',
    arabic: 'عبد السميع',
    transliteration: 'Abd as-Samī‘',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin As-Samī‘, traduit ici par « Celui qui entend tout ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est As-Samī‘.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-basir',
    gender: 'boy',
    name: 'Abd al-Baṣīr',
    arabic: 'عبد البصير',
    transliteration: 'Abd al-Baṣīr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Baṣīr, traduit ici par « Celui qui voit tout ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Baṣīr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-hakam',
    gender: 'boy',
    name: 'Abd al-Ḥakam',
    arabic: 'عبد الحكم',
    transliteration: 'Abd al-Ḥakam',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ḥakam, traduit ici par « Le Juge ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ḥakam.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-adl',
    gender: 'boy',
    name: 'Abd al-‘Adl',
    arabic: 'عبد العدل',
    transliteration: 'Abd al-‘Adl',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-‘Adl, traduit ici par « Le Parfaitement Juste ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-‘Adl.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-latif',
    gender: 'boy',
    name: 'Abd al-Laṭīf',
    arabic: 'عبد اللطيف',
    transliteration: 'Abd al-Laṭīf',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Laṭīf, traduit ici par « Le Subtil, Le Très Doux ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Laṭīf.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-khabir',
    gender: 'boy',
    name: 'Abd al-Khabīr',
    arabic: 'عبد الخبير',
    transliteration: 'Abd al-Khabīr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Khabīr, traduit ici par « Le Parfaitement Informé ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Khabīr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-halim',
    gender: 'boy',
    name: 'Abd al-Ḥalīm',
    arabic: 'عبد الحليم',
    transliteration: 'Abd al-Ḥalīm',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ḥalīm, traduit ici par « Le Très Clément ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ḥalīm.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-azim',
    gender: 'boy',
    name: 'Abd al-‘Aẓīm',
    arabic: 'عبد العظيم',
    transliteration: 'Abd al-‘Aẓīm',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-‘Aẓīm, traduit ici par « L’Immense, Le Magnifique ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-‘Aẓīm.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-ghafur',
    gender: 'boy',
    name: 'Abd al-Ghafūr',
    arabic: 'عبد الغفور',
    transliteration: 'Abd al-Ghafūr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ghafūr, traduit ici par « Le Grand Pardonneur ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ghafūr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-ash-shakur',
    gender: 'boy',
    name: 'Abd ash-Shakūr',
    arabic: 'عبد الشكور',
    transliteration: 'Abd ash-Shakūr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Ash-Shakūr, traduit ici par « Celui qui récompense abondamment ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Ash-Shakūr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-aliyy',
    gender: 'boy',
    name: 'Abd al-‘Aliyy',
    arabic: 'عبد العلي',
    transliteration: 'Abd al-‘Aliyy',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-‘Aliyy, traduit ici par « Le Très-Haut ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-‘Aliyy.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-kabir',
    gender: 'boy',
    name: 'Abd al-Kabīr',
    arabic: 'عبد الكبير',
    transliteration: 'Abd al-Kabīr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Kabīr, traduit ici par « Le Très Grand ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Kabīr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-hafiz',
    gender: 'boy',
    name: 'Abd al-Ḥafīẓ',
    arabic: 'عبد الحفيظ',
    transliteration: 'Abd al-Ḥafīẓ',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ḥafīẓ, traduit ici par « Le Préservateur ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ḥafīẓ.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muqit',
    gender: 'boy',
    name: 'Abd al-Muqīt',
    arabic: 'عبد المقيت',
    transliteration: 'Abd al-Muqīt',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muqīt, traduit ici par « Le Nourricier, Le Soutien ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muqīt.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-hasib',
    gender: 'boy',
    name: 'Abd al-Ḥasīb',
    arabic: 'عبد اﻟﺣسيب',
    transliteration: 'Abd al-Ḥasīb',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ḥasīb, traduit ici par « Celui qui suffit et tient compte ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ḥasīb.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-jalil',
    gender: 'boy',
    name: 'Abd al-Jalīl',
    arabic: 'عبد الجليل',
    transliteration: 'Abd al-Jalīl',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Jalīl, traduit ici par « Le Majestueux ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Jalīl.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-karim',
    gender: 'boy',
    name: 'Abd al-Karīm',
    arabic: 'عبد الكريم',
    transliteration: 'Abd al-Karīm',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Karīm, traduit ici par « Le Très Généreux ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Karīm.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-ar-raqib',
    gender: 'boy',
    name: 'Abd ar-Raqīb',
    arabic: 'عبد الرقيب',
    transliteration: 'Abd ar-Raqīb',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Ar-Raqīb, traduit ici par « Le Vigilant ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Ar-Raqīb.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mujib',
    gender: 'boy',
    name: 'Abd al-Mujīb',
    arabic: 'عبد ٱلمجيب',
    transliteration: 'Abd al-Mujīb',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mujīb, traduit ici par « Celui qui répond ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mujīb.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-wasi',
    gender: 'boy',
    name: 'Abd al-Wāsi‘',
    arabic: 'عبد الواسع',
    transliteration: 'Abd al-Wāsi‘',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Wāsi‘, traduit ici par « L’Immense, Celui qui embrasse toute chose ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Wāsi‘.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-hakim',
    gender: 'boy',
    name: 'Abd al-Ḥakīm',
    arabic: 'عبد الحكيم',
    transliteration: 'Abd al-Ḥakīm',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ḥakīm, traduit ici par « Le Parfaitement Sage ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ḥakīm.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-wadud',
    gender: 'boy',
    name: 'Abd al-Wadūd',
    arabic: 'عبد الودود',
    transliteration: 'Abd al-Wadūd',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Wadūd, traduit ici par « Le Très Aimant ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Wadūd.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-majid',
    gender: 'boy',
    name: 'Abd al-Majīd',
    arabic: 'عبد المجيد',
    transliteration: 'Abd al-Majīd',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Majīd, traduit ici par « Le Glorieux ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Majīd.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-baith',
    gender: 'boy',
    name: 'Abd al-Bā‘ith',
    arabic: 'عبد الباعث',
    transliteration: 'Abd al-Bā‘ith',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Bā‘ith, traduit ici par « Celui qui ressuscite ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Bā‘ith.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-ash-shahid',
    gender: 'boy',
    name: 'Abd ash-Shahīd',
    arabic: 'عبد الشهيد',
    transliteration: 'Abd ash-Shahīd',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Ash-Shahīd, traduit ici par « Le Témoin de toute chose ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Ash-Shahīd.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-haqq',
    gender: 'boy',
    name: 'Abd al-Ḥaqq',
    arabic: 'عبد الحق',
    transliteration: 'Abd al-Ḥaqq',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ḥaqq, traduit ici par « La Vérité absolue ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ḥaqq.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-wakil',
    gender: 'boy',
    name: 'Abd al-Wakīl',
    arabic: 'عبد الوكيل',
    transliteration: 'Abd al-Wakīl',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Wakīl, traduit ici par « Le Garant, Celui à qui l’on confie ses affaires ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Wakīl.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-qawiyy',
    gender: 'boy',
    name: 'Abd al-Qawiyy',
    arabic: 'عبد القوي',
    transliteration: 'Abd al-Qawiyy',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Qawiyy, traduit ici par « Le Très Fort ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Qawiyy.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-matin',
    gender: 'boy',
    name: 'Abd al-Matīn',
    arabic: 'عبد المتين',
    transliteration: 'Abd al-Matīn',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Matīn, traduit ici par « L’Inébranlable ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Matīn.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-waliyy',
    gender: 'boy',
    name: 'Abd al-Waliyy',
    arabic: 'عبد الولي',
    transliteration: 'Abd al-Waliyy',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Waliyy, traduit ici par « Le Protecteur proche ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Waliyy.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-hamid',
    gender: 'boy',
    name: 'Abd al-Ḥamīd',
    arabic: 'عبد الحميد',
    transliteration: 'Abd al-Ḥamīd',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ḥamīd, traduit ici par « Le Digne de louange ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ḥamīd.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muhsi',
    gender: 'boy',
    name: 'Abd al-Muḥṣī',
    arabic: 'عبد المحصي',
    transliteration: 'Abd al-Muḥṣī',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muḥṣī, traduit ici par « Celui qui dénombre toute chose ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muḥṣī.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mubdi',
    gender: 'boy',
    name: 'Abd al-Mubdi’',
    arabic: 'عبد المبدئ',
    transliteration: 'Abd al-Mubdi’',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mubdi’, traduit ici par « Celui qui initie la création ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mubdi’.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muid',
    gender: 'boy',
    name: 'Abd al-Mu‘īd',
    arabic: 'عبد ٱلمعيد',
    transliteration: 'Abd al-Mu‘īd',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mu‘īd, traduit ici par « Celui qui ramène et restaure ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mu‘īd.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muhyi',
    gender: 'boy',
    name: 'Abd al-Muḥyī',
    arabic: 'عبد المحيي',
    transliteration: 'Abd al-Muḥyī',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muḥyī, traduit ici par « Celui qui donne la vie ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muḥyī.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mumit',
    gender: 'boy',
    name: 'Abd al-Mumīt',
    arabic: 'عبد المميت',
    transliteration: 'Abd al-Mumīt',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mumīt, traduit ici par « Celui qui donne la mort ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mumīt.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-hayy',
    gender: 'boy',
    name: 'Abd al-Ḥayy',
    arabic: 'عبد الحي',
    transliteration: 'Abd al-Ḥayy',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ḥayy, traduit ici par « Le Vivant ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ḥayy.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-qayyum',
    gender: 'boy',
    name: 'Abd al-Qayyūm',
    arabic: 'عبد القيوم',
    transliteration: 'Abd al-Qayyūm',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Qayyūm, traduit ici par « Celui qui subsiste par Lui-même et soutient toute chose ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Qayyūm.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-wajid',
    gender: 'boy',
    name: 'Abd al-Wājid',
    arabic: 'عبد الواجد',
    transliteration: 'Abd al-Wājid',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Wājid, traduit ici par « Celui qui ne manque de rien ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Wājid.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-maajid',
    gender: 'boy',
    name: 'Abd al-Mājid',
    arabic: 'عبد الماجد',
    transliteration: 'Abd al-Mājid',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mājid, traduit ici par « L’Illustre, Le Magnifique ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mājid.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-wahid',
    gender: 'boy',
    name: 'Abd al-Wāḥid',
    arabic: 'عبد الواحد',
    transliteration: 'Abd al-Wāḥid',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Wāḥid, traduit ici par « L’Unique ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Wāḥid.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-ahad',
    gender: 'boy',
    name: 'Abd al-Aḥad',
    arabic: 'عبد الاحد',
    transliteration: 'Abd al-Aḥad',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Aḥad, traduit ici par « L’Un, L’Absolument Unique ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Aḥad.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-as-samad',
    gender: 'boy',
    name: 'Abd aṣ-Ṣamad',
    arabic: 'عبد الصمد',
    transliteration: 'Abd aṣ-Ṣamad',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Aṣ-Ṣamad, traduit ici par « L’Absolu, Celui dont tous dépendent ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Aṣ-Ṣamad.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-qadir',
    gender: 'boy',
    name: 'Abd al-Qādir',
    arabic: 'عبد القادر',
    transliteration: 'Abd al-Qādir',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Qādir, traduit ici par « Le Tout-Capable ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Qādir.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muqtadir',
    gender: 'boy',
    name: 'Abd al-Muqtadir',
    arabic: 'عبد المقتدر',
    transliteration: 'Abd al-Muqtadir',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muqtadir, traduit ici par « Le Parfaitement Puissant ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muqtadir.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muqaddim',
    gender: 'boy',
    name: 'Abd al-Muqaddim',
    arabic: 'عبد المقدم',
    transliteration: 'Abd al-Muqaddim',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muqaddim, traduit ici par « Celui qui fait avancer ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muqaddim.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muakhkhir',
    gender: 'boy',
    name: 'Abd al-Mu’akhkhir',
    arabic: 'عبد المؤخر',
    transliteration: 'Abd al-Mu’akhkhir',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mu’akhkhir, traduit ici par « Celui qui retarde ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mu’akhkhir.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-awwal',
    gender: 'boy',
    name: 'Abd al-Awwal',
    arabic: 'عبد الأول',
    transliteration: 'Abd al-Awwal',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Awwal, traduit ici par « Le Premier ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Awwal.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-akhir',
    gender: 'boy',
    name: 'Abd al-Ākhir',
    arabic: 'عبد الآخر',
    transliteration: 'Abd al-Ākhir',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ākhir, traduit ici par « Le Dernier ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ākhir.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-az-zahir',
    gender: 'boy',
    name: 'Abd aẓ-Ẓāhir',
    arabic: 'عبد الظاهر',
    transliteration: 'Abd aẓ-Ẓāhir',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Aẓ-Ẓāhir, traduit ici par « Le Manifeste ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Aẓ-Ẓāhir.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-batin',
    gender: 'boy',
    name: 'Abd al-Bāṭin',
    arabic: 'عبد الباطن',
    transliteration: 'Abd al-Bāṭin',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Bāṭin, traduit ici par « Le Caché, Celui qui connaît l’invisible ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Bāṭin.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-wali',
    gender: 'boy',
    name: 'Abd al-Wālī',
    arabic: 'عبد الوالي',
    transliteration: 'Abd al-Wālī',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Wālī, traduit ici par « Le Gouverneur suprême ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Wālī.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mutaali',
    gender: 'boy',
    name: 'Abd al-Muta‘ālī',
    arabic: 'عبد المتعالي',
    transliteration: 'Abd al-Muta‘ālī',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muta‘ālī, traduit ici par « Le Très Élevé ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muta‘ālī.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-barr',
    gender: 'boy',
    name: 'Abd al-Barr',
    arabic: 'عبد البر',
    transliteration: 'Abd al-Barr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Barr, traduit ici par « La Source de toute bonté ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Barr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-at-tawwab',
    gender: 'boy',
    name: 'Abd at-Tawwāb',
    arabic: 'عبد التواب',
    transliteration: 'Abd at-Tawwāb',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin At-Tawwāb, traduit ici par « Celui qui accueille sans cesse le repentir ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est At-Tawwāb.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muntaqim',
    gender: 'boy',
    name: 'Abd al-Muntaqim',
    arabic: 'عبد المنتقم',
    transliteration: 'Abd al-Muntaqim',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muntaqim, traduit ici par « Celui qui rétribue avec justice ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muntaqim.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-afuw',
    gender: 'boy',
    name: 'Abd al-‘Afūw',
    arabic: 'عبد العفو',
    transliteration: 'Abd al-‘Afūw',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-‘Afūw, traduit ici par « Celui qui efface les fautes ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-‘Afūw.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-ar-rauf',
    gender: 'boy',
    name: 'Abd ar-Ra’ūf',
    arabic: 'عبد الرؤوف',
    transliteration: 'Abd ar-Ra’ūf',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Ar-Ra’ūf, traduit ici par « Le Très Compatissant ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Ar-Ra’ūf.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-muqsit',
    gender: 'boy',
    name: 'Abd al-Muqsiṭ',
    arabic: 'عبد المقسط',
    transliteration: 'Abd al-Muqsiṭ',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Muqsiṭ, traduit ici par « Le Parfaitement Équitable ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Muqsiṭ.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-jami',
    gender: 'boy',
    name: 'Abd al-Jāmi‘',
    arabic: 'عبد الجامع',
    transliteration: 'Abd al-Jāmi‘',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Jāmi‘, traduit ici par « Le Rassembleur ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Jāmi‘.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-ghaniyy',
    gender: 'boy',
    name: 'Abd al-Ghaniyy',
    arabic: 'عبد ٱلغني',
    transliteration: 'Abd al-Ghaniyy',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Ghaniyy, traduit ici par « Celui qui se suffit à Lui-même ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Ghaniyy.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mughni',
    gender: 'boy',
    name: 'Abd al-Mughnī',
    arabic: 'عبد ٱلمغني',
    transliteration: 'Abd al-Mughnī',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Mughnī, traduit ici par « Celui qui enrichit ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Mughnī.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-mani',
    gender: 'boy',
    name: 'Abd al-Māni‘',
    arabic: 'عبد المانع',
    transliteration: 'Abd al-Māni‘',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Māni‘, traduit ici par « Celui qui empêche et protège ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Māni‘.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-ad-darr',
    gender: 'boy',
    name: 'Abd aḍ-Ḍārr',
    arabic: 'عبد الضار',
    transliteration: 'Abd aḍ-Ḍārr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Aḍ-Ḍārr, traduit ici par « Celui qui permet l’épreuve ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Aḍ-Ḍārr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-an-nafi',
    gender: 'boy',
    name: 'Abd an-Nāfi‘',
    arabic: 'عبد النافع',
    transliteration: 'Abd an-Nāfi‘',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin An-Nāfi‘, traduit ici par « Celui qui accorde le bienfait ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est An-Nāfi‘.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-an-nur',
    gender: 'boy',
    name: 'Abd an-Nūr',
    arabic: 'عبد النور',
    transliteration: 'Abd an-Nūr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin An-Nūr, traduit ici par « La Lumière ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est An-Nūr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-hadi',
    gender: 'boy',
    name: 'Abd al-Hādī',
    arabic: 'عبد الهادي',
    transliteration: 'Abd al-Hādī',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Hādī, traduit ici par « Le Guide ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Hādī.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-badi',
    gender: 'boy',
    name: 'Abd al-Badī‘',
    arabic: 'عبد البديع',
    transliteration: 'Abd al-Badī‘',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Badī‘, traduit ici par « L’Incomparable Créateur ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Badī‘.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-baqi',
    gender: 'boy',
    name: 'Abd al-Bāqī',
    arabic: 'عبد الباقي',
    transliteration: 'Abd al-Bāqī',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Bāqī, traduit ici par « L’Éternel, Celui qui demeure ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Bāqī.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-al-warith',
    gender: 'boy',
    name: 'Abd al-Wārith',
    arabic: 'عبد الوارث',
    transliteration: 'Abd al-Wārith',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Al-Wārith, traduit ici par « L’Héritier ultime ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Al-Wārith.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-ar-rashid',
    gender: 'boy',
    name: 'Abd ar-Rashīd',
    arabic: 'عبد الرشيد',
    transliteration: 'Abd ar-Rashīd',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Ar-Rashīd, traduit ici par « Le Guide vers la droiture ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Ar-Rashīd.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
  {
    id: 'abd-as-sabur',
    gender: 'boy',
    name: 'Abd aṣ-Ṣabūr',
    arabic: 'عبد الصبور',
    transliteration: 'Abd aṣ-Ṣabūr',
    origin: ['Arabe'],
    meaning: '« Serviteur de… » : construction avec le Nom divin Aṣ-Ṣabūr, traduit ici par « Le Très Patient ».',
    story: 'Ce prénom suit la construction arabe ʿAbd + un Nom d’Allah. Ici, le second élément est Aṣ-Ṣabūr.',
    status: 'permitted',
    statusReason: 'Construction de servitude vouée à Allah à travers l’un de Ses Noms. Elle est permise lorsque le second élément est bien un Nom divin établi ; cela ne signifie pas que chaque combinaison possède la même recommandation textuelle que Abdullah et Abd ar-Rahman.',
    variants: [],
    tags: ['foi'],
    editorialLevel: 'sourced',
    sourceNote: 'Référentiel interne OUMMAH des 99 Noms : Islamic Relief UK, contenu indiqué comme vérifié par Sheikh Dr. Saalim Al-Azhari. Principe de construction : ʿAbd + Nom d’Allah.',
  },
];