import type { MuslimName, NameTag } from './types';
import { CURATED_EXTRA_NAMES } from './curated-extra';
import { ABD_ALLAH_NAMES } from './abd-names';
import { EXTENDED_CURATED_NAMES } from './extended-curated';

export const NAME_TAG_LABELS: Record<NameTag, string> = {
  court: 'Court', rare: 'Rare', classique: 'Classique', coranique: 'Coranique', prophete: 'Prophètes',
  compagnon: 'Compagnons', sahabiyya: 'Sahabiyyat', foi: 'Foi', force: 'Force', sagesse: 'Sagesse', doux: 'Doux',
  'facile-france': 'Facile en français',
};

const P = 'Nom d’un prophète mentionné dans le Coran : un choix noble par son précédent, sans prétendre qu’un texte ordonne de porter ce prénom.';
const C = 'Nom porté par un Compagnon connu. Le mérite appartient à la personne ; le prénom reste un bon choix par son sens et son précédent.';
const S = 'Nom porté par une femme connue des premières générations musulmanes. Le précédent historique est noble, sans transformer le prénom en obligation religieuse.';

export const VERIFIED_MUSLIM_NAMES: MuslimName[] = [
  { id:'abdullah', gender:'boy', name:'Abdullah', arabic:'عبد الله', transliteration:'ʿAbd Allāh', pronunciation:'Ab-doul-lah', origin:['Arabe'], meaning:'Serviteur d’Allah.', story:'Nom composé de ʿabd, « serviteur », et Allah. Il exprime directement la servitude vouée à Allah.', status:'recommended', statusReason:'Le Prophète ﷺ a cité Abdullah parmi les noms les plus aimés d’Allah.', variants:['Abdallah','Abdullah'], tags:['classique','foi','facile-france'], historicalRole:'Nom porté par de nombreux Compagnons.', sourceNote:'Sahih Muslim 2132.' },
  { id:'abdurrahman', gender:'boy', name:'Abd ar-Rahman', arabic:'عبد الرحمن', transliteration:'ʿAbd ar-Raḥmān', pronunciation:'Abd ar-Rah-man', origin:['Arabe'], meaning:'Serviteur du Tout Miséricordieux.', story:'Nom composé de ʿabd, « serviteur », et ar-Rahman, l’un des noms d’Allah.', status:'recommended', statusReason:'Le Prophète ﷺ a cité Abd ar-Rahman parmi les noms les plus aimés d’Allah.', variants:['Abderrahmane','Abdurrahman','Abd al-Rahman'], tags:['classique','foi'], sourceNote:'Sahih Muslim 2132.' },
  { id:'muhammad', gender:'boy', name:'Muhammad', arabic:'محمد', transliteration:'Muḥammad', pronunciation:'Mou-ham-mad', origin:['Arabe'], meaning:'Celui qui est abondamment loué.', story:'Nom du dernier Prophète ﷺ, mentionné explicitement dans le Coran.', status:'recommended', statusReason:'Nom du Messager d’Allah ﷺ et nom de belle signification.', variants:['Mohammed','Mohamed','Muhammad'], tags:['classique','coranique','foi','facile-france'], historicalRole:'Nom du Prophète Muhammad ﷺ.', quranReference:'3:144 · 33:40 · 47:2 · 48:29' },
  { id:'ahmad', gender:'boy', name:'Ahmad', arabic:'أحمد', transliteration:'Aḥmad', pronunciation:'Ah-mad', origin:['Arabe'], meaning:'Très digne de louange ; celui qui loue beaucoup.', story:'Nom mentionné dans le Coran dans l’annonce faite par ʿIsa عليه السلام.', status:'recommended', statusReason:'Nom prophétique, de sens noble et explicitement mentionné dans le Coran.', variants:['Ahmed','Ahmad'], tags:['court','classique','coranique','foi','facile-france'], historicalRole:'Un des noms du Prophète ﷺ.', quranReference:'61:6' },

  { id:'adam', gender:'boy', name:'Adam', arabic:'آدم', transliteration:'Ādam', origin:['Sémitique'], meaning:'Nom sémitique traditionnellement rapproché de la terre / du sol ; dans l’Islam, nom du premier homme et prophète.', story:'Adam عليه السلام est le premier homme et un prophète dans la tradition islamique.', status:'recommended', statusReason:P, variants:['Adam','Âdam'], tags:['court','classique','coranique','prophete','facile-france'], historicalRole:'Prophète Adam عليه السلام.', quranReference:'Notamment 2:31-37' },
  { id:'idris', gender:'boy', name:'Idris', arabic:'إدريس', transliteration:'Idrīs', origin:['Sémitique','Usage arabe'], meaning:'Étymologie ancienne discutée ; dans l’usage musulman, le nom renvoie d’abord au prophète qui le porte.', story:'Idris عليه السلام est cité parmi les prophètes véridiques et patients.', status:'recommended', statusReason:P, variants:['Idris','Idriss'], tags:['court','coranique','prophete','rare','facile-france'], historicalRole:'Prophète Idris عليه السلام.', quranReference:'19:56-57 · 21:85' },
  { id:'nuh', gender:'boy', name:'Nuh', arabic:'نوح', transliteration:'Nūḥ', origin:['Sémitique','Usage arabe'], meaning:'Forme arabe de Noé ; le nom sémitique est traditionnellement rapproché du repos et de la consolation.', story:'Nuh عليه السلام est un messager majeur ; une sourate porte son nom.', status:'recommended', statusReason:P, variants:['Nouh','Nuh','Noûh'], tags:['court','rare','coranique','prophete'], historicalRole:'Prophète Nuh عليه السلام.', quranReference:'Sourate 71' },
  { id:'hud', gender:'boy', name:'Hud', arabic:'هود', transliteration:'Hūd', origin:['Sémitique','Usage arabe'], meaning:'Nom prophétique ancien ; son étymologie exacte n’est pas établie avec certitude.', story:'Hud عليه السلام fut envoyé au peuple de ʿAd.', status:'recommended', statusReason:P, variants:['Hud','Houd'], tags:['court','rare','coranique','prophete'], historicalRole:'Prophète Hud عليه السلام.', quranReference:'7:65 · Sourate 11' },
  { id:'salih', gender:'boy', name:'Salih', arabic:'صالح', transliteration:'Ṣāliḥ', origin:['Arabe'], meaning:'Vertueux, bon, intègre.', story:'Salih عليه السلام fut envoyé au peuple de Thamud.', status:'recommended', statusReason:P, variants:['Salih','Saleh','Salah'], tags:['coranique','prophete','foi'], historicalRole:'Prophète Salih عليه السلام.', quranReference:'7:73' },
  { id:'ibrahim', gender:'boy', name:'Ibrahim', arabic:'إبراهيم', transliteration:'Ibrāhīm', origin:['Sémitique','Usage arabe'], meaning:'Forme arabe d’Abraham ; traditionnellement interprété comme « père d’une multitude / de nombreux peuples ».', story:'Ibrahim عليه السلام occupe une place centrale dans le Coran et est décrit comme un modèle de foi.', status:'recommended', statusReason:P, variants:['Ibrahim','Ibrahîm'], tags:['classique','coranique','prophete','foi','facile-france'], historicalRole:'Prophète Ibrahim عليه السلام.', quranReference:'Notamment 2:124-132' },
  { id:'lut', gender:'boy', name:'Lut', arabic:'لوط', transliteration:'Lūṭ', origin:['Sémitique','Usage arabe'], meaning:'Forme arabe de Lot ; étymologie sémitique ancienne discutée, sans traduction française certaine.', story:'Lut عليه السلام est cité à plusieurs reprises dans le Coran.', status:'recommended', statusReason:P, variants:['Lut','Loth'], tags:['court','rare','coranique','prophete'], historicalRole:'Prophète Lut عليه السلام.', quranReference:'7:80-84' },
  { id:'ismail', gender:'boy', name:'Ismail', arabic:'إسماعيل', transliteration:'Ismāʿīl', origin:['Sémitique','Usage arabe'], meaning:'« Dieu entend / Allah a entendu », sens traditionnel du nom sémitique Ismaël.', story:'Ismail عليه السلام est loué dans le Coran pour sa fidélité à la promesse et sa patience.', status:'recommended', statusReason:P, variants:['Ismaïl','Ismail'], tags:['classique','coranique','prophete','facile-france'], historicalRole:'Prophète Ismail عليه السلام.', quranReference:'19:54-55' },
  { id:'ishaq', gender:'boy', name:'Ishaq', arabic:'إسحاق', transliteration:'Isḥāq', origin:['Sémitique','Usage arabe'], meaning:'« Il rira / il rit », sens traditionnel du nom sémitique Isaac.', story:'Ishaq عليه السلام est le fils d’Ibrahim et un prophète mentionné dans le Coran.', status:'recommended', statusReason:P, variants:['Ishaq','Ishak','Isaac'], tags:['rare','coranique','prophete'], historicalRole:'Prophète Ishaq عليه السلام.', quranReference:'11:71-73' },
  { id:'yaqub', gender:'boy', name:'Yaqub', arabic:'يعقوب', transliteration:'Yaʿqūb', origin:['Sémitique','Usage arabe'], meaning:'Forme arabe de Jacob ; nom sémitique traditionnellement lié au « talon » et, par extension, à celui qui suit.', story:'Yaqub عليه السلام, également appelé Israël, est le père de Yusuf.', status:'recommended', statusReason:P, variants:['Yaqub','Yacoub','Yaqoub'], tags:['rare','coranique','prophete'], historicalRole:'Prophète Yaqub عليه السلام.', quranReference:'12:6' },
  { id:'yusuf', gender:'boy', name:'Yusuf', arabic:'يوسف', transliteration:'Yūsuf', pronunciation:'You-souf', origin:['Sémitique','Usage arabe'], meaning:'« Dieu ajoute / qu’Il ajoute », sens traditionnel du nom sémitique Joseph / Yusuf.', story:'L’histoire de Yusuf عليه السلام occupe une sourate entière du Coran.', status:'recommended', statusReason:P, variants:['Youssef','Yusuf','Yusef'], tags:['court','classique','coranique','prophete','facile-france'], historicalRole:'Prophète Yusuf عليه السلام.', quranReference:'Sourate 12' },
  { id:'shuayb', gender:'boy', name:'Shuayb', arabic:'شعيب', transliteration:'Shuʿayb', origin:['Arabe'], meaning:'Ancien prénom arabe ; son étymologie précise est discutée selon les lexiques.', story:'Shuayb عليه السلام fut envoyé aux gens de Madyan.', status:'recommended', statusReason:P, variants:['Shuayb','Chouaib','Choaib'], tags:['rare','coranique','prophete'], historicalRole:'Prophète Shuayb عليه السلام.', quranReference:'7:85' },
  { id:'ayyub', gender:'boy', name:'Ayyub', arabic:'أيوب', transliteration:'Ayyūb', origin:['Sémitique','Usage arabe'], meaning:'Forme arabe de Job ; l’étymologie sémitique du nom est discutée et ne possède pas de traduction française certaine.', story:'Ayyub عليه السلام est associé à la patience dans l’épreuve.', status:'recommended', statusReason:P, variants:['Ayyub','Ayoub','Ayyoub'], tags:['coranique','prophete','sagesse','facile-france'], historicalRole:'Prophète Ayyub عليه السلام.', quranReference:'21:83-84' },
  { id:'musa', gender:'boy', name:'Musa', arabic:'موسى', transliteration:'Mūsā', origin:['Ancienne','Usage arabe'], meaning:'Forme arabe de Moïse ; l’étymologie est discutée, avec une tradition biblique le reliant au fait d’être « tiré des eaux ».', story:'Musa عليه السلام est le prophète le plus fréquemment nommé dans le Coran.', status:'recommended', statusReason:P, variants:['Moussa','Musa'], tags:['court','classique','coranique','prophete','facile-france'], historicalRole:'Prophète Musa عليه السلام.', quranReference:'Notamment sourates 20 et 28' },
  { id:'harun', gender:'boy', name:'Harun', arabic:'هارون', transliteration:'Hārūn', origin:['Sémitique','Usage arabe'], meaning:'Forme arabe d’Aaron ; l’étymologie sémitique est ancienne et discutée, sans traduction française unique certaine.', story:'Harun عليه السلام est le frère de Musa et son soutien dans la mission.', status:'recommended', statusReason:P, variants:['Harun','Haroun','Aaron'], tags:['coranique','prophete','facile-france'], historicalRole:'Prophète Harun عليه السلام.', quranReference:'20:29-36' },
  { id:'dawud', gender:'boy', name:'Dawud', arabic:'داود', transliteration:'Dāwūd', origin:['Sémitique','Usage arabe'], meaning:'« Bien-aimé », sens traditionnellement associé au nom sémitique David / Dawud.', story:'Dawud عليه السلام fut prophète et roi ; le Zabur lui fut donné.', status:'recommended', statusReason:P, variants:['Dawud','Daoud','Dâwûd'], tags:['coranique','prophete','force'], historicalRole:'Prophète Dawud عليه السلام.', quranReference:'4:163 · 17:55' },
  { id:'sulayman', gender:'boy', name:'Sulayman', arabic:'سليمان', transliteration:'Sulaymān', origin:['Sémitique','Usage arabe'], meaning:'« Homme de paix / paisible », nom sémitique apparenté à la racine de paix (s-l-m / sh-l-m).', story:'Sulayman عليه السلام fut prophète et roi, fils de Dawud.', status:'recommended', statusReason:P, variants:['Sulayman','Souleymane','Suleiman'], tags:['coranique','prophete','sagesse'], historicalRole:'Prophète Sulayman عليه السلام.', quranReference:'27:15-19' },
  { id:'ilyas', gender:'boy', name:'Ilyas', arabic:'إلياس', transliteration:'Ilyās', origin:['Sémitique','Usage arabe'], meaning:'Étymologie ancienne discutée ; dans l’usage musulman, le nom renvoie d’abord au prophète qui le porte.', story:'Ilyas عليه السلام est un prophète mentionné dans le Coran.', status:'recommended', statusReason:P, variants:['Ilyas','Ilyes','Elyas'], tags:['court','coranique','prophete','rare','facile-france'], historicalRole:'Prophète Ilyas عليه السلام.', quranReference:'6:85 · 37:123-132' },
  { id:'yunus', gender:'boy', name:'Yunus', arabic:'يونس', transliteration:'Yūnus', origin:['Sémitique','Usage arabe'], meaning:'Forme arabe de Jonas ; le nom sémitique est traditionnellement associé à la « colombe ».', story:'Yunus عليه السلام est notamment connu pour l’épreuve du grand poisson et son invocation.', status:'recommended', statusReason:P, variants:['Yunus','Younes','Younès'], tags:['court','coranique','prophete','facile-france'], historicalRole:'Prophète Yunus عليه السلام.', quranReference:'10:98 · 21:87-88' },
  { id:'zakariya', gender:'boy', name:'Zakariya', arabic:'زكريا', transliteration:'Zakariyyā', origin:['Sémitique','Usage arabe'], meaning:'« Dieu se souvient / Allah s’est souvenu », sens traditionnel du nom sémitique Zacharie.', story:'Zakariya عليه السلام invoqua Allah pour une descendance pieuse malgré son grand âge.', status:'recommended', statusReason:P, variants:['Zakariya','Zakaria','Zacharia'], tags:['coranique','prophete','foi'], historicalRole:'Prophète Zakariya عليه السلام.', quranReference:'3:37-41 · 19:2-11' },
  { id:'yahya', gender:'boy', name:'Yahya', arabic:'يحيى', transliteration:'Yaḥyā', origin:['Sémitique','Usage arabe'], meaning:'Nom donné au prophète Yahya ; lié en arabe à la vie.', story:'Le Coran indique que ce nom fut donné à Yahya عليه السلام par Allah.', status:'recommended', statusReason:P, variants:['Yahya','Yahia'], tags:['coranique','prophete','rare'], historicalRole:'Prophète Yahya عليه السلام.', quranReference:'19:7' },
  { id:'isa', gender:'boy', name:'Isa', arabic:'عيسى', transliteration:'ʿĪsā', origin:['Sémitique','Usage arabe'], meaning:'Forme arabe du nom de Jésus.', story:'ʿIsa عليه السلام, fils de Maryam, est un grand prophète et messager dans l’Islam.', status:'recommended', statusReason:P, variants:['Isa','Issa','Îsâ'], tags:['court','coranique','prophete','facile-france'], historicalRole:'Prophète ʿIsa عليه السلام.', quranReference:'3:45 · 19:34' },

  { id:'umar', gender:'boy', name:'Umar', arabic:'عمر', transliteration:'ʿUmar', origin:['Arabe'], meaning:'Associé à la vie et à la longévité dans l’usage lexical arabe.', story:'Nom de ʿUmar ibn al-Khattab رضي الله عنه, deuxième calife bien guidé.', status:'recommended', statusReason:C, variants:['Omar','Umar'], tags:['court','classique','compagnon','force','facile-france'], historicalRole:'ʿUmar ibn al-Khattab رضي الله عنه.' },
  { id:'ali', gender:'boy', name:'Ali', arabic:'علي', transliteration:'ʿAlī', origin:['Arabe'], meaning:'Élevé, noble.', story:'Nom de ʿAli ibn Abi Talib رضي الله عنه, cousin et gendre du Prophète ﷺ.', status:'recommended', statusReason:C, variants:['Ali','Aly'], tags:['court','classique','compagnon','force','facile-france'], historicalRole:'ʿAli ibn Abi Talib رضي الله عنه.' },
  { id:'bilal', gender:'boy', name:'Bilal', arabic:'بلال', transliteration:'Bilāl', origin:['Arabe'], meaning:'Humidité qui désaltère ; fraîcheur.', story:'Bilal ibn Rabah رضي الله عنه fut un Compagnon célèbre et muezzin du Prophète ﷺ.', status:'recommended', statusReason:C, variants:['Bilal','Bilâl'], tags:['court','classique','compagnon','facile-france'], historicalRole:'Bilal ibn Rabah رضي الله عنه.' },
  { id:'hamza', gender:'boy', name:'Hamza', arabic:'حمزة', transliteration:'Ḥamza', origin:['Arabe'], meaning:'Nom arabe ancien, associé dans l’usage à la force et à la fermeté.', story:'Hamza ibn ʿAbd al-Muttalib رضي الله عنه était l’oncle du Prophète ﷺ et un Compagnon majeur.', status:'recommended', statusReason:C, variants:['Hamza','Hamzah'], tags:['court','classique','compagnon','force','facile-france'], historicalRole:'Hamza ibn ʿAbd al-Muttalib رضي الله عنه.' },
  { id:'salman', gender:'boy', name:'Salman', arabic:'سلمان', transliteration:'Salmān', origin:['Arabe'], meaning:'Associé à la paix et à la sûreté.', story:'Salman al-Farisi رضي الله عنه est connu pour son long parcours vers la vérité.', status:'recommended', statusReason:C, variants:['Salman','Selman'], tags:['compagnon','sagesse','rare','facile-france'], historicalRole:'Salman al-Farisi رضي الله عنه.' },
  { id:'zayd', gender:'boy', name:'Zayd', arabic:'زيد', transliteration:'Zayd', origin:['Arabe'], meaning:'Accroissement, augmentation.', story:'Zayd ibn Haritha رضي الله عنه est le seul Compagnon nommé explicitement dans le Coran.', status:'recommended', statusReason:C, variants:['Zayd','Zaid','Zeid'], tags:['court','coranique','compagnon','facile-france'], historicalRole:'Zayd ibn Haritha رضي الله عنه.', quranReference:'33:37' },
  { id:'anas', gender:'boy', name:'Anas', arabic:'أنس', transliteration:'Anas', origin:['Arabe'], meaning:'Familiarité, cordialité, réconfort.', story:'Anas ibn Malik رضي الله عنه servit le Prophète ﷺ et transmit de nombreux hadiths.', status:'recommended', statusReason:C, variants:['Anas'], tags:['court','classique','compagnon','doux','facile-france'], historicalRole:'Anas ibn Malik رضي الله عنه.' },
  { id:'talha', gender:'boy', name:'Talha', arabic:'طلحة', transliteration:'Ṭalḥa', origin:['Arabe'], meaning:'Nom arabe ancien, également associé à un arbre.', story:'Talha ibn ʿUbayd Allah رضي الله عنه compte parmi les Compagnons éminents.', status:'recommended', statusReason:C, variants:['Talha','Talhah'], tags:['compagnon','rare'], historicalRole:'Talha ibn ʿUbayd Allah رضي الله عنه.' },
  { id:'zubayr', gender:'boy', name:'Zubayr', arabic:'الزبير', transliteration:'az-Zubayr', origin:['Arabe'], meaning:'Nom arabe ancien ; diminutif lexical lié à la fermeté.', story:'Az-Zubayr ibn al-ʿAwwam رضي الله عنه fut un Compagnon proche du Prophète ﷺ.', status:'recommended', statusReason:C, variants:['Zubayr','Zoubair','Zubair'], tags:['compagnon','force','rare'], historicalRole:'Az-Zubayr ibn al-ʿAwwam رضي الله عنه.' },
  { id:'saad', gender:'boy', name:'Saad', arabic:'سعد', transliteration:'Saʿd', origin:['Arabe'], meaning:'Bonheur, félicité, bonne fortune.', story:'Nom porté par plusieurs Compagnons, notamment Saʿd ibn Abi Waqqas رضي الله عنه.', status:'recommended', statusReason:C, variants:['Saad','Saʿd'], tags:['court','compagnon','doux','facile-france'], historicalRole:'Saʿd ibn Abi Waqqas رضي الله عنه.' },
  { id:'muadh', gender:'boy', name:'Muadh', arabic:'معاذ', transliteration:'Muʿādh', origin:['Arabe'], meaning:'Protégé, mis à l’abri.', story:'Muʿadh ibn Jabal رضي الله عنه était connu pour son savoir.', status:'recommended', statusReason:C, variants:['Muadh','Mouadh','Moaz'], tags:['compagnon','sagesse','rare'], historicalRole:'Muʿadh ibn Jabal رضي الله عنه.' },
  { id:'ammar', gender:'boy', name:'Ammar', arabic:'عمار', transliteration:'ʿAmmār', origin:['Arabe'], meaning:'Très bâtisseur ; celui qui fait vivre et prospérer.', story:'ʿAmmar ibn Yasir رضي الله عنه fut parmi les premiers musulmans.', status:'recommended', statusReason:C, variants:['Ammar','Amar'], tags:['compagnon','force','facile-france'], historicalRole:'ʿAmmar ibn Yasir رضي الله عنه.' },
  { id:'khalid', gender:'boy', name:'Khalid', arabic:'خالد', transliteration:'Khālid', origin:['Arabe'], meaning:'Durable, demeurant.', story:'Khalid ibn al-Walid رضي الله عنه fut un Compagnon et chef militaire célèbre.', status:'recommended', statusReason:C, variants:['Khalid','Khaled'], tags:['compagnon','force','classique','facile-france'], historicalRole:'Khalid ibn al-Walid رضي الله عنه.' },
  { id:'hasan', gender:'boy', name:'Hasan', arabic:'حسن', transliteration:'Ḥasan', origin:['Arabe'], meaning:'Beau, bon, excellent.', story:'Al-Hasan ibn ʿAli رضي الله عنهما était le petit-fils du Prophète ﷺ.', status:'recommended', statusReason:'Sens excellent et nom du petit-fils du Prophète ﷺ.', variants:['Hasan','Hassan'], tags:['court','classique','doux','facile-france'], historicalRole:'Al-Hasan ibn ʿAli رضي الله عنهما.' },
  { id:'husayn', gender:'boy', name:'Husayn', arabic:'حسين', transliteration:'Ḥusayn', origin:['Arabe'], meaning:'Diminutif affectueux de Hasan : beau, bon.', story:'Al-Husayn ibn ʿAli رضي الله عنهما était le petit-fils du Prophète ﷺ.', status:'recommended', statusReason:'Bon sens et nom du petit-fils du Prophète ﷺ.', variants:['Husayn','Hussein','Houssein'], tags:['classique','doux'], historicalRole:'Al-Husayn ibn ʿAli رضي الله عنهما.', nuance:'La variante « Houssem » est un autre prénom en arabe ; ne pas les confondre.' },

  { id:'rayyan', gender:'boy', name:'Rayan', arabic:'رَيَّان', transliteration:'Rayyān', pronunciation:'Ra-yan', origin:['Arabe'], meaning:'Bien abreuvé, désaltéré ; luxuriant, verdoyant.', story:'Ar-Rayyân est le nom d’une des huit portes du Paradis. Les jeûneurs y seront appelés et entreront par cette porte au Jour de la Résurrection.', status:'permitted', statusReason:'Sens positif et association religieuse authentiquement attestée. Le hadith décrit la porte ar-Rayyân ; il ne formule pas une recommandation explicite de donner ce prénom.', variants:['Rayyan','Rayane','Raiyan'], tags:['doux','foi','facile-france'], sourceNote:'Sahih al-Bukhari 1896 et 3257 ; Sahih Muslim 1152.' , sources:[{kind:'hadith',label:'Sahih al-Bukhari',reference:'Hadith 1896 — Ar-Rayyân est une porte du Paradis réservée aux jeûneurs.',url:'https://sunnah.com/bukhari/30/6',supports:['repère religieux','nom de la porte ar-Rayyân']},{kind:'hadith',label:'Sahih Muslim',reference:'Hadith 1152 — la porte Rayyân est réservée aux jeûneurs.',url:'https://sunnah.com/muslim:1152',supports:['repère religieux','nom de la porte ar-Rayyân']},{kind:'editorial',label:'INSEE · Fichier des prénoms',reference:'Données françaises de prénoms attribués entre 1900 et 2025 ; utilisées comme repère pour privilégier, lorsque c’est clair, la graphie la plus usuelle en France.',url:'https://www.insee.fr/fr/statistiques/8595130',supports:['usage de la graphie en France'],note:'La fréquence d’une graphie ne détermine ni son sens ni son statut religieux.'}] },
  { id:'luqman', gender:'boy', name:'Luqman', arabic:'لقمان', transliteration:'Luqmān', origin:['Ancienne','Usage arabe'], meaning:'Nom ancien dont l’étymologie exacte est discutée ; la fiche privilégie son repère historique plutôt qu’une traduction incertaine.', story:'Luqman est un homme sage auquel une sourate du Coran consacre un passage et des conseils à son fils.', status:'permitted', statusReason:'Bon précédent coranique. Son statut de prophète est discuté ; la majorité le présente comme un homme sage.', variants:['Luqman','Lokman','Louqman'], tags:['coranique','sagesse','rare'], historicalRole:'Luqman le sage.', quranReference:'31:12-19', nuance:'Ne pas le classer automatiquement parmi les prophètes.' },
  { id:'karim', gender:'boy', name:'Karim', arabic:'كريم', transliteration:'Karīm', origin:['Arabe'], meaning:'Généreux, noble, honorable.', story:'Adjectif arabe de belle signification, largement utilisé comme prénom.', status:'permitted', statusReason:'Sens positif. « Al-Karim » est aussi un nom divin lorsqu’il est employé avec l’article et le sens absolu ; « Karim » comme prénom humain est d’usage courant.', variants:['Karim','Kareem'], tags:['court','doux','facile-france'], nuance:'La nuance porte sur l’usage absolu des noms divins, pas sur l’adjectif humain « Karim ».' },
  { id:'hakim', gender:'boy', name:'Hakim', arabic:'حكيم', transliteration:'Ḥakīm', origin:['Arabe'], meaning:'Sage, judicieux.', story:'Adjectif arabe désignant une personne sage ou judicieuse.', status:'permitted', statusReason:'Sens positif dans l’usage humain.', variants:['Hakim','Hakim'], tags:['sagesse','facile-france'], nuance:'Comme pour certains attributs, l’usage humain relatif se distingue de l’attribut divin absolu « al-Hakim ».' },
  { id:'amin', gender:'boy', name:'Amin', arabic:'أمين', transliteration:'Amīn', origin:['Arabe'], meaning:'Digne de confiance, loyal.', story:'Prénom arabe fondé sur une qualité morale claire.', status:'permitted', statusReason:'Sens positif et aucune interdiction connue.', variants:['Amin','Amine'], tags:['court','doux','facile-france'] },
  { id:'samir', gender:'boy', name:'Samir', arabic:'سمير', transliteration:'Samīr', origin:['Arabe'], meaning:'Compagnon de conversation du soir.', story:'Prénom arabe culturel de sens social et agréable.', status:'permitted', statusReason:'Sens convenable et aucune interdiction connue.', variants:['Samir','Sameer'], tags:['facile-france','doux'] },

  { id:'maryam', gender:'girl', name:'Maryam', arabic:'مريم', transliteration:'Maryam', pronunciation:'Mar-yam', origin:['Sémitique','Usage arabe'], meaning:'Nom sémitique ancien ; son étymologie fait l’objet de plusieurs interprétations. Dans l’usage musulman, il renvoie avant tout à Maryam, mère de ʿIsa.', story:'Maryam عليها السلام est la seule femme nommée explicitement dans le Coran et une sourate porte son nom.', status:'recommended', statusReason:'Nom d’une femme exceptionnellement honorée dans le Coran et de bon précédent.', variants:['Maryam','Mariam','Meryem'], tags:['classique','coranique','foi','facile-france'], historicalRole:'Maryam bint ʿImran عليها السلام.', quranReference:'Sourate 19 · 3:42' },
  { id:'khadija', gender:'girl', name:'Khadija', arabic:'خديجة', transliteration:'Khadīja', origin:['Arabe'], meaning:'Nom arabe ancien ; étymologiquement lié à une naissance avant terme.', story:'Khadija bint Khuwaylid رضي الله عنها fut la première épouse du Prophète ﷺ et la première à croire en son message.', status:'recommended', statusReason:S, variants:['Khadija','Khadidja','Khadija'], tags:['classique','sahabiyya','foi','facile-france'], historicalRole:'Khadija bint Khuwaylid رضي الله عنها.' },
  { id:'aisha', gender:'girl', name:'Aisha', arabic:'عائشة', transliteration:'ʿĀʾisha', origin:['Arabe'], meaning:'Vivante, pleine de vie.', story:'ʿAisha رضي الله عنها fut épouse du Prophète ﷺ et une grande transmettrice de savoir.', status:'recommended', statusReason:S, variants:['Aisha','Aïcha','Ayesha'], tags:['classique','sahabiyya','sagesse','facile-france'], historicalRole:'ʿAisha bint Abi Bakr رضي الله عنها.' },
  { id:'fatima', gender:'girl', name:'Fatima', arabic:'فاطمة', transliteration:'Fāṭima', origin:['Arabe'], meaning:'Celle qui se sèvre / qui se détourne.', story:'Fatima az-Zahra رضي الله عنها était la fille du Prophète ﷺ.', status:'recommended', statusReason:S, variants:['Fatima','Fatma'], tags:['classique','sahabiyya','facile-france'], historicalRole:'Fatima bint Muhammad رضي الله عنها.' },
  { id:'hafsa', gender:'girl', name:'Hafsa', arabic:'حفصة', transliteration:'Ḥafṣa', origin:['Arabe'], meaning:'Jeune lionne.', story:'Hafsa bint ʿUmar رضي الله عنها fut épouse du Prophète ﷺ.', status:'recommended', statusReason:S, variants:['Hafsa','Hafssa'], tags:['court','sahabiyya','force'], historicalRole:'Hafsa bint ʿUmar رضي الله عنها.' },
  { id:'zaynab', gender:'girl', name:'Zaynab', arabic:'زينب', transliteration:'Zaynab', origin:['Arabe'], meaning:'Nom arabe ancien, traditionnellement associé à une belle plante ou à la beauté.', story:'Plusieurs femmes proches du Prophète ﷺ portaient ce nom. Il l’a également donné en remplacement de « Barrah » dans des récits authentiques.', status:'recommended', statusReason:S, variants:['Zaynab','Zeinab','Zeynep'], tags:['classique','sahabiyya','facile-france'], historicalRole:'Nom de plusieurs femmes de la Maison prophétique et des premières générations.', sourceNote:'Sahih Muslim 2140-2142 ; Sahih al-Bukhari 6192.' },
  { id:'ruqayya', gender:'girl', name:'Ruqayya', arabic:'رقية', transliteration:'Ruqayya', origin:['Arabe'], meaning:'Élévation, progression ; nom arabe ancien.', story:'Ruqayya رضي الله عنها était une fille du Prophète ﷺ.', status:'recommended', statusReason:S, variants:['Ruqayya','Roqaya','Rouqaya'], tags:['sahabiyya','doux'], historicalRole:'Ruqayya bint Muhammad رضي الله عنها.' },
  { id:'umm-kulthum', gender:'girl', name:'Umm Kulthum', arabic:'أم كلثوم', transliteration:'Umm Kulthūm', origin:['Arabe'], meaning:'Nom traditionnel composé ; « Umm » signifie mère de.', story:'Umm Kulthum رضي الله عنها était une fille du Prophète ﷺ. Le nom est historiquement utilisé comme prénom composé.', status:'recommended', statusReason:S, variants:['Oum Kalthoum','Umm Kulthum','Oum Koulthoum'], tags:['sahabiyya','classique'], historicalRole:'Umm Kulthum bint Muhammad رضي الله عنها.', nuance:'Historiquement, « Umm » peut fonctionner comme partie d’un nom ou d’une kunya selon le contexte.' },
  { id:'safiyya', gender:'girl', name:'Safiyya', arabic:'صفية', transliteration:'Ṣafiyya', origin:['Arabe'], meaning:'Pure, choisie, amie sincère.', story:'Safiyya bint Huyayy رضي الله عنها fut épouse du Prophète ﷺ.', status:'recommended', statusReason:S, variants:['Safiyya','Safia','Sofia?'], tags:['sahabiyya','doux','facile-france'], historicalRole:'Safiyya bint Huyayy رضي الله عنها.', nuance:'« Sofia » a généralement une autre origine ; ne pas l’assimiler automatiquement à Safiyya.' },
  { id:'sumayya', gender:'girl', name:'Sumayya', arabic:'سمية', transliteration:'Sumayya', origin:['Arabe'], meaning:'Ancien diminutif arabe ; le sens lexical précis est discuté, tandis que l’usage historique du prénom est bien établi.', story:'Sumayya bint Khayyat رضي الله عنها est connue comme l’une des premières martyres de l’Islam.', status:'recommended', statusReason:S, variants:['Sumayya','Soumaya','Soumeyya'], tags:['sahabiyya','force','facile-france'], historicalRole:'Sumayya bint Khayyat رضي الله عنها.' },
  { id:'asma', gender:'girl', name:'Asma', arabic:'أسماء', transliteration:'Asmāʾ', origin:['Arabe'], meaning:'Nom arabe ancien ; forme plurielle de « nom » dans la langue.', story:'Asma bint Abi Bakr رضي الله عنها est connue pour son courage et son rôle lors de l’Hégire.', status:'recommended', statusReason:S, variants:['Asma','Asmaa'], tags:['court','sahabiyya','force','facile-france'], historicalRole:'Asma bint Abi Bakr رضي الله عنها.' },
  { id:'juwayriya', gender:'girl', name:'Juwayriya', arabic:'جويرية', transliteration:'Juwayriya', origin:['Arabe'], meaning:'Diminutif arabe traditionnel de jāriya.', story:'Juwayriya رضي الله عنها fut épouse du Prophète ﷺ. Son nom précédent, Barrah, fut changé en Juwayriya.', status:'recommended', statusReason:S, variants:['Juwayriya','Jouwayriya','Juwairiya'], tags:['sahabiyya','rare'], historicalRole:'Juwayriya bint al-Harith رضي الله عنها.', sourceNote:'Sahih Muslim 2140.' },
  { id:'maymuna', gender:'girl', name:'Maymuna', arabic:'ميمونة', transliteration:'Maymūna', origin:['Arabe'], meaning:'Bénie, de bon augure.', story:'Maymuna bint al-Harith رضي الله عنها fut épouse du Prophète ﷺ.', status:'recommended', statusReason:S, variants:['Maymuna','Maimouna','Maymouna'], tags:['sahabiyya','doux'], historicalRole:'Maymuna bint al-Harith رضي الله عنها.' },
  { id:'nusaybah', gender:'girl', name:'Nusaybah', arabic:'نسيبة', transliteration:'Nusayba', origin:['Arabe'], meaning:'Ancien prénom arabe ; le sens lexical exact varie selon les analyses, mais l’usage historique du nom est bien attesté.', story:'Nusaybah bint Kaʿb رضي الله عنها est connue pour son courage et son engagement.', status:'recommended', statusReason:S, variants:['Nusaybah','Nousayba','Nusaiba'], tags:['sahabiyya','force','rare'], historicalRole:'Nusaybah bint Kaʿb رضي الله عنها.' },
  { id:'khawla', gender:'girl', name:'Khawla', arabic:'خولة', transliteration:'Khawla', origin:['Arabe'], meaning:'Jeune gazelle dans l’usage arabe classique.', story:'Nom porté par plusieurs femmes des premières générations musulmanes.', status:'recommended', statusReason:S, variants:['Khawla','Khaoula'], tags:['sahabiyya','doux','rare'], historicalRole:'Nom porté notamment par Khawla bint Thaʿlaba رضي الله عنها.' },

  { id:'amina', gender:'girl', name:'Amina', arabic:'آمنة', transliteration:'Āmina', origin:['Arabe'], meaning:'En sécurité, paisible, rassurée.', story:'Nom arabe classique de sens positif ; Amina bint Wahb était la mère du Prophète ﷺ.', status:'permitted', statusReason:'Sens positif et usage historique honorable.', variants:['Amina','Aminah'], tags:['classique','doux','facile-france'], historicalRole:'Amina bint Wahb, mère du Prophète ﷺ.' },
  { id:'salma', gender:'girl', name:'Salma', arabic:'سلمى', transliteration:'Salmā', origin:['Arabe'], meaning:'Paisible, saine et sauve.', story:'Prénom arabe ancien lié à la racine de paix et de sécurité.', status:'permitted', statusReason:'Sens positif et aucune interdiction connue.', variants:['Salma','Selma'], tags:['court','doux','facile-france'] },
  { id:'huda', gender:'girl', name:'Huda', arabic:'هدى', transliteration:'Hudā', origin:['Arabe'], meaning:'Guidée, direction, bonne orientation.', story:'Le mot hudā est très présent dans le Coran avec le sens de guidée ; son usage comme prénom est culturel.', status:'permitted', statusReason:'Sens positif. Le fait qu’un mot soit coranique ne crée pas à lui seul une recommandation spécifique comme prénom.', variants:['Huda','Houda'], tags:['court','coranique','foi','facile-france'] },
  { id:'nur', gender:'girl', name:'Nur', arabic:'نور', transliteration:'Nūr', origin:['Arabe'], meaning:'Lumière.', story:'Nūr est un mot coranique et un prénom largement utilisé pour les filles comme pour les garçons selon les cultures.', status:'permitted', statusReason:'Sens positif. Son caractère « coranique » décrit le mot, pas une recommandation nominative.', variants:['Nur','Nour','Noor'], tags:['court','coranique','doux','facile-france'], nuance:'Prénom mixte dans plusieurs cultures.' },
  { id:'rahma', gender:'girl', name:'Rahma', arabic:'رحمة', transliteration:'Raḥma', origin:['Arabe'], meaning:'Miséricorde, compassion.', story:'Mot central du vocabulaire coranique, devenu un prénom courant dans de nombreux pays.', status:'permitted', statusReason:'Sens très positif ; aucun texte ne fait de ce mot une recommandation nominative spécifique.', variants:['Rahma','Rahmah'], tags:['court','coranique','foi','doux','facile-france'] },
  { id:'iman', gender:'girl', name:'Iman', arabic:'إيمان', transliteration:'Īmān', origin:['Arabe'], meaning:'Foi.', story:'Mot religieux majeur en arabe, utilisé comme prénom dans de nombreuses cultures musulmanes.', status:'permitted', statusReason:'Sens positif. Comme pour tout nom-valeur, éviter d’en déduire une qualité garantie de la personne.', variants:['Iman','Imane'], tags:['court','foi','facile-france'] },
  { id:'safa', gender:'girl', name:'Safa', arabic:'صفا', transliteration:'Ṣafā', origin:['Arabe'], meaning:'Pureté, limpidité ; également nom du mont as-Safa.', story:'As-Safa est l’un des deux monts associés au saʿy du Hajj et de la ʿUmra.', status:'permitted', statusReason:'Sens positif et association religieuse connue ; pas de recommandation nominative spécifique.', variants:['Safa','Safaa'], tags:['court','coranique','foi','doux','facile-france'], quranReference:'2:158' },
  { id:'marwa', gender:'girl', name:'Marwa', arabic:'مروة', transliteration:'Marwa', origin:['Arabe'], meaning:'Pierre claire / silex blanc selon les usages lexicaux ; nom du mont al-Marwa.', story:'Al-Marwa est l’un des deux monts associés au saʿy.', status:'permitted', statusReason:'Sens convenable et association religieuse connue ; pas de recommandation nominative spécifique.', variants:['Marwa','Maroua'], tags:['court','coranique','foi','facile-france'], quranReference:'2:158' },
  { id:'tasnim', gender:'girl', name:'Tasnim', arabic:'تسنيم', transliteration:'Tasnīm', origin:['Arabe'], meaning:'Nom d’une source élevée du Paradis dans le Coran.', story:'Tasnim apparaît dans la description du Paradis.', status:'note', statusReason:'Le mot a un beau contexte coranique, mais être mentionné dans le Coran ne signifie pas automatiquement « prénom recommandé ».', variants:['Tasnim','Tesnim'], tags:['coranique','rare','doux','facile-france'], quranReference:'83:27-28' },
  { id:'salsabil', gender:'girl', name:'Salsabil', arabic:'سلسبيل', transliteration:'Salsabīl', origin:['Arabe'], meaning:'Nom d’une source du Paradis mentionnée dans le Coran.', story:'Le terme apparaît dans la description des boissons du Paradis.', status:'note', statusReason:'Beau contexte coranique, mais pas de recommandation nominative spécifique.', variants:['Salsabil','Salsabeel'], tags:['coranique','rare','doux'], quranReference:'76:18' },
  { id:'sidra', gender:'girl', name:'Sidra', arabic:'سدرة', transliteration:'Sidra', origin:['Arabe'], meaning:'Jujubier.', story:'Le terme sidra apparaît dans le Coran, notamment dans l’expression Sidrat al-Muntaha.', status:'note', statusReason:'Le mot a une association coranique, mais l’usage comme prénom relève d’un choix culturel permis.', variants:['Sidra'], tags:['coranique','rare','doux','facile-france'], quranReference:'53:14-16' },
  { id:'bushra', gender:'girl', name:'Bushra', arabic:'بشرى', transliteration:'Bushrā', origin:['Arabe'], meaning:'Bonne nouvelle, heureuse annonce.', story:'Mot arabe et coranique de sens positif.', status:'permitted', statusReason:'Sens positif et aucune interdiction connue.', variants:['Bushra','Bouchra'], tags:['coranique','doux','facile-france'] },
  { id:'najwa', gender:'girl', name:'Najwa', arabic:'نجوى', transliteration:'Najwā', origin:['Arabe'], meaning:'Confidence, conversation secrète.', story:'Mot arabe présent dans le Coran avec différents contextes.', status:'note', statusReason:'Le mot est linguistiquement valable mais ses contextes coraniques varient ; il ne faut pas lui attribuer automatiquement une valeur spirituelle positive.', variants:['Najwa','Nejwa'], tags:['coranique','rare'], nuance:'Exemple utile de mot coranique dont la présence dans le texte ne suffit pas à établir une recommandation.' },
  { id:'aya', gender:'girl', name:'Aya', arabic:'آية', transliteration:'Āya', origin:['Arabe'], meaning:'Signe, preuve ; verset dans l’usage coranique.', story:'Āya est un terme central du Coran, employé pour les signes d’Allah et les versets.', status:'permitted', statusReason:'Sens positif ; l’usage comme prénom est culturel et permis.', variants:['Aya','Ayah'], tags:['court','coranique','foi','facile-france'] },
  { id:'lin', gender:'girl', name:'Lin', arabic:'لين', transliteration:'Līn', origin:['Arabe','Autres langues possibles'], meaning:'Douceur, souplesse en arabe.', story:'Prénom très court dont le son peut aussi exister dans d’autres langues avec des origines différentes.', status:'note', statusReason:'Permis si le sens arabe de douceur est visé ; vérifier l’origine retenue lorsque la famille lui attribue une autre étymologie.', variants:['Lin','Lynn','Leen'], tags:['court','doux','rare','facile-france'], nuance:'Même graphie sonore, plusieurs origines possibles.' },
  { id:'inaya', gender:'girl', name:'Inaya', arabic:'عناية', transliteration:'ʿInāya', origin:['Arabe'], meaning:'Soin, attention, sollicitude.', story:'Prénom moderne dérivé d’un mot arabe clair.', status:'permitted', statusReason:'Sens positif et aucune interdiction connue.', variants:['Inaya','Inayah'], tags:['doux','facile-france'] },
  { id:'amal', gender:'girl', name:'Amal', arabic:'أمل', transliteration:'Amal', origin:['Arabe'], meaning:'Espoir.', story:'Prénom arabe court fondé sur un mot de sens positif.', status:'permitted', statusReason:'Sens positif et aucune interdiction connue.', variants:['Amal'], tags:['court','doux','facile-france'] },
  { id:'hayat', gender:'girl', name:'Hayat', arabic:'حياة', transliteration:'Ḥayāt', origin:['Arabe'], meaning:'Vie.', story:'Mot arabe courant et présent dans le Coran, utilisé comme prénom.', status:'permitted', statusReason:'Sens positif et aucune interdiction connue.', variants:['Hayat','Hayet'], tags:['coranique','facile-france'] },
];

export const EDITORIAL_MUSLIM_NAMES: MuslimName[] = [
  ...VERIFIED_MUSLIM_NAMES,
  ...CURATED_EXTRA_NAMES.filter((candidate) => !VERIFIED_MUSLIM_NAMES.some((item) => normalizeNameSearch(item.name) === normalizeNameSearch(candidate.name))),
  ...EXTENDED_CURATED_NAMES.filter((candidate) => ![...VERIFIED_MUSLIM_NAMES, ...CURATED_EXTRA_NAMES].some((item) => normalizeNameSearch(item.name) === normalizeNameSearch(candidate.name))),
  ...ABD_ALLAH_NAMES.filter((candidate) => !VERIFIED_MUSLIM_NAMES.some((item) => normalizeNameSearch(item.name) === normalizeNameSearch(candidate.name))),
];


function dedupeByStableId(names: MuslimName[]) {
  const seen = new Set<string>();
  return names.filter((item) => {
    if (seen.has(item.id)) return false;
    seen.add(item.id);
    return true;
  });
}

export const MUSLIM_NAMES: MuslimName[] = dedupeByStableId(EDITORIAL_MUSLIM_NAMES).map((item) => ({
  ...item,
  variants: buildVariants(item),
  editorialLevel: item.editorialLevel ?? (item.sourceNote || item.quranReference ? 'sourced' as const : 'reviewed' as const),
}));


function buildVariants(item: MuslimName) {
  const raw = [item.name, item.transliteration, ...item.variants];
  const expanded = raw.flatMap((value) => {
    const plain = value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[ʿʾ’‘]/g, '').replace(/\s+/g, ' ').trim();
    const french = plain
      .replace(/^Abd ar-/i, 'Abder')
      .replace(/^Abd al-/i, 'Abdel')
      .replace(/kh/gi, 'kh');
    return [value, plain, french];
  });
  return Array.from(new Set(expanded.filter(Boolean))).filter((value) => value !== item.name).slice(0, 12);
}

export function isAbdName(item: MuslimName) {
  const normalized = normalizeNameSearch(item.name);
  return item.gender === 'boy' && (item.id.startsWith('abd-') || normalized.startsWith('abd ') || normalized.startsWith('abdel') || normalized.startsWith('abder'));
}

export const ABD_NAMES = MUSLIM_NAMES.filter(isAbdName);
export const NON_ABD_NAMES = MUSLIM_NAMES.filter((item) => !isAbdName(item));
export const VERIFIED_NAMES = MUSLIM_NAMES.filter((item) => item.editorialLevel !== 'catalogue');
export const CATALOGUE_NAMES = MUSLIM_NAMES.filter((item) => item.editorialLevel === 'catalogue');
export const BOY_NAMES = MUSLIM_NAMES.filter((item) => item.gender === 'boy');
export const GIRL_NAMES = MUSLIM_NAMES.filter((item) => item.gender === 'girl');

export function getMuslimName(value?: string | string[]) {
  const id = Array.isArray(value) ? value[0] : value;
  return MUSLIM_NAMES.find((item) => item.id === id);
}

export function normalizeNameSearch(value: string) {
  return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[ʿʾ’'`-]/g, ' ').replace(/\s+/g, ' ').trim();
}

export function searchMuslimNames(query: string, names = MUSLIM_NAMES) {
  const needle = normalizeNameSearch(query);
  if (!needle) return names;
  return names.filter((item) => normalizeNameSearch([item.name,item.arabic,item.transliteration,item.meaning,item.origin.join(' '),item.variants.join(' '),item.historicalRole ?? ''].join(' ')).includes(needle));
}
