import type { MuslimName, NameTag } from './types';

const permitted = 'Sens positif ou neutre et aucun problème religieux connu dans cet usage.';
const lexicalSource = 'Sens lexical arabe courant, synthèse éditoriale OUMMAH. À distinguer d’une recommandation religieuse spécifique.';

function n(
  id:string, gender:'boy'|'girl', name:string, arabic:string, transliteration:string,
  meaning:string, variants:string[], tags:NameTag[] = [], origin:string[]=['Arabe'],
  story?:string,
): MuslimName {
  return {
    id, gender, name, arabic, transliteration, origin, meaning,
    story: story ?? `Prénom ${origin.join(' / ').toLowerCase()} utilisé dans plusieurs familles musulmanes. La fiche retient ici son sens lexical le plus courant.`,
    status:'permitted', statusReason:permitted, variants, tags,
    editorialLevel:'reviewed', meaningConfidence:'medium', sourceNote:lexicalSource,
  };
}

export const CURATED_EXTRA_NAMES: MuslimName[] = [
  // Garçons
  n('adil','boy','Adil','عادل','ʿĀdil','Juste, équitable, droit.',['Adil','Adel','Aadil'],['court','sagesse','facile-france']),
  n('amir','boy','Amir','أمير','Amīr','Prince, commandant, chef.',['Amir','Emir','Ameer'],['court','classique','facile-france']),
  n('amin','boy','Amin','أمين','Amīn','Digne de confiance, loyal, sûr.',['Amin','Amine','Ameen'],['court','classique','facile-france']),
  n('anas','boy','Anas','أنس','Anas','Affection, familiarité, présence rassurante.',['Anas','Anass'],['court','compagnon','doux','facile-france']),
  n('asim','boy','Asim','عاصم','ʿĀṣim','Protecteur, celui qui préserve.',['Asim','Assim','Aasim'],['court','force','facile-france']),
  n('aziz','boy','Aziz','عزيز','ʿAzīz','Cher, précieux, puissant, estimé.',['Aziz','Azziz'],['court','force','facile-france']),
  n('badir','boy','Badr','بدر','Badr','Pleine lune.',['Badr','Bader','Badre'],['court','classique','facile-france']),
  n('bashir','boy','Bashir','بشير','Bashīr','Porteur de bonne nouvelle.',['Bashir','Bachir','Basheer'],['foi','facile-france']),
  n('bassam','boy','Bassam','بسّام','Bassām','Très souriant, jovial.',['Bassam','Bessam'],['doux','facile-france']),
  n('bilal','boy','Bilal','بلال','Bilāl','Humidité, eau fraîche ; nom célèbre du Compagnon Bilal ibn Rabah.',['Bilal','Bilel'],['compagnon','classique','facile-france']),
  n('burhan','boy','Burhan','برهان','Burhān','Preuve claire, argument décisif.',['Burhan','Borhan','Bourhane'],['coranique','sagesse']),
  n('danish','boy','Danish','دانش','Dānesh','Savoir, connaissance.',['Danish','Danesh'],['sagesse','rare'],['Perse']),
  n('dawud2','boy','Daoud','داود','Dāwūd','Forme française courante de Dawud, nom d’un prophète.',['Daoud','Dawud','Dawoud','David'],['prophete','coranique','facile-france'],['Sémitique','Usage arabe']),
  n('fadil','boy','Fadil','فاضل','Fāḍil','Vertueux, excellent, méritant.',['Fadil','Fadel','Fadhel'],['sagesse','facile-france']),
  n('fahd','boy','Fahd','فهد','Fahd','Léopard, panthère.',['Fahd','Fahed'],['court','force']),
  n('fahim','boy','Fahim','فهيم','Fahīm','Intelligent, compréhensif, perspicace.',['Fahim','Faheem'],['sagesse']),
  n('faisal','boy','Faisal','فيصل','Fayṣal','Celui qui tranche, arbitre, décide avec discernement.',['Faisal','Fayçal','Faysal','Feisal'],['sagesse','force']),
  n('faris','boy','Faris','فارس','Fāris','Cavalier, chevalier.',['Faris','Fares','Farès'],['force','facile-france']),
  n('faruq','boy','Faruq','فاروق','Fārūq','Celui qui distingue le vrai du faux.',['Faruq','Farouk','Farooq'],['sagesse','compagnon']),
  n('ghazi','boy','Ghazi','غازي','Ghāzī','Combattant, celui qui part en expédition.',['Ghazi','Gazi'],['force','rare']),
  n('habib','boy','Habib','حبيب','Ḥabīb','Bien-aimé, cher.',['Habib','Habib'],['doux','classique','facile-france']),
  n('hadi','boy','Hadi','هادي','Hādī','Guide, celui qui conduit.',['Hadi','Hady'],['court','foi','facile-france']),
  n('hakim','boy','Hakim','حكيم','Ḥakīm','Sage, judicieux.',['Hakim','Hakeem'],['sagesse','facile-france']),
  n('hamid','boy','Hamid','حامد','Ḥāmid','Celui qui loue, reconnaissant.',['Hamid','Hamed','Hameed'],['foi','facile-france']),
  n('hassan','boy','Hassan','حسن','Ḥasan','Beau, bon, excellent.',['Hassan','Hasan','Hacen'],['classique','facile-france']),
  n('haytham','boy','Haytham','هيثم','Haytham','Jeune aigle ou jeune faucon, selon l’usage lexical classique.',['Haytham','Haitham','Haithem'],['force','rare']),
  n('hilal','boy','Hilal','هلال','Hilāl','Croissant de lune.',['Hilal','Hilel'],['court','doux','facile-france']),
  n('hisham','boy','Hisham','هشام','Hishām','Générosité ; celui qui brise le pain pour le partager, selon l’étymologie traditionnelle.',['Hisham','Hichem','Hicham'],['classique','facile-france']),
  n('ihsan','boy','Ihsan','إحسان','Iḥsān','Excellence, bienfaisance, faire le bien de la meilleure manière.',['Ihsan','Ihsane'],['foi','sagesse']),
  n('ikram','boy','Ikram','إكرام','Ikrām','Honneur, générosité, fait d’honorer.',['Ikram','Ekram'],['coranique','doux']),
  n('imad','boy','Imad','عماد','ʿImād','Pilier, soutien, appui.',['Imad','Emad'],['court','force','facile-france']),
  n('iyad','boy','Iyad','إياد','Iyād','Soutien, appui, force.',['Iyad','Eyad','Iyyad'],['court','force','facile-france']),
  n('jalal','boy','Jalal','جلال','Jalāl','Majesté, grandeur, dignité.',['Jalal','Djalal'],['force']),
  n('jamal','boy','Jamal','جمال','Jamāl','Beauté.',['Jamal','Djamel','Jamel'],['classique','facile-france']),
  n('jamil','boy','Jamil','جميل','Jamīl','Beau, agréable.',['Jamil','Djamil','Jamel'],['doux','facile-france']),
  n('jawad','boy','Jawad','جواد','Jawād','Généreux ; également cheval de qualité dans l’arabe classique.',['Jawad','Jaouad','Djawad'],['sagesse','facile-france']),
  n('kamil','boy','Kamil','كامل','Kāmil','Complet, accompli.',['Kamil','Kamel','Kaamil'],['sagesse','facile-france']),
  n('karim','boy','Karim','كريم','Karīm','Généreux, noble.',['Karim','Kareem'],['classique','sagesse','facile-france']),
  n('khalil','boy','Khalil','خليل','Khalīl','Ami intime, compagnon proche.',['Khalil','Khelil'],['doux','classique','facile-france']),
  n('luay','boy','Luay','لؤي','Luʾayy','Petit taureau sauvage ; ancien prénom arabe.',['Luay','Louay','Loay'],['rare','facile-france']),
  n('maher','boy','Maher','ماهر','Māhir','Habile, compétent, talentueux.',['Maher','Mahir'],['sagesse','facile-france']),
  n('majid','boy','Majid','ماجد','Mājid','Glorieux, noble, illustre.',['Majid','Majed','Maged'],['sagesse']),
  n('malik','boy','Malik','مالك','Mālik','Possesseur, maître ; aussi nom de l’ange gardien de l’Enfer dans le Coran.',['Malik','Malek'],['classique','coranique','facile-france']),
  n('mansur','boy','Mansur','منصور','Manṣūr','Victorieux, secouru.',['Mansur','Mansour','Mansoor'],['force','facile-france']),
  n('marwan','boy','Marwan','مروان','Marwān','Ancien prénom arabe ; associé au marw, une pierre claire ou silex.',['Marwan','Marouane','Merouane'],['classique','facile-france']),
  n('mazin','boy','Mazin','مازن','Māzin','Nuage porteur de pluie ; ancien prénom arabe.',['Mazin','Mazen'],['doux','rare']),
  n('munir','boy','Munir','منير','Munīr','Lumineux, rayonnant.',['Munir','Mounir','Muneer'],['coranique','doux','facile-france']),
  n('nadim','boy','Nadim','نديم','Nadīm','Compagnon de conversation, ami de veillée.',['Nadim','Nadeem'],['doux','facile-france']),
  n('nadir','boy','Nadir','نادر','Nādir','Rare, précieux par sa rareté.',['Nadir','Nader'],['rare','facile-france']),
  n('nasir','boy','Nasir','ناصر','Nāṣir','Soutien, défenseur, secoureur.',['Nasir','Nasser','Nacer'],['force','facile-france']),
  n('nawfal','boy','Nawfal','نوفل','Nawfal','Généreux ; également ancien terme arabe lié à l’abondance.',['Nawfal','Naufal','Noufel'],['rare']),
  n('qasim','boy','Qasim','قاسم','Qāsim','Celui qui partage, répartit.',['Qasim','Kacem','Kassem','Qassem'],['classique','facile-france']),
  n('rafiq','boy','Rafiq','رفيق','Rafīq','Compagnon, ami, doux dans la compagnie.',['Rafiq','Rafik','Rafeeq'],['doux','facile-france']),
  n('rami','boy','Rami','رامي','Rāmī','Archer, tireur ; celui qui lance.',['Rami','Ramy'],['court','facile-france']),
  n('rashid','boy','Rashid','رشيد','Rashīd','Bien guidé, raisonnable, mûr.',['Rashid','Rachid','Rasheed'],['sagesse','foi','facile-france']),
  n('rayyan','boy','Rayyan','ريان','Rayyān','Bien irrigué, désaltéré, luxuriant ; nom d’une porte du Paradis dans un hadith authentique.',['Rayyan','Rayan','Rayane','Raiyan'],['foi','doux','facile-france']),
  n('ridwan','boy','Ridwan','رضوان','Riḍwān','Satisfaction, agrément.',['Ridwan','Redouane','Ridhwan'],['foi','facile-france']),
  n('sabir','boy','Sabir','صابر','Ṣābir','Patient, persévérant.',['Sabir','Saber'],['foi','sagesse']),
  n('sadiq','boy','Sadiq','صادق','Ṣādiq','Véridique, sincère.',['Sadiq','Sadek','Sadeq'],['foi','sagesse']),
  n('sami','boy','Sami','سامي','Sāmī','Élevé, noble, sublime.',['Sami','Samy'],['court','facile-france']),
  n('samir','boy','Samir','سمير','Samīr','Compagnon de veillée, agréable interlocuteur du soir.',['Samir','Sameer'],['doux','facile-france']),
  n('shakir','boy','Shakir','شاكر','Shākir','Reconnaissant, celui qui remercie.',['Shakir','Chakir','Shakeer'],['foi','sagesse']),
  n('suhayl','boy','Suhayl','سهيل','Suhayl','Doux, facile ; également nom de l’étoile Canopus dans la tradition arabe.',['Suhayl','Souheil','Sohail','Souhail'],['doux','rare']),
  n('taha2','boy','Taha','طه','Ṭā-Hā','Nom traditionnellement utilisé comme prénom à partir des lettres ouvrant la sourate 20.',['Taha','Ta-Ha'],['coranique','court','facile-france']),
  n('tariq','boy','Tariq','طارق','Ṭāriq','Celui qui vient de nuit ; l’astre nocturne qui frappe, dans le contexte coranique.',['Tariq','Tarek','Tarik'],['coranique','force','facile-france']),
  n('tayyib','boy','Tayyib','طيب','Ṭayyib','Bon, pur, agréable.',['Tayyib','Taieb','Tayeb'],['foi']),
  n('wael','boy','Wael','وائل','Wāʾil','Celui qui cherche refuge, qui revient vers un abri.',['Wael','Waël','Wail'],['court','facile-france']),
  n('walid','boy','Walid','وليد','Walīd','Nouveau-né, jeune enfant.',['Walid','Waleed'],['classique','facile-france']),
  n('yamin','boy','Yamin','يمين','Yamīn','Main droite ; côté droit ; serment selon le contexte.',['Yamin','Yamine'],['facile-france']),
  n('yasin2','boy','Yasin','يس','Yā-Sīn','Nom traditionnellement utilisé comme prénom à partir des lettres ouvrant la sourate 36.',['Yasin','Yassine','Yacine','Yaseen'],['coranique','classique','facile-france']),
  n('zahir','boy','Zahir','ظاهر','Ẓāhir','Apparent, manifeste, éclatant.',['Zahir','Dahir'],['sagesse']),
  n('zaid','boy','Zaid','زيد','Zayd','Accroissement, augmentation, abondance.',['Zaid','Zayd','Zeid'],['compagnon','court','facile-france']),
  n('zaki','boy','Zaki','زكي','Zakī','Pur, vertueux, intelligent.',['Zaki','Zaky'],['court','foi','facile-france']),
  n('zayn','boy','Zayn','زين','Zayn','Beauté, ornement, grâce.',['Zayn','Zain','Zein'],['court','doux','facile-france']),
  n('ziyad','boy','Ziyad','زياد','Ziyād','Croissance, augmentation, abondance.',['Ziyad','Ziad'],['facile-france']),

  // Filles
  n('abir','girl','Abir','عبير','ʿAbīr','Parfum, senteur agréable.',['Abir','Abeer'],['doux','facile-france']),
  n('adila','girl','Adila','عادلة','ʿĀdila','Juste, équitable.',['Adila','Adela','Aadila'],['sagesse','facile-france']),
  n('afaf','girl','Afaf','عفاف','ʿAfāf','Chasteté, pudeur, vertu.',['Afaf','Afaaf'],['foi','sagesse']),
  n('afra','girl','Afra','عفراء','ʿAfrāʾ','Blancheur légèrement rosée ; ancien prénom arabe.',['Afra','Afraa'],['doux','rare']),
  n('alia','girl','Alia','عالية','ʿĀliya','Élevée, noble, de haut rang.',['Alia','Aliya','Aaliyah','Alya'],['doux','facile-france']),
  n('alya2','girl','Alya','عليا','ʿUlyā / ʿAlyā','Très élevée, sublime ; selon la graphie arabe retenue.',['Alya','Alia','Aliya'],['doux','facile-france']),
  n('amira','girl','Amira','أميرة','Amīra','Princesse, femme qui commande.',['Amira','Emira'],['classique','doux','facile-france']),
  n('anisah','girl','Anisa','أنيسة','Anīsa','Amicale, sociable, réconfortante.',['Anisa','Anissa','Anisah'],['doux','facile-france']),
  n('arwa','girl','Arwa','أروى','Arwā','Gracieuse ; peut aussi désigner la femelle du bouquetin dans l’arabe classique.',['Arwa','Aroua'],['sahabiyya','doux','rare']),
  n('asmaa2','girl','Asma','أسماء','Asmāʾ','Nom propre arabe ancien ; traditionnellement compris comme « élevée, sublime » ou pluriel de « nom » selon l’analyse.',['Asma','Asmaa'],['sahabiyya','classique','facile-france']),
  n('ayat','girl','Ayat','آيات','Āyāt','Signes, versets ; pluriel de āya.',['Ayat','Ayaat'],['coranique','foi']),
  n('basma','girl','Basma','بسمة','Basma','Sourire.',['Basma','Bessma'],['doux','facile-france']),
  n('batul','girl','Batul','بتول','Batūl','Dévouée, chaste, qui se consacre.',['Batul','Batoul','Batool'],['foi','rare']),
  n('dalia','girl','Dalia','دالية','Dāliya','Vigne, branche de vigne ; le prénom peut aussi avoir d’autres origines selon les cultures.',['Dalia','Dalya'],['doux','facile-france']),
  n('dima','girl','Dima','ديمة','Dīma','Pluie douce et continue, sans tonnerre.',['Dima','Deema'],['doux','rare','facile-france']),
  n('duha','girl','Duha','ضحى','Ḍuḥā','Matinée, clarté du matin.',['Duha','Doha','Douha'],['coranique','doux']),
  n('farah','girl','Farah','فرح','Faraḥ','Joie, bonheur.',['Farah','Fara'],['doux','facile-france']),
  n('farida','girl','Farida','فريدة','Farīda','Unique, incomparable, précieuse.',['Farida','Ferida'],['doux','facile-france']),
  n('ghada','girl','Ghada','غادة','Ghāda','Jeune femme gracieuse ; souplesse et délicatesse dans l’arabe classique.',['Ghada','Ghadaa'],['doux','rare']),
  n('ghalia','girl','Ghalia','غالية','Ghāliya','Précieuse, chère, de grande valeur.',['Ghalia','Ghalya','Ralia'],['doux','facile-france']),
  n('habiba','girl','Habiba','حبيبة','Ḥabība','Bien-aimée, chère.',['Habiba','Habibah'],['doux','classique']),
  n('hadiya','girl','Hadiya','هادية','Hādiya','Celle qui guide ; calme, posée selon l’usage.',['Hadiya','Hadya'],['foi','doux']),
  n('hajar','girl','Hajar','هاجر','Hājar','Forme arabe du nom de Hagar, mère d’Ismaïl dans la tradition islamique.',['Hajar','Hajer','Hagar'],['classique','facile-france'],['Sémitique','Usage arabe']),
  n('hala','girl','Hala','هالة','Hāla','Halo lumineux autour de la lune.',['Hala','Haala'],['doux','court','facile-france']),
  n('hana','girl','Hana','هناء','Hanāʾ','Bonheur, félicité, bien-être.',['Hana','Hanaa','Hena'],['doux','facile-france']),
  n('hanan','girl','Hanan','حنان','Ḥanān','Tendresse, affection, compassion.',['Hanan','Hanane'],['doux','classique','facile-france']),
  n('hiba','girl','Hiba','هبة','Hiba','Don, cadeau.',['Hiba','Heba'],['doux','court','facile-france']),
  n('ibtihal','girl','Ibtihal','ابتهال','Ibtihāl','Supplication humble, invocation fervente.',['Ibtihal','Ibtihale'],['foi','rare']),
  n('ikhlas','girl','Ikhlas','إخلاص','Ikhlāṣ','Sincérité, pureté de l’intention.',['Ikhlas','Ikhlass'],['foi','coranique']),
  n('ilham','girl','Ilham','إلهام','Ilhām','Inspiration.',['Ilham','Elham'],['doux','facile-france']),
  n('isra','girl','Isra','إسراء','Isrāʾ','Voyage nocturne.',['Isra','Israa'],['coranique','foi','facile-france']),
  n('jannah','girl','Jannah','جنة','Janna','Jardin, paradis.',['Jannah','Janna','Jenna'],['coranique','foi','doux']),
  n('jawhara','girl','Jawhara','جوهرة','Jawhara','Joyau, pierre précieuse.',['Jawhara','Jouhara','Johara'],['doux']),
  n('karima','girl','Karima','كريمة','Karīma','Généreuse, noble.',['Karima','Kareema'],['sagesse','classique','facile-france']),
  n('kawthar','girl','Kawthar','كوثر','Kawthar','Abondance de bien ; nom d’un don accordé au Prophète ﷺ et titre de la sourate 108.',['Kawthar','Kawtar','Kaouthar'],['coranique','foi']),
  n('lamia','girl','Lamia','لامعة','Lāmiʿa','Brillante, rayonnante.',['Lamia','Lamya','Lamiya'],['doux','facile-france']),
  n('layla','girl','Layla','ليلى','Laylā','Nuit ; ancien prénom arabe lié à la nuit sombre.',['Layla','Leila','Laila','Leyla'],['classique','doux','facile-france']),
  n('lina','girl','Lina','لينة','Līna','Jeune palmier ou palmier tendre ; le mot apparaît dans le Coran.',['Lina','Leena'],['coranique','doux','facile-france']),
  n('lubna','girl','Lubna','لبنى','Lubnā','Storax, arbre aromatique ; ancien prénom arabe.',['Lubna','Loubna'],['doux','rare']),
  n('lulwa','girl','Lulwa','لؤلؤة','Luʾluʾa','Perle.',['Lulwa','Louloua','Luluwa'],['doux','rare']),
  n('maha','girl','Maha','مها','Mahā','Oryx ; par extension, beaux yeux dans la poésie arabe.',['Maha','Mahaa'],['doux','court','facile-france']),
  n('malak','girl','Malak','ملك','Malak','Ange.',['Malak','Melek'],['foi','facile-france']),
  n('malika','girl','Malika','ملكة','Malika','Reine.',['Malika','Melek'],['classique','facile-france']),
  n('manal','girl','Manal','منال','Manāl','Ce que l’on atteint, obtient ; accomplissement.',['Manal','Menaal'],['doux','facile-france']),
  n('mariam2','girl','Mariam','مريم','Maryam','Variante très courante de Maryam, nom de la mère de ʿIsa عليه السلام.',['Mariam','Maryam','Meryem','Mariam'],['coranique','classique','facile-france'],['Sémitique','Usage arabe']),
  n('maysa','girl','Maysa','ميساء','Maysāʾ','Celle qui marche avec grâce.',['Maysa','Maisa','Mayssa'],['doux','rare']),
  n('muna','girl','Muna','منى','Munā','Souhaits, aspirations, désirs.',['Muna','Mouna','Mona'],['doux','facile-france']),
  n('nadia','girl','Nadia','نادية','Nādiya','Généreuse, fraîche ; selon la racine et la vocalisation.',['Nadia','Nadiya','Nadya'],['doux','facile-france']),
  n('naima','girl','Naima','نعيمة','Naʿīma','Heureuse, vivant dans le bien-être et la douceur.',['Naima','Naïma','Naeema'],['doux','classique','facile-france']),
  n('najla','girl','Najla','نجلاء','Najlāʾ','Aux grands et beaux yeux ; large, ample.',['Najla','Nejla'],['doux','rare']),
  n('nawal','girl','Nawal','نوال','Nawāl','Don, faveur, ce que l’on obtient.',['Nawal','Nawel'],['doux','facile-france']),
  n('nourhan','girl','Nourhan','نورهان','Nūrhan','Composé moderne associant nūr « lumière » et khān/hān « souverain » selon les usages turco-persans.',['Nourhan','Nurhan'],['doux','rare'],['Arabe','Turc/Persan']),
  n('rabia','girl','Rabia','رابعة','Rābiʿa','Quatrième ; ancien prénom arabe.',['Rabia','Rabiya','Rabiah'],['classique']),
  n('rana','girl','Rana','رنا','Ranā','Regarder longuement avec admiration ; selon l’usage arabe.',['Rana','Ranaa'],['doux','court','facile-france']),
  n('rania','girl','Rania','رانيا','Rāniya','Celle qui regarde attentivement, contemplative.',['Rania','Raniya'],['doux','facile-france']),
  n('rawan','girl','Rawan','روان','Rawān','Prénom moderne à plusieurs analyses ; souvent associé au fait de couler doucement ou à une forme persane.',['Rawan','Rawan','Rauane'],['doux','rare'],['Arabe','Perse']),
  n('reem','girl','Reem','ريم','Rīm','Gazelle blanche, antilope.',['Reem','Rim','Rym'],['doux','court','facile-france']),
  n('rim','girl','Rim','ريم','Rīm','Gazelle blanche, antilope.',['Rim','Reem','Rym'],['doux','court','facile-france']),
  n('sabah','girl','Sabah','صباح','Ṣabāḥ','Matin.',['Sabah','Sabaah'],['doux','facile-france']),
  n('sabrine','girl','Sabrina','صابرين','Ṣābirīn','Patientes, persévérantes ; forme culturelle liée à la racine ṣ-b-r.',['Sabrina','Sabrine','Sabreen'],['sagesse','facile-france']),
  n('sahar','girl','Sahar','سحر','Saḥar','Fin de la nuit, juste avant l’aube.',['Sahar','Sehar'],['doux','rare']),
  n('samah','girl','Samah','سماح','Samāḥ','Générosité, indulgence, tolérance.',['Samah','Semah'],['sagesse','doux']),
  n('samar','girl','Samar','سمر','Samar','Conversation du soir, veillée.',['Samar','Semar'],['doux','facile-france']),
  n('samia','girl','Samia','سامية','Sāmiya','Élevée, noble, sublime.',['Samia','Samiya','Samya'],['doux','facile-france']),
  n('sana','girl','Sana','سناء','Sanāʾ','Éclat, splendeur, rayonnement.',['Sana','Sanaa','Sena'],['doux','facile-france']),
  n('shahd','girl','Shahd','شهد','Shahd','Miel.',['Shahd','Chahed'],['doux','court']),
  n('shams','girl','Shams','شمس','Shams','Soleil.',['Shams','Chems'],['coranique','court']),
  n('siham','girl','Siham','سهام','Sihām','Flèches.',['Siham','Sihem'],['classique','facile-france']),
  n('souad','girl','Souad','سعاد','Suʿād','Bonheur, félicité.',['Souad','Suad','Soad'],['classique','doux','facile-france']),
  n('sundus','girl','Sundus','سندس','Sundus','Soie fine, brocart du Paradis dans le vocabulaire coranique.',['Sundus','Sondos','Sundos'],['coranique','rare']),
  n('tahira','girl','Tahira','طاهرة','Ṭāhira','Pure, chaste.',['Tahira','Tahera'],['foi','sagesse']),
  n('warda','girl','Warda','وردة','Warda','Rose, fleur.',['Warda','Ouarda','Warda'],['doux','facile-france']),
  n('widad','girl','Widad','وداد','Widād','Affection, amour, amitié.',['Widad','Wydad','Ouidad'],['doux']),
  n('yara','girl','Yara','يارا','Yārā','Prénom de plusieurs origines ; en persan, associé à l’ami ou à l’aide selon l’analyse.',['Yara'],['doux','facile-france'],['Perse','Usage arabe moderne']),
  n('yasmin','girl','Yasmin','ياسمين','Yāsmīn','Jasmin, fleur de jasmin.',['Yasmin','Yasmine','Yasmeen','Jasmine'],['doux','facile-france'],['Perse','Usage arabe']),
  n('yumna','girl','Yumna','يمنى','Yumnā','Bénie, de bon augure ; côté droit.',['Yumna','Youmna','Yomna'],['foi','doux']),
  n('zahra','girl','Zahra','زهراء','Zahrāʾ','Lumineuse, éclatante, fleurie.',['Zahra','Zohra','Zahraa'],['doux','classique','facile-france']),
  n('zaina','girl','Zaina','زينة','Zayna','Beauté, ornement, parure.',['Zaina','Zayna','Zeina','Zeyna'],['doux','facile-france']),
  n('zakia','girl','Zakia','زكية','Zakiyya','Pure, vertueuse, intelligente.',['Zakia','Zakiya','Zakiyya'],['foi','sagesse']),
  n('zaynab2','girl','Zeinab','زينب','Zaynab','Variante très courante de Zaynab ; ancien prénom arabe porté par plusieurs femmes des premières générations.',['Zeinab','Zaynab','Zeyneb','Zineb'],['sahabiyya','classique','facile-france']),
];
