import type { MuslimName, NameTag } from './types';

const BTN_ARABIC_URL='https://www.behindthename.com/names/usage/arabic';
const permitted='Sens positif ou neutre et aucun problème religieux connu dans cet usage.';

function e(id:string,gender:'boy'|'girl',name:string,arabic:string,transliteration:string,meaning:string,variants:string[],origin:string[],tags:NameTag[]=[]):MuslimName{return {id,gender,name,arabic,transliteration,meaning,variants,origin,tags,story:`Prénom ${origin.join(' / ').toLowerCase()} documenté dans les répertoires de prénoms. OUMMAH retient ici un sens français court et directement utile aux parents.`,status:'permitted',statusReason:permitted,editorialLevel:'reviewed',meaningConfidence:'medium',sources:[{kind:'catalogue',label:'Muslim Names Dataset (CC0)',reference:`Entrée « ${name} » · base de 14 585 prénoms issue de muslimnames.com`,supports:['écriture latine','écriture arabe','sens de départ','genre'],note:'Le sens anglais de la source a été reformulé en français par OUMMAH ; la base sert de point de départ culturel, pas de verdict religieux.'},{kind:'linguistic',label:'Behind the Name · répertoire des noms arabes',reference:`Repère linguistique pour « ${name} »`,url:BTN_ARABIC_URL,supports:['comparaison des formes','origine et sens lorsque le prénom y est documenté'],note:'Source linguistique secondaire utilisée pour confronter les translittérations et éviter de déduire un statut religieux d’une simple étymologie.'}],language:origin.some(x=>x.toLowerCase().includes('arabe'))?['Arabe']:undefined,culture:origin};}

export const EXTENDED_CURATED_NAMES:MuslimName[]=[
  e('aabid','boy','Aabid','عابد','ʿĀbid','Adorateur, dévot ; celui qui se consacre à l’adoration.',['Abid','Aabid'],['Arabe'],['foi']),
  e('aaqil','boy','Aqil','عاقل','ʿĀqil','Intelligent, raisonnable, sensé.',['Aqil','Aqeel','Akil'],['Arabe'],['sagesse','facile-france']),
  e('abaan','boy','Aban','أبان','Abān','Clair, manifeste ; également ancien prénom arabe.',['Aban','Abaane'],['Arabe'],['rare']),
  e('abbas','boy','Abbas','عباس','ʿAbbās','Austère, sévère ; également associé au lion dans l’usage arabe.',['Abbas','Abbès'],['Arabe'],['compagnon','classique']),
  e('abrar-b','boy','Abrar','أبرار','Abrār','Les vertueux, les pieux.',['Abrar'],['Arabe'],['foi','coranique']),
  e('adeeb','boy','Adib','أديب','Adīb','Cultivé, lettré, courtois.',['Adib','Adeeb'],['Arabe'],['sagesse']),
  e('adham','boy','Adham','أدهم','Adham','Noir profond ; traditionnellement associé au cheval noir.',['Adham'],['Arabe'],['force','rare']),
  e('adiyy','boy','Adiyy','عدي','ʿAdiyy','Ancien prénom arabe ; nom porté par le Compagnon ʿAdiyy ibn Hatim.',['Adiyy','Adi'],['Arabe'],['compagnon','rare']),
  e('afif','boy','Afif','عفيف','ʿAfīf','Chaste, pudique, intègre.',['Afif','Afeef'],['Arabe'],['sagesse']),
  e('afnan-b','boy','Afnan','أفنان','Afnān','Branches, rameaux.',['Afnan'],['Arabe'],['coranique','doux']),
  e('ahsan','boy','Ahsan','أحسن','Aḥsan','Meilleur, plus beau, plus excellent.',['Ahsan'],['Arabe'],['sagesse']),
  e('ajmal','boy','Ajmal','أجمل','Ajmal','Plus beau, très beau.',['Ajmal'],['Arabe'],['doux']),
  e('akif','boy','Akif','عاكف','ʿĀkif','Dévoué, retiré pour l’adoration ; assidu.',['Akif','Aakif'],['Arabe'],['foi']),
  e('akram','boy','Akram','أكرم','Akram','Très généreux, plus noble.',['Akram'],['Arabe'],['sagesse','facile-france']),
  e('alaa-b','boy','Alaa','علاء','ʿAlāʾ','Élévation, excellence, noblesse.',['Alaa','Ala'],['Arabe'],['sagesse']),
  e('aleem','boy','Alim','عليم','ʿAlīm','Savant, instruit, connaisseur.',['Alim','Aleem'],['Arabe'],['sagesse']),
  e('aqdas','boy','Aqdas','أقدس','Aqdas','Très pur, très sacré.',['Aqdas'],['Arabe'],['rare']),
  e('arif','boy','Arif','عارف','ʿĀrif','Connaisseur, celui qui sait et reconnaît.',['Arif','Aref'],['Arabe'],['sagesse']),
  e('arqam','boy','Arqam','أرقم','Arqam','Ancien prénom arabe ; nom du Compagnon al-Arqam ibn Abi al-Arqam.',['Arqam'],['Arabe'],['compagnon','rare']),
  e('ashraf','boy','Ashraf','أشرف','Ashraf','Plus noble, plus honorable.',['Ashraf','Achraf'],['Arabe'],['sagesse','facile-france']),
  e('ata','boy','Ata','عطاء','ʿAṭāʾ','Don, cadeau, faveur.',['Ata','Ataa'],['Arabe'],['doux','court']),
  e('atif','boy','Atif','عاطف','ʿĀṭif','Compatissant, affectueux, bienveillant.',['Atif','Atef'],['Arabe'],['doux']),
  e('awad','boy','Awad','عوض','ʿAwaḍ','Compensation, remplacement, don en retour.',['Awad','Aouad'],['Arabe'],['rare']),
  e('aws','boy','Aws','أوس','Aws','Ancien prénom arabe ; également nom d’une tribu médinoise.',['Aws'],['Arabe'],['compagnon','court','rare']),
  e('azhar','boy','Azhar','أزهر','Azhar','Brillant, lumineux, éclatant.',['Azhar'],['Arabe'],['doux']),
  e('bahaa','boy','Baha','بهاء','Bahāʾ','Splendeur, éclat, beauté.',['Baha','Bahaa'],['Arabe'],['doux']),
  e('bakr','boy','Bakr','بكر','Bakr','Jeune chameau ; ancien prénom arabe.',['Bakr'],['Arabe'],['compagnon','court']),
  e('barak','boy','Barak','بركة','Baraka','Bénédiction, bienfait.',['Barak','Baraka'],['Arabe'],['foi']),
  e('barir','boy','Barir','برير','Barīr','Fidèle, pieux, bienfaisant.',['Barir','Bareer'],['Arabe'],['foi','rare']),
  e('basil','boy','Basil','باسل','Bāsil','Brave, courageux, intrépide.',['Basil','Bassil'],['Arabe'],['force','facile-france']),
  e('burayd','boy','Burayd','بريد','Burayd','Ancien prénom arabe, notamment porté par Burayda ibn al-Husayb.',['Burayd','Buraid','Bureid'],['Arabe'],['compagnon','rare']),
  e('dhiya','boy','Diya','ضياء','Ḍiyāʾ','Lumière, éclat, rayonnement.',['Diya','Dhiya','Ziya'],['Arabe'],['doux']),
  e('ezzeddine','boy','Izz ad-Din','عز الدين','ʿIzz ad-Dīn','Gloire, puissance ou honneur de la religion.',['Izz ad-Din','Ezzedine','Izzeddin'],['Arabe'],['foi']),
  e('fadi','boy','Fadi','فادي','Fādī','Celui qui rachète, se sacrifie ou sauve.',['Fadi','Fady'],['Arabe'],['doux','facile-france']),
  e('fakhr','boy','Fakhr','فخر','Fakhr','Fierté, honneur, gloire.',['Fakhr','Fakher'],['Arabe'],['force']),
  e('falih','boy','Falih','فالح','Fāliḥ','Réussi, prospère, celui qui réussit.',['Falih','Faleh'],['Arabe'],['sagesse']),
  e('fawaz','boy','Fawaz','فواز','Fawwāz','Très victorieux, couronné de succès.',['Fawaz','Fawwaz','Faouaz'],['Arabe'],['force']),
  e('fawzi','boy','Fawzi','فوزي','Fawzī','Victorieux, lié au succès.',['Fawzi','Fouzi','Faouzi'],['Arabe'],['force','facile-france']),
  e('firas','boy','Firas','فراس','Firās','Perspicace ; également associé au lion dans l’usage ancien.',['Firas','Firass'],['Arabe'],['force','sagesse']),
  e('ghayth','boy','Ghayth','غيث','Ghayth','Pluie secourable, pluie bénéfique.',['Ghayth','Ghaith','Raith'],['Arabe'],['doux','rare']),
  e('ghiyath','boy','Ghiyath','غياث','Ghiyāth','Secours, aide, délivrance.',['Ghiyath','Ghiath'],['Arabe'],['doux','rare']),
  e('habibullah','boy','Habibullah','حبيب الله','Ḥabīb Allāh','Bien-aimé d’Allah ; construction honorifique traditionnelle.',['Habibullah','Habib Allah'],['Arabe'],['foi']),
  e('hafiz','boy','Hafiz','حافظ','Ḥāfiẓ','Gardien, protecteur ; celui qui mémorise.',['Hafiz','Hafez'],['Arabe'],['foi','sagesse']),
  e('haidar','boy','Haidar','حيدر','Ḥaydar','Lion.',['Haidar','Haydar','Hyder'],['Arabe'],['force']),
  e('hamdan','boy','Hamdan','حمدان','Ḥamdān','Celui qui loue beaucoup ; lié à la louange.',['Hamdan','Hamdane'],['Arabe'],['foi']),
  e('hani','boy','Hani','هاني','Hāniʾ','Heureux, satisfait, serein.',['Hani','Hany'],['Arabe'],['doux','facile-france']),
  e('harith','boy','Harith','حارث','Ḥārith','Laboureur, cultivateur ; celui qui acquiert par son effort.',['Harith','Hareth','Haris'],['Arabe'],['compagnon']),
  e('hashim','boy','Hashim','هاشم','Hāshim','Celui qui brise ; traditionnellement celui qui brisait le pain pour le partager.',['Hashim','Hachem'],['Arabe'],['classique']),
  e('hatim','boy','Hatim','حاتم','Ḥātim','Juge, arbitre ; celui qui tranche.',['Hatim','Hatem'],['Arabe'],['sagesse','facile-france']),
  e('hazim','boy','Hazim','حازم','Ḥāzim','Ferme, déterminé, résolu.',['Hazim','Hazem'],['Arabe'],['force']),
  e('hilm','boy','Hilm','حلم','Ḥilm','Clémence, maîtrise de soi, douceur de caractère.',['Hilm'],['Arabe'],['sagesse','doux','rare']),
  e('humam','boy','Humam','همام','Humām','Courageux, énergique, déterminé.',['Humam','Houmam'],['Arabe'],['force']),
  e('husam','boy','Husam','حسام','Ḥusām','Lame tranchante, épée.',['Husam','Houssam','Hossam'],['Arabe'],['force','facile-france']),
  e('ibad','boy','Ibad','عباد','ʿIbād','Serviteurs, adorateurs.',['Ibad','Ebad'],['Arabe'],['foi']),
  e('idham','boy','Idham','إدهام','Idhām','Obscurité profonde ; noirceur.',['Idham'],['Arabe'],['rare']),
  e('iftikhar','boy','Iftikhar','افتخار','Iftikhār','Fierté, honneur.',['Iftikhar','Iftikhaar'],['Arabe'],['sagesse']),
  e('imran','boy','Imran','عمران','ʿImrān','Prospérité, peuplement ; nom de la famille de Maryam dans le Coran.',['Imran','Omran'],['Arabe'],['coranique','classique','facile-france']),
  e('irfan','boy','Irfan','عرفان','ʿIrfān','Connaissance, reconnaissance, gratitude.',['Irfan','Erfan'],['Arabe'],['sagesse']),
  e('isam','boy','Isam','عصام','ʿIṣām','Lien, attache, protection.',['Isam','Issam'],['Arabe'],['force','facile-france']),
  e('jabbar','boy','Jabir','جابر','Jābir','Celui qui répare, console, restaure.',['Jabir','Jaber'],['Arabe'],['compagnon','doux']),
  e('jafar','boy','Jafar','جعفر','Jaʿfar','Petit cours d’eau, ruisseau.',['Jafar','Jaafar','Djaafar'],['Arabe'],['compagnon','classique']),
  e('kanaan','boy','Kinan','كنان','Kinān','Protection, couverture, abri.',['Kinan','Kenan'],['Arabe'],['force','facile-france']),
  e('labib','boy','Labib','لبيب','Labīb','Intelligent, raisonnable, perspicace.',['Labib','Labeeb'],['Arabe'],['sagesse']),
  e('latif','boy','Latif','لطيف','Laṭīf','Doux, subtil, bienveillant.',['Latif','Lateef'],['Arabe'],['doux']),
  e('luay','boy','Luay','لؤي','Luʾayy','Petit taureau sauvage ; ancien prénom arabe.',['Luay','Louay','Loay'],['Arabe'],['rare','facile-france']),
  e('lutfi','boy','Lutfi','لطفي','Luṭfī','Bienveillant, gracieux ; lié à la douceur.',['Lutfi','Lotfi','Loutfi'],['Arabe'],['doux','facile-france']),
  e('maher','boy','Maher','ماهر','Māhir','Habile, compétent, expert.',['Maher','Mahir'],['Arabe'],['sagesse','facile-france']),
  e('majdi','boy','Majdi','مجدي','Majdī','Glorieux, noble ; lié à la gloire.',['Majdi','Mejdi'],['Arabe'],['sagesse']),
  e('makki','boy','Makki','مكي','Makkī','Originaire de La Mecque, mecquois.',['Makki','Mekki'],['Arabe'],['foi']),
  e('mamun','boy','Mamun','مأمون','Maʾmūn','Digne de confiance, en sécurité.',['Mamun','Mamoun','Maamoun'],['Arabe'],['sagesse']),
  e('maruf','boy','Maruf','معروف','Maʿrūf','Connu, reconnu ; le bien convenable.',['Maruf','Maarouf','Marouf'],['Arabe'],['foi','sagesse']),
  e('masud','boy','Masud','مسعود','Masʿūd','Heureux, fortuné, favorisé.',['Masud','Massoud','Masood'],['Arabe'],['doux']),
  e('miftah','boy','Miftah','مفتاح','Miftāḥ','Clé.',['Miftah','Meftah'],['Arabe'],['rare']),
  e('mishal','boy','Mishal','مشعل','Mishʿal','Torche, flambeau.',['Mishal','Meshaal'],['Arabe'],['doux']),
  e('moin','boy','Muin','معين','Muʿīn','Aide, soutien, assistant.',['Muin','Moeen','Moin'],['Arabe'],['doux']),
  e('mujahid','boy','Mujahid','مجاهد','Mujāhid','Celui qui fournit un effort, qui lutte avec détermination.',['Mujahid','Moudjahid'],['Arabe'],['force']),
  e('munif','boy','Munif','منيف','Munīf','Élevé, noble, remarquable.',['Munif','Mounif'],['Arabe'],['sagesse']),
  e('muntasir','boy','Muntasir','منتصر','Muntaṣir','Victorieux, triomphant.',['Muntasir','Mountassir'],['Arabe'],['force']),
  e('murtada','boy','Murtada','مرتضى','Murtaḍā','Agréé, choisi, accepté.',['Murtada','Mourtada','Mortaza'],['Arabe'],['foi']),
  e('mustafa','boy','Mustafa','مصطفى','Muṣṭafā','Choisi, élu.',['Mustafa','Mostafa','Moustapha'],['Arabe'],['foi','classique','facile-france']),
  e('muwaffaq','boy','Muwaffaq','موفق','Muwaffaq','Celui à qui la réussite est accordée.',['Muwaffaq','Mouaffaq'],['Arabe'],['sagesse']),
  e('nabil','boy','Nabil','نبيل','Nabīl','Noble, honorable.',['Nabil','Nabeel'],['Arabe'],['sagesse','facile-france']),
  e('nadim','boy','Nadim','نديم','Nadīm','Compagnon de conversation, convive.',['Nadim','Nadeem'],['Arabe'],['doux','facile-france']),
  e('naji','boy','Naji','ناجي','Nājī','Sauvé, délivré ; celui qui échappe au danger.',['Naji','Nadjii'],['Arabe'],['doux']),
  e('najib','boy','Najib','نجيب','Najīb','Noble, distingué, intelligent.',['Najib','Nadjib','Najeeb'],['Arabe'],['sagesse','facile-france']),
  e('nasih','boy','Nasih','ناصح','Nāṣiḥ','Sincère conseiller, bienveillant.',['Nasih','Naseh'],['Arabe'],['sagesse']),
  e('nasir','boy','Nasir','ناصر','Nāṣir','Secoureur, défenseur, celui qui aide.',['Nasir','Nasser','Naseer'],['Arabe'],['force']),
  e('nawfal','boy','Nawfal','نوفل','Nawfal','Généreux ; également ancien terme arabe pour la mer ou le don abondant selon les usages.',['Nawfal','Naufal','Noufel'],['Arabe'],['compagnon','rare']),
  e('nizam','boy','Nizam','نظام','Niẓām','Ordre, organisation, système.',['Nizam','Nidham'],['Arabe'],['sagesse']),
  e('qasim','boy','Qasim','قاسم','Qāsim','Celui qui partage, répartit.',['Qasim','Kacem','Kassim'],['Arabe'],['classique']),
  e('qays','boy','Qays','قيس','Qays','Ancien prénom arabe ; mesure, dureté ou intensité selon les analyses lexicales.',['Qays','Kais','Qais'],['Arabe'],['rare','facile-france']),
  e('rafiq','boy','Rafiq','رفيق','Rafīq','Compagnon, ami, camarade.',['Rafiq','Rafik'],['Arabe'],['doux','facile-france']),
  e('raghib','boy','Raghib','راغب','Rāghib','Désireux, aspirant, plein d’intérêt.',['Raghib','Ragheb'],['Arabe'],['doux']),
  e('raif','boy','Raif','رائف','Rāʾif','Compatissant, clément.',['Raif','Raef'],['Arabe'],['doux']),
  e('rajab','boy','Rajab','رجب','Rajab','Nom du septième mois du calendrier hégirien ; respect, vénération.',['Rajab','Redjeb'],['Arabe'],['foi']),
  e('rami','boy','Rami','رامي','Rāmī','Archer, tireur ; celui qui lance.',['Rami','Ramy'],['Arabe'],['force','facile-france']),
  e('rashad','boy','Rashad','رشاد','Rashād','Droiture, maturité, bon jugement.',['Rashad','Rached'],['Arabe'],['sagesse']),
  e('ridwan','boy','Ridwan','رضوان','Riḍwān','Agrément, satisfaction, contentement.',['Ridwan','Redouane','Ridhwan'],['Arabe'],['foi']),
  e('riyad','boy','Riyad','رياض','Riyāḍ','Jardins, prairies.',['Riyad','Riad'],['Arabe'],['doux','facile-france']),
  e('sabir','boy','Sabir','صابر','Ṣābir','Patient, persévérant.',['Sabir','Saber'],['Arabe'],['sagesse','foi']),
  e('sadiq','boy','Sadiq','صادق','Ṣādiq','Véridique, sincère.',['Sadiq','Sadek','Sadeq'],['Arabe'],['sagesse','foi']),
  e('safi','boy','Safi','صافي','Ṣāfī','Pur, limpide, sincère.',['Safi','Safy'],['Arabe'],['doux']),
  e('salah','boy','Salah','صلاح','Ṣalāḥ','Droiture, rectitude, vertu.',['Salah','Saleh'],['Arabe'],['foi','sagesse','facile-france']),
  e('salim','boy','Salim','سالم','Sālim','Sain, sauf, intact, en sécurité.',['Salim','Salem'],['Arabe'],['doux','facile-france']),
  e('shadi','boy','Shadi','شادي','Shādī','Chanteur ; celui qui recherche le savoir ou la littérature selon l’usage.',['Shadi','Chadi'],['Arabe'],['doux','facile-france']),
  e('shakir','boy','Shakir','شاكر','Shākir','Reconnaissant, reconnaissant envers Allah.',['Shakir','Chakir'],['Arabe'],['foi']),
  e('sharif','boy','Sharif','شريف','Sharīf','Noble, honorable.',['Sharif','Cherif','Chérif'],['Arabe'],['sagesse','facile-france']),
  e('suhayb','boy','Suhayb','صهيب','Ṣuhayb','Ancien prénom arabe ; diminutif associé à une teinte rousse ou blonde.',['Suhayb','Souhayb','Sohaib'],['Arabe'],['compagnon','rare']),
  e('suhayl','boy','Suhayl','سهيل','Suhayl','Doux, facile ; également nom de l’étoile Canopus en arabe.',['Suhayl','Souheil','Sohail'],['Arabe'],['doux','facile-france']),
  e('tamim','boy','Tamim','تميم','Tamīm','Complet, solide, accompli.',['Tamim','Tameem'],['Arabe'],['compagnon','sagesse']),
  e('tawfiq','boy','Tawfiq','توفيق','Tawfīq','Réussite accordée, succès, conciliation.',['Tawfiq','Tewfik','Toufik'],['Arabe'],['foi','sagesse']),
  e('taym','boy','Taym','تيم','Taym','Serviteur dévoué, amour passionné dans l’arabe ancien.',['Taym','Taim'],['Arabe'],['rare']),
  e('thabit','boy','Thabit','ثابت','Thābit','Ferme, stable, constant.',['Thabit','Sabet'],['Arabe'],['compagnon','force']),
  e('ubaid','boy','Ubayd','عبيد','ʿUbayd','Petit serviteur ; diminutif ancien de ʿabd.',['Ubayd','Oubeid'],['Arabe'],['rare']),
  e('uqba','boy','Uqba','عقبة','ʿUqba','Suite, conséquence ; passage difficile ou col.',['Uqba','Oqba'],['Arabe'],['compagnon','rare']),
  e('wael','boy','Wael','وائل','Wāʾil','Celui qui cherche refuge, qui revient vers un refuge.',['Wael','Waël','Wail'],['Arabe'],['facile-france']),
  e('wafi','boy','Wafi','وافي','Wāfī','Fidèle, complet, qui tient ses engagements.',['Wafi','Wafy'],['Arabe'],['sagesse']),
  e('wahib','boy','Wahib','واهب','Wāhib','Donateur, généreux, celui qui offre.',['Wahib','Waheb'],['Arabe'],['doux']),
  e('walid','boy','Walid','وليد','Walīd','Nouveau-né, jeune enfant.',['Walid','Oualid'],['Arabe'],['classique','facile-france']),
  e('wasim','boy','Wasim','وسيم','Wasīm','Beau, élégant, de belle apparence.',['Wasim','Wassim'],['Arabe'],['doux','facile-france']),
  e('yamin','boy','Yamin','يمين','Yamīn','Droite, côté droit ; serment.',['Yamin','Yamine'],['Arabe'],['foi']),
  e('yasir','boy','Yasir','ياسر','Yāsir','Aisé, facile ; celui qui rend les choses faciles.',['Yasir','Yasser','Yacir'],['Arabe'],['compagnon','facile-france']),
  e('zahir','boy','Zahir','ظاهر','Ẓāhir','Apparent, manifeste, éclatant.',['Zahir','Dahir'],['Arabe'],['sagesse']),
  e('zaki','boy','Zaki','زكي','Zakī','Pur, vertueux, intelligent.',['Zaki','Zaky'],['Arabe'],['foi','sagesse']),
  e('zayn','boy','Zayn','زين','Zayn','Beauté, grâce, ornement.',['Zayn','Zain','Zein'],['Arabe'],['doux','court','facile-france']),
  e('ziyad','boy','Ziyad','زياد','Ziyād','Croissance, augmentation, abondance.',['Ziyad','Ziad'],['Arabe'],['facile-france']),
  e('aaliyah','girl','Aaliyah','عالية','ʿĀliya','Élevée, sublime, de haut rang.',['Aaliyah','Aliya','Alia'],['Arabe'],['doux','facile-france']),
  e('aamal','girl','Amaal','آمال','Āmāl','Espoirs, aspirations.',['Amaal','Amal'],['Arabe'],['doux']),
  e('adiba-g','girl','Adiba','أديبة','Adība','Cultivée, lettrée, courtoise.',['Adiba','Adeeba'],['Arabe'],['sagesse']),
  e('afaf','girl','Afaf','عفاف','ʿAfāf','Chasteté, pudeur, vertu.',['Afaf'],['Arabe'],['foi','sagesse']),
  e('afifa','girl','Afifa','عفيفة','ʿAfīfa','Chaste, pudique, vertueuse.',['Afifa','Afeefa'],['Arabe'],['foi','sagesse']),
  e('aliya','girl','Aliya','عالية','ʿĀliya','Élevée, noble, sublime.',['Aliya','Alia','Alya'],['Arabe'],['doux','facile-france']),
  e('amira-g','girl','Amira','أميرة','Amīra','Princesse, cheffe.',['Amira','Emira'],['Arabe'],['classique','facile-france']),
  e('anbar','girl','Anbar','عنبر','ʿAnbar','Ambre gris ; parfum précieux.',['Anbar','Amber'],['Arabe'],['doux','rare']),
  e('aneesa','girl','Anisa','أنيسة','Anīsa','Amicale, sociable, réconfortante.',['Anisa','Anissa','Anisah'],['Arabe'],['doux','facile-france']),
  e('aqila','girl','Aqila','عقيلة','ʿAqīla','Intelligente, noble, distinguée.',['Aqila','Akila'],['Arabe'],['sagesse']),
  e('areej','girl','Areej','أريج','Arīj','Parfum agréable, fragrance.',['Areej','Arij'],['Arabe'],['doux']),
  e('arij','girl','Arij','أريج','Arīj','Parfum agréable, fragrance.',['Arij','Areej'],['Arabe'],['doux']),
  e('aseel','girl','Aseel','أصيل','Aṣīl','Noble, authentique ; aussi moment de fin d’après-midi selon le mot arabe.',['Aseel','Assil'],['Arabe'],['doux']),
  e('asiya','girl','Asiya','آسية','Āsiya','Celle qui soigne, console ou soutient ; nom traditionnel de l’épouse croyante de Pharaon.',['Asiya','Assia','Asiyah'],['Arabe'],['foi','classique','facile-france']),
  e('aziza-g','girl','Aziza','عزيزة','ʿAzīza','Chère, précieuse, puissante, respectée.',['Aziza'],['Arabe'],['doux','force']),
  e('azra','girl','Azra','عذراء','ʿAdhrāʾ','Vierge, jeune fille.',['Azra'],['Arabe'],['rare']),
  e('badriya','girl','Badriya','بدرية','Badriyya','Liée à la pleine lune ; lumineuse comme la lune.',['Badriya','Badriyah'],['Arabe'],['doux']),
  e('bahia','girl','Bahia','بهية','Bahiyya','Splendide, rayonnante, belle.',['Bahia','Bahiya'],['Arabe'],['doux','facile-france']),
  e('balqis','girl','Balqis','بلقيس','Balqīs','Nom traditionnel de la reine de Saba dans la tradition islamique ; étymologie ancienne incertaine.',['Balqis','Bilkis','Belkis'],['Arabe'],['coranique','rare']),
  e('baria','girl','Baria','بارعة','Bāriʿa','Excellente, remarquable, habile.',['Baria','Barea'],['Arabe'],['sagesse']),
  e('bayan','girl','Bayan','بيان','Bayān','Clarté, explication, éloquence.',['Bayan','Bayane'],['Arabe'],['coranique','sagesse']),
  e('dalal','girl','Dalal','دلال','Dalāl','Grâce, coquetterie, charme délicat.',['Dalal','Dallal'],['Arabe'],['doux']),
  e('dana','girl','Dana','دانة','Dāna','Grande perle dans l’usage du Golfe ; ce prénom possède aussi d’autres origines.',['Dana','Danah'],['Arabe','Autres origines'],['doux','facile-france']),
  e('dania','girl','Dania','دانية','Dāniya','Proche, rapprochée ; accessible.',['Dania','Daniya','Danya'],['Arabe'],['coranique','doux']),
  e('dareen','girl','Dareen','دارين','Dārīn','Nom lié historiquement à Darin, lieu connu pour ses parfums ; associé à la fragrance.',['Dareen','Darin'],['Arabe'],['doux','rare']),
  e('dhikra','girl','Dhikra','ذكرى','Dhikrā','Souvenir, rappel.',['Dhikra','Zikra'],['Arabe'],['foi','doux']),
  e('eman','girl','Eman','إيمان','Īmān','Foi.',['Eman','Iman','Imane'],['Arabe'],['foi','facile-france']),
  e('fadia','girl','Fadia','فادية','Fādiya','Celle qui se sacrifie, rachète ou sauve.',['Fadia','Fadya'],['Arabe'],['doux']),
  e('fahima','girl','Fahima','فهيمة','Fahīma','Intelligente, compréhensive, perspicace.',['Fahima','Faheema'],['Arabe'],['sagesse']),
  e('faiza','girl','Faiza','فائزة','Fāʾiza','Victorieuse, couronnée de succès.',['Faiza','Fayza'],['Arabe'],['force']),
  e('fajr','girl','Fajr','فجر','Fajr','Aube, apparition de la lumière du matin.',['Fajr','Fadjar'],['Arabe'],['coranique','doux']),
  e('fariha','girl','Fariha','فريحة','Farīḥa','Joyeuse, heureuse.',['Fariha','Fareeha'],['Arabe'],['doux']),
  e('fatin','girl','Fatin','فاتن','Fātin','Charmante, captivante.',['Fatin','Fatine'],['Arabe'],['doux']),
  e('firdaws','girl','Firdaws','فردوس','Firdaws','Paradis, jardin suprême.',['Firdaws','Firdaus','Firdous'],['Arabe','Persan ancien'],['coranique','foi']),
  e('ghufran','girl','Ghufran','غفران','Ghufrān','Pardon, absolution.',['Ghufran','Ghofran'],['Arabe'],['foi']),
  e('hadeel','girl','Hadeel','هديل','Hadīl','Roulement ou chant doux de la colombe.',['Hadeel','Hadil'],['Arabe'],['doux']),
  e('hafiza-g','girl','Hafiza','حافظة','Ḥāfiẓa','Gardienne, protectrice ; celle qui mémorise.',['Hafiza','Hafidha'],['Arabe'],['foi','sagesse']),
  e('halima','girl','Halima','حليمة','Ḥalīma','Clémente, douce, patiente.',['Halima','Halimah'],['Arabe'],['doux','sagesse','classique']),
  e('hamida','girl','Hamida','حميدة','Ḥamīda','Louable, digne d’éloge.',['Hamida','Hameeda'],['Arabe'],['doux']),
  e('haneen','girl','Hanin','حنين','Ḥanīn','Nostalgie tendre, désir affectueux.',['Hanin','Haneen'],['Arabe'],['doux']),
  e('hasna','girl','Hasna','حسناء','Ḥasnāʾ','Belle, gracieuse.',['Hasna','Hasnaa'],['Arabe'],['doux']),
  e('hawra','girl','Hawra','حوراء','Ḥawrāʾ','Aux yeux très contrastés ; beauté du regard dans l’arabe classique.',['Hawra','Haoura'],['Arabe'],['doux','rare']),
  e('hidaya','girl','Hidaya','هداية','Hidāya','Guidée, orientation vers le bien.',['Hidaya','Hedaya'],['Arabe'],['foi']),
  e('huriya','girl','Huriya','حورية','Ḥūriyya','Femme d’une grande beauté ; lié au terme ḥūr.',['Huriya','Houria','Huriyya'],['Arabe'],['doux']),
  e('ibtisam','girl','Ibtisam','ابتسام','Ibtisām','Sourire.',['Ibtisam','Ibtissam'],['Arabe'],['doux','facile-france']),
  e('iffat','girl','Iffat','عفة','ʿIffa','Chasteté, retenue, pudeur.',['Iffat','Effat'],['Arabe'],['foi','sagesse']),
  e('inshirah','girl','Inshirah','انشراح','Inshirāḥ','Épanouissement, ouverture du cœur, soulagement.',['Inshirah','Inchira'],['Arabe'],['foi','doux']),
  e('joud','girl','Joud','جود','Jūd','Générosité, largesse.',['Joud','Joud'],['Arabe'],['doux','court','facile-france']),
  e('jumana','girl','Jumana','جمانة','Jumāna','Perle, petite perle.',['Jumana','Joumana'],['Arabe'],['doux','facile-france']),
  e('kanza','girl','Kanza','كنزة','Kanza','Trésor ; forme féminine moderne liée à kanz.',['Kanza','Kenza'],['Arabe'],['doux','facile-france']),
  e('khayra','girl','Khayra','خيرة','Khayra','Bonne, vertueuse ; le meilleur choix.',['Khayra','Khaira'],['Arabe'],['foi','doux']),
  e('latifa-g','girl','Latifa','لطيفة','Laṭīfa','Douce, bienveillante, subtile.',['Latifa','Lateefa'],['Arabe'],['doux']),
  e('laya','girl','Layan','ليان','Layān','Douceur de vie, souplesse, aisance.',['Layan','Layane','Layaan'],['Arabe'],['doux','facile-france']),
  e('maha-g','girl','Maha','مها','Mahā','Oryx ; par extension, beaux yeux dans la poésie arabe.',['Maha'],['Arabe'],['doux','court']),
  e('mahira','girl','Mahira','ماهرة','Māhira','Habile, compétente, experte.',['Mahira','Maheera'],['Arabe'],['sagesse']),
  e('maissa','girl','Maysa','ميساء','Maysāʾ','Celle qui marche avec grâce.',['Maysa','Maisa','Mayssa'],['Arabe'],['doux']),
  e('majd','girl','Majd','مجد','Majd','Gloire, noblesse, honneur.',['Majd'],['Arabe'],['sagesse','court']),
  e('malaz','girl','Maladh','ملاذ','Malādh','Refuge, abri, protection.',['Maladh','Malaz'],['Arabe'],['doux','rare']),
  e('maram','girl','Maram','مرام','Marām','But, aspiration, souhait recherché.',['Maram'],['Arabe'],['doux','facile-france']),
  e('mardiya','girl','Mardiya','مرضية','Marḍiyya','Agréée, satisfaisante, digne d’agrément.',['Mardiya','Mardhiyya'],['Arabe'],['foi','coranique']),
  e('maysun','girl','Maysun','ميسون','Maysūn','Belle de visage et de maintien ; ancien prénom arabe.',['Maysun','Maisoun','Maysoun'],['Arabe'],['doux','rare']),
  e('misk','girl','Misk','مسك','Misk','Musc, parfum précieux.',['Misk'],['Arabe'],['coranique','doux','court']),
  e('mubina','girl','Mubina','مبينة','Mubīna','Claire, évidente, explicite.',['Mubina','Mobeena'],['Arabe'],['sagesse']),
  e('muhsina','girl','Muhsina','محسنة','Muḥsina','Bienfaisante, celle qui agit avec excellence.',['Muhsina','Mohsina'],['Arabe'],['foi','sagesse']),
  e('munira','girl','Munira','منيرة','Munīra','Lumineuse, rayonnante.',['Munira','Mounira'],['Arabe'],['doux','facile-france']),
  e('nabila-g','girl','Nabila','نبيلة','Nabīla','Noble, honorable.',['Nabila','Nabeela'],['Arabe'],['sagesse','facile-france']),
  e('nada','girl','Nada','ندى','Nadā','Rosée ; générosité dans certains emplois arabes.',['Nada'],['Arabe'],['doux','court','facile-france']),
  e('nadira','girl','Nadira','نادرة','Nāḍira','Rare, précieuse, exceptionnelle.',['Nadira','Nadeira'],['Arabe'],['rare','doux']),
  e('nafila','girl','Nafila','نافلة','Nāfila','Acte surérogatoire, don supplémentaire.',['Nafila'],['Arabe'],['foi','rare']),
  e('nahla','girl','Nahla','نحلة','Naḥla','Abeille ; peut aussi évoquer un don selon la racine.',['Nahla','Nahlaa'],['Arabe'],['doux']),
  e('najah','girl','Najah','نجاح','Najāḥ','Réussite, succès.',['Najah','Nedjah'],['Arabe'],['sagesse']),
  e('najma','girl','Najma','نجمة','Najma','Étoile.',['Najma','Nejma'],['Arabe'],['doux']),
  e('nasiba','girl','Nasiba','نسيبة','Nasība','Part, destinée, lot ; également prénom historique.',['Nasiba','Naseeba'],['Arabe'],['sahabiyya','rare']),
  e('nawal-g','girl','Nawal','نوال','Nawāl','Don, faveur, ce que l’on obtient.',['Nawal','Nawel'],['Arabe'],['doux','facile-france']),
  e('nour','girl','Nour','نور','Nūr','Lumière.',['Nour','Noor','Nur'],['Arabe'],['coranique','doux','facile-france']),
  e('nuha','girl','Nuha','نهى','Nuhā','Raison, intelligence ; capacité à se retenir.',['Nuha','Noha'],['Arabe'],['coranique','sagesse']),
  e('qamar','girl','Qamar','قمر','Qamar','Lune.',['Qamar','Kamar'],['Arabe'],['coranique','doux']),
  e('qudsia','girl','Qudsia','قدسية','Qudsiyya','Sacrée, pure, liée à la sainteté.',['Qudsia','Qodsiya'],['Arabe'],['foi']),
  e('rabab','girl','Rabab','رباب','Rabāb','Nuages blancs ; également nom d’un ancien instrument à cordes.',['Rabab','Rebab'],['Arabe'],['doux']),
  e('rabiaa','girl','Raniah','رانية','Rāniya','Celle qui regarde attentivement, contemplative.',['Raniah','Rania','Raniya'],['Arabe'],['doux']),
  e('rafah','girl','Rafah','رفاه','Rafāh','Bien-être, aisance, prospérité.',['Rafah'],['Arabe'],['doux']),
  e('rafifa','girl','Rafifa','رفيفة','Rafīfa','Douce, délicate ; qui frémit ou ondule légèrement.',['Rafifa','Rafeefa'],['Arabe'],['doux']),
  e('rahaf','girl','Rahaf','رهف','Rahaf','Délicatesse, finesse, douceur.',['Rahaf'],['Arabe'],['doux','facile-france']),
  e('rahil','girl','Rahil','رحيل','Raḥīl','Départ, voyage.',['Rahil','Raheel'],['Arabe'],['rare']),
  e('raja','girl','Raja','رجاء','Rajāʾ','Espoir, attente confiante.',['Raja','Rajaa'],['Arabe'],['doux','foi']),
  e('rand','girl','Rand','رند','Rand','Arbre aromatique, laurier.',['Rand'],['Arabe'],['doux','court']),
  e('rasha','girl','Rasha','رشا','Rashā','Jeune gazelle.',['Rasha'],['Arabe'],['doux']),
  e('rawda','girl','Rawda','روضة','Rawḍa','Jardin verdoyant, prairie.',['Rawda','Raouda'],['Arabe'],['coranique','doux']),
  e('rayanah','girl','Rayhana','ريحانة','Rayḥāna','Plante parfumée, basilic, fragrance.',['Rayhana','Rayhane','Raihana'],['Arabe'],['doux','sahabiyya']),
  e('reem-g','girl','Reem','ريم','Rīm','Gazelle blanche.',['Reem','Rim','Rym'],['Arabe'],['doux','court']),
  e('rida-g','girl','Rida','رضا','Riḍā','Satisfaction, contentement, agrément.',['Rida','Reda'],['Arabe'],['foi']),
  e('saba','girl','Saba','سبأ','Sabaʾ','Nom de Saba ; associé au royaume de Saba mentionné dans le Coran.',['Saba','Sabaa'],['Arabe'],['coranique','rare']),
  e('sabiha','girl','Sabiha','صبيحة','Ṣabīḥa','Matin, belle comme le matin ; gracieuse.',['Sabiha'],['Arabe'],['doux']),
  e('sadia','girl','Sadia','سعيدة','Saʿīda','Heureuse, chanceuse, fortunée.',['Sadia','Saida','Saïda'],['Arabe'],['doux','facile-france']),
  e('safaa','girl','Safaa','صفاء','Ṣafāʾ','Pureté, clarté, sérénité.',['Safaa','Safa'],['Arabe'],['doux','foi']),
  e('sahar-g','girl','Sahar','سحر','Saḥar','Fin de la nuit, juste avant l’aube.',['Sahar'],['Arabe'],['doux']),
  e('salwa','girl','Salwa','سلوى','Salwā','Consolation, réconfort ; le mot désigne aussi la caille dans le Coran.',['Salwa','Selwa'],['Arabe'],['coranique','doux','facile-france']),
  e('samira','girl','Samira','سميرة','Samīra','Compagne de conversation du soir.',['Samira','Sameera'],['Arabe'],['doux','facile-france']),
  e('sawsan','girl','Sawsan','سوسن','Sawsan','Lis, fleur de lys.',['Sawsan','Soussan'],['Arabe'],['doux']),
  e('shaima','girl','Shaima','شيماء','Shaymāʾ','Celle qui porte des marques ou grains de beauté ; ancien prénom arabe.',['Shaima','Chaima','Shayma'],['Arabe'],['sahabiyya','facile-france']),
  e('shatha','girl','Shatha','شذى','Shadhā','Parfum, fragrance qui se répand.',['Shatha','Shaza'],['Arabe'],['doux']),
  e('shifa','girl','Shifa','شفاء','Shifāʾ','Guérison, remède.',['Shifa','Chifa'],['Arabe'],['coranique','foi']),
  e('suhaila','girl','Suhaila','سهيلة','Suhayla','Douce, facile ; diminutif féminin lié à Suhayl.',['Suhaila','Souhaila','Soheila'],['Arabe'],['doux','facile-france']),
  e('sukayna','girl','Sukayna','سكينة','Sukayna','Petite tranquillité ; forme diminutive liée à sakina, sérénité.',['Sukayna','Soukayna','Sokeina'],['Arabe'],['sahabiyya','doux']),
  e('taqwa','girl','Taqwa','تقوى','Taqwā','Piété, conscience révérencielle d’Allah.',['Taqwa','Takwa'],['Arabe'],['coranique','foi']),
  e('thurayya','girl','Thurayya','ثريا','Thurayyā','Les Pléiades ; constellation brillante.',['Thurayya','Soraya','Suraya'],['Arabe'],['doux','rare']),
  e('tuba','girl','Tuba','طوبى','Ṭūbā','Bonheur, félicité ; terme de bonne annonce.',['Tuba','Touba'],['Arabe'],['coranique','foi']),
  e('wafa','girl','Wafa','وفاء','Wafāʾ','Fidélité, loyauté, accomplissement d’une promesse.',['Wafa','Wafaa'],['Arabe'],['sagesse','doux']),
  e('wajd','girl','Wajd','وجد','Wajd','Émotion profonde, amour, état d’extase ou de passion.',['Wajd'],['Arabe'],['doux','rare']),
  e('wasila','girl','Wasila','وسيلة','Wasīla','Moyen de rapprochement, voie, intermédiaire.',['Wasila','Wassila'],['Arabe'],['foi','facile-france']),
  e('yusra','girl','Yusra','يسرى','Yusrā','Facilité, aisance ; la plus facile.',['Yusra','Yousra'],['Arabe'],['coranique','doux','facile-france']),
  e('zahida','girl','Zahida','زاهدة','Zāhida','Ascète, détachée des excès matériels.',['Zahida'],['Arabe'],['foi']),
  e('zahira','girl','Zahira','زاهرة','Zāhira','Brillante, éclatante, fleurissante.',['Zahira','Zahera'],['Arabe'],['doux']),
  e('zakiya','girl','Zakiya','زكية','Zakiyya','Pure, vertueuse, intelligente.',['Zakiya','Zakiyya','Zakia'],['Arabe'],['foi','sagesse']),
  e('zubaida','girl','Zubaida','زبيدة','Zubayda','Petite crème, essence choisie ; ce qu’il y a de meilleur.',['Zubaida','Zoubeida','Zubayda'],['Arabe'],['doux','classique']),
];
