import type { MuslimName, NameSource, NameTag } from './types';

const WEHR = 'Hans Wehr, A Dictionary of Modern Written Arabic';
const BTN = 'Behind the Name';

function arabicSource(arabic: string, meaning: string): NameSource[] {
  return [
    {
      kind: 'linguistic',
      label: WEHR,
      reference: `Contrôle lexical de « ${arabic} » — sens retenu : ${meaning}`,
      supports: ['sens lexical arabe', 'forme arabe'],
      note: 'Référence lexicale ; elle ne constitue pas à elle seule une recommandation religieuse du prénom.',
    },
    {
      kind: 'editorial',
      label: 'OUMMAH · usage Maghreb & diaspora',
      reference: 'Regroupement des graphies françaises et maghrébines les plus courantes autour d’une fiche canonique.',
      supports: ['variantes d’écriture', 'usage francophone et maghrébin'],
    },
  ];
}

function d(
  id: string,
  gender: 'boy' | 'girl',
  name: string,
  arabic: string,
  transliteration: string,
  meaning: string,
  variants: string[],
  tags: NameTag[] = [],
  origin: string[] = ['Arabe'],
  story?: string,
  extra?: Partial<MuslimName>,
): MuslimName {
  return {
    id,
    gender,
    name,
    arabic,
    transliteration,
    origin,
    meaning,
    story: story ?? `Prénom bien implanté au Maghreb et/ou dans la diaspora francophone. Son sens principal retenu ici est : « ${meaning.replace(/[.!?]+$/g, '')} ».`,
    status: 'permitted',
    statusReason: 'Sens convenable et aucun interdit religieux connu dans cet usage.',
    variants,
    tags,
    language: origin.some((value) => value.includes('Arabe')) ? ['Arabe'] : undefined,
    culture: ['Maghreb', 'Diaspora francophone'],
    meaningConfidence: 'high',
    editorialLevel: 'sourced',
    sources: arabicSource(arabic, meaning),
    ...extra,
  };
}

export const MAGHREB_DIASPORA_NAMES: MuslimName[] = [
  // Garçons — formes réellement fréquentes au Maghreb / en France.
  d('bahri','boy','Bahri','بحري','Baḥrī','Maritime, lié à la mer, « de la mer ».',['Bahri','Bahry','Bahree'],['rare','doux','facile-france'],['Arabe'],
    'Bahri est l’adjectif arabe formé sur baḥr (بحر), « mer ». La racine ب ح ر est très présente dans le Coran ; cela ne signifie pas que Bahri soit lui-même un prénom coranique.',
    { quranReference: '2:50 ; 2:164 ; 5:96', sources: [
      { kind:'linguistic', label:'Quranic Arabic Corpus', reference:'Racine ب ح ر : baḥr, « mer »', url:'https://corpus.quran.com/qurandictionary.jsp?q=bHr', supports:['racine arabe','emploi coranique de baḥr'] },
      ...arabicSource('بحري','Maritime, lié à la mer, « de la mer ».')
    ]}),
  d('mehdi','boy','Mehdi','مهدي','Mahdī','Guidé, celui qui est bien dirigé.',['Mehdi','Mahdi','Medhi','Mhedi'],['foi','classique','facile-france']),
  d('nassim','boy','Nassim','نسيم','Nasīm','Brise, souffle d’air doux.',['Nassim','Nasim','Naseem'],['doux','facile-france']),
  d('sofiane','boy','Sofiane','سفيان','Sufyān','Ancien prénom arabe ; son étymologie exacte est discutée.',['Sofiane','Soufiane','Sufyan','Soufyan'],['classique','facile-france'],['Arabe'],
    'Sofiane est la graphie francophone très répandue de Sufyān. Le nom est ancien dans l’histoire arabe ; plutôt que de lui attribuer un faux sens certain, OUMMAH signale que son étymologie précise est discutée.',
    { meaningConfidence:'medium' }),
  d('yanis','boy','Yanis','—','Yanis','Forme française et grecque apparentée à Jean/Yannis, traditionnellement rattachée à l’idée « Dieu fait grâce ».',['Yanis','Yannis','Giannis'],['facile-france'],['Grec','Usage français'],
    'Yanis est très porté dans les familles maghrébines de France mais n’est pas, à l’origine, un prénom arabe. Il correspond à une forme grecque/française de la famille de Jean/Yannis.',
    { language:['Grec','Français'], meaningConfidence:'high', sources:[
      { kind:'linguistic', label:BTN, reference:'Yanis — usage grec et français ; variante de Gianis/Yannis', url:'https://www.behindthename.com/name/yanis/', supports:['origine','variantes','étymologie'] },
      { kind:'editorial', label:'OUMMAH · usage Maghreb & diaspora', reference:'Prénom international très répandu dans la diaspora maghrébine francophone.', supports:['contexte d’usage'] }
    ]}),
  d('nael','boy','Naël','نائل','Nāʾil','Celui qui atteint, obtient ou parvient à quelque chose.',['Naël','Nael','Nail','Naïl','Nayel'],['court','facile-france'],['Arabe'], undefined,
    { sources:[
      { kind:'linguistic', label:BTN, reference:'Nail / نائل — « attainer »', url:'https://www.behindthename.com/name/nail', supports:['sens','origine arabe','variantes'] },
      ...arabicSource('نائل','Celui qui atteint, obtient ou parvient à quelque chose.')
    ]}),
  d('naim','boy','Naïm','نعيم','Naʿīm','Bien-être, douceur de vivre ; heureux, à l’aise, paisible.',['Naïm','Naim','Na’im','Naeem'],['doux','facile-france'],['Arabe'], undefined,
    { sources:[
      { kind:'linguistic', label:BTN, reference:'Naim / نعيم — « tranquil, happy, at ease »', url:'https://www.behindthename.com/name/naim', supports:['sens','racine arabe','forme maghrébine Naïm'] },
      ...arabicSource('نعيم','Bien-être, douceur de vivre ; heureux, à l’aise, paisible.')
    ]}),
  d('said','boy','Saïd','سعيد','Saʿīd','Heureux, chanceux, fortuné.',['Saïd','Said','Saïd'],['classique','doux','facile-france']),
  d('mourad','boy','Mourad','مراد','Murād','But recherché, souhait, désir.',['Mourad','Murad','Morad'],['classique','facile-france']),
  d('aymen','boy','Aymen','أيمن','Ayman','Plus chanceux, béni ; également lié au côté droit.',['Aymen','Ayman','Aimen'],['facile-france']),
  d('moncef','boy','Moncef','منصف','Munṣif','Équitable, juste, impartial.',['Moncef','Mounsef','Munsef','Munsif'],['sagesse','facile-france']),
  d('fethi','boy','Fethi','فتحي','Fatḥī','Lié à l’ouverture, à la victoire ou à la réussite.',['Fethi','Fathi','Fethy'],['facile-france']),
  d('ghaith','boy','Ghaith','غيث','Ghayth','Pluie bienfaisante, secours.',['Ghaith','Ghayth','Gaith'],['doux','rare']),
  d('ghassan','boy','Ghassan','غسان','Ghassān','Ancien prénom arabe ; associé historiquement aux Ghassanides.',['Ghassan','Ghassen','Gassan'],['classique'],['Arabe'],
    'Ghassan est un ancien nom arabe surtout connu par la confédération des Ghassanides. Son étymologie lexicale est moins sûre que son usage historique ; OUMMAH ne lui attribue donc pas un sens artificiellement précis.',
    { meaningConfidence:'medium' }),
  d('housni','boy','Housni','حسني','Ḥusnī','Beau, bon ; « lié à la beauté / à la bonté ».',['Housni','Husni','Hosni'],['doux','facile-france']),
  d('mounaim','boy','Mounaim','منعم','Munʿim','Celui qui comble de bienfaits, bienfaiteur.',['Mounaim','Mounem','Munim','Munʿim'],['doux','rare']),
  d('nidal','boy','Nidal','نضال','Niḍāl','Lutte, effort, combat au sens d’engagement et de persévérance.',['Nidal','Nidhal'],['force','facile-france']),
  d('raouf','boy','Raouf','رؤوف','Raʾūf','Très compatissant, plein de douceur.',['Raouf','Ra’uf','Rauf'],['doux','facile-france']),
  d('seif','boy','Seif','سيف','Sayf','Épée.',['Seif','Saif','Sayf','Seyf'],['force','court','facile-france']),
  d('skander','boy','Skander','إسكندر','Iskandar','Forme arabe d’Alexandre ; traditionnellement interprété comme « défenseur des hommes ».',['Skander','Iskander','Iskandar','Eskander'],['classique','facile-france'],['Grec','Forme arabisée'],
    'Skander est une forme maghrébine d’Iskandar, lui-même forme arabisée d’Alexandre. Son sens vient donc de l’étymologie grecque, pas d’une racine arabe.',
    { language:['Grec','Arabe (forme adaptée)'], sources:[
      { kind:'linguistic', label:BTN, reference:'Iskandar — forme arabe d’Alexander', url:'https://www.behindthename.com/name/iskandar', supports:['origine','filiation étymologique'] },
      { kind:'editorial', label:'OUMMAH · usage Maghreb & diaspora', reference:'Skander est une graphie particulièrement fréquente en Afrique du Nord.', supports:['variante maghrébine'] }
    ]}),
  d('wajdi','boy','Wajdi','وجدي','Wajdī','Passionné, ému ; lié au sentiment profond et à l’élan du cœur.',['Wajdi','Wajdy'],['doux']),
  d('wissam-boy','boy','Wissam','وسام','Wisām','Décoration, médaille, distinction honorifique.',['Wissam','Wisam','Wesam'],['facile-france']),
  d('moez','boy','Moez','معز','Muʿizz','Celui qui honore, renforce ou donne de la puissance.',['Moez','Moëz','Muizz','Muʿizz'],['rare','facile-france']),
  d('mouloud','boy','Mouloud','مولود','Mawlūd','Nouveau-né, enfant qui vient de naître.',['Mouloud','Mawlid','Mawloud'],['classique','facile-france']),
  d('rabeh','boy','Rabah','رابح','Rābiḥ','Gagnant, celui qui réussit ou tire un bénéfice.',['Rabah','Rabeh','Rabih'],['facile-france']),
  d('achraf-fr','boy','Achraf','أشرف','Ashraf','Plus noble, plus honorable ; très noble.',['Achraf','Ashraf','Echref'],['sagesse','facile-france']),
  d('bassem-fr','boy','Bassem','باسم','Bāsim','Souriant.',['Bassem','Basem','Basim'],['doux','facile-france']),
  d('chams-boy','boy','Chams','شمس','Shams','Soleil.',['Chams','Shams'],['court','doux','facile-france']),

  // Filles — priorité aux formes réellement rencontrées au Maghreb et en diaspora.
  d('sonia','girl','Sonia','—','Sonia','Sagesse, par sa filiation avec Sophia.',['Sonia','Sonya','Sonja'],['classique','facile-france'],['Grec','Forme européenne'],
    'Sonia est très utilisée au Maghreb mais son origine n’est pas arabe : c’est une variante de Sonya, diminutif russe de Sophia, nom grec associé à la sagesse.',
    { language:['Grec (étymologie)','Russe / langues européennes (forme)'], sources:[
      { kind:'linguistic', label:BTN, reference:'Sonia — variante de Sonya ; Sonya est un diminutif russe de Sophia', url:'https://www.behindthename.com/name/sonia', supports:['origine','variantes','filiation avec Sophia'] },
      { kind:'linguistic', label:BTN, reference:'Sonya — diminutif russe de Sophia', url:'https://www.behindthename.com/name/sonya', supports:['étymologie','sens hérité de Sophia'] },
      { kind:'editorial', label:'OUMMAH · usage Maghreb & diaspora', reference:'Usage culturel maghrébin distingué de l’origine linguistique du prénom.', supports:['contexte d’usage'] }
    ]}),
  d('liham','boy','Lyham','—','Lyham','Sens non établi avec certitude ; souvent rapproché de Liam/William (« volonté » + « casque/protection »), mais les sources françaises se contredisent.',['Lyham','Liham','Lïham'],['rare','facile-france'],['Usage français et maghrébin','Étymologie discutée'],
    'Lyham/Liham est un prénom moderne porté notamment dans des familles maghrébines en France. Les sources publiques lui attribuent des origines contradictoires. OUMMAH préfère donc afficher cette incertitude plutôt que d’inventer une origine arabe.',
    { language:['Origine discutée'], meaningConfidence:'medium', status:'note', statusReason:'Prénom d’usage contemporain ; son étymologie exacte n’est pas suffisamment établie pour être présentée comme certaine.', sources:[
      { kind:'linguistic', label:'Journal des Femmes', reference:'Liham rapproché de Liam/William ; étymologie germanique proposée', url:'https://www.journaldesfemmes.fr/prenoms/liham/prenom-31729', supports:['une des hypothèses étymologiques','usage en France'] },
      { kind:'linguistic', label:'Parents.fr', reference:'Liham/Lyham : autre présentation étymologique, montrant la divergence des sources grand public', url:'https://www.parents.fr/prenoms/liham-46517', supports:['variantes','constat de sources contradictoires'] },
      { kind:'editorial', label:'OUMMAH · prudence étymologique', reference:'Aucune origine arabe précise n’est affirmée en l’absence de source lexicographique solide.', supports:['niveau de confiance'] }
    ]}),
  d('ines-mag','girl','Inès','إيناس','Īnās','Sociabilité, familiarité, compagnie agréable.',['Inès','Ines','Inas','Inass'],['doux','facile-france'],['Arabe'],
    'Dans son usage maghrébin, Inès est souvent une graphie francophone de Īnās (إيناس). Il existe aussi un prénom européen Inés d’une autre origine : les deux histoires ne doivent pas être confondues.'),
  d('nesrine','girl','Nesrine','نسرين','Nasrīn','Églantier / rose sauvage ; nom floral d’origine persane passé en arabe.',['Nesrine','Nasrine','Nasrin','Nesrin'],['doux','facile-france'],['Perse','Usage arabe'], undefined,
    { language:['Persan','Arabe (usage)'], sources:[
      { kind:'linguistic', label:BTN, reference:'Nasrin / نسرين — nom persan associé à une rose sauvage', url:'https://www.behindthename.com/name/nasrin', supports:['origine persane','sens floral','variantes'] },
      { kind:'editorial', label:'OUMMAH · usage Maghreb & diaspora', reference:'Nesrine est une graphie francophone très fréquente de Nasrin.', supports:['variante maghrébine'] }
    ]}),
  d('lilia','girl','Lilia','ليليا','Lilia','Lys, fleur de lys, dans son origine européenne.',['Lilia','Lylia','Lilya'],['doux','facile-france'],['Latin / langues européennes','Usage maghrébin'],
    'Lilia est couramment porté au Maghreb, mais il n’est pas nécessaire de lui inventer une racine arabe : il appartient à la famille européenne de Lily/Lilia, liée au lys.',
    { language:['Latin / langues européennes'], sources:[
      { kind:'linguistic', label:BTN, reference:'Lilia — forme liée à Lily/Lilium selon les usages européens', url:'https://www.behindthename.com/name/lilia', supports:['origine','famille du prénom'] },
      { kind:'editorial', label:'OUMMAH · usage Maghreb & diaspora', reference:'Usage maghrébin moderne distingué de l’étymologie.', supports:['contexte d’usage'] }
    ]}),
  d('rima','girl','Rima','ريما','Rīmā','Gazelle blanche / jeune gazelle, par extension de rīm (ريم).',['Rima','Rym','Reema'],['doux','facile-france']),
  d('zahia','girl','Zahia','زاهية','Zāhiya','Rayonnante, éclatante, florissante.',['Zahia','Zahiya'],['doux','facile-france']),
  d('roua','girl','Roua','رؤى','Ruʾā','Visions, rêves, perceptions.',['Roua','Rouaa','Roaa','Ru’a'],['doux','rare','facile-france']),
  d('wissal','girl','Wissal','وصال','Wiṣāl','Union, rapprochement, lien, rencontre après séparation.',['Wissal','Wisal','Ouissal'],['doux','facile-france']),
  d('wiam','girl','Wiam','وئام','Wiʾām','Harmonie, concorde, entente.',['Wiam','Wiem','Wiaam'],['doux','facile-france']),
  d('ahlem','girl','Ahlem','أحلام','Aḥlām','Rêves.',['Ahlem','Ahlam'],['doux','facile-france']),
  d('emna','girl','Emna','آمنة','Āmina','En sécurité, paisible, rassurée.',['Emna','Amna','Amina'],['doux','facile-france'],['Arabe'],
    'Emna est une graphie tunisienne/francophone courante de Āmina/Āmna (آمنة). Elle ne doit pas être confondue automatiquement avec Amīna (أمينة), « digne de confiance », même si les deux formes se rapprochent en français.'),
  d('feryel','girl','Feryel','فريال','Faryāl','Prénom d’origine persane ; souvent interprété comme « belle / gracieuse », mais l’étymologie exacte varie selon les sources.',['Feryel','Feriel','Ferial','Faryal'],['doux','rare','facile-france'],['Perse','Usage arabe'],
    'Feryel/Ferial est très présent en Afrique du Nord. Les sources s’accordent sur une origine persane mais divergent sur l’analyse détaillée ; la fiche conserve donc une formulation prudente.',
    { language:['Persan','Arabe (usage)'], meaningConfidence:'medium' }),
  d('rihab','girl','Rihab','رحاب','Riḥāb','Vastes espaces, étendues, lieux spacieux.',['Rihab','Rehab','Rihabe'],['doux','facile-france']),
  d('najat','girl','Najat','نجاة','Najāt','Salut, délivrance, fait d’être sauvée.',['Najat','Nadjet','Nejât'],['foi','doux','facile-france']),
  d('insaf','girl','Insaf','إنصاف','Inṣāf','Équité, justice, impartialité.',['Insaf','Insaaf'],['sagesse','facile-france']),
  d('wissam-girl','girl','Wissam','وسام','Wisām','Décoration, médaille, distinction honorifique.',['Wissam','Wisam','Wesam'],['facile-france']),
  d('yamina','girl','Yamina','يمينة','Yamīna','Liée à la droite ; heureuse, de bon augure dans l’usage traditionnel.',['Yamina','Yemina'],['classique','facile-france']),
  d('chokri','boy','Chokri','شكري','Shukrī','Reconnaissant, reconnaissant envers les bienfaits ; lié au remerciement.',['Chokri','Shukri','Choukri'],['doux','facile-france']),
  d('hachemi','boy','Hachemi','هاشمي','Hāshimī','Hachémite ; appartenant ou se rattachant à la lignée de Hāshim.',['Hachemi','Hashimi','Hachemy'],['classique','facile-france'],['Arabe'],
    'Hachemi est un adjectif de relation formé sur Hāshim, ancêtre du clan des Banū Hāshim. Le sens est donc généalogique/historique, pas une qualité morale automatique.'),
  d('khemais','boy','Khemais','خميس','Khamīs','Jeudi ; ancien prénom arabe lié au nom du jour de la semaine.',['Khemais','Khamis','Khmais'],['rare','facile-france']),
  d('larbi','boy','Larbi','العربي','al-ʿArabī','L’Arabe, l’homme arabe.',['Larbi','El Arbi','Al-Arbi','Arbi'],['classique','facile-france']),
  d('mabrouk','boy','Mabrouk','مبروك','Mabrūk','Béni, félicité ; forme maghrébine courante liée à l’idée de bénédiction.',['Mabrouk','Mabruk','Mebrouk'],['classique','facile-france']),
  d('tahar','boy','Tahar','طاهر','Ṭāhir','Pur, propre, chaste.',['Tahar','Tahir','Taher'],['foi','classique','facile-france']),
  d('wadie','boy','Wadie','وديع','Wadīʿ','Doux, calme, paisible.',['Wadie','Wadi','Wadih','Wadi‘'],['doux','rare']),
  d('tayeb','boy','Tayeb','طيب','Ṭayyib','Bon, pur, agréable, sain.',['Tayeb','Taieb','Tayyib','Tayib'],['foi','doux','facile-france']),
  d('lakhdar','boy','Lakhdar','الأخضر','al-Akhḍar','Le vert ; celui qui est vert / verdoyant.',['Lakhdar','Lakhder','Akhdar','El Khadr'],['classique','facile-france']),
  d('atef','boy','Atef','عاطف','ʿĀṭif','Compatissant, affectueux, bienveillant.',['Atef','Atif','Aatif'],['doux','facile-france']),
  d('fella','girl','Fella','فلة','Fulla','Jasmin d’Arabie, fleur blanche très parfumée.',['Fella','Fella','Fulla'],['doux','facile-france'],['Arabe','Usage maghrébin']),
  d('fadila','girl','Fadila','فاضلة','Fāḍila','Vertueuse, excellente, méritante.',['Fadila','Fadhila','Fadhela'],['sagesse','facile-france']),
  d('hakima','girl','Hakima','حكيمة','Ḥakīma','Sage, judicieuse.',['Hakima','Hakeema'],['sagesse','facile-france']),
  d('hania','girl','Hania','هانئة','Hāniʾa','Heureuse, paisible, qui vit dans l’aisance et la satisfaction.',['Hania','Haniya','Hanie'],['doux','facile-france']),
  d('mounia','girl','Mounia','منية','Munya','Souhait, désir, aspiration.',['Mounia','Munya','Mounya'],['doux','facile-france']),
  d('nassima','girl','Nassima','نسيمة','Nasīma','Brise légère, souffle doux.',['Nassima','Nasima','Naseema'],['doux','facile-france']),
  d('rachida','girl','Rachida','رشيدة','Rashīda','Bien guidée, raisonnable, mûre.',['Rachida','Rashida'],['sagesse','facile-france']),
  d('radia','girl','Radia','راضية','Rāḍiya','Satisfaite, contente, agréée.',['Radia','Radhia','Radiya'],['foi','doux','facile-france']),
  d('souad','girl','Souad','سعاد','Suʿād','Bonheur, félicité, bonne fortune.',['Souad','Suad','Souaad'],['classique','doux','facile-france']),
  d('salima','girl','Salima','سليمة','Salīma','Saine, sauve, intacte, en sécurité.',['Salima','Selima'],['doux','facile-france']),
  d('sanaa','girl','Sanaa','سناء','Sanāʾ','Éclat, splendeur, hauteur, rayonnement.',['Sanaa','Sana','Sanae'],['doux','facile-france']),
  d('souhila','girl','Souhila','سهيلة','Suhayla','Douce, facile, aisée ; forme féminine de Suhayl.',['Souhila','Sohila','Suhayla'],['doux','facile-france']),
  d('wassila','girl','Wassila','وسيلة','Wasīla','Moyen, voie, ce par quoi l’on se rapproche ou atteint un but.',['Wassila','Wasila','Ouassila'],['foi','facile-france']),
  d('nadia-maghreb','girl','Nadia','نادية','Nādiya','Fraîche, humide de rosée ; une étymologie arabe possible du prénom Nadia.',['Nadia','Nadiya','Nadya'],['doux','facile-france'],['Arabe','Autres origines possibles'],
    'Nadia existe dans plusieurs traditions. Dans l’analyse arabe de نادية, le nom peut évoquer la fraîcheur ou la rosée ; dans les langues slaves, Nadya est aussi un diminutif de Nadezhda, « espérance ». La fiche signale donc les deux pistes au lieu d’en imposer une seule.',
    { language:['Arabe','Langues slaves (autre origine possible)'], meaningConfidence:'medium', sources:[
      ...arabicSource('نادية','Fraîche, humide de rosée.'),
      { kind:'linguistic', label:BTN, reference:'Nadya/Nadia existe aussi dans les traditions slaves comme forme de Nadezhda.', url:'https://www.behindthename.com/name/nadia', supports:['origine alternative','variantes'] }
    ]}),

  d('aref','boy','Aref','عارف','ʿĀrif','Connaissant, savant, celui qui sait.',['Aref','Arif','Aarif'],['sagesse','facile-france']),
  d('iheb','boy','Iheb','إيهاب','Īhāb','Don, présent, fait d’accorder.',['Iheb','Ihab','Ehab'],['doux','facile-france']),
  d('mahfoud','boy','Mahfoud','محفوظ','Maḥfūẓ','Préservé, protégé, gardé.',['Mahfoud','Mahfouz','Mahfuz'],['foi','facile-france']),
  d('marzouk','boy','Marzouk','مرزوق','Marzūq','Pourvu, gratifié d’une subsistance.',['Marzouk','Marzouq','Marzuk'],['foi','facile-france']),
  d('mokhtar','boy','Mokhtar','مختار','Mukhtār','Choisi, sélectionné.',['Mokhtar','Mukhtar','Mokhtar'],['classique','facile-france']),
  d('rabi','boy','Rabie','ربيع','Rabīʿ','Printemps.',['Rabie','Rabi','Rabee'],['doux','facile-france']),
  d('zoubir','boy','Zoubir','زبير','Zubayr','Ancien prénom arabe ; forme maghrébine de Zubayr, nom d’un Compagnon.',['Zoubir','Zubair','Zubayr','Zoubayr'],['compagnon','classique','facile-france'],['Arabe'],
    'Zoubir est une graphie maghrébine de Zubayr ibn al-ʿAwwām, Compagnon du Prophète ﷺ. L’étymologie exacte du nom ancien est moins importante ici que son précédent historique.',
    { historicalRole:'Zubayr ibn al-ʿAwwām رضي الله عنه, Compagnon du Prophète ﷺ.', meaningConfidence:'medium' }),
  d('nassira','girl','Nassira','ناصرة','Nāṣira','Celle qui aide, soutient ou secourt.',['Nassira','Nasira','Nacera'],['doux','facile-france']),
  d('mounira','girl','Mounira','منيرة','Munīra','Lumineuse, rayonnante.',['Mounira','Munira'],['doux','facile-france']),
  d('cherifa','girl','Cherifa','شريفة','Sharīfa','Noble, honorable.',['Cherifa','Sharifa','Chérifa'],['sagesse','facile-france']),
  d('fatiha','girl','Fatiha','فاتحة','Fātiḥa','Celle qui ouvre ; ouverture.',['Fatiha','Fateha'],['foi','classique','facile-france'],['Arabe'],
    'Fātiḥa signifie « ouverture ». Le mot est aussi le titre de la première sourate du Coran, al-Fātiḥa. Cela ne signifie pas que le prénom soit spécifiquement recommandé par un texte.',
    { quranReference:'Sourate 1 · Al-Fātiḥa' }),
  d('sakina','girl','Sakina','سكينة','Sakīna','Quiétude, sérénité, tranquillité.',['Sakina','Sakina','Sékina'],['foi','doux','facile-france']),
  d('rabiaa','girl','Rabiaa','ربيعة','Rabīʿa','Prénom arabe ancien ; forme féminine liée à Rabīʿ et à l’idée de printemps.',['Rabiaa','Rabia','Rabi‘a'],['classique','doux']),

  d('djamila','girl','Djamila','جميلة','Jamīla','Belle, gracieuse, agréable.',['Djamila','Jamila','Jemila'],['doux','classique','facile-france']),
  d('dalila-mag','girl','Dalila','دليلة','Dalīla','Guide, celle qui indique le chemin ; preuve ou indication.',['Dalila','Dalilah'],['sagesse','facile-france']),
  d('wahiba','girl','Wahiba','واهبة','Wāhiba','Donatrice, généreuse, celle qui donne.',['Wahiba','Ouahiba','Wahiba'],['doux','facile-france']),
  d('zoubida','girl','Zoubida','زبيدة','Zubayda','Petite part précieuse ; diminutif de zubda, « crème, essence, meilleur de quelque chose ».',['Zoubida','Zubayda','Zubeida'],['classique','doux','facile-france']),
  d('dorra','girl','Dorra','درة','Durra','Perle.',['Dorra','Dorra','Durra','Dura'],['doux','court','facile-france']),
  d('ilhem','girl','Ilhem','إلهام','Ilhām','Inspiration.',['Ilhem','Ilham','Elhem'],['doux','facile-france']),
  d('ibtissem','girl','Ibtissem','ابتسام','Ibtisām','Sourire.',['Ibtissem','Ibtissam','Ibtisam'],['doux','facile-france']),
  d('nawres','girl','Nawres','نورس','Nawras','Mouette, oiseau marin.',['Nawres','Nawrass','Nawras'],['rare','doux']),
  d('dounia','girl','Dounia','دنيا','Dunyā','Le monde d’ici-bas, la vie présente.',['Dounia','Dunia','Dunya'],['coranique','facile-france'],['Arabe'],
    'Dunyā est un mot arabe très fréquent dans le vocabulaire islamique pour désigner la vie présente / ce monde. Le fait que le mot soit coranique ne constitue pas une recommandation particulière de le donner comme prénom.',
    { status:'note', statusReason:'Prénom culturellement permis ; son sens renvoie à la vie d’ici-bas et mérite simplement d’être compris.', quranReference:'Le terme al-dunyā apparaît à de nombreuses reprises dans le Coran.' }),

];

// Graphies maghrébines/françaises ajoutées à des fiches qui existent déjà.
// Elles restent UNE seule fiche : la recherche retrouve toutes les orthographes sans créer de doublons.
export const MAGHREB_VARIANTS_BY_ID: Record<string, string[]> = {
  adil: ['Adel'],
  amin: ['Amine'],
  anas: ['Anis'],
  ayyub: ['Ayoub'],
  bilal: ['Bilel'],
  dawud: ['Daoud','Dawoud'],
  faris: ['Fares','Farès'],
  faruq: ['Farouk'],
  hisham: ['Hichem','Hicham'],
  hilal: ['Hilel'],
  jamal: ['Djamel'],
  jalal: ['Jalel'],
  jamil: ['Djamil'],
  kamil: ['Kamel'],
  munir: ['Mounir'],
  nasir: ['Nacer','Nasser'],
  qays: ['Kais','Kaïs','Qais'],
  rafiq: ['Rafik'],
  rashid: ['Rachid','Rached'],
  rida: ['Reda','Ridha'],
  salim: ['Selim'],
  sulayman: ['Slimane','Souleymane'],
  tawfiq: ['Toufik','Tewfik'],
  tariq: ['Tarek','Tarik'],
  uthman: ['Othman'],
  yunus: ['Younes','Younès'],
  zakariyya: ['Zakaria'],
  ziyad: ['Zied','Ziad'],
  maryam: ['Meryem','Meriem','Mariem','Meryam'],
  sumayya: ['Soumia','Soumeya'],
  yasmin: ['Yasmine','Yasmina'],
  asiya: ['Assia'],
  amal: ['Amel'],
  nawal: ['Nawel','Naouel'],
  layla: ['Leila','Leïla','Leyla','Laila'],
  lubna: ['Loubna'],
  thurayya: ['Soraya','Soraya'],
  siham: ['Sihem'],
  zahra: ['Zohra'],
  nur: ['Nour','Noura','Nora'],
  yusra: ['Yosra'],
  shaima: ['Chaima','Chaïma'],
  kawthar: ['Kawther','Kaouthar'],
  manal: ['Manel'],
  kanza: ['Kenza'],
  lina: ['Lyna'],
  iman: ['Imen','Imane'],
  masud: ['Messaoud','Massoud'],
  mawlud: ['Miloud','Mouloud'],
  khalid: ['Khaled'],
  hafiz: ['Hafid','Hafedh','Hafez'],
  sadiq: ['Sadek','Seddik'],
  bashir: ['Bachir'],
  ibrahim: ['Brahim'],
  jamilah: ['Djamila','Jamila'],
  anisa: ['Anissa'],
  hind: ['Henda'],
  husayn: ['Houcine','Hocine','Hussein'],
  shakir: ['Chaker'],
  ishaq: ['Ishak'],
  lutfi: ['Lotfi'],
  mahdi: ['Mehdi','Medhi'],
  yasin: ['Yacine','Yassine'],
  ilyas: ['Ilyes','Ilias','Lyes'],
  husam: ['Houssem','Houssam'],
  wasim: ['Wassim'],
  aisha: ['Aicha','Aïcha'],
  khadija: ['Khadidja'],
  rim: ['Rym'],
  riyad: ['Riadh','Ryad','Riad'],
  khayra: ['Kheira','Kheïra'],
  asma: ['Asmae','Asmaa'],
  safiyya: ['Safiya','Safia'],
  basma: ['Besma'],
  bushra: ['Bochra','Bouchra'],
};
