/**
 * English text of the French sentences stored in the name data (roles, stories, nuances, origins, Quran
 * references, source lines). Keyed by the French sentence: a sentence missing here stays in French.
 * Hadith excerpts are the English text of the fawazahmed0 collections; the verse is Saheeh International.
 */
export const NAME_TEXT_EN: Record<string, string> = {
  // Roles
  'Nom porté par de nombreux Compagnons.': 'Name borne by many Companions.',
  'Nom du Prophète Muhammad ﷺ.': 'Name of the Prophet Muhammad ﷺ.',
  'Un des noms du Prophète ﷺ.': 'One of the names of the Prophet ﷺ.',
  'Luqman le sage.': 'Luqman the wise.',
  'Nom de plusieurs femmes de la Maison prophétique et des premières générations.': 'Name of several women of the Prophet’s household and of the first generations.',
  'Nom porté notamment par Khawla bint Thaʿlaba رضي الله عنها.': 'Name borne notably by Khawla bint Thaʿlaba رضي الله عنها.',
  'Amina bint Wahb, mère du Prophète ﷺ.': 'Amina bint Wahb, mother of the Prophet ﷺ.',
  'Zubayr ibn al-ʿAwwām رضي الله عنه, Compagnon du Prophète ﷺ.': 'Zubayr ibn al-ʿAwwām رضي الله عنه, Companion of the Prophet ﷺ.',

  // Stories
  'Nom composé de ʿabd, « serviteur », et Allah. Il exprime directement la servitude vouée à Allah.': 'Name made of ʿabd, “servant”, and Allah. It directly expresses servitude devoted to Allah.',
  'Nom composé de ʿabd, « serviteur », et ar-Rahman, l’un des noms d’Allah.': 'Name made of ʿabd, “servant”, and ar-Rahman, one of the names of Allah.',
  'Nom du dernier Prophète ﷺ, mentionné explicitement dans le Coran.': 'Name of the last Prophet ﷺ, mentioned explicitly in the Quran.',
  'Nom mentionné dans le Coran dans l’annonce faite par ʿIsa عليه السلام.': 'Name mentioned in the Quran in the good news given by ʿIsa عليه السلام.',
  'Adam عليه السلام est le premier homme et un prophète dans la tradition islamique.': 'Adam عليه السلام is the first man and a prophet in the Islamic tradition.',
  'Idris عليه السلام est cité parmi les prophètes véridiques et patients.': 'Idris عليه السلام is cited among the truthful and patient prophets.',
  'Nuh عليه السلام est un messager majeur ; une sourate porte son nom.': 'Nuh عليه السلام is a major messenger; a surah bears his name.',
  'Hud عليه السلام fut envoyé au peuple de ʿAd.': 'Hud عليه السلام was sent to the people of ʿAd.',
  'Salih عليه السلام fut envoyé au peuple de Thamud.': 'Salih عليه السلام was sent to the people of Thamud.',
  'Ibrahim عليه السلام occupe une place centrale dans le Coran et est décrit comme un modèle de foi.': 'Ibrahim عليه السلام holds a central place in the Quran and is described as a model of faith.',
  'Lut عليه السلام est cité à plusieurs reprises dans le Coran.': 'Lut عليه السلام is mentioned several times in the Quran.',
  'Ismail عليه السلام est loué dans le Coran pour sa fidélité à la promesse et sa patience.': 'Ismail عليه السلام is praised in the Quran for being true to his promise and for his patience.',
  'Ishaq عليه السلام est le fils d’Ibrahim et un prophète mentionné dans le Coran.': 'Ishaq عليه السلام is the son of Ibrahim and a prophet mentioned in the Quran.',
  'Yaqub عليه السلام, également appelé Israël, est le père de Yusuf.': 'Yaqub عليه السلام, also called Israel, is the father of Yusuf.',
  'L’histoire de Yusuf عليه السلام occupe une sourate entière du Coran.': 'The story of Yusuf عليه السلام fills a whole surah of the Quran.',
  'Shuayb عليه السلام fut envoyé aux gens de Madyan.': 'Shuayb عليه السلام was sent to the people of Madyan.',
  'Ayyub عليه السلام est associé à la patience dans l’épreuve.': 'Ayyub عليه السلام is associated with patience in trial.',
  'Musa عليه السلام est le prophète le plus fréquemment nommé dans le Coran.': 'Musa عليه السلام is the prophet named most often in the Quran.',
  'Harun عليه السلام est le frère de Musa et son soutien dans la mission.': 'Harun عليه السلام is the brother of Musa and his support in the mission.',
  'Sulayman عليه السلام fut prophète et roi, fils de Dawud.': 'Sulayman عليه السلام was a prophet and a king, the son of Dawud.',
  'Ilyas عليه السلام est un prophète mentionné dans le Coran.': 'Ilyas عليه السلام is a prophet mentioned in the Quran.',
  'Yunus عليه السلام est notamment connu pour l’épreuve du grand poisson et son invocation.': 'Yunus عليه السلام is known notably for the trial of the great fish and his supplication.',
  'Zakariya عليه السلام invoqua Allah pour une descendance pieuse malgré son grand âge.': 'Zakariya عليه السلام asked Allah for pious offspring despite his old age.',
  'Le Coran indique que ce nom fut donné à Yahya عليه السلام par Allah.': 'The Quran states that this name was given to Yahya عليه السلام by Allah.',
  'ʿIsa عليه السلام, fils de Maryam, est un grand prophète et messager dans l’Islam.': 'ʿIsa عليه السلام, son of Maryam, is a great prophet and messenger in Islam.',
  'Nom de ʿUmar ibn al-Khattab رضي الله عنه, deuxième calife bien guidé.': 'Name of ʿUmar ibn al-Khattab رضي الله عنه, the second rightly guided caliph.',
  'Nom de ʿAli ibn Abi Talib رضي الله عنه, cousin et gendre du Prophète ﷺ.': 'Name of ʿAli ibn Abi Talib رضي الله عنه, cousin and son-in-law of the Prophet ﷺ.',
  'Bilal ibn Rabah رضي الله عنه fut un Compagnon célèbre et muezzin du Prophète ﷺ.': 'Bilal ibn Rabah رضي الله عنه was a famous Companion and the muezzin of the Prophet ﷺ.',
  'Hamza ibn ʿAbd al-Muttalib رضي الله عنه était l’oncle du Prophète ﷺ et un Compagnon majeur.': 'Hamza ibn ʿAbd al-Muttalib رضي الله عنه was the uncle of the Prophet ﷺ and a major Companion.',
  'Salman al-Farisi رضي الله عنه est connu pour son long parcours vers la vérité.': 'Salman al-Farisi رضي الله عنه is known for his long journey towards the truth.',
  'Anas ibn Malik رضي الله عنه servit le Prophète ﷺ et transmit de nombreux hadiths.': 'Anas ibn Malik رضي الله عنه served the Prophet ﷺ and transmitted many hadiths.',
  'Talha ibn ʿUbayd Allah رضي الله عنه compte parmi les Compagnons éminents.': 'Talha ibn ʿUbayd Allah رضي الله عنه is among the eminent Companions.',
  'Az-Zubayr ibn al-ʿAwwam رضي الله عنه fut un Compagnon proche du Prophète ﷺ.': 'Az-Zubayr ibn al-ʿAwwam رضي الله عنه was a close Companion of the Prophet ﷺ.',
  'Nom porté par plusieurs Compagnons, notamment Saʿd ibn Abi Waqqas رضي الله عنه.': 'Name borne by several Companions, notably Saʿd ibn Abi Waqqas رضي الله عنه.',
  'Muʿadh ibn Jabal رضي الله عنه était connu pour son savoir.': 'Muʿadh ibn Jabal رضي الله عنه was known for his knowledge.',
  'ʿAmmar ibn Yasir رضي الله عنه fut parmi les premiers musulmans.': 'ʿAmmar ibn Yasir رضي الله عنه was among the first Muslims.',
  'Khalid ibn al-Walid رضي الله عنه fut un Compagnon et chef militaire célèbre.': 'Khalid ibn al-Walid رضي الله عنه was a Companion and a famous military commander.',
  'Al-Husayn ibn ʿAli رضي الله عنهما était le petit-fils du Prophète ﷺ.': 'Al-Husayn ibn ʿAli رضي الله عنهما was the grandson of the Prophet ﷺ.',
  'Ar-Rayyân est le nom d’une des huit portes du Paradis. Les jeûneurs y seront appelés et entreront par cette porte au Jour de la Résurrection.': 'Ar-Rayyan is the name of one of the eight gates of Paradise. Those who fast will be called to it and will enter through this gate on the Day of Resurrection.',
  'Luqman est un homme sage auquel une sourate du Coran consacre un passage et des conseils à son fils.': 'Luqman is a wise man to whom a surah of the Quran devotes a passage, with his advice to his son.',
  'Adjectif arabe de belle signification, largement utilisé comme prénom.': 'Arabic adjective with a beautiful meaning, widely used as a first name.',
  'Adjectif arabe désignant une personne sage ou judicieuse.': 'Arabic adjective describing a wise or judicious person.',
  'Prénom arabe fondé sur une qualité morale claire.': 'Arabic first name based on a clear moral quality.',
  'Prénom arabe culturel de sens social et agréable.': 'Cultural Arabic first name with a social, pleasant meaning.',
  'Khadija bint Khuwaylid رضي الله عنها fut la première épouse du Prophète ﷺ et la première à croire en son message.': 'Khadija bint Khuwaylid رضي الله عنها was the first wife of the Prophet ﷺ and the first to believe in his message.',
  'ʿAisha رضي الله عنها fut épouse du Prophète ﷺ et une grande transmettrice de savoir.': 'ʿAisha رضي الله عنها was a wife of the Prophet ﷺ and a great transmitter of knowledge.',
  'Fatima az-Zahra رضي الله عنها était la fille du Prophète ﷺ.': 'Fatima az-Zahra رضي الله عنها was the daughter of the Prophet ﷺ.',
  'Hafsa bint ʿUmar رضي الله عنها fut épouse du Prophète ﷺ.': 'Hafsa bint ʿUmar رضي الله عنها was a wife of the Prophet ﷺ.',
  'Ruqayya رضي الله عنها était une fille du Prophète ﷺ.': 'Ruqayya رضي الله عنها was a daughter of the Prophet ﷺ.',
  'Umm Kulthum رضي الله عنها était une fille du Prophète ﷺ. Le nom est historiquement utilisé comme prénom composé.': 'Umm Kulthum رضي الله عنها was a daughter of the Prophet ﷺ. The name has historically been used as a compound first name.',
  'Safiyya bint Huyayy رضي الله عنها fut épouse du Prophète ﷺ.': 'Safiyya bint Huyayy رضي الله عنها was a wife of the Prophet ﷺ.',
  'Sumayya bint Khayyat رضي الله عنها est connue comme l’une des premières martyres de l’Islam.': 'Sumayya bint Khayyat رضي الله عنها is known as one of the first martyrs of Islam.',
  'Asma bint Abi Bakr رضي الله عنها est connue pour son courage et son rôle lors de l’Hégire.': 'Asma bint Abi Bakr رضي الله عنها is known for her courage and her role during the Hijra.',
  'Juwayriya رضي الله عنها fut épouse du Prophète ﷺ. Son nom précédent, Barrah, fut changé en Juwayriya.': 'Juwayriya رضي الله عنها was a wife of the Prophet ﷺ. Her earlier name, Barrah, was changed to Juwayriya.',
  'Maymuna bint al-Harith رضي الله عنها fut épouse du Prophète ﷺ.': 'Maymuna bint al-Harith رضي الله عنها was a wife of the Prophet ﷺ.',
  'Nom porté par plusieurs femmes des premières générations musulmanes.': 'Name borne by several women of the first Muslim generations.',
  'Emna est une graphie tunisienne/francophone courante de Āmina/Āmna (آمنة). Elle ne doit pas être confondue automatiquement avec Amīna (أمينة), « digne de confiance », même si les deux formes se rapprochent en français.': 'Emna is a common Tunisian/French spelling of Āmina/Āmna (آمنة). It should not automatically be confused with Amīna (أمينة), “trustworthy”, even though the two forms look alike in French.',
  'Prénom arabe ancien lié à la racine de paix et de sécurité.': 'Ancient Arabic first name linked to the root of peace and safety.',
  'Le mot hudā est très présent dans le Coran avec le sens de guidée ; son usage comme prénom est culturel.': 'The word hudā occurs often in the Quran with the meaning of guidance; its use as a first name is cultural.',
  'Mot central du vocabulaire coranique, devenu un prénom courant dans de nombreux pays.': 'A central word of the Quranic vocabulary, now a common first name in many countries.',
  'As-Safa est l’un des deux monts associés au saʿy du Hajj et de la ʿUmra.': 'As-Safa is one of the two hills associated with the saʿy of Hajj and ʿUmra.',
  'Al-Marwa est l’un des deux monts associés au saʿy.': 'Al-Marwa is one of the two hills associated with the saʿy.',
  'Tasnim apparaît dans la description du Paradis.': 'Tasnim appears in the description of Paradise.',
  'Le terme apparaît dans la description des boissons du Paradis.': 'The term appears in the description of the drinks of Paradise.',
  'Le terme sidra apparaît dans le Coran, notamment dans l’expression Sidrat al-Muntaha.': 'The term sidra appears in the Quran, notably in the expression Sidrat al-Muntaha.',
  'Mot arabe et coranique de sens positif.': 'Arabic and Quranic word with a positive meaning.',
  'Mot arabe présent dans le Coran avec différents contextes.': 'Arabic word found in the Quran in different contexts.',
  'Āya est un terme central du Coran, employé pour les signes d’Allah et les versets.': 'Āya is a central term of the Quran, used for the signs of Allah and for verses.',
  'Prénom très court dont le son peut aussi exister dans d’autres langues avec des origines différentes.': 'A very short first name whose sound may also exist in other languages, with different origins.',
  'Prénom moderne dérivé d’un mot arabe clair.': 'Modern first name derived from a clear Arabic word.',
  'Prénom arabe court fondé sur un mot de sens positif.': 'Short Arabic first name based on a word with a positive meaning.',
  'Mot arabe courant et présent dans le Coran, utilisé comme prénom.': 'Common Arabic word found in the Quran, used as a first name.',
  'Bahri est l’adjectif arabe formé sur baḥr (بحر), « mer ». La racine ب ح ر est très présente dans le Coran ; cela ne signifie pas que Bahri soit lui-même un prénom coranique.': 'Bahri is the Arabic adjective formed on baḥr (بحر), “sea”. The root ب ح ر occurs often in the Quran; this does not mean that Bahri is itself a Quranic name.',
  'Sofiane est la graphie francophone très répandue de Sufyān. Le nom est ancien dans l’histoire arabe ; plutôt que de lui attribuer un faux sens certain, OUMMAH signale que son étymologie précise est discutée.': 'Sofiane is the widespread French spelling of Sufyān. The name is old in Arab history; rather than give it a false certain meaning, OUMMAH notes that its exact etymology is disputed.',
  'Yanis est très porté dans les familles maghrébines de France mais n’est pas, à l’origine, un prénom arabe. Il correspond à une forme grecque/française de la famille de Jean/Yannis.': 'Yanis is very common in North African families in France but is not originally an Arabic name. It is a Greek/French form from the family of Jean/Yannis.',
  'Ghassan est un ancien nom arabe surtout connu par la confédération des Ghassanides. Son étymologie lexicale est moins sûre que son usage historique ; OUMMAH ne lui attribue donc pas un sens artificiellement précis.': 'Ghassan is an old Arabic name known mainly through the Ghassanid confederation. Its lexical etymology is less certain than its historical use, so OUMMAH does not give it an artificially precise meaning.',
  'Skander est une forme maghrébine d’Iskandar, lui-même forme arabisée d’Alexandre. Son sens vient donc de l’étymologie grecque, pas d’une racine arabe.': 'Skander is a North African form of Iskandar, itself an Arabized form of Alexander. Its meaning therefore comes from Greek etymology, not from an Arabic root.',
  'Sonia est très utilisée au Maghreb mais son origine n’est pas arabe : c’est une variante de Sonya, diminutif russe de Sophia, nom grec associé à la sagesse.': 'Sonia is widely used in North Africa but its origin is not Arabic: it is a variant of Sonya, a Russian diminutive of Sophia, a Greek name associated with wisdom.',
  'Lyham/Liham est un prénom moderne porté notamment dans des familles maghrébines en France. Les sources publiques lui attribuent des origines contradictoires. OUMMAH préfère donc afficher cette incertitude plutôt que d’inventer une origine arabe.': 'Lyham/Liham is a modern first name borne notably in North African families in France. Public sources give it contradictory origins, so OUMMAH shows this uncertainty rather than invent an Arabic origin.',
  'Dans son usage maghrébin, Inès est souvent une graphie francophone de Īnās (إيناس). Il existe aussi un prénom européen Inés d’une autre origine : les deux histoires ne doivent pas être confondues.': 'In North African use, Inès is often a French spelling of Īnās (إيناس). There is also a European name Inés with another origin: the two histories should not be confused.',
  'Lilia est couramment porté au Maghreb, mais il n’est pas nécessaire de lui inventer une racine arabe : il appartient à la famille européenne de Lily/Lilia, liée au lys.': 'Lilia is common in North Africa, but there is no need to invent an Arabic root for it: it belongs to the European family of Lily/Lilia, linked to the lily.',
  'Feryel/Ferial est très présent en Afrique du Nord. Les sources s’accordent sur une origine persane mais divergent sur l’analyse détaillée ; la fiche conserve donc une formulation prudente.': 'Feryel/Ferial is very common in North Africa. Sources agree on a Persian origin but differ on the detailed analysis, so this entry keeps a cautious wording.',
  'Hachemi est un adjectif de relation formé sur Hāshim, ancêtre du clan des Banū Hāshim. Le sens est donc généalogique/historique, pas une qualité morale automatique.': 'Hachemi is a relational adjective formed on Hāshim, ancestor of the Banū Hāshim clan. Its meaning is therefore genealogical/historical, not an automatic moral quality.',
  'Zoubir est une graphie maghrébine de Zubayr ibn al-ʿAwwām, Compagnon du Prophète ﷺ. L’étymologie exacte du nom ancien est moins importante ici que son précédent historique.': 'Zoubir is a North African spelling of Zubayr ibn al-ʿAwwām, Companion of the Prophet ﷺ. The exact etymology of the old name matters less here than its historical precedent.',
  'Fātiḥa signifie « ouverture ». Le mot est aussi le titre de la première sourate du Coran, al-Fātiḥa. Cela ne signifie pas que le prénom soit spécifiquement recommandé par un texte.': 'Fātiḥa means “opening”. The word is also the title of the first surah of the Quran, al-Fātiḥa. This does not mean that the name is specifically recommended by a text.',
  'Dunyā est un mot arabe très fréquent dans le vocabulaire islamique pour désigner la vie présente / ce monde. Le fait que le mot soit coranique ne constitue pas une recommandation particulière de le donner comme prénom.': 'Dunyā is a very frequent Arabic word in Islamic vocabulary for the present life / this world. The fact that the word is Quranic is not a particular recommendation to give it as a first name.',

  // Stories of the names added with Behind the Name: its English text, word for word
  '‘Uthmân fut un Compagnon du Prophète Muhammad ﷺ et épousa deux de ses filles. Il fut le troisième calife des musulmans.': 'Uthman was a companion of the Prophet Muhammad who married two of his daughters. He was the third caliph of the Muslims.',
  'Mus‘ab ibn ‘Umayr fut un Compagnon du Prophète Muhammad ﷺ.': 'Mus\'ab ibn Umayr was a companion of the Prophet Muhammad.',
  'C’était le nom d’une épouse du Prophète Muhammad ﷺ.': 'This was the name of a wife of the Prophet Muhammad.',
  'C’était le nom de l’une des épouses du Prophète Muhammad ﷺ.': 'This was the name of one of the wives of the Prophet Muhammad.',

  // Nuances
  'La variante « Houssem » est un autre prénom en arabe ; ne pas les confondre.': 'The variant “Houssem” is a different name in Arabic; do not confuse them.',
  'Ne pas le classer automatiquement parmi les prophètes.': 'Do not automatically count him among the prophets.',
  'La nuance porte sur l’usage absolu des noms divins, pas sur l’adjectif humain « Karim ».': 'The caution concerns the absolute use of divine names, not the human adjective “Karim”.',
  'Comme pour certains attributs, l’usage humain relatif se distingue de l’attribut divin absolu « al-Hakim ».': 'As with some attributes, the relative human use is distinct from the absolute divine attribute “al-Hakim”.',
  'Historiquement, « Umm » peut fonctionner comme partie d’un nom ou d’une kunya selon le contexte.': 'Historically, “Umm” can work as part of a name or of a kunya, depending on the context.',
  '« Sofia » a généralement une autre origine ; ne pas l’assimiler automatiquement à Safiyya.': '“Sofia” usually has another origin; do not automatically treat it as Safiyya.',
  'Prénom mixte dans plusieurs cultures.': 'Unisex first name in several cultures.',
  'Exemple utile de mot coranique dont la présence dans le texte ne suffit pas à établir une recommandation.': 'A useful example of a Quranic word whose presence in the text is not enough to make it a recommendation.',
  'Même graphie sonore, plusieurs origines possibles.': 'Same sound, several possible origins.',

  // Quran references
  'Le terme al-dunyā apparaît à de nombreuses reprises dans le Coran.': 'The term al-dunyā appears many times in the Quran.',

  // Origins
  'Arabe': 'Arabic',
  'Sémitique': 'Semitic',
  'Usage arabe': 'Arabic usage',
  'Ancienne': 'Ancient',
  'Autres langues possibles': 'Other possible languages',
  'Perse': 'Persian',
  'Turc/Persan': 'Turkish/Persian',
  'Usage arabe moderne': 'Modern Arabic usage',
  'Autres origines': 'Other origins',
  'Persan ancien': 'Old Persian',
  'Grec': 'Greek',
  'Usage français': 'French usage',
  'Forme arabisée': 'Arabized form',
  'Forme européenne': 'European form',
  'Usage français et maghrébin': 'French and North African usage',
  'Étymologie discutée': 'Disputed etymology',
  'Latin / langues européennes': 'Latin / European languages',
  'Usage maghrébin': 'North African usage',

  // Source labels, references and notes
  'Coran': 'Quran',
  'Coran · traduction Hamidullah': 'Quran · Saheeh International',
  'Référence': 'Reference',
  'INSEE · Fichier des prénoms': 'INSEE · French first-name file',
  'Le sens de la fiche est une reformulation française ; la base n’est pas un avis religieux.': 'The dataset is not a religious ruling.',
  'Source linguistique ; elle ne donne pas de statut religieux.': 'Linguistic source; it gives no religious status.',
  'La présence dans le Coran ne constitue pas, à elle seule, une recommandation de porter le prénom.': 'Being in the Quran is not, by itself, a recommendation to give the name.',
  'La fréquence d’une graphie ne détermine ni son sens ni son statut religieux.': 'How common a spelling is decides neither its meaning nor its religious status.',
  'Sahih al-Bukhari 1896 et 3257 ; Sahih Muslim 1152.': 'Sahih al-Bukhari 1896 and 3257; Sahih Muslim 1152.',
  'Hadith 1896 — Ar-Rayyân est une porte du Paradis réservée aux jeûneurs.': 'Hadith 1896 — Ar-Rayyan is a gate of Paradise reserved for those who fast.',
  'Hadith 1152 — la porte Rayyân est réservée aux jeûneurs.': 'Hadith 1152 — the gate Rayyan is reserved for those who fast.',
  'Données françaises de prénoms attribués entre 1900 et 2025 ; utilisées comme repère pour privilégier, lorsque c’est clair, la graphie la plus usuelle en France.': 'French data on first names given between 1900 and 2025; used to prefer, when it is clear, the most usual spelling in France.',
  'Sahih Muslim 2140-2142 ; Sahih al-Bukhari 6192.': 'Sahih Muslim 2140-2142; Sahih al-Bukhari 6192.',
  'Racine ب ح ر : baḥr, « mer »': 'Root ب ح ر: baḥr, “sea”',
  'Yanis — usage grec et français ; variante de Gianis/Yannis': 'Yanis — Greek and French usage; variant of Gianis/Yannis',
  'Nail / نائل — « attainer »': 'Nail / نائل — “attainer”',
  'Naim / نعيم — « tranquil, happy, at ease »': 'Naim / نعيم — “tranquil, happy, at ease”',
  'Iskandar — forme arabe d’Alexander': 'Iskandar — Arabic form of Alexander',
  'Sonia — variante de Sonya ; Sonya est un diminutif russe de Sophia': 'Sonia — variant of Sonya; Sonya is a Russian diminutive of Sophia',
  'Sonya — diminutif russe de Sophia': 'Sonya — Russian diminutive of Sophia',
  'Liham rapproché de Liam/William ; étymologie germanique proposée': 'Liham linked to Liam/William; Germanic etymology proposed',
  'Liham/Lyham : autre présentation étymologique, montrant la divergence des sources grand public': 'Liham/Lyham: another etymology, showing how general-audience sources disagree',
  'Nasrin / نسرين — nom persan associé à une rose sauvage': 'Nasrin / نسرين — Persian name associated with a wild rose',
  'Lilia — forme liée à Lily/Lilium selon les usages européens': 'Lilia — form linked to Lily/Lilium in European usage',
  'Ce Nom figure dans la liste des Noms d’Allah établie par Ibn ‘Uthaymîn à partir du Coran et de la Sunna (al-Qawâ‘id al-Muthlâ, p. 15-16).': 'This Name is in the list of the Names of Allah drawn up by Ibn ‘Uthaymîn from the Quran and the Sunna (al-Qawâ‘id al-Muthlâ, pp. 15-16).',
  '6:89 — « C’est à eux que Nous avons donné le Livre, la sagesse et la prophétie. »': '6:89 — “Those are the ones to whom We gave the Scripture and authority and prophethood.”',
  'Hadith rapporté par ‘Ubaydullah al-Khawlânî : « J’ai entendu ‘Uthman bin ‘Affan dire… »': 'Narrated \'Ubaidullah Al-Khaulani: “I heard `Uthman bin `Affan saying…”',
  'Hadith rapporté par Usama bin Zaid.': 'Narrated Usama bin Zaid.',
  '‘Abd ar-Rahmân ibn ‘Awf : « Mus‘ab bin ‘Umair a été martyrisé… »': '`Abdur-Rahman bin `Auf: “Mus`ab bin `Umair was martyred…”',
  '‘Aisha : « Sauda bint Zam‘a, l’épouse du Prophète (ﷺ), est sortie… »': '`Aisha: “Sauda bint Zam`a the wife of the Prophet (ﷺ) went out…”',
  '‘Aisha : « Hind bint ‘Utba est venue et a dit : Ô Messager d’Allah !… »': '\'Aishah: “Hind bint \'Utba came and said, O Allah\'s Messenger!…”',
};

/** Sentences built on a pattern (prophet roles, ʿAbd + Name stories, dataset and Behind the Name lines). */
const PATTERNS_EN: [RegExp, string][] = [
  [/^Prophète (.+)$/, 'Prophet $1'],
  [/^Ce prénom suit la construction arabe ʿAbd \+ un Nom d’Allah\. Ici, le second élément est (.+)\.$/, 'This name follows the Arabic pattern ʿAbd + a Name of Allah. Here the second part is $1.'],
  [/^Entrée « (.+) » · base de 14 585 prénoms issue de muslimnames\.com$/, 'Entry “$1” · dataset of 14,585 names from muslimnames.com'],
  [/^Page « (.+) »$/, 'Page “$1”'],
  [/^Notamment sourates (\d+) et (\d+)$/, 'Notably surahs $1 and $2'],
  [/^Notamment /, 'Notably '],
  [/Sourate (\d+)/g, 'Surah $1'],
];

/** English for a French sentence of the name data; unknown sentences stay in French. */
export function nameTextEn(french: string): string {
  const known = NAME_TEXT_EN[french];
  if (known) return known;
  let text = french;
  for (const [pattern, english] of PATTERNS_EN) text = text.replace(pattern, english);
  return text;
}

/** Meaning of the names added on 2026-10-05: the Behind the Name definition, word for word. */
export const ADDITION_MEANINGS_EN: Record<string, string> = {
  'al-yasa': 'Name of a prophet mentioned in the Quran (6:86; 38:48), which the Saheeh International translation renders as “Elisha”.',
  uthman: 'Means "baby bustard" in Arabic (a bustard is a type of large bird).',
  usama: 'Means "lion" in Arabic.',
  musab: 'Means "hard, difficult, tough" in Arabic, from the root صعب (ṣaʿuba) meaning "to be hard, to be difficult".',
  sawda: 'Means "black" in Arabic.',
  hind: 'Possibly means "group of camels" in Arabic.',
  ramla: 'Means "sand" in Arabic.',
};
