// Generated on 2026-10-05: each entry was checked, not assumed.
// dataset: the name (same gender) is in the Muslim Names Dataset CSV (huggingface.co/datasets/wpacademy/muslim-names-dataset).
// behindTheName: the page exists and its usage matches the fiche's origin; when the page shows an Arabic-script form,
// it is the fiche's Arabic spelling.
export const VERIFIED_NAME_SOURCES: Record<string, { dataset?: string; behindTheName?: string }> = {
  'aabid': { dataset: "Aabid" },
  'abbas': { dataset: "Abbas" },
  'abdullah': { dataset: "Abdallah", behindTheName: 'https://www.behindthename.com/name/abdullah' },
  'abdurrahman': { behindTheName: 'https://www.behindthename.com/name/abderrahman' },
  'abir': { behindTheName: 'https://www.behindthename.com/name/abir' },
  'abrar-b': { dataset: "Abrar" },
  'adam': { behindTheName: 'https://www.behindthename.com/name/adam' },
  'adeeb': { dataset: "Adib" },
  'adham': { dataset: "Adham" },
  'adiba-g': { dataset: "Adiba" },
  'adil': { dataset: "Adil", behindTheName: 'https://www.behindthename.com/name/adil' },
  'adila': { dataset: "Aadila", behindTheName: 'https://www.behindthename.com/name/adila' },
  'adiyy': { dataset: "Adi" },
  'afaf': { dataset: "Afaf", behindTheName: 'https://www.behindthename.com/name/afaf' },
  'afif': { dataset: "Afif" },
  'afifa': { dataset: "Afifa" },
  'afnan-b': { dataset: "Afnan" },
  'afra': { dataset: "Afraa", behindTheName: 'https://www.behindthename.com/name/afra' },
  'ahlem': { dataset: "Ahlem" },
  'ahmad': { dataset: "Ahmad", behindTheName: 'https://www.behindthename.com/name/ahmad' },
  'ahsan': { dataset: "Ahsan" },
  'aisha': { dataset: "Aisha", behindTheName: 'https://www.behindthename.com/name/aisha' },
  'ajmal': { dataset: "Ajmal" },
  'akif': { dataset: "Akif" },
  'akram': { dataset: "Akram" },
  'aleem': { dataset: "Alim" },
  'ali': { dataset: "Ali", behindTheName: 'https://www.behindthename.com/name/ali' },
  'alia': { dataset: "Alia", behindTheName: 'https://www.behindthename.com/name/alia' },
  'alya2': { dataset: "Alia", behindTheName: 'https://www.behindthename.com/name/alya' },
  'amal': { behindTheName: 'https://www.behindthename.com/name/amal' },
  'amin': { dataset: "Amin", behindTheName: 'https://www.behindthename.com/name/amin' },
  'amina': { dataset: "Emna", behindTheName: 'https://www.behindthename.com/name/amina' },
  'amir': { dataset: "Amir", behindTheName: 'https://www.behindthename.com/name/amir' },
  'amira': { dataset: "Amira", behindTheName: 'https://www.behindthename.com/name/amira' },
  'ammar': { dataset: "Ammar", behindTheName: 'https://www.behindthename.com/name/ammar' },
  'anas': { dataset: "Anas", behindTheName: 'https://www.behindthename.com/name/anas' },
  'anbar': { dataset: "Anbar" },
  'anisah': { dataset: "Anissa", behindTheName: 'https://www.behindthename.com/name/anisa' },
  'aqdas': { dataset: "Aqdas" },
  'areej': { dataset: "Areej" },
  'arif': { dataset: "Arif" },
  'arqam': { dataset: "Arqam" },
  'arwa': { behindTheName: 'https://www.behindthename.com/name/arwa' },
  'aseel': { dataset: "Aseel" },
  'ashraf': { dataset: "Ashraf" },
  'asim': { dataset: "Asim", behindTheName: 'https://www.behindthename.com/name/asim' },
  'asiya': { dataset: "Asiya" },
  'asma': { dataset: "Asma", behindTheName: 'https://www.behindthename.com/name/asma' },
  'ata': { dataset: "Ata" },
  'atif': { dataset: "Atif" },
  'awad': { dataset: "Awad" },
  'aws': { dataset: "Aws" },
  'aya': { dataset: "Aya", behindTheName: 'https://www.behindthename.com/name/aya' },
  'ayat': { dataset: "Ayat", behindTheName: 'https://www.behindthename.com/name/ayat' },
  'aymen': { dataset: "Ayman" },
  'ayyub': { dataset: "Ayyub", behindTheName: 'https://www.behindthename.com/name/ayyub' },
  'azhar': { dataset: "Azhar" },
  'aziz': { dataset: "Aziz", behindTheName: 'https://www.behindthename.com/name/aziz' },
  'aziza-g': { dataset: "Aziza" },
  'azra': { dataset: "Azra" },
  'badir': { dataset: "Badr", behindTheName: 'https://www.behindthename.com/name/badr' },
  'badriya': { dataset: "Badriya" },
  'bahaa': { dataset: "Baha" },
  'bahia': { dataset: "Bahia" },
  'bahri': { dataset: "Bahri" },
  'bakr': { dataset: "Bakr" },
  'balqis': { dataset: "Balqis" },
  'barak': { dataset: "Barak" },
  'baria': { dataset: "Baria" },
  'barir': { dataset: "Barir" },
  'bashir': { dataset: "Bashir", behindTheName: 'https://www.behindthename.com/name/bashir' },
  'basil': { dataset: "Basil" },
  'basma': { dataset: "Basma", behindTheName: 'https://www.behindthename.com/name/basma' },
  'bassam': { dataset: "Bassam", behindTheName: 'https://www.behindthename.com/name/bassam' },
  'bassem-fr': { dataset: "Bassem" },
  'batul': { dataset: "Batul", behindTheName: 'https://www.behindthename.com/name/batul' },
  'bayan': { dataset: "Bayan" },
  'bilal': { dataset: "Bilal", behindTheName: 'https://www.behindthename.com/name/bilal' },
  'burayd': { dataset: "Burayd" },
  'burhan': { dataset: "Burhan", behindTheName: 'https://www.behindthename.com/name/burhan' },
  'bushra': { dataset: "Bushra", behindTheName: 'https://www.behindthename.com/name/bushra' },
  'chams-boy': { dataset: "Chams" },
  'cherifa': { dataset: "Sharifa" },
  'chokri': { dataset: "Chokri" },
  'dalia': { dataset: "Dalia", behindTheName: 'https://www.behindthename.com/name/dalia' },
  'dalila-mag': { dataset: "Dalila" },
  'dana': { dataset: "Dana" },
  'dania': { dataset: "Dania" },
  'danish': { dataset: "Danish", behindTheName: 'https://www.behindthename.com/name/danesh' },
  'dawud': { dataset: "Dawud", behindTheName: 'https://www.behindthename.com/name/dawud' },
  'dhikra': { dataset: "Zikra" },
  'dhiya': { dataset: "Diya" },
  'dima': { dataset: "Dima", behindTheName: 'https://www.behindthename.com/name/dima' },
  'djamila': { dataset: "Djamila" },
  'dorra': { dataset: "Durra" },
  'dounia': { dataset: "Dounia" },
  'duha': { dataset: "Duha", behindTheName: 'https://www.behindthename.com/name/duha' },
  'ezzeddine': { dataset: "Izzaddin" },
  'fadi': { dataset: "Fadi" },
  'fadia': { dataset: "Fadia" },
  'fadil': { dataset: "Fadil", behindTheName: 'https://www.behindthename.com/name/fadil' },
  'fadila': { dataset: "Fadila" },
  'fahd': { dataset: "Fahd", behindTheName: 'https://www.behindthename.com/name/fahd' },
  'fahim': { dataset: "Fahim", behindTheName: 'https://www.behindthename.com/name/fahim' },
  'fahima': { dataset: "Faheema" },
  'faisal': { dataset: "Faisal", behindTheName: 'https://www.behindthename.com/name/faisal' },
  'faiza': { dataset: "Faiza" },
  'fakhr': { dataset: "Fakhr" },
  'falih': { dataset: "Falih" },
  'farah': { dataset: "Farah", behindTheName: 'https://www.behindthename.com/name/farah' },
  'farida': { dataset: "Farida", behindTheName: 'https://www.behindthename.com/name/farida' },
  'fariha': { dataset: "Fariha" },
  'faris': { dataset: "Faris", behindTheName: 'https://www.behindthename.com/name/faris' },
  'faruq': { dataset: "Faruq", behindTheName: 'https://www.behindthename.com/name/faruq' },
  'fatiha': { dataset: "Fatiha" },
  'fatima': { dataset: "Fatima", behindTheName: 'https://www.behindthename.com/name/fatima' },
  'fatin': { dataset: "Fatin" },
  'fawaz': { dataset: "Fawaz" },
  'fawzi': { dataset: "Fawzi" },
  'feryel': { dataset: "Faryal" },
  'fethi': { dataset: "Fathi" },
  'firas': { dataset: "Firas" },
  'firdaws': { dataset: "Firdaws" },
  'ghada': { dataset: "Ghada", behindTheName: 'https://www.behindthename.com/name/ghada' },
  'ghalia': { dataset: "Ghalia", behindTheName: 'https://www.behindthename.com/name/ghalia' },
  'ghassan': { dataset: "Ghassan" },
  'ghayth': { dataset: "Ghayth" },
  'ghazi': { dataset: "Ghazi", behindTheName: 'https://www.behindthename.com/name/ghazi' },
  'ghiyath': { dataset: "Ghiyath" },
  'ghufran': { dataset: "Ghufran" },
  'habib': { dataset: "Habib", behindTheName: 'https://www.behindthename.com/name/habib' },
  'habiba': { dataset: "Habiba", behindTheName: 'https://www.behindthename.com/name/habiba' },
  'habibullah': { dataset: "Habibullah" },
  'hachemi': { dataset: "Hashimi" },
  'hadeel': { dataset: "Hadeel" },
  'hadi': { dataset: "Hadi", behindTheName: 'https://www.behindthename.com/name/hadi' },
  'hadiya': { dataset: "Hadiya", behindTheName: 'https://www.behindthename.com/name/hadiya' },
  'hafiz': { dataset: "Hafiz" },
  'hafiza-g': { dataset: "Hafiza" },
  'hafsa': { dataset: "Hafsa", behindTheName: 'https://www.behindthename.com/name/hafsa' },
  'haidar': { dataset: "Haidar" },
  'hajar': { dataset: "Hajar", behindTheName: 'https://www.behindthename.com/name/hajar' },
  'hakim': { dataset: "Hakim", behindTheName: 'https://www.behindthename.com/name/hakim' },
  'hakima': { dataset: "Hakima" },
  'hala': { dataset: "Hala", behindTheName: 'https://www.behindthename.com/name/hala' },
  'halima': { dataset: "Halima" },
  'hamdan': { dataset: "Hamdan" },
  'hamid': { dataset: "Hamid", behindTheName: 'https://www.behindthename.com/name/hamid' },
  'hamida': { dataset: "Hamida" },
  'hamza': { dataset: "Hamza", behindTheName: 'https://www.behindthename.com/name/hamza' },
  'hana': { dataset: "Hana", behindTheName: 'https://www.behindthename.com/name/hana' },
  'hanan': { dataset: "Hanan", behindTheName: 'https://www.behindthename.com/name/hanan' },
  'haneen': { dataset: "Hanin" },
  'hani': { dataset: "Hani" },
  'hania': { dataset: "Hania" },
  'harith': { dataset: "Harith" },
  'harun': { dataset: "Harun", behindTheName: 'https://www.behindthename.com/name/harun' },
  'hasan': { dataset: "Hasan", behindTheName: 'https://www.behindthename.com/name/hasan' },
  'hashim': { dataset: "Hashim" },
  'hasna': { dataset: "Hasna" },
  'hatim': { dataset: "Hatim" },
  'hawra': { dataset: "Hawra" },
  'hayat': { dataset: "Hayet", behindTheName: 'https://www.behindthename.com/name/hayat' },
  'haytham': { dataset: "Haytham", behindTheName: 'https://www.behindthename.com/name/haytham' },
  'hazim': { dataset: "Hazim" },
  'hiba': { dataset: "Hiba", behindTheName: 'https://www.behindthename.com/name/hiba' },
  'hidaya': { dataset: "Hedaya" },
  'hilal': { dataset: "Hilal", behindTheName: 'https://www.behindthename.com/name/hilal' },
  'hisham': { dataset: "Hisham", behindTheName: 'https://www.behindthename.com/name/hisham' },
  'housni': { dataset: "Husni" },
  'hud': { dataset: "Hud" },
  'huda': { dataset: "Huda", behindTheName: 'https://www.behindthename.com/name/huda' },
  'humam': { dataset: "Humam" },
  'huriya': { dataset: "Huriya" },
  'husam': { dataset: "Husam" },
  'husayn': { dataset: "Husayn", behindTheName: 'https://www.behindthename.com/name/husayn' },
  'ibad': { dataset: "Ibad" },
  'ibrahim': { dataset: "Ibrahim", behindTheName: 'https://www.behindthename.com/name/ibrahim' },
  'ibtihal': { dataset: "Ibtihal", behindTheName: 'https://www.behindthename.com/name/ibtihal' },
  'idris': { dataset: "Idris", behindTheName: 'https://www.behindthename.com/name/idris' },
  'iffat': { dataset: "Iffat" },
  'iftikhar': { dataset: "Iftikhar" },
  'iheb': { dataset: "Ihab" },
  'ihsan': { dataset: "Ihsan", behindTheName: 'https://www.behindthename.com/name/ihsan' },
  'ikhlas': { behindTheName: 'https://www.behindthename.com/name/ikhlas' },
  'ikram': { dataset: "Ikram", behindTheName: 'https://www.behindthename.com/name/ikram' },
  'ilham': { dataset: "Ilham", behindTheName: 'https://www.behindthename.com/name/ilham' },
  'ilyas': { dataset: "Ilyas", behindTheName: 'https://www.behindthename.com/name/ilyas' },
  'imad': { dataset: "Imad", behindTheName: 'https://www.behindthename.com/name/imad' },
  'iman': { dataset: "Eman", behindTheName: 'https://www.behindthename.com/name/iman' },
  'imran': { dataset: "Imran" },
  'inaya': { dataset: "Inaya", behindTheName: 'https://www.behindthename.com/name/inaya' },
  'ines-mag': { dataset: "Ines" },
  'inshirah': { dataset: "Inshirah" },
  'irfan': { dataset: "Irfan" },
  'isa': { dataset: "Isa", behindTheName: 'https://www.behindthename.com/name/isa' },
  'isam': { dataset: "Isam" },
  'ishaq': { dataset: "Ishaq", behindTheName: 'https://www.behindthename.com/name/ishaq' },
  'ismail': { dataset: "Ismail", behindTheName: 'https://www.behindthename.com/name/ismail' },
  'isra': { dataset: "Isra", behindTheName: 'https://www.behindthename.com/name/isra' },
  'iyad': { dataset: "Iyad", behindTheName: 'https://www.behindthename.com/name/iyad' },
  'jabbar': { dataset: "Jabir" },
  'jafar': { dataset: "Jafar" },
  'jalal': { dataset: "Jalal", behindTheName: 'https://www.behindthename.com/name/jalal' },
  'jamal': { dataset: "Jamal", behindTheName: 'https://www.behindthename.com/name/jamal' },
  'jamil': { dataset: "Jamil", behindTheName: 'https://www.behindthename.com/name/jamil' },
  'jannah': { dataset: "Jannah", behindTheName: 'https://www.behindthename.com/name/jannah' },
  'jawad': { dataset: "Jawad", behindTheName: 'https://www.behindthename.com/name/jawad' },
  'jawhara': { dataset: "Jawhara", behindTheName: 'https://www.behindthename.com/name/jawhara' },
  'joud': { dataset: "Joud" },
  'jumana': { dataset: "Jumana" },
  'juwayriya': { dataset: "Juwayriya", behindTheName: 'https://www.behindthename.com/name/juwayriya' },
  'kamil': { dataset: "Kamil", behindTheName: 'https://www.behindthename.com/name/kamil' },
  'kanaan': { dataset: "Kinan" },
  'kanza': { dataset: "Kanza" },
  'karim': { dataset: "Karim", behindTheName: 'https://www.behindthename.com/name/karim' },
  'karima': { dataset: "Karima", behindTheName: 'https://www.behindthename.com/name/karima' },
  'kawthar': { dataset: "Kawtar", behindTheName: 'https://www.behindthename.com/name/kawthar' },
  'khadija': { dataset: "Khadija", behindTheName: 'https://www.behindthename.com/name/khadija' },
  'khalid': { dataset: "Khaled", behindTheName: 'https://www.behindthename.com/name/khalid' },
  'khalil': { dataset: "Khalil", behindTheName: 'https://www.behindthename.com/name/khalil' },
  'khawla': { dataset: "Khawla", behindTheName: 'https://www.behindthename.com/name/khawla' },
  'khayra': { dataset: "Khaira" },
  'labib': { dataset: "Labib" },
  'lamia': { dataset: "Lamia", behindTheName: 'https://www.behindthename.com/name/lamia' },
  'latif': { dataset: "Latif" },
  'latifa-g': { dataset: "Latifa" },
  'laya': { dataset: "Layan" },
  'layla': { dataset: "Layla", behindTheName: 'https://www.behindthename.com/name/layla' },
  'lilia': { dataset: "Lilia" },
  'lin': { dataset: "Leen", behindTheName: 'https://www.behindthename.com/name/leen' },
  'lina': { dataset: "Leena", behindTheName: 'https://www.behindthename.com/name/lina' },
  'luay': { dataset: "Luay", behindTheName: 'https://www.behindthename.com/name/luay' },
  'lubna': { dataset: "Lubna", behindTheName: 'https://www.behindthename.com/name/lubna' },
  'lulwa': { dataset: "Lulwa", behindTheName: 'https://www.behindthename.com/name/lulwa' },
  'luqman': { dataset: "Luqman", behindTheName: 'https://www.behindthename.com/name/luqman' },
  'lut': { dataset: "Lut" },
  'lutfi': { dataset: "Lutfi" },
  'mabrouk': { dataset: "Mabruk" },
  'maha': { dataset: "Maha", behindTheName: 'https://www.behindthename.com/name/maha' },
  'maher': { dataset: "Mahir", behindTheName: 'https://www.behindthename.com/name/maher' },
  'mahfoud': { dataset: "Mahfoud" },
  'mahira': { dataset: "Mahira" },
  'majdi': { dataset: "Majdi" },
  'majid': { dataset: "Majid", behindTheName: 'https://www.behindthename.com/name/majid' },
  'makki': { dataset: "Makki" },
  'malak': { dataset: "Malak", behindTheName: 'https://www.behindthename.com/name/malak' },
  'malaz': { dataset: "Maladh" },
  'malik': { behindTheName: 'https://www.behindthename.com/name/malik' },
  'malika': { dataset: "Malika", behindTheName: 'https://www.behindthename.com/name/malika' },
  'mamun': { dataset: "Mamun" },
  'manal': { dataset: "Manal", behindTheName: 'https://www.behindthename.com/name/manal' },
  'mansur': { dataset: "Mansur", behindTheName: 'https://www.behindthename.com/name/mansur' },
  'maram': { dataset: "Maram" },
  'maruf': { dataset: "Maruf" },
  'marwa': { dataset: "Marwa", behindTheName: 'https://www.behindthename.com/name/marwa' },
  'marwan': { dataset: "Marwan", behindTheName: 'https://www.behindthename.com/name/marwan' },
  'maryam': { dataset: "Maryam", behindTheName: 'https://www.behindthename.com/name/maryam' },
  'marzouk': { dataset: "Marzuq" },
  'masud': { dataset: "Masud" },
  'maymuna': { behindTheName: 'https://www.behindthename.com/name/maymuna' },
  'maysa': { dataset: "Maysa", behindTheName: 'https://www.behindthename.com/name/maysa' },
  'maysun': { dataset: "Maysun" },
  'mazin': { dataset: "Mazin", behindTheName: 'https://www.behindthename.com/name/mazin' },
  'mehdi': { dataset: "Mahdi" },
  'miftah': { dataset: "Miftah" },
  'mishal': { dataset: "Mishal" },
  'moez': { dataset: "Moez" },
  'moin': { dataset: "Muin" },
  'mokhtar': { dataset: "Mukhtar" },
  'moncef': { dataset: "Moncef" },
  'mounaim': { dataset: "Munim" },
  'mounia': { dataset: "Mounia" },
  'mourad': { dataset: "Mourad" },
  'muadh': { dataset: "Muadh", behindTheName: 'https://www.behindthename.com/name/muadh' },
  'mubina': { dataset: "Mubina" },
  'muhammad': { dataset: "Muhammad", behindTheName: 'https://www.behindthename.com/name/muhammad' },
  'muhsina': { dataset: "Muhsina" },
  'mujahid': { dataset: "Mujahid" },
  'muna': { dataset: "Muna", behindTheName: 'https://www.behindthename.com/name/muna' },
  'munif': { dataset: "Munif" },
  'munir': { dataset: "Munir", behindTheName: 'https://www.behindthename.com/name/munir' },
  'munira': { dataset: "Munira" },
  'muntasir': { dataset: "Muntasir" },
  'murtada': { dataset: "Murtada" },
  'musa': { dataset: "Musa", behindTheName: 'https://www.behindthename.com/name/musa' },
  'mustafa': { dataset: "Mustafa" },
  'muwaffaq': { dataset: "Muwaffaq" },
  'nabil': { dataset: "Nabil" },
  'nabila-g': { dataset: "Nabila" },
  'nada': { dataset: "Nada" },
  'nadia': { dataset: "Nadya", behindTheName: 'https://www.behindthename.com/name/nadia' },
  'nadim': { dataset: "Nadim", behindTheName: 'https://www.behindthename.com/name/nadim' },
  'nadir': { dataset: "Nadir", behindTheName: 'https://www.behindthename.com/name/nadir' },
  'nadira': { dataset: "Nadira" },
  'nael': { dataset: "Nail" },
  'nahla': { dataset: "Nahla" },
  'naim': { dataset: "Naim" },
  'naima': { dataset: "Naima", behindTheName: 'https://www.behindthename.com/name/naima' },
  'najah': { dataset: "Najah" },
  'najat': { dataset: "Najat" },
  'naji': { dataset: "Naji" },
  'najib': { dataset: "Najib" },
  'najla': { dataset: "Najla", behindTheName: 'https://www.behindthename.com/name/najla' },
  'najma': { dataset: "Najma" },
  'najwa': { dataset: "Najwa", behindTheName: 'https://www.behindthename.com/name/najwa' },
  'nasih': { dataset: "Nasih" },
  'nasir': { dataset: "Nasir", behindTheName: 'https://www.behindthename.com/name/nasir' },
  'nassim': { dataset: "Nassim" },
  'nassima': { dataset: "Nasima" },
  'nassira': { dataset: "Nasira" },
  'nawal': { dataset: "Nawal", behindTheName: 'https://www.behindthename.com/name/nawal' },
  'nawfal': { dataset: "Nawfal", behindTheName: 'https://www.behindthename.com/name/nawfal' },
  'nesrine': { dataset: "Nasrin" },
  'nidal': { dataset: "Nidal" },
  'nizam': { dataset: "Nizam" },
  'nourhan': { behindTheName: 'https://www.behindthename.com/name/nourhan' },
  'nuh': { dataset: "Nuh", behindTheName: 'https://www.behindthename.com/name/nuh' },
  'nuha': { dataset: "Nuha" },
  'nur': { dataset: "Nur", behindTheName: 'https://www.behindthename.com/name/nur' },
  'nusaybah': { dataset: "Nusaybah", behindTheName: 'https://www.behindthename.com/name/nusaybah' },
  'qamar': { dataset: "Qamar" },
  'qasim': { dataset: "Qasim", behindTheName: 'https://www.behindthename.com/name/qasim' },
  'qays': { dataset: "Qays" },
  'qudsia': { dataset: "Qudsia" },
  'rabab': { dataset: "Rabab" },
  'rabeh': { dataset: "Rabah" },
  'rabi': { dataset: "Rabi" },
  'rabia': { dataset: "Rabia", behindTheName: 'https://www.behindthename.com/name/rabia' },
  'rabiaa': { dataset: "Raniya" },
  'rachida': { dataset: "Rachida" },
  'radia': { dataset: "Radiya" },
  'rafah': { dataset: "Rafah" },
  'rafiq': { dataset: "Rafiq", behindTheName: 'https://www.behindthename.com/name/rafiq' },
  'raghib': { dataset: "Raghib" },
  'rahaf': { dataset: "Rahaf" },
  'rahil': { dataset: "Rahil" },
  'rahma': { dataset: "Rahma", behindTheName: 'https://www.behindthename.com/name/rahma' },
  'raif': { dataset: "Raif" },
  'rajab': { dataset: "Rajab" },
  'rami': { dataset: "Rami", behindTheName: 'https://www.behindthename.com/name/rami' },
  'rana': { dataset: "Ranaa", behindTheName: 'https://www.behindthename.com/name/rana' },
  'rand': { dataset: "Rand" },
  'rania': { dataset: "Rania" },
  'raouf': { dataset: "Raouf" },
  'rasha': { dataset: "Rasha" },
  'rashad': { dataset: "Rashad" },
  'rashid': { dataset: "Rashid", behindTheName: 'https://www.behindthename.com/name/rashid' },
  'rawan': { dataset: "Rawan", behindTheName: 'https://www.behindthename.com/name/rawan' },
  'rawda': { dataset: "Rawda" },
  'rayanah': { dataset: "Raihana" },
  'rayyan': { dataset: "Rayan", behindTheName: 'https://www.behindthename.com/name/rayan' },
  'reem': { dataset: "Reem", behindTheName: 'https://www.behindthename.com/name/reem' },
  'rida-g': { dataset: "Rida" },
  'ridwan': { dataset: "Ridwan", behindTheName: 'https://www.behindthename.com/name/ridwan' },
  'rihab': { dataset: "Rehab" },
  'rima': { dataset: "Rima" },
  'riyad': { dataset: "Riyad" },
  'roua': { dataset: "Rua" },
  'ruqayya': { dataset: "Ruqayya", behindTheName: 'https://www.behindthename.com/name/ruqayya' },
  'saad': { dataset: "Saad", behindTheName: 'https://www.behindthename.com/name/saad' },
  'saba': { dataset: "Saba" },
  'sabah': { dataset: "Sabah", behindTheName: 'https://www.behindthename.com/name/sabah' },
  'sabiha': { dataset: "Sabiha" },
  'sabir': { dataset: "Sabir", behindTheName: 'https://www.behindthename.com/name/sabir' },
  'sabrine': { dataset: "Sabrina" },
  'sadia': { dataset: "Sadia" },
  'sadiq': { dataset: "Sadiq", behindTheName: 'https://www.behindthename.com/name/sadiq' },
  'safa': { dataset: "Safa", behindTheName: 'https://www.behindthename.com/name/safa' },
  'safaa': { dataset: "Safaa" },
  'safi': { dataset: "Safi" },
  'safiyya': { dataset: "Safiyya", behindTheName: 'https://www.behindthename.com/name/safiyya' },
  'sahar': { dataset: "Sahar" },
  'said': { dataset: "Said" },
  'salah': { dataset: "Salah" },
  'salih': { dataset: "Salih", behindTheName: 'https://www.behindthename.com/name/salih' },
  'salim': { dataset: "Salim" },
  'salima': { dataset: "Salima" },
  'salma': { dataset: "Salma", behindTheName: 'https://www.behindthename.com/name/salma' },
  'salman': { dataset: "Salman", behindTheName: 'https://www.behindthename.com/name/salman' },
  'salsabil': { dataset: "Salsabil", behindTheName: 'https://www.behindthename.com/name/salsabil' },
  'salwa': { dataset: "Salwa" },
  'samah': { dataset: "Samah" },
  'samar': { dataset: "Samar" },
  'sami': { dataset: "Sami", behindTheName: 'https://www.behindthename.com/name/sami' },
  'samia': { dataset: "Samia" },
  'samir': { dataset: "Samir", behindTheName: 'https://www.behindthename.com/name/samir' },
  'samira': { dataset: "Samira" },
  'sana': { dataset: "Sana" },
  'sawsan': { dataset: "Sawsan" },
  'seif': { dataset: "Seif" },
  'shadi': { dataset: "Shadi" },
  'shaima': { dataset: "Shaima" },
  'shakir': { dataset: "Shakir", behindTheName: 'https://www.behindthename.com/name/shakir' },
  'sharif': { dataset: "Sharif" },
  'shatha': { dataset: "Shatha" },
  'shifa': { dataset: "Shifa" },
  'shuayb': { dataset: "Shuayb", behindTheName: 'https://www.behindthename.com/name/shuayb' },
  'sidra': { dataset: "Sidra", behindTheName: 'https://www.behindthename.com/name/sidra' },
  'skander': { dataset: "Iskandar" },
  'sofiane': { dataset: "Sofiane" },
  'sonia': { dataset: "Sonia" },
  'souad': { dataset: "Souad" },
  'suhaila': { dataset: "Suhaila" },
  'suhayb': { dataset: "Suhayb" },
  'suhayl': { dataset: "Suhayl", behindTheName: 'https://www.behindthename.com/name/suhayl' },
  'sukayna': { dataset: "Sakina" },
  'sulayman': { dataset: "Sulayman", behindTheName: 'https://www.behindthename.com/name/sulayman' },
  'sumayya': { dataset: "Sumayya", behindTheName: 'https://www.behindthename.com/name/sumayya' },
  'sundus': { dataset: "Sundus" },
  'taha2': { dataset: "Taha", behindTheName: 'https://www.behindthename.com/name/taha' },
  'tahar': { dataset: "Tahar" },
  'tahira': { dataset: "Tahira" },
  'talha': { dataset: "Talha", behindTheName: 'https://www.behindthename.com/name/talha' },
  'tamim': { dataset: "Tamim" },
  'taqwa': { dataset: "Taqwa" },
  'tariq': { dataset: "Tariq", behindTheName: 'https://www.behindthename.com/name/tariq' },
  'tasnim': { dataset: "Tasnim", behindTheName: 'https://www.behindthename.com/name/tasnim' },
  'tawfiq': { dataset: "Tawfiq" },
  'tayyib': { dataset: "Tayyib", behindTheName: 'https://www.behindthename.com/name/tayyib' },
  'thabit': { dataset: "Thabit" },
  'thurayya': { dataset: "Thurayya" },
  'tuba': { dataset: "Tuba" },
  'ubaid': { dataset: "Ubayd" },
  'umar': { dataset: "Umar", behindTheName: 'https://www.behindthename.com/name/umar' },
  'umm-kulthum': { dataset: "Umm-kulthum" },
  'uqba': { dataset: "Uqba" },
  'wadie': { dataset: "Wadi" },
  'wael': { dataset: "Wael", behindTheName: 'https://www.behindthename.com/name/wael' },
  'wafa': { dataset: "Wafa" },
  'wafi': { dataset: "Wafi" },
  'wahib': { dataset: "Wahib" },
  'wahiba': { dataset: "Wahiba" },
  'wajdi': { dataset: "Wajdi" },
  'walid': { dataset: "Walid", behindTheName: 'https://www.behindthename.com/name/walid' },
  'warda': { dataset: "Warda" },
  'wasila': { dataset: "Wasila" },
  'wasim': { dataset: "Wasim" },
  'wiam': { dataset: "Wiam" },
  'widad': { dataset: "Widad" },
  'wissal': { dataset: "Wisal" },
  'wissam-boy': { dataset: "Wissam" },
  'yahya': { dataset: "Yahya", behindTheName: 'https://www.behindthename.com/name/yahya' },
  'yamin': { behindTheName: 'https://www.behindthename.com/name/yamine' },
  'yamina': { dataset: "Yamina" },
  'yaqub': { dataset: "Yaqub", behindTheName: 'https://www.behindthename.com/name/yaqub' },
  'yara': { dataset: "Yara" },
  'yasin2': { dataset: "Yasin" },
  'yasir': { dataset: "Yasir" },
  'yasmin': { dataset: "Yasmin" },
  'yumna': { dataset: "Yumna" },
  'yunus': { dataset: "Yunus", behindTheName: 'https://www.behindthename.com/name/yunus' },
  'yusra': { dataset: "Yusra" },
  'yusuf': { dataset: "Yusuf", behindTheName: 'https://www.behindthename.com/name/yusuf' },
  'zahia': { dataset: "Zahia" },
  'zahida': { dataset: "Zahida" },
  'zahir': { dataset: "Zahir", behindTheName: 'https://www.behindthename.com/name/zahir' },
  'zahira': { dataset: "Zahira" },
  'zahra': { dataset: "Zahra" },
  'zaina': { dataset: "Zaina" },
  'zakariya': { dataset: "Zakariya", behindTheName: 'https://www.behindthename.com/name/zakariya' },
  'zaki': { dataset: "Zaki", behindTheName: 'https://www.behindthename.com/name/zaki' },
  'zakia': { dataset: "Zakia" },
  'zayd': { dataset: "Zayd", behindTheName: 'https://www.behindthename.com/name/zayd' },
  'zayn': { dataset: "Zayn", behindTheName: 'https://www.behindthename.com/name/zayn' },
  'zaynab': { dataset: "Zaynab", behindTheName: 'https://www.behindthename.com/name/zaynab' },
  'ziyad': { dataset: "Ziyad", behindTheName: 'https://www.behindthename.com/name/ziyad' },
  'zoubir': { dataset: "Zubayr" },
  'zubaida': { dataset: "Zubaida" },
  'zubayr': { dataset: "Zubayr", behindTheName: 'https://www.behindthename.com/name/zubayr' },
};
