// Generated on 2026-10-05: each entry was checked, not assumed.
// dataset: the name (same gender) is in the Muslim Names Dataset CSV (huggingface.co/datasets/wpacademy/muslim-names-dataset).
// behindTheName: the page exists and its usage matches the fiche's origin; when the page shows an Arabic-script form,
// it is the fiche's Arabic spelling.
export const VERIFIED_NAME_SOURCES: Record<string, { dataset?: string; behindTheName?: string }> = {
  'aabid': { dataset: "Aabid", behindTheName: 'https://www.behindthename.com/name/aabid' },
  'aamal': { behindTheName: 'https://www.behindthename.com/name/amal' },
  'abaan': { behindTheName: 'https://www.behindthename.com/name/aban' },
  'abbas': { dataset: "Abbas", behindTheName: 'https://www.behindthename.com/name/abbas' },
  'abd-al-alim': { behindTheName: 'https://www.behindthename.com/name/abdelalim' },
  'abd-al-aziz': { behindTheName: 'https://www.behindthename.com/name/abdelaziz' },
  'abd-al-fattah': { behindTheName: 'https://www.behindthename.com/name/abdelfattah' },
  'abd-al-hadi': { behindTheName: 'https://www.behindthename.com/name/abdelhadi' },
  'abd-al-hafiz': { behindTheName: 'https://www.behindthename.com/name/abdelhafiz' },
  'abd-al-hakim': { behindTheName: 'https://www.behindthename.com/name/abdelhakim' },
  'abd-al-halim': { behindTheName: 'https://www.behindthename.com/name/abdelhalim' },
  'abd-al-hamid': { behindTheName: 'https://www.behindthename.com/name/abdelhamid' },
  'abd-al-haqq': { behindTheName: 'https://www.behindthename.com/name/abdelhaqq' },
  'abd-al-jabbar': { behindTheName: 'https://www.behindthename.com/name/abdeljabbar' },
  'abd-al-jalil': { behindTheName: 'https://www.behindthename.com/name/abdeljalil' },
  'abd-al-karim': { behindTheName: 'https://www.behindthename.com/name/abdelkarim' },
  'abd-al-latif': { behindTheName: 'https://www.behindthename.com/name/abdellatif' },
  'abd-al-majid': { behindTheName: 'https://www.behindthename.com/name/abdelmajid' },
  'abd-al-wahhab': { behindTheName: 'https://www.behindthename.com/name/abdelwahhab' },
  'abd-al-wahid': { behindTheName: 'https://www.behindthename.com/name/abdelwahid' },
  'abd-ar-rahim': { behindTheName: 'https://www.behindthename.com/name/abderrahim' },
  'abdullah': { dataset: "Abdallah", behindTheName: 'https://www.behindthename.com/name/abdullah' },
  'abdurrahman': { behindTheName: 'https://www.behindthename.com/name/abderrahman' },
  'abir': { behindTheName: 'https://www.behindthename.com/name/abir' },
  'abrar-b': { dataset: "Abrar", behindTheName: 'https://www.behindthename.com/name/abrar' },
  'adam': { behindTheName: 'https://www.behindthename.com/name/adam' },
  'adeeb': { dataset: "Adib", behindTheName: 'https://www.behindthename.com/name/adib' },
  'adham': { dataset: "Adham", behindTheName: 'https://www.behindthename.com/name/adham' },
  'adiba-g': { dataset: "Adiba", behindTheName: 'https://www.behindthename.com/name/adiba' },
  'adil': { dataset: "Adil", behindTheName: 'https://www.behindthename.com/name/adil' },
  'adila': { dataset: "Aadila", behindTheName: 'https://www.behindthename.com/name/adila' },
  'adiyy': { dataset: "Adi" },
  'afaf': { dataset: "Afaf", behindTheName: 'https://www.behindthename.com/name/afaf' },
  'afif': { dataset: "Afif", behindTheName: 'https://www.behindthename.com/name/afif' },
  'afifa': { dataset: "Afifa", behindTheName: 'https://www.behindthename.com/name/afifa' },
  'afnan-b': { dataset: "Afnan", behindTheName: 'https://www.behindthename.com/name/afnan' },
  'afra': { dataset: "Afraa", behindTheName: 'https://www.behindthename.com/name/afra' },
  'ahlem': { dataset: "Ahlem", behindTheName: 'https://www.behindthename.com/name/ahlem' },
  'ahmad': { dataset: "Ahmad", behindTheName: 'https://www.behindthename.com/name/ahmad' },
  'ahsan': { dataset: "Ahsan", behindTheName: 'https://www.behindthename.com/name/ahsan' },
  'aisha': { dataset: "Aisha", behindTheName: 'https://www.behindthename.com/name/aisha' },
  'ajmal': { dataset: "Ajmal", behindTheName: 'https://www.behindthename.com/name/ajmal' },
  'akif': { dataset: "Akif", behindTheName: 'https://www.behindthename.com/name/akif' },
  'akram': { dataset: "Akram", behindTheName: 'https://www.behindthename.com/name/akram' },
  'alaa-b': { behindTheName: 'https://www.behindthename.com/name/alaa' },
  'aleem': { dataset: "Alim", behindTheName: 'https://www.behindthename.com/name/alim' },
  'ali': { dataset: "Ali", behindTheName: 'https://www.behindthename.com/name/ali' },
  'alia': { dataset: "Alia", behindTheName: 'https://www.behindthename.com/name/alia' },
  'alya2': { dataset: "Alia", behindTheName: 'https://www.behindthename.com/name/alya' },
  'amal': { behindTheName: 'https://www.behindthename.com/name/amal' },
  'amin': { dataset: "Amin", behindTheName: 'https://www.behindthename.com/name/amin' },
  'amina': { dataset: "Emna", behindTheName: 'https://www.behindthename.com/name/amina' },
  'amir': { dataset: "Amir", behindTheName: 'https://www.behindthename.com/name/amir' },
  'amira': { dataset: "Amira", behindTheName: 'https://www.behindthename.com/name/amira' },
  'ammar': { dataset: "Ammar", behindTheName: 'https://www.behindthename.com/name/ammar' },
  'anas': { dataset: "Anas", behindTheName: 'https://www.behindthename.com/name/anas' },
  'anbar': { dataset: "Anbar", behindTheName: 'https://www.behindthename.com/name/anbar' },
  'anisah': { dataset: "Anissa", behindTheName: 'https://www.behindthename.com/name/anisa' },
  'aqdas': { dataset: "Aqdas", behindTheName: 'https://www.behindthename.com/name/aqdas' },
  'aqila': { behindTheName: 'https://www.behindthename.com/name/aqila' },
  'areej': { dataset: "Areej", behindTheName: 'https://www.behindthename.com/name/areej' },
  'arif': { dataset: "Arif", behindTheName: 'https://www.behindthename.com/name/arif' },
  'arqam': { dataset: "Arqam" },
  'arwa': { behindTheName: 'https://www.behindthename.com/name/arwa' },
  'aseel': { dataset: "Aseel", behindTheName: 'https://www.behindthename.com/name/aseel' },
  'ashraf': { dataset: "Ashraf", behindTheName: 'https://www.behindthename.com/name/ashraf' },
  'asim': { dataset: "Asim", behindTheName: 'https://www.behindthename.com/name/asim' },
  'asiya': { dataset: "Asiya", behindTheName: 'https://www.behindthename.com/name/asiya' },
  'asma': { dataset: "Asma", behindTheName: 'https://www.behindthename.com/name/asma' },
  'ata': { dataset: "Ata", behindTheName: 'https://www.behindthename.com/name/ata' },
  'atif': { dataset: "Atif", behindTheName: 'https://www.behindthename.com/name/atif' },
  'awad': { dataset: "Awad", behindTheName: 'https://www.behindthename.com/name/awad' },
  'aws': { dataset: "Aws", behindTheName: 'https://www.behindthename.com/name/aws' },
  'aya': { dataset: "Aya", behindTheName: 'https://www.behindthename.com/name/aya' },
  'ayat': { dataset: "Ayat", behindTheName: 'https://www.behindthename.com/name/ayat' },
  'aymen': { dataset: "Ayman", behindTheName: 'https://www.behindthename.com/name/aymen' },
  'ayyub': { dataset: "Ayyub", behindTheName: 'https://www.behindthename.com/name/ayyub' },
  'azhar': { dataset: "Azhar", behindTheName: 'https://www.behindthename.com/name/azhar' },
  'aziz': { dataset: "Aziz", behindTheName: 'https://www.behindthename.com/name/aziz' },
  'aziza-g': { dataset: "Aziza", behindTheName: 'https://www.behindthename.com/name/aziza' },
  'azra': { dataset: "Azra", behindTheName: 'https://www.behindthename.com/name/azra' },
  'badir': { dataset: "Badr", behindTheName: 'https://www.behindthename.com/name/badr' },
  'badriya': { dataset: "Badriya", behindTheName: 'https://www.behindthename.com/name/badriya' },
  'bahaa': { dataset: "Baha", behindTheName: 'https://www.behindthename.com/name/baha' },
  'bahia': { dataset: "Bahia", behindTheName: 'https://www.behindthename.com/name/bahia' },
  'bahri': { dataset: "Bahri", behindTheName: 'https://www.behindthename.com/name/bahri' },
  'bakr': { dataset: "Bakr", behindTheName: 'https://www.behindthename.com/name/bakr' },
  'balqis': { dataset: "Balqis", behindTheName: 'https://www.behindthename.com/name/balqis' },
  'barak': { dataset: "Barak", behindTheName: 'https://www.behindthename.com/name/barak' },
  'baria': { dataset: "Baria" },
  'barir': { dataset: "Barir" },
  'bashir': { dataset: "Bashir", behindTheName: 'https://www.behindthename.com/name/bashir' },
  'basil': { dataset: "Basil", behindTheName: 'https://www.behindthename.com/name/basil' },
  'basma': { dataset: "Basma", behindTheName: 'https://www.behindthename.com/name/basma' },
  'bassam': { dataset: "Bassam", behindTheName: 'https://www.behindthename.com/name/bassam' },
  'bassem-fr': { dataset: "Bassem", behindTheName: 'https://www.behindthename.com/name/bassem' },
  'batul': { dataset: "Batul", behindTheName: 'https://www.behindthename.com/name/batul' },
  'bayan': { dataset: "Bayan", behindTheName: 'https://www.behindthename.com/name/bayan' },
  'bilal': { dataset: "Bilal", behindTheName: 'https://www.behindthename.com/name/bilal' },
  'burayd': { dataset: "Burayd" },
  'burhan': { dataset: "Burhan", behindTheName: 'https://www.behindthename.com/name/burhan' },
  'bushra': { dataset: "Bushra", behindTheName: 'https://www.behindthename.com/name/bushra' },
  'chams-boy': { dataset: "Chams", behindTheName: 'https://www.behindthename.com/name/chams' },
  'cherifa': { dataset: "Sharifa", behindTheName: 'https://www.behindthename.com/name/cherifa' },
  'chokri': { dataset: "Chokri", behindTheName: 'https://www.behindthename.com/name/chokri' },
  'dalal': { behindTheName: 'https://www.behindthename.com/name/dalal' },
  'dalia': { dataset: "Dalia", behindTheName: 'https://www.behindthename.com/name/dalia' },
  'dalila-mag': { dataset: "Dalila" },
  'dana': { dataset: "Dana", behindTheName: 'https://www.behindthename.com/name/dana' },
  'dania': { dataset: "Dania", behindTheName: 'https://www.behindthename.com/name/dania' },
  'danish': { dataset: "Danish", behindTheName: 'https://www.behindthename.com/name/danesh' },
  'dareen': { behindTheName: 'https://www.behindthename.com/name/dareen' },
  'dawud': { dataset: "Dawud", behindTheName: 'https://www.behindthename.com/name/dawud' },
  'dhikra': { dataset: "Zikra", behindTheName: 'https://www.behindthename.com/name/dhikra' },
  'dhiya': { dataset: "Diya", behindTheName: 'https://www.behindthename.com/name/diya' },
  'dima': { dataset: "Dima", behindTheName: 'https://www.behindthename.com/name/dima' },
  'djamila': { dataset: "Djamila", behindTheName: 'https://www.behindthename.com/name/djamila' },
  'dorra': { dataset: "Durra", behindTheName: 'https://www.behindthename.com/name/dorra' },
  'dounia': { dataset: "Dounia", behindTheName: 'https://www.behindthename.com/name/dounia' },
  'duha': { dataset: "Duha", behindTheName: 'https://www.behindthename.com/name/duha' },
  'ezzeddine': { dataset: "Izzaddin", behindTheName: 'https://www.behindthename.com/name/ezzedine' },
  'fadi': { dataset: "Fadi", behindTheName: 'https://www.behindthename.com/name/fadi' },
  'fadia': { dataset: "Fadia", behindTheName: 'https://www.behindthename.com/name/fadia' },
  'fadil': { dataset: "Fadil", behindTheName: 'https://www.behindthename.com/name/fadil' },
  'fadila': { dataset: "Fadila", behindTheName: 'https://www.behindthename.com/name/fadhila' },
  'fahd': { dataset: "Fahd", behindTheName: 'https://www.behindthename.com/name/fahd' },
  'fahim': { dataset: "Fahim", behindTheName: 'https://www.behindthename.com/name/fahim' },
  'fahima': { dataset: "Faheema", behindTheName: 'https://www.behindthename.com/name/fahima' },
  'faisal': { dataset: "Faisal", behindTheName: 'https://www.behindthename.com/name/faisal' },
  'faiza': { dataset: "Faiza", behindTheName: 'https://www.behindthename.com/name/faiza' },
  'fajr': { behindTheName: 'https://www.behindthename.com/name/fajr' },
  'fakhr': { dataset: "Fakhr", behindTheName: 'https://www.behindthename.com/name/fakhr' },
  'falih': { dataset: "Falih", behindTheName: 'https://www.behindthename.com/name/falih' },
  'farah': { dataset: "Farah", behindTheName: 'https://www.behindthename.com/name/farah' },
  'farida': { dataset: "Farida", behindTheName: 'https://www.behindthename.com/name/farida' },
  'fariha': { dataset: "Fariha", behindTheName: 'https://www.behindthename.com/name/fariha' },
  'faris': { dataset: "Faris", behindTheName: 'https://www.behindthename.com/name/faris' },
  'faruq': { dataset: "Faruq", behindTheName: 'https://www.behindthename.com/name/faruq' },
  'fatiha': { dataset: "Fatiha", behindTheName: 'https://www.behindthename.com/name/fatiha' },
  'fatima': { dataset: "Fatima", behindTheName: 'https://www.behindthename.com/name/fatima' },
  'fatin': { dataset: "Fatin", behindTheName: 'https://www.behindthename.com/name/fatin' },
  'fawaz': { dataset: "Fawaz", behindTheName: 'https://www.behindthename.com/name/fawaz' },
  'fawzi': { dataset: "Fawzi", behindTheName: 'https://www.behindthename.com/name/fawzi' },
  'feryel': { dataset: "Faryal", behindTheName: 'https://www.behindthename.com/name/faryal' },
  'fethi': { dataset: "Fathi", behindTheName: 'https://www.behindthename.com/name/fethi' },
  'firas': { dataset: "Firas", behindTheName: 'https://www.behindthename.com/name/firas' },
  'firdaws': { dataset: "Firdaws", behindTheName: 'https://www.behindthename.com/name/firdaws' },
  'ghada': { dataset: "Ghada", behindTheName: 'https://www.behindthename.com/name/ghada' },
  'ghalia': { dataset: "Ghalia", behindTheName: 'https://www.behindthename.com/name/ghalia' },
  'ghassan': { dataset: "Ghassan", behindTheName: 'https://www.behindthename.com/name/ghassan' },
  'ghayth': { dataset: "Ghayth", behindTheName: 'https://www.behindthename.com/name/ghayth' },
  'ghazi': { dataset: "Ghazi", behindTheName: 'https://www.behindthename.com/name/ghazi' },
  'ghiyath': { dataset: "Ghiyath" },
  'ghufran': { dataset: "Ghufran", behindTheName: 'https://www.behindthename.com/name/ghufran' },
  'habib': { dataset: "Habib", behindTheName: 'https://www.behindthename.com/name/habib' },
  'habiba': { dataset: "Habiba", behindTheName: 'https://www.behindthename.com/name/habiba' },
  'habibullah': { dataset: "Habibullah", behindTheName: 'https://www.behindthename.com/name/habibullah' },
  'hachemi': { dataset: "Hashimi" },
  'hadeel': { dataset: "Hadeel", behindTheName: 'https://www.behindthename.com/name/hadeel' },
  'hadi': { dataset: "Hadi", behindTheName: 'https://www.behindthename.com/name/hadi' },
  'hadiya': { dataset: "Hadiya", behindTheName: 'https://www.behindthename.com/name/hadiya' },
  'hafiz': { dataset: "Hafiz", behindTheName: 'https://www.behindthename.com/name/hafiz' },
  'hafiza-g': { dataset: "Hafiza", behindTheName: 'https://www.behindthename.com/name/hafiza' },
  'hafsa': { dataset: "Hafsa", behindTheName: 'https://www.behindthename.com/name/hafsa' },
  'haidar': { dataset: "Haidar", behindTheName: 'https://www.behindthename.com/name/haidar' },
  'hajar': { dataset: "Hajar", behindTheName: 'https://www.behindthename.com/name/hajar' },
  'hakim': { dataset: "Hakim", behindTheName: 'https://www.behindthename.com/name/hakim' },
  'hakima': { dataset: "Hakima", behindTheName: 'https://www.behindthename.com/name/hakima' },
  'hala': { dataset: "Hala", behindTheName: 'https://www.behindthename.com/name/hala' },
  'halima': { dataset: "Halima", behindTheName: 'https://www.behindthename.com/name/halima' },
  'hamdan': { dataset: "Hamdan", behindTheName: 'https://www.behindthename.com/name/hamdan' },
  'hamid': { dataset: "Hamid", behindTheName: 'https://www.behindthename.com/name/hamid' },
  'hamida': { dataset: "Hamida", behindTheName: 'https://www.behindthename.com/name/hamida' },
  'hamza': { dataset: "Hamza", behindTheName: 'https://www.behindthename.com/name/hamza' },
  'hana': { dataset: "Hana", behindTheName: 'https://www.behindthename.com/name/hana' },
  'hanan': { dataset: "Hanan", behindTheName: 'https://www.behindthename.com/name/hanan' },
  'haneen': { dataset: "Hanin", behindTheName: 'https://www.behindthename.com/name/hanin' },
  'hani': { dataset: "Hani" },
  'hania': { dataset: "Hania", behindTheName: 'https://www.behindthename.com/name/hania' },
  'harith': { dataset: "Harith", behindTheName: 'https://www.behindthename.com/name/harith' },
  'harun': { dataset: "Harun", behindTheName: 'https://www.behindthename.com/name/harun' },
  'hasan': { dataset: "Hasan", behindTheName: 'https://www.behindthename.com/name/hasan' },
  'hashim': { dataset: "Hashim", behindTheName: 'https://www.behindthename.com/name/hashim' },
  'hasna': { dataset: "Hasna", behindTheName: 'https://www.behindthename.com/name/hasna' },
  'hatim': { dataset: "Hatim", behindTheName: 'https://www.behindthename.com/name/hatim' },
  'hawra': { dataset: "Hawra", behindTheName: 'https://www.behindthename.com/name/hawra' },
  'hayat': { dataset: "Hayet", behindTheName: 'https://www.behindthename.com/name/hayat' },
  'haytham': { dataset: "Haytham", behindTheName: 'https://www.behindthename.com/name/haytham' },
  'hazim': { dataset: "Hazim", behindTheName: 'https://www.behindthename.com/name/hazim' },
  'hiba': { dataset: "Hiba", behindTheName: 'https://www.behindthename.com/name/hiba' },
  'hidaya': { dataset: "Hedaya" },
  'hilal': { dataset: "Hilal", behindTheName: 'https://www.behindthename.com/name/hilal' },
  'hisham': { dataset: "Hisham", behindTheName: 'https://www.behindthename.com/name/hisham' },
  'housni': { dataset: "Husni", behindTheName: 'https://www.behindthename.com/name/husni' },
  'hud': { dataset: "Hud" },
  'huda': { dataset: "Huda", behindTheName: 'https://www.behindthename.com/name/huda' },
  'humam': { dataset: "Humam", behindTheName: 'https://www.behindthename.com/name/humam' },
  'huriya': { dataset: "Huriya", behindTheName: 'https://www.behindthename.com/name/huriya' },
  'husam': { dataset: "Husam", behindTheName: 'https://www.behindthename.com/name/husam' },
  'husayn': { dataset: "Husayn", behindTheName: 'https://www.behindthename.com/name/husayn' },
  'ibad': { dataset: "Ibad" },
  'ibrahim': { dataset: "Ibrahim", behindTheName: 'https://www.behindthename.com/name/ibrahim' },
  'ibtihal': { dataset: "Ibtihal", behindTheName: 'https://www.behindthename.com/name/ibtihal' },
  'ibtisam': { behindTheName: 'https://www.behindthename.com/name/ibtisam' },
  'idris': { dataset: "Idris", behindTheName: 'https://www.behindthename.com/name/idris' },
  'iffat': { dataset: "Iffat", behindTheName: 'https://www.behindthename.com/name/iffat' },
  'iftikhar': { dataset: "Iftikhar", behindTheName: 'https://www.behindthename.com/name/iftikhar' },
  'iheb': { dataset: "Ihab", behindTheName: 'https://www.behindthename.com/name/iheb' },
  'ihsan': { dataset: "Ihsan", behindTheName: 'https://www.behindthename.com/name/ihsan' },
  'ikhlas': { behindTheName: 'https://www.behindthename.com/name/ikhlas' },
  'ikram': { dataset: "Ikram", behindTheName: 'https://www.behindthename.com/name/ikram' },
  'ilham': { dataset: "Ilham", behindTheName: 'https://www.behindthename.com/name/ilham' },
  'ilyas': { dataset: "Ilyas", behindTheName: 'https://www.behindthename.com/name/ilyas' },
  'imad': { dataset: "Imad", behindTheName: 'https://www.behindthename.com/name/imad' },
  'iman': { dataset: "Eman", behindTheName: 'https://www.behindthename.com/name/iman' },
  'imran': { dataset: "Imran", behindTheName: 'https://www.behindthename.com/name/imran' },
  'inaya': { dataset: "Inaya", behindTheName: 'https://www.behindthename.com/name/inaya' },
  'ines-mag': { dataset: "Ines", behindTheName: 'https://www.behindthename.com/name/inas' },
  'insaf': { behindTheName: 'https://www.behindthename.com/name/insaf' },
  'inshirah': { dataset: "Inshirah", behindTheName: 'https://www.behindthename.com/name/inshirah' },
  'irfan': { dataset: "Irfan", behindTheName: 'https://www.behindthename.com/name/irfan' },
  'isa': { dataset: "Isa", behindTheName: 'https://www.behindthename.com/name/isa' },
  'isam': { dataset: "Isam", behindTheName: 'https://www.behindthename.com/name/isam' },
  'ishaq': { dataset: "Ishaq", behindTheName: 'https://www.behindthename.com/name/ishaq' },
  'ismail': { dataset: "Ismail", behindTheName: 'https://www.behindthename.com/name/ismail' },
  'isra': { dataset: "Isra", behindTheName: 'https://www.behindthename.com/name/isra' },
  'iyad': { dataset: "Iyad", behindTheName: 'https://www.behindthename.com/name/iyad' },
  'jabbar': { dataset: "Jabir", behindTheName: 'https://www.behindthename.com/name/jabir' },
  'jafar': { dataset: "Jafar", behindTheName: 'https://www.behindthename.com/name/jafar' },
  'jalal': { dataset: "Jalal", behindTheName: 'https://www.behindthename.com/name/jalal' },
  'jamal': { dataset: "Jamal", behindTheName: 'https://www.behindthename.com/name/jamal' },
  'jamil': { dataset: "Jamil", behindTheName: 'https://www.behindthename.com/name/jamil' },
  'jannah': { dataset: "Jannah", behindTheName: 'https://www.behindthename.com/name/jannah' },
  'jawad': { dataset: "Jawad", behindTheName: 'https://www.behindthename.com/name/jawad' },
  'jawhara': { dataset: "Jawhara", behindTheName: 'https://www.behindthename.com/name/jawhara' },
  'joud': { dataset: "Joud", behindTheName: 'https://www.behindthename.com/name/joud' },
  'jumana': { dataset: "Jumana", behindTheName: 'https://www.behindthename.com/name/jumana' },
  'juwayriya': { dataset: "Juwayriya", behindTheName: 'https://www.behindthename.com/name/juwayriya' },
  'kamil': { dataset: "Kamil", behindTheName: 'https://www.behindthename.com/name/kamil' },
  'kanaan': { dataset: "Kinan", behindTheName: 'https://www.behindthename.com/name/kinan' },
  'kanza': { dataset: "Kanza", behindTheName: 'https://www.behindthename.com/name/kanza' },
  'karim': { dataset: "Karim", behindTheName: 'https://www.behindthename.com/name/karim' },
  'karima': { dataset: "Karima", behindTheName: 'https://www.behindthename.com/name/karima' },
  'kawthar': { dataset: "Kawtar", behindTheName: 'https://www.behindthename.com/name/kawthar' },
  'khadija': { dataset: "Khadija", behindTheName: 'https://www.behindthename.com/name/khadija' },
  'khalid': { dataset: "Khaled", behindTheName: 'https://www.behindthename.com/name/khalid' },
  'khalil': { dataset: "Khalil", behindTheName: 'https://www.behindthename.com/name/khalil' },
  'khawla': { dataset: "Khawla", behindTheName: 'https://www.behindthename.com/name/khawla' },
  'khayra': { dataset: "Khaira", behindTheName: 'https://www.behindthename.com/name/khayra' },
  'khemais': { behindTheName: 'https://www.behindthename.com/name/khemais' },
  'labib': { dataset: "Labib", behindTheName: 'https://www.behindthename.com/name/labib' },
  'lakhdar': { behindTheName: 'https://www.behindthename.com/name/lakhdar' },
  'lamia': { dataset: "Lamia", behindTheName: 'https://www.behindthename.com/name/lamia' },
  'larbi': { behindTheName: 'https://www.behindthename.com/name/larbi' },
  'latif': { dataset: "Latif", behindTheName: 'https://www.behindthename.com/name/latif' },
  'latifa-g': { dataset: "Latifa", behindTheName: 'https://www.behindthename.com/name/latifa' },
  'laya': { dataset: "Layan", behindTheName: 'https://www.behindthename.com/name/layan' },
  'layla': { dataset: "Layla", behindTheName: 'https://www.behindthename.com/name/layla' },
  'lilia': { dataset: "Lilia" },
  'lin': { dataset: "Leen", behindTheName: 'https://www.behindthename.com/name/leen' },
  'lina': { dataset: "Leena", behindTheName: 'https://www.behindthename.com/name/lina' },
  'luay': { dataset: "Luay", behindTheName: 'https://www.behindthename.com/name/luay' },
  'lubna': { dataset: "Lubna", behindTheName: 'https://www.behindthename.com/name/lubna' },
  'lulwa': { dataset: "Lulwa", behindTheName: 'https://www.behindthename.com/name/lulwa' },
  'luqman': { dataset: "Luqman", behindTheName: 'https://www.behindthename.com/name/luqman' },
  'lut': { dataset: "Lut" },
  'lutfi': { dataset: "Lutfi", behindTheName: 'https://www.behindthename.com/name/lutfi' },
  'mabrouk': { dataset: "Mabruk", behindTheName: 'https://www.behindthename.com/name/mabrouk' },
  'maha': { dataset: "Maha", behindTheName: 'https://www.behindthename.com/name/maha' },
  'maher': { dataset: "Mahir", behindTheName: 'https://www.behindthename.com/name/maher' },
  'mahfoud': { dataset: "Mahfoud", behindTheName: 'https://www.behindthename.com/name/mahfoud' },
  'mahira': { dataset: "Mahira", behindTheName: 'https://www.behindthename.com/name/mahira' },
  'majd': { behindTheName: 'https://www.behindthename.com/name/majd' },
  'majdi': { dataset: "Majdi", behindTheName: 'https://www.behindthename.com/name/majdi' },
  'majid': { dataset: "Majid", behindTheName: 'https://www.behindthename.com/name/majid' },
  'makki': { dataset: "Makki" },
  'malak': { dataset: "Malak", behindTheName: 'https://www.behindthename.com/name/malak' },
  'malaz': { dataset: "Maladh" },
  'malik': { behindTheName: 'https://www.behindthename.com/name/malik' },
  'malika': { dataset: "Malika", behindTheName: 'https://www.behindthename.com/name/malika' },
  'mamun': { dataset: "Mamun", behindTheName: 'https://www.behindthename.com/name/mamun' },
  'manal': { dataset: "Manal", behindTheName: 'https://www.behindthename.com/name/manal' },
  'mansur': { dataset: "Mansur", behindTheName: 'https://www.behindthename.com/name/mansur' },
  'maram': { dataset: "Maram", behindTheName: 'https://www.behindthename.com/name/maram' },
  'maruf': { dataset: "Maruf", behindTheName: 'https://www.behindthename.com/name/maruf' },
  'marwa': { dataset: "Marwa", behindTheName: 'https://www.behindthename.com/name/marwa' },
  'marwan': { dataset: "Marwan", behindTheName: 'https://www.behindthename.com/name/marwan' },
  'maryam': { dataset: "Maryam", behindTheName: 'https://www.behindthename.com/name/maryam' },
  'marzouk': { dataset: "Marzuq", behindTheName: 'https://www.behindthename.com/name/marzouk' },
  'masud': { dataset: "Masud", behindTheName: 'https://www.behindthename.com/name/masud' },
  'maymuna': { behindTheName: 'https://www.behindthename.com/name/maymuna' },
  'maysa': { dataset: "Maysa", behindTheName: 'https://www.behindthename.com/name/maysa' },
  'maysun': { dataset: "Maysun", behindTheName: 'https://www.behindthename.com/name/maysun' },
  'mazin': { dataset: "Mazin", behindTheName: 'https://www.behindthename.com/name/mazin' },
  'mehdi': { dataset: "Mahdi", behindTheName: 'https://www.behindthename.com/name/mehdi' },
  'miftah': { dataset: "Miftah", behindTheName: 'https://www.behindthename.com/name/miftah' },
  'mishal': { dataset: "Mishal", behindTheName: 'https://www.behindthename.com/name/mishal' },
  'misk': { behindTheName: 'https://www.behindthename.com/name/misk' },
  'moez': { dataset: "Moez", behindTheName: 'https://www.behindthename.com/name/moez' },
  'moin': { dataset: "Muin", behindTheName: 'https://www.behindthename.com/name/muin' },
  'mokhtar': { dataset: "Mukhtar", behindTheName: 'https://www.behindthename.com/name/mokhtar' },
  'moncef': { dataset: "Moncef", behindTheName: 'https://www.behindthename.com/name/moncef' },
  'mouloud': { behindTheName: 'https://www.behindthename.com/name/mouloud' },
  'mounaim': { dataset: "Munim", behindTheName: 'https://www.behindthename.com/name/mounaim' },
  'mounia': { dataset: "Mounia", behindTheName: 'https://www.behindthename.com/name/mounia' },
  'mourad': { dataset: "Mourad", behindTheName: 'https://www.behindthename.com/name/mourad' },
  'muadh': { dataset: "Muadh", behindTheName: 'https://www.behindthename.com/name/muadh' },
  'mubina': { dataset: "Mubina", behindTheName: 'https://www.behindthename.com/name/mubina' },
  'muhammad': { dataset: "Muhammad", behindTheName: 'https://www.behindthename.com/name/muhammad' },
  'muhsina': { dataset: "Muhsina", behindTheName: 'https://www.behindthename.com/name/muhsina' },
  'mujahid': { dataset: "Mujahid", behindTheName: 'https://www.behindthename.com/name/mujahid' },
  'muna': { dataset: "Muna", behindTheName: 'https://www.behindthename.com/name/muna' },
  'munif': { dataset: "Munif" },
  'munir': { dataset: "Munir", behindTheName: 'https://www.behindthename.com/name/munir' },
  'munira': { dataset: "Munira", behindTheName: 'https://www.behindthename.com/name/munira' },
  'muntasir': { dataset: "Muntasir", behindTheName: 'https://www.behindthename.com/name/muntasir' },
  'murtada': { dataset: "Murtada", behindTheName: 'https://www.behindthename.com/name/murtada' },
  'musa': { dataset: "Musa", behindTheName: 'https://www.behindthename.com/name/musa' },
  'mustafa': { dataset: "Mustafa", behindTheName: 'https://www.behindthename.com/name/mustafa' },
  'muwaffaq': { dataset: "Muwaffaq", behindTheName: 'https://www.behindthename.com/name/muwaffaq' },
  'nabil': { dataset: "Nabil", behindTheName: 'https://www.behindthename.com/name/nabil' },
  'nabila-g': { dataset: "Nabila", behindTheName: 'https://www.behindthename.com/name/nabila' },
  'nada': { dataset: "Nada", behindTheName: 'https://www.behindthename.com/name/nada' },
  'nadia': { dataset: "Nadya", behindTheName: 'https://www.behindthename.com/name/nadia' },
  'nadim': { dataset: "Nadim", behindTheName: 'https://www.behindthename.com/name/nadim' },
  'nadir': { dataset: "Nadir", behindTheName: 'https://www.behindthename.com/name/nadir' },
  'nadira': { dataset: "Nadira", behindTheName: 'https://www.behindthename.com/name/nadira' },
  'nael': { dataset: "Nail", behindTheName: 'https://www.behindthename.com/name/nail' },
  'nahla': { dataset: "Nahla" },
  'naim': { dataset: "Naim", behindTheName: 'https://www.behindthename.com/name/naim' },
  'naima': { dataset: "Naima", behindTheName: 'https://www.behindthename.com/name/naima' },
  'najah': { dataset: "Najah", behindTheName: 'https://www.behindthename.com/name/najah' },
  'najat': { dataset: "Najat", behindTheName: 'https://www.behindthename.com/name/najat' },
  'naji': { dataset: "Naji", behindTheName: 'https://www.behindthename.com/name/naji' },
  'najib': { dataset: "Najib", behindTheName: 'https://www.behindthename.com/name/najib' },
  'najla': { dataset: "Najla", behindTheName: 'https://www.behindthename.com/name/najla' },
  'najma': { dataset: "Najma", behindTheName: 'https://www.behindthename.com/name/najma' },
  'najwa': { dataset: "Najwa", behindTheName: 'https://www.behindthename.com/name/najwa' },
  'nasih': { dataset: "Nasih", behindTheName: 'https://www.behindthename.com/name/nasih' },
  'nasir': { dataset: "Nasir", behindTheName: 'https://www.behindthename.com/name/nasir' },
  'nassim': { dataset: "Nassim", behindTheName: 'https://www.behindthename.com/name/nassim' },
  'nassima': { dataset: "Nasima", behindTheName: 'https://www.behindthename.com/name/nassima' },
  'nassira': { dataset: "Nasira", behindTheName: 'https://www.behindthename.com/name/nassira' },
  'nawal': { dataset: "Nawal", behindTheName: 'https://www.behindthename.com/name/nawal' },
  'nawfal': { dataset: "Nawfal", behindTheName: 'https://www.behindthename.com/name/nawfal' },
  'nesrine': { dataset: "Nasrin", behindTheName: 'https://www.behindthename.com/name/nesrine' },
  'nidal': { dataset: "Nidal", behindTheName: 'https://www.behindthename.com/name/nidal' },
  'nizam': { dataset: "Nizam", behindTheName: 'https://www.behindthename.com/name/nizam' },
  'nourhan': { behindTheName: 'https://www.behindthename.com/name/nourhan' },
  'nuh': { dataset: "Nuh", behindTheName: 'https://www.behindthename.com/name/nuh' },
  'nuha': { dataset: "Nuha", behindTheName: 'https://www.behindthename.com/name/nuha' },
  'nur': { dataset: "Nur", behindTheName: 'https://www.behindthename.com/name/nur' },
  'nusaybah': { dataset: "Nusaybah", behindTheName: 'https://www.behindthename.com/name/nusaybah' },
  'qamar': { dataset: "Qamar", behindTheName: 'https://www.behindthename.com/name/qamar' },
  'qasim': { dataset: "Qasim", behindTheName: 'https://www.behindthename.com/name/qasim' },
  'qays': { dataset: "Qays", behindTheName: 'https://www.behindthename.com/name/qays' },
  'qudsia': { dataset: "Qudsia" },
  'rabab': { dataset: "Rabab", behindTheName: 'https://www.behindthename.com/name/rabab' },
  'rabeh': { dataset: "Rabah", behindTheName: 'https://www.behindthename.com/name/rabah' },
  'rabi': { dataset: "Rabi", behindTheName: 'https://www.behindthename.com/name/rabie' },
  'rabia': { dataset: "Rabia", behindTheName: 'https://www.behindthename.com/name/rabia' },
  'rabiaa': { dataset: "Raniya", behindTheName: 'https://www.behindthename.com/name/raniah' },
  'rachida': { dataset: "Rachida", behindTheName: 'https://www.behindthename.com/name/rachida' },
  'radia': { dataset: "Radiya", behindTheName: 'https://www.behindthename.com/name/radia' },
  'rafah': { dataset: "Rafah", behindTheName: 'https://www.behindthename.com/name/rafah' },
  'rafiq': { dataset: "Rafiq", behindTheName: 'https://www.behindthename.com/name/rafiq' },
  'raghib': { dataset: "Raghib", behindTheName: 'https://www.behindthename.com/name/raghib' },
  'rahaf': { dataset: "Rahaf", behindTheName: 'https://www.behindthename.com/name/rahaf' },
  'rahil': { dataset: "Rahil" },
  'rahma': { dataset: "Rahma", behindTheName: 'https://www.behindthename.com/name/rahma' },
  'raif': { dataset: "Raif", behindTheName: 'https://www.behindthename.com/name/raif' },
  'raja': { behindTheName: 'https://www.behindthename.com/name/raja' },
  'rajab': { dataset: "Rajab", behindTheName: 'https://www.behindthename.com/name/rajab' },
  'rami': { dataset: "Rami", behindTheName: 'https://www.behindthename.com/name/rami' },
  'rana': { dataset: "Ranaa", behindTheName: 'https://www.behindthename.com/name/rana' },
  'rand': { dataset: "Rand" },
  'rania': { dataset: "Rania" },
  'raouf': { dataset: "Raouf", behindTheName: 'https://www.behindthename.com/name/raouf' },
  'rasha': { dataset: "Rasha", behindTheName: 'https://www.behindthename.com/name/rasha' },
  'rashad': { dataset: "Rashad", behindTheName: 'https://www.behindthename.com/name/rashad' },
  'rashid': { dataset: "Rashid", behindTheName: 'https://www.behindthename.com/name/rashid' },
  'rawan': { dataset: "Rawan", behindTheName: 'https://www.behindthename.com/name/rawan' },
  'rawda': { dataset: "Rawda", behindTheName: 'https://www.behindthename.com/name/rawda' },
  'rayanah': { dataset: "Raihana", behindTheName: 'https://www.behindthename.com/name/rayhana' },
  'rayyan': { dataset: "Rayan", behindTheName: 'https://www.behindthename.com/name/rayan' },
  'reem': { dataset: "Reem", behindTheName: 'https://www.behindthename.com/name/reem' },
  'rida-g': { dataset: "Rida", behindTheName: 'https://www.behindthename.com/name/rida' },
  'ridwan': { dataset: "Ridwan", behindTheName: 'https://www.behindthename.com/name/ridwan' },
  'rihab': { dataset: "Rehab", behindTheName: 'https://www.behindthename.com/name/rihab' },
  'rima': { dataset: "Rima", behindTheName: 'https://www.behindthename.com/name/rima' },
  'riyad': { dataset: "Riyad", behindTheName: 'https://www.behindthename.com/name/riyad' },
  'roua': { dataset: "Rua", behindTheName: 'https://www.behindthename.com/name/roua' },
  'ruqayya': { dataset: "Ruqayya", behindTheName: 'https://www.behindthename.com/name/ruqayya' },
  'saad': { dataset: "Saad", behindTheName: 'https://www.behindthename.com/name/saad' },
  'saba': { dataset: "Saba", behindTheName: 'https://www.behindthename.com/name/sabaa' },
  'sabah': { dataset: "Sabah", behindTheName: 'https://www.behindthename.com/name/sabah' },
  'sabiha': { dataset: "Sabiha", behindTheName: 'https://www.behindthename.com/name/sabiha' },
  'sabir': { dataset: "Sabir", behindTheName: 'https://www.behindthename.com/name/sabir' },
  'sabrine': { dataset: "Sabrina", behindTheName: 'https://www.behindthename.com/name/sabrine' },
  'sadia': { dataset: "Sadia", behindTheName: 'https://www.behindthename.com/name/saida' },
  'sadiq': { dataset: "Sadiq", behindTheName: 'https://www.behindthename.com/name/sadiq' },
  'safa': { dataset: "Safa", behindTheName: 'https://www.behindthename.com/name/safa' },
  'safaa': { dataset: "Safaa", behindTheName: 'https://www.behindthename.com/name/safaa' },
  'safi': { dataset: "Safi", behindTheName: 'https://www.behindthename.com/name/safy' },
  'safiyya': { dataset: "Safiyya", behindTheName: 'https://www.behindthename.com/name/safiyya' },
  'sahar': { dataset: "Sahar", behindTheName: 'https://www.behindthename.com/name/sahar' },
  'said': { dataset: "Said", behindTheName: 'https://www.behindthename.com/name/said' },
  'salah': { dataset: "Salah", behindTheName: 'https://www.behindthename.com/name/salah' },
  'salih': { dataset: "Salih", behindTheName: 'https://www.behindthename.com/name/salih' },
  'salim': { dataset: "Salim", behindTheName: 'https://www.behindthename.com/name/salim' },
  'salima': { dataset: "Salima", behindTheName: 'https://www.behindthename.com/name/salima' },
  'salma': { dataset: "Salma", behindTheName: 'https://www.behindthename.com/name/salma' },
  'salman': { dataset: "Salman", behindTheName: 'https://www.behindthename.com/name/salman' },
  'salsabil': { dataset: "Salsabil", behindTheName: 'https://www.behindthename.com/name/salsabil' },
  'salwa': { dataset: "Salwa", behindTheName: 'https://www.behindthename.com/name/salwa' },
  'samah': { dataset: "Samah", behindTheName: 'https://www.behindthename.com/name/samah' },
  'samar': { dataset: "Samar", behindTheName: 'https://www.behindthename.com/name/samar' },
  'sami': { dataset: "Sami", behindTheName: 'https://www.behindthename.com/name/sami' },
  'samia': { dataset: "Samia", behindTheName: 'https://www.behindthename.com/name/samia' },
  'samir': { dataset: "Samir", behindTheName: 'https://www.behindthename.com/name/samir' },
  'samira': { dataset: "Samira", behindTheName: 'https://www.behindthename.com/name/samira' },
  'sana': { dataset: "Sana", behindTheName: 'https://www.behindthename.com/name/sana' },
  'sawsan': { dataset: "Sawsan", behindTheName: 'https://www.behindthename.com/name/sawsan' },
  'seif': { dataset: "Seif", behindTheName: 'https://www.behindthename.com/name/seif' },
  'shadi': { dataset: "Shadi", behindTheName: 'https://www.behindthename.com/name/shadi' },
  'shahd': { behindTheName: 'https://www.behindthename.com/name/shahd' },
  'shaima': { dataset: "Shaima", behindTheName: 'https://www.behindthename.com/name/shaima' },
  'shakir': { dataset: "Shakir", behindTheName: 'https://www.behindthename.com/name/shakir' },
  'shams': { behindTheName: 'https://www.behindthename.com/name/shams' },
  'sharif': { dataset: "Sharif", behindTheName: 'https://www.behindthename.com/name/sharif' },
  'shatha': { dataset: "Shatha", behindTheName: 'https://www.behindthename.com/name/shatha' },
  'shifa': { dataset: "Shifa", behindTheName: 'https://www.behindthename.com/name/shifa' },
  'shuayb': { dataset: "Shuayb", behindTheName: 'https://www.behindthename.com/name/shuayb' },
  'sidra': { dataset: "Sidra", behindTheName: 'https://www.behindthename.com/name/sidra' },
  'siham': { behindTheName: 'https://www.behindthename.com/name/siham' },
  'skander': { dataset: "Iskandar", behindTheName: 'https://www.behindthename.com/name/skander' },
  'sofiane': { dataset: "Sofiane", behindTheName: 'https://www.behindthename.com/name/sofiane' },
  'sonia': { dataset: "Sonia" },
  'souad': { dataset: "Souad", behindTheName: 'https://www.behindthename.com/name/souad' },
  'suhaila': { dataset: "Suhaila", behindTheName: 'https://www.behindthename.com/name/suhaila' },
  'suhayb': { dataset: "Suhayb", behindTheName: 'https://www.behindthename.com/name/suhayb' },
  'suhayl': { dataset: "Suhayl", behindTheName: 'https://www.behindthename.com/name/suhayl' },
  'sukayna': { dataset: "Sakina", behindTheName: 'https://www.behindthename.com/name/sukayna' },
  'sulayman': { dataset: "Sulayman", behindTheName: 'https://www.behindthename.com/name/sulayman' },
  'sumayya': { dataset: "Sumayya", behindTheName: 'https://www.behindthename.com/name/sumayya' },
  'sundus': { dataset: "Sundus", behindTheName: 'https://www.behindthename.com/name/sundus' },
  'taha2': { dataset: "Taha", behindTheName: 'https://www.behindthename.com/name/taha' },
  'tahar': { dataset: "Tahar", behindTheName: 'https://www.behindthename.com/name/tahar' },
  'tahira': { dataset: "Tahira", behindTheName: 'https://www.behindthename.com/name/tahira' },
  'talha': { dataset: "Talha", behindTheName: 'https://www.behindthename.com/name/talha' },
  'tamim': { dataset: "Tamim", behindTheName: 'https://www.behindthename.com/name/tamim' },
  'taqwa': { dataset: "Taqwa", behindTheName: 'https://www.behindthename.com/name/taqwa' },
  'tariq': { dataset: "Tariq", behindTheName: 'https://www.behindthename.com/name/tariq' },
  'tasnim': { dataset: "Tasnim", behindTheName: 'https://www.behindthename.com/name/tasnim' },
  'tawfiq': { dataset: "Tawfiq", behindTheName: 'https://www.behindthename.com/name/tawfiq' },
  'taym': { behindTheName: 'https://www.behindthename.com/name/taym' },
  'tayyib': { dataset: "Tayyib", behindTheName: 'https://www.behindthename.com/name/tayyib' },
  'thabit': { dataset: "Thabit", behindTheName: 'https://www.behindthename.com/name/thabit' },
  'thurayya': { dataset: "Thurayya", behindTheName: 'https://www.behindthename.com/name/thurayya' },
  'tuba': { dataset: "Tuba", behindTheName: 'https://www.behindthename.com/name/tuba' },
  'ubaid': { dataset: "Ubayd", behindTheName: 'https://www.behindthename.com/name/ubayd' },
  'umar': { dataset: "Umar", behindTheName: 'https://www.behindthename.com/name/umar' },
  'umm-kulthum': { dataset: "Umm-kulthum" },
  'uqba': { dataset: "Uqba", behindTheName: 'https://www.behindthename.com/name/uqba' },
  'wadie': { dataset: "Wadi", behindTheName: 'https://www.behindthename.com/name/wadie' },
  'wael': { dataset: "Wael", behindTheName: 'https://www.behindthename.com/name/wael' },
  'wafa': { dataset: "Wafa", behindTheName: 'https://www.behindthename.com/name/wafa' },
  'wafi': { dataset: "Wafi" },
  'wahib': { dataset: "Wahib" },
  'wahiba': { dataset: "Wahiba", behindTheName: 'https://www.behindthename.com/name/ouahiba' },
  'wajd': { behindTheName: 'https://www.behindthename.com/name/wajd' },
  'wajdi': { dataset: "Wajdi", behindTheName: 'https://www.behindthename.com/name/wajdi' },
  'walid': { dataset: "Walid", behindTheName: 'https://www.behindthename.com/name/walid' },
  'warda': { dataset: "Warda", behindTheName: 'https://www.behindthename.com/name/warda' },
  'wasila': { dataset: "Wasila", behindTheName: 'https://www.behindthename.com/name/wasila' },
  'wasim': { dataset: "Wasim", behindTheName: 'https://www.behindthename.com/name/wasim' },
  'wiam': { dataset: "Wiam", behindTheName: 'https://www.behindthename.com/name/wiam' },
  'widad': { dataset: "Widad", behindTheName: 'https://www.behindthename.com/name/widad' },
  'wissal': { dataset: "Wisal", behindTheName: 'https://www.behindthename.com/name/wissal' },
  'wissam-boy': { dataset: "Wissam", behindTheName: 'https://www.behindthename.com/name/wissam' },
  'wissam-girl': { behindTheName: 'https://www.behindthename.com/name/wissam' },
  'yahya': { dataset: "Yahya", behindTheName: 'https://www.behindthename.com/name/yahya' },
  'yamin': { behindTheName: 'https://www.behindthename.com/name/yamine' },
  'yamina': { dataset: "Yamina", behindTheName: 'https://www.behindthename.com/name/yamina' },
  'yaqub': { dataset: "Yaqub", behindTheName: 'https://www.behindthename.com/name/yaqub' },
  'yara': { dataset: "Yara", behindTheName: 'https://www.behindthename.com/name/yara' },
  'yasin2': { dataset: "Yasin" },
  'yasir': { dataset: "Yasir", behindTheName: 'https://www.behindthename.com/name/yasir' },
  'yasmin': { dataset: "Yasmin", behindTheName: 'https://www.behindthename.com/name/yasmin' },
  'yumna': { dataset: "Yumna", behindTheName: 'https://www.behindthename.com/name/yumna' },
  'yunus': { dataset: "Yunus", behindTheName: 'https://www.behindthename.com/name/yunus' },
  'yusra': { dataset: "Yusra", behindTheName: 'https://www.behindthename.com/name/yusra' },
  'yusuf': { dataset: "Yusuf", behindTheName: 'https://www.behindthename.com/name/yusuf' },
  'zahia': { dataset: "Zahia", behindTheName: 'https://www.behindthename.com/name/zahia' },
  'zahida': { dataset: "Zahida", behindTheName: 'https://www.behindthename.com/name/zahida' },
  'zahir': { dataset: "Zahir", behindTheName: 'https://www.behindthename.com/name/zahir' },
  'zahira': { dataset: "Zahira", behindTheName: 'https://www.behindthename.com/name/zahira' },
  'zahra': { dataset: "Zahra", behindTheName: 'https://www.behindthename.com/name/zahra' },
  'zaina': { dataset: "Zaina", behindTheName: 'https://www.behindthename.com/name/zaina' },
  'zakariya': { dataset: "Zakariya", behindTheName: 'https://www.behindthename.com/name/zakariya' },
  'zaki': { dataset: "Zaki", behindTheName: 'https://www.behindthename.com/name/zaki' },
  'zakia': { dataset: "Zakia", behindTheName: 'https://www.behindthename.com/name/zakia' },
  'zayd': { dataset: "Zayd", behindTheName: 'https://www.behindthename.com/name/zayd' },
  'zayn': { dataset: "Zayn", behindTheName: 'https://www.behindthename.com/name/zayn' },
  'zaynab': { dataset: "Zaynab", behindTheName: 'https://www.behindthename.com/name/zaynab' },
  'ziyad': { dataset: "Ziyad", behindTheName: 'https://www.behindthename.com/name/ziyad' },
  'zoubir': { dataset: "Zubayr", behindTheName: 'https://www.behindthename.com/name/zoubir' },
  'zubaida': { dataset: "Zubaida", behindTheName: 'https://www.behindthename.com/name/zubaida' },
  'zubayr': { dataset: "Zubayr", behindTheName: 'https://www.behindthename.com/name/zubayr' },
};
