import type { Invocation, Source } from "./pilgrimageTypes";

const H = (reference: string): Source => ({ kind: "AUTHENTIC_HADITH", reference });
const Q = (reference: string): Source => ({ kind: "QURAN", reference });

/** Invocations, in the order of the journey. */
export const INVOCATIONS: Invocation[] = [
  {
    id: "travel",
    moment: "Le voyage",
    title: "En prenant la route",
    arabic: "اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ، اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى",
    transliteration: "Allâhu akbar (×3). Subhâna lladhî sakhkhara lanâ hâdhâ wa mâ kunnâ lahu muqrinîn, wa innâ ilâ rabbinâ la-munqalibûn. Allâhumma innâ nas’aluka fî safarinâ hâdhâ l-birra wa t-taqwâ, wa mina l-‘amali mâ tardâ.",
    translation: "Allah est le plus grand (×3). Gloire à Celui qui a mis ceci à notre service alors que nous n’étions pas capables de le dominer ; c’est vers notre Seigneur que nous retournerons. Ô Allah, nous Te demandons, dans ce voyage, la bonté et la piété, et des œuvres qui Te satisfont.",
    context: "En montant dans le moyen de transport, au départ du voyage.",
    status: "SUNNA AUTHENTIQUE",
    sources: [H("Sahîh Muslim 1342")],
  },
  {
    id: "talbiyah",
    moment: "L’ihrâm",
    title: "La talbiya",
    arabic: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ",
    transliteration: "Labbayka Allâhumma labbayk, labbayka lâ sharîka laka labbayk, inna l-hamda wa-n-ni‘mata laka wa-l-mulk, lâ sharîka lak.",
    translation: "Me voici, ô Allah, me voici. Me voici, Tu n’as pas d’associé, me voici. La louange, le bienfait et la royauté T’appartiennent. Tu n’as pas d’associé.",
    context: "À partir de l’entrée en ihrâm, et à répéter jusqu’au rite qui met fin à cette récitation.",
    status: "SUNNA AUTHENTIQUE",
    sources: [H("Sahîh al-Bukhârî 1549")],
  },
  {
    id: "takbir",
    moment: "Le Tawâf",
    title: "En passant la Pierre noire",
    arabic: "اللَّهُ أَكْبَرُ",
    transliteration: "Allâhu akbar",
    translation: "Allah est le plus grand.",
    context: "Le Prophète ﷺ faisait un signe vers l’angle de la Pierre noire et disait « Allâhu akbar » à chaque passage. Également à chaque caillou lancé aux Jamarât.",
    status: "SUNNA AUTHENTIQUE",
    sources: [H("Sahîh al-Bukhârî 1613"), H("Sahîh Muslim 1218")],
  },
  {
    id: "rabbana",
    moment: "Le Tawâf",
    title: "Un bien ici-bas et dans l’au-delà",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    transliteration: "Rabbanâ âtinâ fî d-dunyâ hasanatan wa fî l-âkhirati hasanatan wa qinâ ‘adhâba n-nâr",
    translation: "Seigneur, accorde-nous un bien ici-bas et un bien dans l’au-delà, et protège-nous du châtiment du Feu.",
    context: "Invocation coranique générale pendant les rites, sans l’imposer à un tour particulier.",
    status: "INVOCATION CORANIQUE GÉNÉRALE",
    sources: [Q("Coran 2:201")],
  },
  {
    id: "free",
    moment: "Le Tawâf",
    title: "Invocation libre",
    arabic: "",
    transliteration: "Invocation libre",
    translation: "Le pèlerin invoque Allah avec ses propres paroles, dans sa langue.",
    context: "Pendant le Tawâf et le Sa‘y lorsqu’aucune formule spécifique n’est établie.",
    status: "INVOCATION LIBRE",
    sources: [],
  },
  {
    id: "safa",
    moment: "Le Sa‘y",
    title: "En approchant de Safâ",
    arabic: "إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللَّهِ — أَبْدَأُ بِمَا بَدَأَ اللَّهُ بِهِ",
    transliteration: "Inna s-Safâ wa-l-Marwata min sha‘â’iri llâh — Abda’u bimâ bada’a llâhu bih",
    translation: "Safâ et Marwa font partie des rites d’Allah. — Je commence par ce par quoi Allah a commencé.",
    context: "Récité par le Prophète ﷺ en approchant de Safâ au début du Sa‘y ; ce n’est pas une formule obligatoire à chaque passage.",
    status: "SUNNA AUTHENTIQUE",
    sources: [Q("Coran 2:158"), H("Sahîh Muslim 1218")],
  },
  {
    id: "safa-dhikr",
    moment: "Le Sa‘y",
    title: "Sur Safâ et sur Marwa",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ، أَنْجَزَ وَعْدَهُ، وَنَصَرَ عَبْدَهُ، وَهَزَمَ الْأَحْزَابَ وَحْدَهُ",
    transliteration: "Lâ ilâha illâ llâhu wahdahu lâ sharîka lah, lahu l-mulku wa lahu l-hamd, wa huwa ‘alâ kulli shay’in qadîr. Lâ ilâha illâ llâhu wahdah, anjaza wa‘dah, wa nasara ‘abdah, wa hazama l-ahzâba wahdah.",
    translation: "Nulle divinité sauf Allah, Seul, sans associé ; à Lui la royauté et la louange, et Il est capable de toute chose. Nulle divinité sauf Allah, Seul ; Il a tenu Sa promesse, secouru Son serviteur et vaincu Seul les coalisés.",
    context: "Face à la Kaaba, après avoir proclamé la grandeur d’Allah : le Prophète ﷺ l’a dit trois fois en invoquant entre chaque fois, sur Safâ puis sur Marwa.",
    status: "SUNNA AUTHENTIQUE",
    sources: [H("Sahîh Muslim 1218")],
  },
  {
    id: "forgiveness",
    moment: "Le Sa‘y",
    title: "Pardon et miséricorde",
    arabic: "رَبِّ اغْفِرْ وَارْحَمْ",
    transliteration: "Rabbi’ghfir warham",
    translation: "Seigneur, pardonne et fais miséricorde.",
    context: "Invocation coranique générale pendant les déplacements et les rites, sans la présenter comme une formule propre à ce rite.",
    status: "INVOCATION CORANIQUE GÉNÉRALE",
    sources: [Q("Coran 23:118")],
  },
  {
    id: "arafa",
    moment: "‘Arafa",
    title: "La meilleure invocation de ‘Arafa",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "Lâ ilâha illâ llâhu wahdahu lâ sharîka lah, lahu l-mulku wa lahu l-hamd, wa huwa ‘alâ kulli shay’in qadîr.",
    translation: "Nulle divinité sauf Allah, Seul, sans associé ; à Lui la royauté et la louange, et Il est capable de toute chose.",
    context: "« La meilleure invocation est celle du jour de ‘Arafa, et la meilleure parole que nous ayons dite, moi et les prophètes avant moi… »",
    status: "HADITH HASAN",
    sources: [H("Sunan at-Tirmidhî 3585")],
  },
  {
    id: "mashar",
    moment: "Muzdalifa",
    title: "Au Mash‘ar al-Harâm",
    arabic: "فَإِذَا أَفَضْتُمْ مِنْ عَرَفَاتٍ فَاذْكُرُوا اللَّهَ عِنْدَ الْمَشْعَرِ الْحَرَامِ",
    transliteration: "Fa-idhâ afadtum min ‘arafâtin fa-dhkurû llâha ‘inda l-mash‘ari l-harâm",
    translation: "Puis, quand vous déferlez depuis ‘Arafât, invoquez Allah auprès du Mash‘ar al-Harâm.",
    context: "Après Fajr à Muzdalifa, le Prophète ﷺ s’est tenu face à la qibla pour invoquer, proclamer Sa grandeur et Son unicité jusqu’à la clarté.",
    status: "VERSET CORANIQUE",
    sources: [Q("Coran 2:198"), H("Sahîh Muslim 1218")],
  },
  {
    id: "mosque-entry",
    moment: "Médine",
    title: "En entrant dans la mosquée",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allâhumma-ftah lî abwâba rahmatik",
    translation: "Ô Allah, ouvre-moi les portes de Ta miséricorde.",
    context: "En entrant dans toute mosquée, dont la Mosquée du Prophète ﷺ et la Mosquée sacrée.",
    status: "SUNNA AUTHENTIQUE",
    sources: [H("Sahîh Muslim 713")],
  },
  {
    id: "baqi",
    moment: "Médine",
    title: "En visitant les tombes",
    arabic: "السَّلَامُ عَلَيْكُمْ أَهْلَ الدِّيَارِ مِنَ الْمُؤْمِنِينَ وَالْمُسْلِمِينَ، وَإِنَّا إِنْ شَاءَ اللَّهُ لَلَاحِقُونَ، أَسْأَلُ اللَّهَ لَنَا وَلَكُمُ الْعَافِيَةَ",
    transliteration: "As-salâmu ‘alaykum ahla d-diyâri mina l-mu’minîna wa l-muslimîn, wa innâ in shâ’a llâhu la-lâhiqûn, as’alu llâha lanâ wa lakumu l-‘âfiya.",
    translation: "Que la paix soit sur vous, habitants de ces demeures, croyants et musulmans. Nous vous rejoindrons, si Allah le veut. Je demande à Allah le salut pour nous et pour vous.",
    context: "Enseignée par le Prophète ﷺ à ses compagnons pour la visite des cimetières (al-Baqî‘, les martyrs de Uhud…).",
    status: "SUNNA AUTHENTIQUE",
    sources: [H("Sahîh Muslim 975")],
  },
  {
    id: "acceptance",
    moment: "À la fin",
    title: "Demander l’acceptation",
    arabic: "رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ",
    transliteration: "Rabbanâ taqabbal minnâ innaka anta s-Samî‘u l-‘Alîm",
    translation: "Seigneur, accepte de nous, car Tu es Celui qui entend et qui sait.",
    context: "Invocation coranique générale après une œuvre, sans la présenter comme une formule spécifique du rite.",
    status: "INVOCATION CORANIQUE GÉNÉRALE",
    sources: [Q("Coran 2:127")],
  },
];

export const INVOCATIONS_BY_ID: Record<string, Invocation> = Object.fromEntries(
  INVOCATIONS.map((invocation) => [invocation.id, invocation]),
);
