import { useState } from "react";
import { Pressable, Text, View } from "react-native";
import type { Assertion, Step } from "./pilgrimageTypes";
import { sourceLabel } from "./pilgrimageTypes";

const groups: Array<[keyof Step, string]> = [["how", "Comment faire ?"], ["when", "Quand ?"], ["whatToSay", "Que dire ?"], ["avoid", "À éviter"], ["women", "Pour les femmes"], ["men", "Pour les hommes"], ["commonMistakes", "Erreurs fréquentes"], ["specialCases", "Cas particuliers"], ["do", "À faire maintenant"]];
export function StepDetails({ step }: { step: Step }) {
  return <>{groups.map(([key, label]) => { const items = step[key] as Assertion[] | undefined; return items?.length ? <Detail key={String(key)} label={label} items={items} /> : null; })}{step.juristicDifferences?.map((d, i) => <View key={`difference-${i}`} style={{ marginTop: 14, padding: 12, borderRadius: 12, borderWidth: 1, borderColor: "#806233" }}><Text style={{ color: "#E5B65D", fontWeight: "800" }}>DIVERGENCE JURIDIQUE</Text><Text style={{ color: "#FFF7E7", fontSize: 16, lineHeight: 24, marginTop: 6 }}>{d.question}</Text>{d.establishedPoint && <Text style={{ color: "#E9DFD0", fontSize: 15, lineHeight: 22, marginTop: 5 }}>{d.establishedPoint}</Text>}{d.views.map(v => <Text key={v.label} style={{ color: "#E9DFD0", fontSize: 15, lineHeight: 22, marginTop: 5 }}>{v.label} : {v.position}{v.consequence ? ` — ${v.consequence}` : ""}</Text>)}{d.practicalNote && <Text style={{ color: "#F0C777", fontSize: 15, lineHeight: 22, marginTop: 6 }}>{d.practicalNote}</Text>}</View>)}</>;
}
function Detail({ label, items }: { label: string; items: Assertion[] }) { const [open, setOpen] = useState(label === "À faire maintenant"); return <View style={{ marginTop: 10 }}><Pressable onPress={() => setOpen(value => !value)}><Text style={{ color: "#E5B65D", fontWeight: "800", fontSize: 14 }}>{open ? "−" : "+"} {label}</Text></Pressable>{open && items.map(item => <View key={item.id} style={{ marginTop: 5 }}><Text style={{ color: "#FFF7E7", fontSize: 16, lineHeight: 25 }}>{item.text}</Text><Text style={{ color: "#D7C6A6", fontSize: 12, marginTop: 4 }}>{item.sources.map(s => `${sourceLabel(s.kind)} · ${s.reference}`).join(" | ")}</Text></View>)}</View>; }
