export type ProphetAudioEpisode = {
  id: string;
  prophetId: string;
  prophetName: string;
  title: string;
  subtitle: string;
  estimatedMinutes: number;
  audioFileName: string;
  audioUrl: string;
  scriptVersion: string;
  verifiedAt: string;
  sourceLabels: string[];
};

const PROPHET_AUDIO_BASE_URL =
  "https://imcqphigckqbwbbzstdf.supabase.co/storage/v1/object/public/prophet-media/audio";

const audio = (audioFileName: string) => ({
  audioFileName,
  audioUrl: `${PROPHET_AUDIO_BASE_URL}/${audioFileName}`,
});

export const PROPHET_AUDIO_EPISODES: Record<string, ProphetAudioEpisode> = {
  adam: {
    id: "adam-complete-fr-capcut-v1",
    prophetId: "adam",
    prophetName: "Âdam",
    title: "L’histoire complète d’Âdam",
    subtitle: "Création, Iblîs, le Jardin, le repentir et les premiers enfants d’Âdam",
    estimatedMinutes: 9,
    ...audio("adam-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v2",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-Baqara 2:30–39",
      "Al-A‘râf 7:11–27",
      "Al-Hijr 15:26–44",
      "Al-Isrâ’ 17:61–65",
      "Al-Kahf 18:50",
      "Tâ-Hâ 20:115–123",
      "Sâd 38:71–85",
      "Al-Mâ’ida 5:27–31",
    ],
  },
  idris: {
    id: "idris-complete-fr-capcut-v1",
    prophetId: "idris",
    prophetName: "Idris",
    title: "L’histoire complète d’Idris",
    subtitle: "L’histoire complète d’Idris",
    estimatedMinutes: 3,
    ...audio("idris-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v2",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Maryam 19:56–57",
      "Al-Anbiyâ’ 21:85–86",
      "Sahih Muslim · récit de l’Isra’ et du Mi‘râj",
    ],
  },
  nuh: {
    id: "nuh-complete-fr-capcut-v1",
    prophetId: "nuh",
    prophetName: "Nouh",
    title: "L’histoire complète de Nouh",
    subtitle: "L’histoire complète de Nouh",
    estimatedMinutes: 10,
    ...audio("nouh-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v2",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-A‘râf 7:59–64",
      "Hûd 11:25–49",
      "Al-Mu’minûn 23:23–30",
      "Ash-Shu‘arâ’ 26:105–122",
      "Al-‘Ankabût 29:14–15",
      "Al-Qamar 54:9–17",
      "Nûh 71:1–28",
      "At-Tahrîm 66:10",
    ],
  },
  hud: {
    id: "hud-complete-fr-capcut-v1",
    prophetId: "hud",
    prophetName: "Hud",
    title: "L’histoire complète de Hud",
    subtitle: "L’histoire complète de Hud",
    estimatedMinutes: 7,
    ...audio("hud-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v2",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-A‘râf 7:65–72",
      "Hûd 11:50–60",
      "Fussilat 41:15–16",
      "Al-Ahqâf 46:21–26",
      "Al-Hâqqa 69:6–8",
      "Sahih al-Bukhari · récit des nuages et du peuple de ‘Âd",
      "Sahih Muslim · invocation lors du vent",
    ],
  },
  salih: {
    id: "salih-complete-fr-capcut-v1",
    prophetId: "salih",
    prophetName: "Salih",
    title: "L’histoire complète de Salih",
    subtitle: "L’histoire complète de Salih",
    estimatedMinutes: 7,
    ...audio("salih-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v2",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-A‘râf 7:73–79",
      "Hûd 11:61–68",
      "Ash-Shu‘arâ’ 26:141–159",
      "An-Naml 27:45–53",
      "Al-Qamar 54:23–31",
      "Ash-Shams 91:11–15",
      "Sahih al-Bukhari 3379–3380 · Al-Hijr et Thamûd",
      "Sahih Muslim 2980 · passage par Al-Hijr",
    ],
  },
  ibrahim: {
    id: "ibrahim-complete-fr-capcut-v1",
    prophetId: "ibrahim",
    prophetName: "Ibrâhîm",
    title: "L’histoire complète d’Ibrâhîm",
    subtitle: "Le monothéisme, les idoles, le feu, l’émigration, la famille, l’épreuve du sacrifice et la Ka‘ba",
    estimatedMinutes: 13,
    ...audio("ibrahim-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v2",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Maryam 19:42–48",
      "Al-An‘âm 6:76–79",
      "Al-Anbiyâ’ 21:57–70",
      "Al-‘Ankabût 29:26",
      "Hûd 11:69–76",
      "Ibrâhîm 14:35–37",
      "As-Sâffât 37:100–111",
      "Al-Baqara 2:125–129",
      "Sahih al-Bukhari 3356, 3358, 3364",
      "Sahih Muslim 2370",
    ],
  },
  musa: {
    id: "moussa-complete-fr-elevenlabs-v1",
    prophetId: "musa",
    prophetName: "Moussa",
    title: "L’histoire complète de Moussa",
    subtitle: "De sa naissance à Pharaon, la mer, le veau d’or et la rencontre avec Al-Khidr",
    estimatedMinutes: 16,
    ...audio("moussa-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-Qasas 28:3–28",
      "Tâ-Hâ 20:9–98",
      "Ash-Shu‘arâ’ 26:18–68",
      "Al-A‘râf 7:130–143",
      "Yûnus 10:90–92",
      "Al-Kahf 18:60–82",
      "Sahih al-Bukhari 3401 · Mûsâ et Al-Khidr",
    ],
  },

  muhammad: {
    id: "muhammad-complete-fr-elevenlabs-v1",
    prophetId: "muhammad",
    prophetName: "Muhammad",
    title: "L’histoire complète de Muhammad",
    subtitle: "De la première révélation à la Hijra, Médine, les grandes épreuves et la fin de la mission",
    estimatedMinutes: 24,
    ...audio("muhammad-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-‘Alaq 96:1–5",
      "Al-Muddaththir 74:1–7",
      "Ash-Shu‘arâ’ 26:214–216",
      "Al-Isrâ’ 17:1",
      "At-Tawbah 9:40",
      "Al-Anfâl 8:9–12",
      "Âl ‘Imrân 3:152–155",
      "Al-Ahzâb 33:9–11, 40",
      "Al-Fath 48:1–3",
      "An-Nasr 110:1–3",
      "Al-Mâ’idah 5:3",
      "Al-Anbiyâ’ 21:107",
      "Sahih al-Bukhari 3, 3231, 3653, 3992, 4075, 4438, 4451, 4463",
      "Sahih Muslim 1218",
    ],
  },

  isa: {
    id: "isa-complete-fr-elevenlabs-v1",
    prophetId: "isa",
    prophetName: "Issa",
    title: "L’histoire complète de Issa",
    subtitle: "Maryam, la naissance miraculeuse, les signes, le message, l’élévation et le retour de Issa",
    estimatedMinutes: 10,
    ...audio("isa-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Âl ‘Imrân 3:42–59",
      "Maryam 19:16–36",
      "Al-Mâ’idah 5:110–118",
      "As-Saff 61:6",
      "An-Nisâ’ 4:157–158",
      "Sahih al-Bukhari 3443, 3448",
      "Sahih Muslim 155, 2937",
    ],
  },

  yusuf: {
    id: "yusuf-complete-fr-elevenlabs-v1",
    prophetId: "yusuf",
    prophetName: "Youssouf",
    title: "L’histoire complète de Youssouf",
    subtitle: "Le rêve, le puits, l’Égypte, la prison, le pouvoir, le pardon et les retrouvailles",
    estimatedMinutes: 19,
    ...audio("yusuf-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Youssouf 12:1–111",
      "Sahih al-Bukhari 3382",
    ],
  },

  ayyub: {
    id: "ayyub-complete-fr-elevenlabs-v1",
    prophetId: "ayyub",
    prophetName: "Ayyoub",
    title: "L’histoire complète de Ayyoub",
    subtitle: "L’épreuve, la patience, l’invocation, la guérison et la confiance en Allah",
    estimatedMinutes: 8,
    ...audio("ayyub-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-Anbiyâ’ 21:83–84",
      "Sâd 38:41–44",
      "Sahih al-Bukhari 3391",
    ],
  },

  yaqub: {
    id: "yaqub-complete-fr-elevenlabs-v1",
    prophetId: "yaqub",
    prophetName: "Yaacoub",
    title: "L’histoire complète de Yaacoub",
    subtitle: "La lignée d’Ibrahim, Youssouf, la patience, l’espérance et la transmission de la foi",
    estimatedMinutes: 7,
    ...audio("yaqub-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-Baqara 2:132–133",
      "Youssouf 12:4–6",
      "Youssouf 12:18",
      "Youssouf 12:84–87",
      "Youssouf 12:96–98",
      "Sahih al-Bukhari 3382",
    ],
  },

  sulayman: {
    id: "sulayman-complete-fr-elevenlabs-v1",
    prophetId: "sulayman",
    prophetName: "Soulayman",
    title: "L’histoire complète de Soulayman",
    subtitle: "Le royaume, les djinns, la fourmi, la huppe, la reine de Saba et la reconnaissance envers Allah",
    estimatedMinutes: 8,
    ...audio("sulayman-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "An-Naml 27:15–44",
      "Saba 34:12–14",
      "Sâd 38:30–40",
    ],
  },

  yunus: {
    id: "yunus-complete-fr-elevenlabs-v1",
    prophetId: "yunus",
    prophetName: "Younous",
    title: "L’histoire complète de Younous",
    subtitle: "Le départ, le navire, le poisson, l’invocation, la délivrance et le repentir de son peuple",
    estimatedMinutes: 7,
    ...audio("yunus-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-Anbiyâ’ 21:87–88",
      "As-Sâffât 37:139–148",
      "Younous 10:98",
      "Sahih al-Bukhari 3412",
    ],
  },

  dawud: {
    id: "dawud-complete-fr-elevenlabs-v1",
    prophetId: "dawud",
    prophetName: "Dawoud",
    title: "L’histoire complète de Dawoud",
    subtitle: "Jalout, la royauté, le Zabour, la justice, l’adoration et le retour vers Allah",
    estimatedMinutes: 7,
    ...audio("dawud-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-Baqara 2:246–251",
      "An-Nisâ’ 4:163",
      "Al-Isrâ’ 17:55",
      "Saba 34:10–11",
      "Sâd 38:17–26",
      "Sahih al-Bukhari 1131, 3417",
      "Sahih Muslim · prière et jeûne de Dawoud",
    ],
  },

  ismail: {
    id: "ismail-complete-fr-elevenlabs-v1",
    prophetId: "ismail",
    prophetName: "Ismaïl",
    title: "L’histoire complète d’Ismaïl",
    subtitle: "Ibrahim, l’épreuve du sacrifice, La Mecque, Zamzam, la Kaaba et la transmission de la foi",
    estimatedMinutes: 7,
    ...audio("ismail-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "As-Sâffât 37:100–107",
      "Al-Baqara 2:125–129",
      "Maryam 19:54–55",
      "Al-Anbiyâ’ 21:85–86",
      "Sahih al-Bukhari 3364",
    ],
  },

  lut: {
    id: "lut-complete-fr-elevenlabs-v1",
    prophetId: "lut",
    prophetName: "Lout",
    title: "L’histoire complète de Lout",
    subtitle: "L’appel, le rejet, les anges, le départ, le châtiment et les enseignements",
    estimatedMinutes: 10,
    ...audio("lut-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-A‘râf 7:80–84",
      "Hûd 11:69–83",
      "Al-Hijr 15:57–77",
      "Ash-Shu‘arâ’ 26:160–175",
      "An-Naml 27:54–58",
      "Al-‘Ankabût 29:28–35",
      "Al-Qamar 54:33–39",
      "At-Tahrîm 66:10",
    ],
  },

  harun: {
    id: "harun-complete-fr-elevenlabs-v1",
    prophetId: "harun",
    prophetName: "Haroun",
    title: "L’histoire complète de Haroun",
    subtitle: "Le soutien de Moussa, la mission auprès de Pharaon et l’épreuve du veau d’or",
    estimatedMinutes: 7,
    ...audio("harun-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Tâ-Hâ 20:25–36, 43–44, 85–94",
      "Al-Qasas 28:34–35",
      "Maryam 19:53",
      "Al-A‘râf 7:142, 150–151",
    ],
  },

  shuayb: {
    id: "shuayb-complete-fr-elevenlabs-v1",
    prophetId: "shuayb",
    prophetName: "Chouaïb",
    title: "L’histoire complète de Chouaïb",
    subtitle: "Madyan, la justice dans le commerce, le rejet du peuple et le châtiment",
    estimatedMinutes: 7,
    ...audio("shuayb-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-A‘râf 7:85–93",
      "Hûd 11:84–95",
      "Ash-Shu‘arâ’ 26:176–189",
      "Al-‘Ankabût 29:36–37",
    ],
  },

  zakariya: {
    id: "zakariya-complete-fr-elevenlabs-v1",
    prophetId: "zakariya",
    prophetName: "Zakariya",
    title: "L’histoire complète de Zakariya",
    subtitle: "Maryam, l’invocation, l’annonce de Yahya et la confiance absolue en Allah",
    estimatedMinutes: 6,
    ...audio("zakariya-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Âl ‘Imrân 3:35–41",
      "Maryam 19:2–11",
    ],
  },

  yahya: {
    id: "yahya-complete-fr-elevenlabs-v1",
    prophetId: "yahya",
    prophetName: "Yahya",
    title: "L’histoire complète de Yahya",
    subtitle: "Sa naissance miraculeuse, sa sagesse, sa pureté et son rang parmi les prophètes",
    estimatedMinutes: 4,
    ...audio("yahya-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Maryam 19:7–15",
      "Âl ‘Imrân 3:39",
      "Al-An‘âm 6:84–85",
    ],
  },

  ishaq: {
    id: "ishaq-complete-fr-elevenlabs-v1",
    prophetId: "ishaq",
    prophetName: "Ishaq",
    title: "L’histoire complète d’Ishaq",
    subtitle: "La bonne nouvelle à Ibrahim, la bénédiction, la prophétie et la continuité de la lignée",
    estimatedMinutes: 4,
    ...audio("ishaq-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Hûd 11:69–73",
      "Adh-Dhâriyât 51:24–30",
      "As-Sâffât 37:112–113",
      "Al-An‘âm 6:84–87",
      "Sâd 38:45–47",
    ],
  },

  ilyas: {
    id: "ilyas-complete-fr-elevenlabs-v1",
    prophetId: "ilyas",
    prophetName: "Ilyas",
    title: "L’histoire complète d’Ilyas",
    subtitle: "L’appel au monothéisme, le rejet de Baal et la fidélité à Allah",
    estimatedMinutes: 3,
    ...audio("ilyas-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "As-Sâffât 37:123–132",
      "Al-An‘âm 6:85",
    ],
  },

  "al-yasa": {
    id: "al-yasa-complete-fr-elevenlabs-v1",
    prophetId: "al-yasa",
    prophetName: "Al-Yasa",
    title: "L’histoire complète d’Al-Yasa",
    subtitle: "Un prophète choisi par Allah, cité parmi les meilleurs serviteurs",
    estimatedMinutes: 3,
    ...audio("al-yasa-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-An‘âm 6:86",
      "Sâd 38:48–49",
    ],
  },

  "dhul-kifl": {
    id: "dhul-kifl-complete-fr-elevenlabs-v1",
    prophetId: "dhul-kifl",
    prophetName: "Dhoul-Kifl",
    title: "L’histoire complète de Dhoul-Kifl",
    subtitle: "La patience, la droiture et le rang d’un serviteur cité parmi les meilleurs",
    estimatedMinutes: 4,
    ...audio("dhul-kifl-fr.m4a"),
    scriptVersion: "2026-09-06-elevenlabs-v1",
    verifiedAt: "2026-09-06",
    sourceLabels: [
      "Al-Anbiyâ’ 21:85–86",
      "Sâd 38:48",
    ],
  },

};
