import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';

/** Styles of the Mosquées screen (src/app/mosques.tsx) and its « Ma mosquée » section. */
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#080713',
  },
  header: {
    minHeight: 96,
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#080713',
  },
  headerButton: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 23,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.18)',
    backgroundColor: '#151022',
  },
  headerCopy: {
    flex: 1,
    marginHorizontal: 13,
  },
  eyebrow: {
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 10,
    letterSpacing: 1.5,
  },
  title: {
    marginTop: 2,
    color: colors.goldLight,
    fontFamily: typography.serifMedium,
    fontSize: 34,
    lineHeight: 39,
  },
  content: {
    width: '100%',
    maxWidth: 760,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 62,
    alignSelf: 'center',
  },
  disabledButton: {
    opacity: 0.72,
  },
  privacyText: { flex: 1, color: colors.textMuted, fontFamily: typography.sans, fontSize: 11, lineHeight: 15 },
  messageCard: {
    marginTop: 14,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.30)',
    backgroundColor: colors.backgroundSecondary,
  },
  messageCopy: {
    flex: 1,
    marginHorizontal: 12,
  },
  messageTitle: {
    color: colors.text,
    fontFamily: typography.serifMedium,
    fontSize: 17,
  },
  messageText: {
    marginTop: 3,
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 12,
    lineHeight: 17,
  },
  settingsButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: colors.goldLight,
  },
  settingsButtonText: {
    color: colors.background,
    fontFamily: typography.sans,
    fontSize: 11,
    fontWeight: '700',
  },
  errorCard: {
    marginTop: 14,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.30)',
    backgroundColor: colors.backgroundSecondary,
  },
  errorText: {
    flex: 1,
    color: colors.textSecondary,
    fontFamily: typography.sans,
    fontSize: 13,
    lineHeight: 18,
  },
  myMosqueCard: {
    minHeight: 142,
    marginTop: 18,
    padding: 11,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.38)',
    backgroundColor: '#100C1B',
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  myMosqueCardFirst: {
    marginTop: 4,
  },
  nextEventCard: {
    marginTop: 10,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.3)',
    backgroundColor: '#140F21',
  },
  nextEventIcon: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: colors.goldLight,
  },
  nextEventCopy: {
    flex: 1,
    minWidth: 0,
  },
  nextEventTitle: {
    marginTop: 3,
    color: colors.text,
    fontFamily: typography.sans,
    fontSize: 14.5,
    fontWeight: '700',
  },
  nextEventDate: {
    marginTop: 2,
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 12,
  },
  favoritesBlock: {
    marginTop: 16,
  },
  favoritesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 9,
  },
  favoritesSeeAll: {
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 12,
    fontWeight: '700',
  },
  favoritesRow: {
    gap: 10,
  },
  favoriteChip: {
    width: 128,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#2B2238',
    backgroundColor: '#120D1F',
  },
  favoriteChipImage: {
    width: '100%',
    height: 70,
  },
  favoriteChipName: {
    minHeight: 40,
    paddingHorizontal: 9,
    paddingVertical: 7,
    color: colors.text,
    fontFamily: typography.sans,
    fontSize: 12,
    fontWeight: '600',
  },
  myMosqueCardActive: {
    borderColor: 'rgba(232,190,91,0.62)',
    backgroundColor: '#120D1E',
  },
  myMosqueImageWrap: {
    width: 112,
    height: 120,
    overflow: 'hidden',
    borderRadius: 19,
    backgroundColor: '#1A1324',
  },
  myMosqueImageBadge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: colors.goldLight,
  },
  myMosqueCopy: {
    flex: 1,
    minWidth: 0,
    marginHorizontal: 12,
  },
  sectionEyebrow: {
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
  },
  myMosqueTitle: {
    marginTop: 5,
    color: '#FFF8F1',
    fontFamily: typography.serifMedium,
    fontSize: 21,
    lineHeight: 24,
  },
  myMosqueText: {
    marginTop: 4,
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 11.5,
    lineHeight: 16,
  },
  nextPrayerRow: {
    marginTop: 10,
    paddingTop: 9,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(199,190,209,0.18)',
  },
  nextPrayerLabel: {
    marginLeft: 5,
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 9.5,
  },
  nextPrayerDot: {
    width: 3,
    height: 3,
    marginHorizontal: 6,
    borderRadius: 2,
    backgroundColor: colors.textMuted,
  },
  nextPrayerValue: {
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 10,
    fontWeight: '700',
  },
  searchWrap: {
    flex: 1,
    height: 54,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#2B2238',
    backgroundColor: '#151022',
  },
  addMosqueButton: {
    minHeight: 66,
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.72)',
    backgroundColor: '#151022',
    shadowColor: colors.goldLight,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  addMosqueIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: colors.goldLight,
  },
  addMosqueCopy: {
    flex: 1,
    marginHorizontal: 12,
  },
  addMosqueTitle: {
    color: colors.text,
    fontFamily: typography.sans,
    fontSize: 14.5,
    fontWeight: '700',
  },
  addMosqueSubtitle: {
    marginTop: 3,
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 12,
    fontWeight: '700',
  },
  searchFilterButton: {
    width: 39,
    height: 39,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(227,181,90,0.12)',
  },
  searchInput: {
    flex: 1,
    height: '100%',
    marginHorizontal: 10,
    color: colors.text,
    fontFamily: typography.sans,
    fontSize: 14,
  },
  sectionHeader: {
    marginTop: 28,
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  sectionHeaderCopy: {
    flex: 1,
    minWidth: 0,
    marginRight: 12,
  },
  sectionTitle: {
    color: colors.goldLight,
    fontFamily: typography.serifMedium,
    fontSize: 29,
    lineHeight: 32,
  },
  sectionSubtitle: {
    marginTop: 4,
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 12,
    lineHeight: 17,
  },
  cacheStatus: {
    marginTop: 4,
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 10,
  },
  cacheWarningCard: {
    marginTop: 14,
    padding: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.28)',
    backgroundColor: colors.backgroundSecondary,
  },
  cacheWarningText: {
    flex: 1,
    color: colors.textSecondary,
    fontFamily: typography.sans,
    fontSize: 12,
    lineHeight: 17,
  },
  modeSwitch: {
    padding: 4,
    flexDirection: 'row',
    gap: 4,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: '#2B2238',
    backgroundColor: '#151022',
  },
  modeButton: {
    minWidth: 66,
    height: 40,
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 15,
  },
  modeButtonActive: {
    backgroundColor: colors.goldLight,
  },
  modeButtonText: {
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 11.5,
    fontWeight: '600',
  },
  modeButtonTextActive: {
    color: colors.background,
  },
  mapCard: {
    height: 520,
    overflow: 'hidden',
    borderRadius: 23,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.34)',
    backgroundColor: colors.surfaceAlt,
  },
  map: {
    flex: 1,
  },
  mapOverlay: {
    position: 'absolute', top: 0, right: 0, bottom: 0, left: 0,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(16,12,25,0.94)',
  },
  mapOverlayIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 29,
    backgroundColor: 'rgba(227,181,90,0.12)',
  },
  mapOverlayTitle: {
    marginTop: 15,
    color: colors.text,
    fontFamily: typography.serifMedium,
    fontSize: 22,
    textAlign: 'center',
  },
  mapOverlayText: {
    maxWidth: 300,
    marginTop: 7,
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  mapOverlayButton: {
    minHeight: 46,
    marginTop: 16,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: colors.goldLight,
  },
  mapOverlayButtonText: {
    color: colors.background,
    fontFamily: typography.sans,
    fontSize: 13,
    fontWeight: '700',
  },
  selectedMosqueCard: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    left: 12,
    padding: 14,
    paddingRight: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.42)',
    backgroundColor: 'rgba(21,16,34,0.97)',
  },
  selectedMosqueClose: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  selectedMosqueName: {
    color: colors.text,
    fontFamily: typography.serifMedium,
    fontSize: 18,
    lineHeight: 22,
  },
  selectedMosqueAddress: {
    marginTop: 3,
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 11,
  },
  selectedMosqueMeta: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedMosqueDistance: {
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 12,
    fontWeight: '700',
  },
  selectedMosqueDot: {
    width: 3,
    height: 3,
    marginHorizontal: 7,
    borderRadius: 2,
    backgroundColor: colors.textMuted,
  },
  selectedMosqueDuration: {
    color: colors.textSecondary,
    fontFamily: typography.sans,
    fontSize: 11.5,
  },
  routeErrorText: {
    marginTop: 7,
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 10.5,
    lineHeight: 15,
  },
  selectedMosqueActions: {
    marginTop: 11,
    flexDirection: 'row',
    gap: 8,
  },
  routeButton: {
    minHeight: 42,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 14,
    backgroundColor: colors.goldLight,
  },
  routeButtonText: {
    color: colors.background,
    fontFamily: typography.sans,
    fontSize: 11.5,
    fontWeight: '700',
  },
  detailButton: {
    minHeight: 42,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.backgroundSecondary,
  },
  detailButtonText: {
    color: colors.text,
    fontFamily: typography.sans,
    fontSize: 11.5,
  },
  mapControls: {
    position: 'absolute',
    right: 12,
    bottom: 14,
    gap: 9,
  },
  mapControlsRaised: {
    bottom: 158,
  },
  mapControlButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(224,188,112,0.42)',
    backgroundColor: colors.backgroundSecondary,
  },
  mapLoading: {
    position: 'absolute',
    top: 12,
    alignSelf: 'center',
    paddingHorizontal: 13,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 15,
    backgroundColor: colors.backgroundSecondary,
  },
  mapLoadingText: {
    color: colors.text,
    fontFamily: typography.sans,
    fontSize: 11,
  },
  emptyCard: {
    minHeight: 220,
    paddingHorizontal: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceAlt,
  },
  emptyTitle: {
    marginTop: 14,
    color: colors.text,
    fontFamily: typography.serifMedium,
    fontSize: 20,
    textAlign: 'center',
  },
  emptyText: {
    maxWidth: 300,
    marginTop: 6,
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  list: {
    gap: 11,
  },
  mosqueCard: {
    minHeight: 142,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#2B2238',
    backgroundColor: '#100C1B',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 5,
  },
  mosqueImageWrap: {
    width: 112,
    height: 122,
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: '#1B1426',
  },
  mosqueImage: {
    width: '100%',
    height: '100%',
  },
  mosqueCopy: {
    flex: 1,
    minWidth: 0,
    marginHorizontal: 11,
  },
  mosqueName: {
    color: '#FFF9F3',
    fontFamily: typography.serifMedium,
    fontSize: 20,
    lineHeight: 23,
  },
  mosqueAddress: {
    marginTop: 4,
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 11.5,
    lineHeight: 16,
  },
  mosqueMetaRow: {
    marginTop: 9,
    flexDirection: 'row',
    alignItems: 'center',
  },
  mosqueDistance: {
    color: colors.goldLight,
    fontFamily: typography.sans,
    fontSize: 12,
    fontWeight: '700',
  },
  mosqueMeta: {
    color: colors.textSecondary,
    fontFamily: typography.sans,
    fontSize: 11.5,
  },
  dot: {
    width: 3,
    height: 3,
    marginHorizontal: 7,
    borderRadius: 2,
    backgroundColor: colors.textMuted,
  },
  tags: {
    marginTop: 9,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  tag: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 9,
    backgroundColor: 'rgba(224,188,112,0.08)',
  },
  tagText: {
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 10,
  },
  availableTag: {
    backgroundColor: 'rgba(90,164,105,0.13)',
  },
  availableDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#7ACA8B',
  },
  availableTagText: {
    color: '#A9D9B1',
    fontFamily: typography.sans,
    fontSize: 9.5,
  },
  mosqueActions: {
    width: 30,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 5,
  },
  mosqueFavoriteButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: 'rgba(224,188,112,0.06)',
  },
  pressed: {
    opacity: 0.7,
    transform: [{ scale: 0.99 }],
  },
  searchRow: { marginTop: 14, flexDirection: 'row', alignItems: 'center', gap: 10 },
  locateButton: {
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: colors.goldLight,
  },
  privacyRow: { marginTop: 8, paddingHorizontal: 4, flexDirection: 'row', alignItems: 'center', gap: 6 },
  locatePrompt: {
    marginTop: 14,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(227,181,90,0.30)',
    backgroundColor: '#151022',
  },
  locatePromptIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 21,
    backgroundColor: 'rgba(227,181,90,0.12)',
  },
  locatePromptCopy: { flex: 1, minWidth: 180 },
  locatePromptTitle: { color: colors.text, fontFamily: typography.serifMedium, fontSize: 18 },
  locatePromptText: { marginTop: 3, color: colors.textSecondary, fontFamily: typography.sans, fontSize: 12, lineHeight: 17 },
  locatePromptButton: {
    flexGrow: 1,
    height: 44,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: colors.goldLight,
  },
  locatePromptButtonText: { color: colors.background, fontFamily: typography.sans, fontSize: 13, fontWeight: '800' },
  illustrationLabel: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    overflow: 'hidden',
    borderRadius: 6,
    backgroundColor: 'rgba(8,7,19,0.72)',
    color: 'rgba(248,244,238,0.78)',
    fontFamily: typography.sans,
    fontSize: 9,
  },
});
