import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { NAMES, type NameEntry } from "../features/names/namesData";
import { loadNameFavorites, saveNameFavorites } from "../features/names/namesStorage";
import { colors } from "../theme/colors";
import { typography } from "../theme/typography";
const norm=(s:string)=>s.toLocaleLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
export default function NamesScreen(){const[g,setG]=useState<"all"|"male"|"female">("all");const[q,setQ]=useState("");const[f,setF]=useState<string[]>([]);const[d,setD]=useState<NameEntry|null>(null);useFocusEffect(useCallback(()=>{void loadNameFavorites().then(setF)},[]));const data=useMemo(()=>NAMES.filter(n=>(g==="all"||n.gender===g)&&(!q||norm(`${n.name} ${n.meaning}`).includes(norm(q)))),[g,q]);const toggle=(id:string)=>{const x=f.includes(id)?f.filter(i=>i!==id):[...f,id];setF(x);void saveNameFavorites(x)};const render=({item}:{item:NameEntry})=><Pressable style={s.item} onPress={()=>setD(item)}><View><Text style={s.name}>{item.name}</Text><Text style={s.arabic}>{item.arabic}</Text><Text style={s.meaning}>{item.meaning}</Text></View><Pressable onPress={()=>toggle(item.id)}><Ionicons name={f.includes(item.id)?"heart":"heart-outline"} size={23} color={colors.goldLight}/></Pressable></Pressable>;return <SafeAreaView style={s.safe}><FlatList data={data} renderItem={render} keyExtractor={x=>x.id} contentContainerStyle={s.content} ListHeaderComponent={<><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color={colors.text}/></Pressable><View><Text style={s.title}>Prénoms</Text><Text style={s.sub}>Trouvez un prénom porteur de sens.</Text></View><Pressable onPress={()=>router.push("/names/favorites")}><Ionicons name="heart-outline" size={24} color={colors.goldLight}/></Pressable></View><View style={s.hero}><Text style={s.kicker}>DÉCOUVRIR</Text><Text style={s.heroTitle}>Un prénom qui vous ressemble</Text><Text style={s.heroText}>Explorez des prénoms musulmans et arabes, avec leur sens et leur origine.</Text><Pressable style={s.inspire} onPress={()=>data.length&&setD(data[Math.floor(Math.random()*data.length)])}><Text>✦ Inspirez-moi</Text></Pressable></View><TextInput value={q} onChangeText={setQ} placeholder="Prénom ou signification" placeholderTextColor={colors.textMuted} style={s.search}/><View style={s.tabs}>{([["all","Tous"],["male","Garçons"],["female","Filles"]] as const).map(([v,l])=><Pressable key={v} onPress={()=>setG(v)} style={[s.tab,g===v&&s.active]}><Text>{l}</Text></Pressable>)}</View><Text style={s.section}>Explorer · {data.length} prénoms</Text></>} />{d&&<View style={s.overlay}><View style={s.sheet}><Pressable onPress={()=>setD(null)}><Text>Fermer</Text></Pressable><Text style={s.detail}>{d.name}</Text><Text style={s.detailArabic}>{d.arabic}</Text><Text style={s.label}>SIGNIFICATION</Text><Text style={s.detailText}>{d.meaning}</Text><Text style={s.label}>ORIGINE</Text><Text style={s.detailText}>{d.origin}</Text><Pressable style={s.favorite} onPress={()=>toggle(d.id)}><Text>{f.includes(d.id)?"♥ Retirer des favoris":"♡ Ajouter aux favoris"}</Text></Pressable></View></View>}</SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:20},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:20},title:{color:colors.text,fontFamily:typography.serifSemibold,fontSize:28},sub:{color:colors.textMuted,fontSize:12},hero:{backgroundColor:colors.surface,borderRadius:24,padding:20,marginBottom:16},kicker:{color:colors.goldLight,fontSize:10},heroTitle:{color:colors.text,fontFamily:typography.serifMedium,fontSize:22,marginTop:8},heroText:{color:colors.textSecondary,marginTop:6},inspire:{backgroundColor:colors.goldLight,padding:10,borderRadius:18,alignSelf:"flex-start",marginTop:14},search:{backgroundColor:colors.surfaceAlt,borderRadius:15,padding:14,color:colors.text},tabs:{flexDirection:"row",gap:8,marginVertical:16},tab:{padding:10,borderRadius:17,backgroundColor:colors.surface},active:{backgroundColor:colors.gold},section:{color:colors.textSecondary,fontSize:17,marginBottom:8},item:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.borderSoft},name:{color:colors.text,fontSize:19,fontFamily:typography.serifMedium},arabic:{color:colors.goldLight,fontSize:17},meaning:{color:colors.textMuted,fontSize:12},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(4,2,10,.72)",justifyContent:"flex-end"},sheet:{backgroundColor:colors.surface,padding:26,borderTopLeftRadius:28,borderTopRightRadius:28},detail:{color:colors.text,fontSize:34,textAlign:"center"},detailArabic:{color:colors.goldLight,fontSize:28,textAlign:"center"},label:{color:colors.goldLight,fontSize:10,marginTop:18},detailText:{color:colors.textSecondary,fontSize:15},favorite:{backgroundColor:colors.goldLight,padding:13,alignItems:"center",marginTop:25,borderRadius:18}});
