import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { router } from "expo-router";
import { ImageBackground, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { colors } from "../theme/colors";
import { typography } from "../theme/typography";
import { HAJJ_STEPS, UMRAH_STEPS } from "../features/pilgrimage/pilgrimageData";
export default function PilgrimageScreen(){return <LinearGradient colors={["#080611","#160D20","#080611"]} style={s.screen}><SafeAreaView><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="chevron-back" size={24} color={colors.text}/></Pressable><Text style={s.eyebrow}>GUIDE DU PÈLERIN</Text><Text style={s.title}>Hajj & ‘Umra</Text><Text style={s.arabic}>الحج والعمرة</Text><View style={s.hero}><ImageBackground source={require("../assets/images/home/shortcuts/pilgrimage-premium.png")} resizeMode="cover" style={s.heroImage}><LinearGradient colors={["rgba(8,6,17,.08)","rgba(8,6,17,.9)"]} style={s.overlay}/><View style={s.heroCopy}><Text style={s.heroTitle}>Un guide clair pour avancer avec sérénité.</Text><Text style={s.heroText}>Comprendre les rites, leurs preuves et les situations particulières.</Text></View></ImageBackground></View><Text style={s.section}>Choisir un parcours</Text><View style={s.actions}><Pressable style={s.action} onPress={()=>router.push("/pilgrimage/umrah")}><Text style={s.actionTitle}>‘Umra</Text><Text style={s.actionText}>{UMRAH_STEPS.length} étapes · guide complet</Text></Pressable><Pressable style={s.action} onPress={()=>router.push("/pilgrimage/hajj")}><Text style={s.actionTitle}>Hajj</Text><Text style={s.actionText}>{HAJJ_STEPS.length} étapes · 3 types</Text></Pressable></View><Pressable style={s.pilgrim} onPress={()=>router.push("/pilgrimage/pilgrim-mode")}><Text style={s.pilgrimTitle}>Mode Pèlerin</Text><Text style={s.actionText}>Avancer étape par étape avec des compteurs simples</Text></Pressable><View style={s.links}><Pressable onPress={()=>router.push("/pilgrimage/invocations")}><Text style={s.link}>Invocations établies</Text></Pressable><Pressable onPress={()=>router.push("/pilgrimage/problems")}><Text style={s.link}>J’ai un problème</Text></Pressable></View></ScrollView></SafeAreaView></LinearGradient>}
const s=StyleSheet.create({screen:{flex:1},content:{padding:22,paddingTop:30,paddingBottom:50},back:{width:44,height:44,borderRadius:22,borderWidth:1,borderColor:"#806233",alignItems:"center",justifyContent:"center",marginBottom:24},eyebrow:{color:colors.goldLight,fontFamily:typography.sans,fontSize:12,fontWeight:"800",letterSpacing:2},title:{color:colors.text,fontFamily:typography.serifSemibold,fontSize:34,marginTop:8},arabic:{color:colors.goldLight,fontSize:26,marginTop:6},hero:{height:310,marginTop:24,borderRadius:26,overflow:"hidden",borderWidth:1,borderColor:"#99753b"},heroImage:{flex:1},overlay:{...StyleSheet.absoluteFill},heroCopy:{position:"absolute",left:20,right:20,bottom:20},heroTitle:{color:"#FFF7E7",fontFamily:typography.serifSemibold,fontSize:25,lineHeight:31},heroText:{color:"#F0E7D9",fontFamily:typography.sans,fontSize:16,lineHeight:23,marginTop:8},section:{color:colors.text,fontFamily:typography.serifSemibold,fontSize:23,marginTop:28,marginBottom:12},actions:{flexDirection:"row",gap:10},action:{flex:1,padding:17,minHeight:120,borderRadius:20,borderWidth:1,borderColor:"#806233",backgroundColor:"#171021"},actionTitle:{color:colors.goldLight,fontFamily:typography.serifSemibold,fontSize:23},actionText:{color:"#E9DFD0",fontFamily:typography.sans,fontSize:14,lineHeight:20,marginTop:7},pilgrim:{marginTop:12,padding:18,borderRadius:20,borderWidth:1,borderColor:colors.goldLight,backgroundColor:"#25182B"},pilgrimTitle:{color:colors.text,fontFamily:typography.serifSemibold,fontSize:22},links:{gap:14,marginTop:26},link:{color:colors.goldLight,fontFamily:typography.sans,fontSize:16,fontWeight:"700"}});
