import { Ionicons } from "@expo/vector-icons";
import { router,useFocusEffect } from "expo-router";
import { useCallback,useState } from "react";
import { ActivityIndicator,Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Switch,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { archiveAdminAnnouncement,getAdminAnnouncements,saveAdminAnnouncement,type AdminAnnouncementAudience,type AdminAnnouncementRow,type AdminAnnouncementStatus } from "../../features/admin/AdminService";
import { colors } from "../../theme/colors";
import { typography } from "../../theme/typography";

const initial=()=>({title:"",body:"",audience:"all" as AdminAnnouncementAudience,status:"draft" as AdminAnnouncementStatus,actionLabel:"",actionRoute:"",startsAt:new Date().toISOString(),endsAt:"",showOnHome:true,showInNotifications:true});
export default function AdminAnnouncements(){
 const [rows,setRows]=useState<AdminAnnouncementRow[]>([]),[form,setForm]=useState(initial()),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{setRows(await getAdminAnnouncements())}catch(e){Alert.alert("Annonces",e instanceof Error?e.message:"Erreur") }finally{setLoading(false);setRefreshing(false)}},[]);
 useFocusEffect(useCallback(()=>{void load()},[load]));
 const edit=(r:AdminAnnouncementRow)=>{setEditing(r.id);setForm({title:r.title,body:r.body,audience:r.audience,status:r.status,actionLabel:r.actionLabel??"",actionRoute:r.actionRoute??"",startsAt:r.startsAt,endsAt:r.endsAt??"",showOnHome:r.showOnHome,showInNotifications:r.showInNotifications})};
 const submit=async()=>{if(form.title.trim().length<3||form.body.trim().length<5){Alert.alert("Champs incomplets","Ajoutez un titre et un message.");return}setSaving(true);try{await saveAdminAnnouncement({id:editing??undefined,title:form.title.trim(),body:form.body.trim(),audience:form.audience,status:form.status,actionLabel:form.actionLabel.trim()||null,actionRoute:form.actionRoute.trim()||null,startsAt:form.startsAt,endsAt:form.endsAt.trim()||null,showOnHome:form.showOnHome,showInNotifications:form.showInNotifications});setEditing(null);setForm(initial());await load(true);Alert.alert("Annonce enregistrée",form.status==="published"?"Elle sera visible pendant sa période de publication.":"Le brouillon est enregistré.")}catch(e){Alert.alert("Enregistrement impossible",e instanceof Error?e.message:"Erreur")}finally{setSaving(false)}};
 return <SafeAreaView style={s.safe} edges={["top"]}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.hbtn}><Ionicons name="arrow-back" size={22} color={colors.goldLight}/></Pressable><View style={{alignItems:"center"}}><Text style={s.eye}>ADMINISTRATION</Text><Text style={s.title}>Annonces OUMMAH</Text></View><Pressable onPress={()=>void load()} style={s.hbtn}><Ionicons name="refresh" size={20} color={colors.goldLight}/></Pressable></View>
 {loading?<ActivityIndicator style={{marginTop:70}} color={colors.goldLight}/>:<ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load(true)}} tintColor={colors.goldLight}/>}> 
 <Text style={s.section}>{editing?"Modifier l’annonce":"Créer une annonce"}</Text><View style={s.form}>
 <Text style={s.label}>Titre</Text><TextInput value={form.title} onChangeText={v=>setForm(x=>({...x,title:v}))} placeholder="Ex. Mise à jour OUMMAH" placeholderTextColor={colors.textMuted} style={s.input}/>
 <Text style={s.label}>Message</Text><TextInput value={form.body} onChangeText={v=>setForm(x=>({...x,body:v}))} multiline maxLength={1200} placeholder="Votre message…" placeholderTextColor={colors.textMuted} style={[s.input,s.area]}/>
 <Text style={s.label}>Public ciblé</Text><View style={s.row}>{(["all","free","premium"] as const).map(v=><Pressable key={v} onPress={()=>setForm(x=>({...x,audience:v}))} style={[s.chip,form.audience===v&&s.chipActive]}><Text style={[s.chipText,form.audience===v&&s.chipTextActive]}>{v==="all"?"Tous":v==="free"?"Gratuits":"Premium"}</Text></Pressable>)}</View>
 <Text style={s.label}>Statut</Text><View style={s.row}>{(["draft","published"] as const).map(v=><Pressable key={v} onPress={()=>setForm(x=>({...x,status:v}))} style={[s.chip,form.status===v&&s.chipActive]}><Text style={[s.chipText,form.status===v&&s.chipTextActive]}>{v==="draft"?"Brouillon":"Publié"}</Text></Pressable>)}</View>
 <Text style={s.label}>Début (ISO)</Text><TextInput value={form.startsAt} onChangeText={v=>setForm(x=>({...x,startsAt:v}))} style={s.input}/><Text style={s.label}>Fin facultative (ISO)</Text><TextInput value={form.endsAt} onChangeText={v=>setForm(x=>({...x,endsAt:v}))} placeholder="2026-08-10T20:00:00Z" placeholderTextColor={colors.textMuted} style={s.input}/>
 <Text style={s.label}>Bouton facultatif</Text><TextInput value={form.actionLabel} onChangeText={v=>setForm(x=>({...x,actionLabel:v}))} placeholder="Ex. Découvrir" placeholderTextColor={colors.textMuted} style={s.input}/><TextInput value={form.actionRoute} onChangeText={v=>setForm(x=>({...x,actionRoute:v}))} placeholder="Ex. /premium" placeholderTextColor={colors.textMuted} style={s.input}/>
 <View style={s.switchRow}><Text style={s.switchText}>Afficher sur l’accueil</Text><Switch value={form.showOnHome} onValueChange={v=>setForm(x=>({...x,showOnHome:v}))} trackColor={{true:colors.goldLight}}/></View><View style={s.switchRow}><Text style={s.switchText}>Ajouter aux notifications internes</Text><Switch value={form.showInNotifications} onValueChange={v=>setForm(x=>({...x,showInNotifications:v}))} trackColor={{true:colors.goldLight}}/></View>
 <Pressable disabled={saving} onPress={()=>void submit()} style={[s.save,saving&&{opacity:.5}]}>{saving?<ActivityIndicator color={colors.background}/>:<Ionicons name="save-outline" size={18} color={colors.background}/>}<Text style={s.saveText}>{editing?"Enregistrer les modifications":"Créer l’annonce"}</Text></Pressable>{editing?<Pressable onPress={()=>{setEditing(null);setForm(initial())}} style={s.cancel}><Text style={s.cancelText}>Annuler la modification</Text></Pressable>:null}
 </View>
 <Text style={s.section}>Annonces existantes</Text>{rows.length===0?<Text style={s.empty}>Aucune annonce.</Text>:rows.map(r=><View key={r.id} style={s.card}><View style={s.cardTop}><Text style={s.cardTitle}>{r.title}</Text><Text style={s.badge}>{r.status==="published"?"PUBLIÉE":r.status==="draft"?"BROUILLON":"ARCHIVÉE"}</Text></View><Text style={s.cardBody} numberOfLines={4}>{r.body}</Text><Text style={s.meta}>{r.audience==="all"?"Tous":r.audience==="free"?"Gratuits":"Premium"} · {new Date(r.startsAt).toLocaleString("fr-FR")}</Text><View style={s.actions}><Pressable onPress={()=>edit(r)} style={s.edit}><Text style={s.editText}>Modifier</Text></Pressable>{r.status!=="archived"?<Pressable onPress={()=>Alert.alert("Archiver",`Archiver « ${r.title} » ?`,[{text:"Annuler",style:"cancel"},{text:"Archiver",style:"destructive",onPress:async()=>{await archiveAdminAnnouncement(r.id);await load(true)}}])} style={s.archive}><Text style={s.archiveText}>Archiver</Text></Pressable>:null}</View></View>)}
 </ScrollView>}</SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{minHeight:70,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:colors.border},hbtn:{width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center",backgroundColor:colors.card},eye:{color:colors.goldMuted,fontSize:8,fontWeight:"800",letterSpacing:1.2},title:{color:colors.text,fontFamily:typography.serifSemibold,fontSize:22},content:{padding:18,paddingBottom:55},section:{marginTop:8,marginBottom:11,color:colors.goldLight,fontFamily:typography.serifMedium,fontSize:18},form:{padding:14,borderRadius:18,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},label:{marginTop:10,marginBottom:7,color:colors.textSecondary,fontSize:10.5,fontWeight:"700"},input:{minHeight:47,paddingHorizontal:13,color:colors.text,borderRadius:12,borderWidth:1,borderColor:colors.border,backgroundColor:colors.background},area:{minHeight:110,paddingTop:12,textAlignVertical:"top"},row:{flexDirection:"row",gap:7},chip:{flex:1,minHeight:40,alignItems:"center",justifyContent:"center",borderRadius:11,borderWidth:1,borderColor:colors.border},chipActive:{backgroundColor:colors.goldLight,borderColor:colors.goldLight},chipText:{color:colors.textMuted,fontSize:10,fontWeight:"800"},chipTextActive:{color:colors.background},switchRow:{minHeight:48,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},switchText:{color:colors.text,fontSize:11},save:{minHeight:50,marginTop:12,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,borderRadius:14,backgroundColor:colors.goldLight},saveText:{color:colors.background,fontWeight:"900"},cancel:{marginTop:8,minHeight:40,alignItems:"center",justifyContent:"center"},cancelText:{color:colors.textMuted,fontWeight:"700"},empty:{padding:30,textAlign:"center",color:colors.textMuted},card:{marginBottom:10,padding:14,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card},cardTop:{flexDirection:"row",alignItems:"center",gap:8},cardTitle:{flex:1,color:colors.text,fontWeight:"800"},badge:{color:colors.goldLight,fontSize:8,fontWeight:"900"},cardBody:{marginTop:7,color:colors.textSecondary,fontSize:10.5,lineHeight:15},meta:{marginTop:8,color:colors.textMuted,fontSize:8.5},actions:{marginTop:11,flexDirection:"row",gap:8},edit:{flex:1,minHeight:38,alignItems:"center",justifyContent:"center",borderRadius:10,backgroundColor:colors.goldLight},editText:{color:colors.background,fontWeight:"800"},archive:{flex:1,minHeight:38,alignItems:"center",justifyContent:"center",borderRadius:10,borderWidth:1,borderColor:"#F28B82"},archiveText:{color:"#F28B82",fontWeight:"800"}});
