import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { categoryById, chapterById, topicById } from "../../../features/fiqh/fiqhData";
import { FiqhChapterMark } from "../../../features/fiqh/components/FiqhChapterMark";
import { colors } from "../../../theme/colors";

export default function FiqhChapter() {
  const { chapterId } = useLocalSearchParams<{ chapterId: string }>();
  const chapter = chapterById.get(chapterId);
  if (!chapter) return <SafeAreaView style={s.screen}><Text style={s.text}>Chapitre introuvable.</Text></SafeAreaView>;
  const category = categoryById.get(chapter.categoryId);
  return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => router.back()}><Text style={s.back}>‹ Retour</Text></Pressable><Text style={s.breadcrumb}>{category?.title ?? chapter.categoryId} › {chapter.title}</Text><FiqhChapterMark chapterId={chapter.id} /><Text style={s.kicker}>CHAPITRE</Text><Text style={s.title}>{chapter.title}</Text><Text style={s.intro}>{chapter.description}</Text><View style={s.progressRow}><Text style={s.progress}>{chapter.topicIds.length} sujets à parcourir</Text>{chapter.categoryId !== "prayer" ? <View style={s.progressTrack}><View style={s.progressFill} /></View> : null}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rail}>{chapter.topicIds.map((id, index) => { const topic = topicById.get(id); if (!topic) return null; return <Pressable key={id} onPress={() => router.push({ pathname: "/fiqh/topic/[topicId]", params: { topicId: id, chapter: chapter.id } })} style={s.card}><View style={s.cardTop}><Text style={s.number}>{String(index + 1).padStart(2, "0")}</Text>{topic.publicationStatus === "coming_soon" || topic.publicationStatus === "blocked" ? <View style={s.soonBadge}><Ionicons name="lock-closed-outline" size={12} color={colors.goldLight} /><Text style={s.soonText}>BIENTÔT</Text></View> : <Ionicons name="chevron-forward" size={18} color={colors.goldLight} />}</View><Text style={s.cardTitle}>{topic.title}</Text><Text style={s.cardText}>{topic.publicationStatus === "coming_soon" || topic.publicationStatus === "blocked" ? "Contenu en préparation documentaire." : topic.summary}</Text></Pressable>; })}</ScrollView><Text style={s.hint}>Faites glisser pour découvrir les sujets suivants.</Text></ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: 22, paddingBottom: 60 }, back: { color: colors.goldLight, fontSize: 18, marginBottom: 16 }, breadcrumb: { color: colors.textMuted, fontSize: 13, marginBottom: 22 }, kicker: { color: colors.goldLight, fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { color: colors.text, fontSize: 34, fontWeight: "800", marginTop: 7 }, intro: { color: colors.textSecondary, fontSize: 16, lineHeight: 24, marginTop: 12 }, progress: { color: colors.textMuted, fontSize: 13 },
  progressRow: { marginTop: 12, gap: 8 },
  progressTrack: { width: 118, height: 3, borderRadius: 2, backgroundColor: colors.surfaceLight, overflow: "hidden" },
  progressFill: { width: "100%", height: 3, borderRadius: 2, backgroundColor: colors.goldLight },
  rail: { gap: 10, paddingRight: 38, marginTop: 18 }, card: { width: 245, minHeight: 170, padding: 17, borderRadius: 17, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderSoft }, cardTop: { flexDirection: "row", justifyContent: "space-between" }, number: { color: colors.goldLight, fontSize: 12, fontWeight: "800" }, soonBadge: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 7, paddingVertical: 4, borderRadius: 10, backgroundColor: "rgba(216, 181, 105, 0.08)", borderWidth: 1, borderColor: colors.goldDark }, soonText: { color: colors.goldLight, fontSize: 9, fontWeight: "800", letterSpacing: 0.7 }, cardTitle: { color: colors.text, fontSize: 20, fontWeight: "800", marginTop: 18 }, cardText: { color: colors.textSecondary, fontSize: 14, lineHeight: 21, marginTop: 6 }, hint: { color: colors.textMuted, fontSize: 12, marginTop: 12 }, text: { color: colors.text } });
