/**
 * English text of the Tahajjud module, looked up by the French text (see tx in tahajjudI18n.ts).
 * Verses: Saheeh International, as in the Quran module. Hadiths: the English text of the collections, word for word.
 * Keep the French keys exactly as written in the screens; a missing key simply shows the French text.
 */
export const TAHAJJUD_EN: Record<string, string> = {
  // ----- Verses (Saheeh International) -------------------------------------------------------------
  'Et de la nuit consacre une partie [avant l’aube] pour des prières surérogatoires afin que ton Seigneur te ressuscite en une position de gloire.':
    'And from [part of] the night, pray with it [i.e., recitation of the Qur’ān] as additional [worship] for you; it is expected that your Lord will resurrect you to a praised station.',
  'Ils s’arrachent de leurs lits pour invoquer leur Seigneur, par crainte et espoir.':
    'Their sides part [i.e., they arise] from [their] beds; they supplicate their Lord in fear and aspiration.',
  'Ils dormaient peu, la nuit, et aux dernières heures de la nuit ils imploraient le pardon [d’Allah].':
    'They used to sleep but little of the night, and in the hours before dawn they would ask forgiveness.',
  'Ceux qui passent les nuits prosternés et debout devant leur Seigneur.':
    'Those who spend [part of] the night to their Lord prostrating and standing [in prayer].',
  '« La nuit d’Al-Qadr est meilleure que mille mois. » (97:3)': '“The Night of Decree is better than a thousand months.” (97:3)',
  '« Lève-toi [pour prier], toute la nuit, excepté une petite partie » (73:2).': '“Arise [to pray] the night, except for a little” (73:2).',
  'Allah décrit les pieux : « et aux dernières heures de la nuit ils imploraient le pardon [d’Allah] ».':
    'Allah describes the righteous: “And in the hours before dawn they would ask forgiveness”.',
  'Sourate Al-Isra, 17:79': 'Surah Al-Isra, 17:79',
  'Sourate As-Sajda, 32:16': 'Surah As-Sajda, 32:16',
  'Sourate Adh-Dhariyat, 51:17-18': 'Surah Adh-Dhariyat, 51:17-18',
  'Sourate Al-Furqan, 25:64': 'Surah Al-Furqan, 25:64',
  'Le verset de Tahajjud (17:79).': 'The verse of Tahajjud (17:79).',

  // ----- Hadiths (English text of the collections) -------------------------------------------------
  'Notre Seigneur, le Béni, le Suprême, descend chaque nuit au ciel le plus proche de nous quand il ne reste qu’un tiers de la nuit, et Il dit : « Y a-t-il quelqu’un qui M’invoque pour que Je lui réponde ? Y a-t-il quelqu’un qui Me demande pour que Je lui accorde sa demande ? Y a-t-il quelqu’un qui cherche Mon pardon pour que Je lui pardonne ? »':
    'Our Lord, the Blessed, the Superior, comes every night down on the nearest Heaven to us when the last third of the night remains, saying: “Is there anyone to invoke Me, so that I may respond to invocation? Is there anyone to ask Me, so that I may grant him his request? Is there anyone seeking My forgiveness, so that I may forgive him?”',
  'La meilleure prière après les prières obligatoires est la prière de nuit.': 'The most excellent prayer after what is prescribed is prayer during the night.',
  'L’action la plus aimée d’Allah est celle qui est faite régulièrement, même si elle est petite.':
    'The most beloved deed to Allah is the most regular and constant even if it were little.',
  'Louange à Allah qui nous a rendu la vie après nous avoir fait mourir, et c’est vers Lui que se fera la résurrection.':
    'All the Praises are for Allah Who has made us alive after He made us die (sleep) and unto Him is the Resurrection.',
  'Al-Bukhari 6312': 'Al-Bukhari 6312, 6324',
  'Celui qui se réveille la nuit et dit ces paroles puis « Ô Allah, pardonne-moi », ou invoque, est exaucé ; et s’il fait ses ablutions et prie, sa prière est acceptée.':
    'Whoever gets up at night and says these words, and then says: Allahumma, Ighfir li (O Allah! Forgive me). Or invokes (Allah), he will be responded to and if he performs ablution (and prays), his prayer will be accepted.',
  'Ô Allah, guide-moi parmi ceux que Tu as guidés, préserve-moi parmi ceux que Tu as préservés, prends-moi sous Ta protection parmi ceux que Tu as pris sous Ta protection, bénis pour moi ce que Tu m’as donné, protège-moi du mal de ce que Tu as décrété… Béni sois-Tu, notre Seigneur, et exalté. (Qunut du Witr)':
    'O Allah, guide me among those Thou hast guided, grant me security among those Thou hast granted security, take me into Thy charge among those Thou hast taken into Thy charge, bless me in what Thou hast given, guard me from the evil of what Thou hast decreed… Blessed and Exalted art Thou, our Lord. (Qunut of the Witr)',
  'Gloire au Roi, le Très-Saint. — trois fois, après le Witr.': 'Glory be to the Sovereign, the Most Holy. — three times, after the Witr.',
  'Satan fait trois nœuds à l’arrière de la tête de l’un de vous lorsqu’il dort. […] Quand on se réveille et qu’on se souvient d’Allah, un nœud se défait ; quand on fait les ablutions, un deuxième nœud se défait ; et quand on prie, le troisième nœud se défait.':
    'Satan puts three knots at the back of the head of any of you if he is asleep. […] When one wakes up and remembers Allah, one knot is undone; and when one performs ablution, the second knot is undone, and when one prays the third knot is undone.',
  'Lorsque l’un d’entre vous se lève la nuit, qu’il commence la prière par deux courtes unités de prière (rak‘a).':
    'When any one of you gets up at night, he should begin the prayer with two short rak‘ahs.',
  'Le Messager d’Allah (ﷺ) ne dépassait jamais onze unités de prière, que ce soit pendant le Ramadan ou en dehors.':
    'Allah’s Messenger (ﷺ) never exceeded eleven rak‘at in Ramadan or in other months.',
  '‘Aïcha · Al-Bukhari 1147, Muslim 738': '‘Aishah · Al-Bukhari 1147, Muslim 738',
  'Faites du witr votre dernière prière de la nuit.': 'Make witr as your last prayer at night.',
  'Celui qui va se coucher avec l’intention de se lever pour prier la nuit, puis le sommeil l’emporte jusqu’au matin, aura la récompense de ce qu’il avait l’intention de faire, et son sommeil sera une aumône que son Seigneur, le Tout-Puissant et Majestueux, lui a accordée.':
    'Whoever goes to his bed intending to get up and pray qiyam at night, then sleep overwhelms him until morning, will have recorded that which he intended and his sleep is a charity given to him by his Lord, the Mighty and Sublime.',
  '‘Aïcha rapporte que lorsqu’il manquait sa prière de nuit à cause d’une douleur ou d’autre chose, il priait douze rak‘at dans la journée.':
    '‘Aishah reported that when sleep or pain overpowered him and made it impossible (for him) to observe prayer in the night, he prayed twelve rak‘ahs during the day.',
  'Ô Allah, Tu es Celui qui pardonne, Tu aimes le pardon, alors pardonne-moi. — enseignée par le Prophète ﷺ à ‘Aïcha pour la nuit d’al-Qadr.':
    'O Allah, indeed You are Pardoning, You love pardon, so pardon me. — taught by the Prophet ﷺ to ‘Aishah for the Night of Al-Qadr.',
  'Cherchez la nuit du Qadr dans les nuits impaires des dix derniers jours de Ramadan.':
    'Search for the Night of Qadr in the odd nights of the last ten days of Ramadan.',
  '« Cherchez la nuit du Qadr dans les nuits impaires des dix derniers jours de Ramadan. » Demain soir est une nuit impaire.':
    '“Search for the Night of Qadr in the odd nights of the last ten days of Ramadan.” Tomorrow evening is an odd night.',
  'Celui qui prie pendant la nuit du destin avec une foi sincère et dans l’espoir d’une récompense d’Allah, tous ses péchés passés seront pardonnés.':
    'Whoever established prayers on the night of Qadr out of sincere faith and hoping for a reward from Allah, then all his previous sins will be forgiven.',
  'Le Prophète ﷺ a dit : « Chaque fois que tu vas te coucher, fais les ablutions comme pour la prière, allonge-toi sur le côté droit… » (Al-Bukhari 247). Préparez ici les invocations que vous voulez faire.':
    'The Prophet ﷺ said: “Whenever you go to bed perform ablution like that for the prayer, lie on your right side…” (Al-Bukhari 247). Prepare here the supplications you want to make.',
  'Le Prophète ﷺ nettoyait ses dents avec le siwak lorsqu’il se levait la nuit (Al-Bukhari 245, Muslim 255).':
    'Whenever the Prophet ﷺ got up at night, he used to clean his mouth with Siwak (Al-Bukhari 245, Muslim 255).',
  'Le serviteur est au plus près de son Seigneur quand il est prosterné : multipliez-y les invocations (Muslim 482).':
    'The nearest a servant comes to his Lord is when he is prostrating himself, so make supplication in this state (Muslim 482).',
  'Le Prophète ﷺ ne dormait pas avant de l’avoir lue (At-Tirmidhi 3404).': 'The Prophet ﷺ would not sleep until he had recited it (At-Tirmidhi 3404).',
  'Le Prophète ﷺ ne dormait pas avant de l’avoir lue, avec Al-Mulk (At-Tirmidhi 3404).':
    'The Prophet ﷺ would not sleep until he had recited it, along with Al-Mulk (At-Tirmidhi 3404).',
  'Récitée par le Prophète ﷺ en se réveillant la nuit (Al-Bukhari 4569).': 'Recited by the Prophet ﷺ when he got up at night (Al-Bukhari 4569).',
  'Ces deux versets suffisent à celui qui les récite la nuit (Al-Bukhari 5009, Muslim 807).':
    'These two verses are sufficient for whoever recites them at night (Al-Bukhari 5009, Muslim 807).',
  'Le Prophète ﷺ ne dormait pas sans la réciter': 'The Prophet ﷺ would not sleep without reciting it',
  'L’évocation d’Allah défait l’un des nœuds du Shaytan (Al-Bukhari 1142).': 'Remembering Allah undoes one of Satan’s knots (Al-Bukhari 1142).',
  'Le Shaytan noue trois nœuds sur la nuque du dormeur ; l’évocation d’Allah, les ablutions et la prière les défont un à un.':
    'Satan ties three knots at the back of the sleeper’s head; remembering Allah, ablution and prayer undo them one by one.',
  'C’est la meilleure prière après les prières obligatoires.': 'It is the best prayer after the obligatory prayers.',
  'C’est la prière surérogatoire de la nuit, mentionnée par le Coran. Le Prophète ﷺ priait la nuit entre ‘Isha et Fajr.':
    'It is the voluntary prayer of the night, mentioned in the Quran. The Prophet ﷺ prayed at night between ‘Isha and Fajr.',
  'La prière de la nuit se fait deux par deux. Le Prophète ﷺ ne dépassait pas onze rak‘at, Witr compris.':
    'The night prayer is prayed two by two. The Prophet ﷺ did not exceed eleven rak‘at, Witr included.',
  'Le Prophète ﷺ, lorsqu’il manquait sa prière de nuit à cause d’une douleur ou d’autre chose, priait douze rak‘at dans la journée.':
    'When the Prophet ﷺ missed his night prayer because of pain or something else, he prayed twelve rak‘at during the day.',
  'Le Witr clôt la prière de la nuit. Après, dites trois fois « Subhana al-Malik al-Quddus ».':
    'The Witr closes the night prayer. Afterwards, say three times “Subhana al-Malik al-Quddus”.',
  'Celui qui se couche avec l’intention de prier la nuit et que le sommeil l’emporte a la récompense de son intention.':
    'Whoever goes to bed intending to pray at night and is overcome by sleep has the reward of his intention.',
  'Une prière volontaire, la nuit. Le dernier tiers de la nuit est le moment où Allah descend au ciel le plus proche.':
    'A voluntary prayer, at night. The last third of the night is when Allah descends to the nearest heaven.',
  'La nuit va du coucher du soleil (Maghrib) à l’aube (Fajr). On la divise en trois : le dernier tiers est le moment où Allah descend au ciel de ce bas monde. OUMMAH le calcule chaque jour à partir de vos horaires.':
    'The night runs from sunset (Maghrib) to dawn (Fajr). It is divided into three: the last third is when Allah descends to the lowest heaven. OUMMAH calculates it every day from your prayer times.',
  'Ouvrez votre prière par deux unités courtes, puis priez deux par deux.': 'Open your prayer with two short rak‘at, then pray two by two.',
  'Au réveil, évoquez Allah avec l’invocation du réveil.': 'When you wake up, remember Allah with the waking supplication.',
  'Ce que rapportent les textes pour la nuit.': 'What the texts report about the night.',

  // ----- Guide --------------------------------------------------------------------------------------
  'Comprendre': 'Understand',
  'Qu’est-ce que Tahajjud ?': 'What is Tahajjud?',
  'Le dernier tiers de la nuit': 'The last third of the night',
  'Sa valeur': 'Its value',
  'Peu, mais régulier': 'Little, but regular',
  'Comment prier': 'How to pray',
  'Six étapes simples, du réveil au Witr.': 'Six simple steps, from waking up to Witr.',
  '1. Se réveiller': '1. Wake up',
  '2. Faire ses ablutions': '2. Make wudu',
  '3. Commencer par deux rak‘at légères': '3. Start with two light rak‘at',
  '4. Combien de rak‘at ?': '4. How many rak‘at?',
  '5. Prolonger la récitation et les prosternations': '5. Lengthen the recitation and the prostrations',
  '6. Terminer par le Witr': '6. End with the Witr',
  'Conseils': 'Tips',
  'Préparer ma nuit': 'Prepare my night',
  'Préparer mes duas': 'Prepare my duas',
  'L’intention compte déjà': 'The intention already counts',
  'Une nuit manquée ?': 'Missed a night?',
  'Le pardon avant l’aube': 'Forgiveness before dawn',
  'Ouvrir les duas': 'Open the duas',
  'Après la prière': 'After the prayer',
  'Ouvrir le dhikr': 'Open the dhikr',
  'Apprendre le Qiyam': 'Learn Qiyam',
  'Guide': 'Guide',

  // ----- Readings and recitation ---------------------------------------------------------------------
  'Sourate 67': 'Surah 67',
  'Sourate 32': 'Surah 32',
  'Sourate 73': 'Surah 73',
  'Fin d’Al ‘Imran': 'End of Al ‘Imran',
  'Fin d’Al-Baqara': 'End of Al-Baqara',
  'Des passages liés à la nuit, ou la sourate de votre choix.': 'Passages about the night, or the surah of your choice.',
  'Sourates courtes classées par longueur, en grand, avec phonétique.': 'Short surahs sorted by length, in large print, with phonetics.',
  'Choisir une autre sourate': 'Choose another surah',
  'Lire quelques versets': 'Read a few verses',
  'Sourate': 'Surah',
  '{0} · {1} versets': '{0} · {1} verses',
  'Texte plus petit': 'Smaller text',
  'Texte plus grand': 'Larger text',
  'Phonétique': 'Phonetics',
  'Traduction': 'Translation',
  'Cette sourate n’est pas encore enregistrée sur le téléphone. Connectez-vous une fois à Internet pour la garder hors connexion.':
    'This surah is not saved on the phone yet. Connect to the internet once to keep it offline.',
  'Traduction du sens : Hamidullah · Phonétique indicative, à vérifier avec un enseignant.':
    'Translation of the meaning: Saheeh International · Phonetics are indicative, check them with a teacher.',
  'Que réciter ?': 'What to recite?',
  'Dans ma prière': 'In my prayer',
  'Après Al-Fatiha, récitez ce que vous connaissez, même une courte sourate. Marquez celles que vous connaissez avec l’étoile pour les retrouver la nuit.':
    'After Al-Fatiha, recite what you know, even a short surah. Mark the ones you know with the star to find them at night.',
  'Toutes': 'All',
  'Je les connais · {0}': 'I know them · {0}',
  'Touchez l’étoile d’une sourate pour l’ajouter ici.': 'Tap a surah’s star to add it here.',
  'Je ne la connais pas': 'I don’t know it',
  'Je la connais': 'I know it',
  'Texte et traduction : le Coran d’OUMMAH. Les sourates courtes restent disponibles hors connexion.':
    'Text and translation: the OUMMAH Quran. Short surahs stay available offline.',
  'À chaque rak‘a': 'In every rak‘a',
  'Al-Fatiha est récitée dans chaque unité de prière.': 'Al-Fatiha is recited in every rak‘a.',
  'Très courtes': 'Very short',
  'Moins de 7 versets : idéales pour commencer.': 'Fewer than 7 verses: ideal to start with.',
  'Courtes': 'Short',
  'De 7 à 11 versets.': '7 to 11 verses.',
  'Moyennes': 'Medium',
  'De 12 à 30 versets : pour prolonger la station debout.': '12 to 30 verses: to lengthen the standing.',
  'Pour aller plus loin': 'To go further',
  'Plus de 30 versets.': 'More than 30 verses.',

  // ----- Home of the module ---------------------------------------------------------------------------
  'Nuit du {0} au {1} {2}': 'Night of {0} to {1} {2}',
  'Dhikr, Coran, duas…': 'Dhikr, Quran, duas…',
  'J’ai prié': 'I prayed',
  'Nuit enregistrée': 'Night saved',
  'Valider ma nuit': 'Log my night',
  'Statistiques': 'Statistics',
  'Calendrier · défis': 'Calendar · challenges',
  'Dire Amine': 'Say Ameen',
  '{0} message non lu': '{0} unread message',
  '{0} messages non lus': '{0} unread messages',
  'Messages · encourager': 'Messages · encourage',
  'NUIT ACCOMPLIE': 'NIGHT COMPLETED',
  '{0} nuits de suite': '{0} nights in a row',
  'Qu’Allah l’accepte': 'May Allah accept it',
  'Qu’Allah l’accepte.': 'May Allah accept it.',
  'DERNIER TIERS EN COURS': 'LAST THIRD UNDER WAY',
  'restantes · Fajr à': 'left · Fajr at',
  'PROCHAIN DERNIER TIERS': 'NEXT LAST THIRD',
  'DERNIER TIERS DE LA NUIT': 'LAST THIRD OF THE NIGHT',
  'jusqu’à {0} · ce soir après ‘Isha': 'until {0} · tonight after ‘Isha',
  'commence dans {0}': 'starts in {0}',
  'Cette nuit': 'Tonight',
  'Un rendez-vous privilégié avec votre Seigneur': 'A special meeting with your Lord',
  'Autorisez la localisation (ou choisissez votre mosquée) pour calculer le dernier tiers.':
    'Allow location (or choose your mosque) to calculate the last third.',
  'Les horaires sont momentanément indisponibles.': 'Prayer times are temporarily unavailable.',
  'Réessayer': 'Try again',
  'Je suis debout': 'I am up',
  'J’ai déjà prié cette nuit': 'I already prayed tonight',
  'Réveil réglé · {0}': 'Alarm set · {0}',
  'Régler mon réveil': 'Set my alarm',
  'Prier maintenant · mode guidé': 'Pray now · guided mode',
  'J’ai prié cette nuit ? Enregistrez-la jusqu’à Dhuhr.': 'Prayed tonight? Log it until Dhuhr.',
  'Vous ne priez pas seul': 'You are not praying alone',
  '{0} membre réveillé · voir la carte': '{0} member awake · see the map',
  '{0} membres réveillés · voir la carte': '{0} members awake · see the map',
  'Mes 7 dernières nuits': 'My last 7 nights',
  'Programme de la nuit': 'Night programme',
  'Chaque action compte automatiquement dans vos objectifs du jour.': 'Each action counts automatically towards your daily goals.',
  'Objectif du jour atteint': 'Daily goal reached',
  'Objectif : {0}/{1}{2}': 'Goal: {0}/{1}{2}',
  'Dhikr de la nuit': 'Night dhikr',
  'SubhanAllah, Alhamdulillah, Allahu akbar…': 'SubhanAllah, Alhamdulillah, Allahu akbar…',
  'Sourate Al-Mulk': 'Surah Al-Mulk',
  'Écouter le Coran': 'Listen to the Quran',
  'Laisser la récitation apaiser la nuit': 'Let the recitation calm the night',
  'Lire un hadith': 'Read a hadith',
  'Le hadith du jour, en une minute': 'The hadith of the day, in one minute',
  'Histoire d’un prophète': 'Story of a prophet',
  'Lire ou écouter un chapitre': 'Read or listen to a chapter',
  'Une dua': 'A dua',
  'Les invocations du Coran et de la Sunna': 'Supplications from the Quran and the Sunnah',
  'Dernier tiers en cours': 'Last third under way',
  'Dernier tiers à {0}': 'Last third at {0}',
  'encore {0} · Fajr à {1}': '{0} left · Fajr at {1}',
  'dans {0} · Fajr à {1}': 'in {0} · Fajr at {1}',
  'Ouvrir Qiyam al-Layl': 'Open Qiyam al-Layl',
  'QIYAM AL-LAYL': 'QIYAM AL-LAYL',
  'C’EST LE MOMENT': 'IT IS TIME',
  'CETTE NUIT': 'TONIGHT',
  'Réveil {0}': 'Alarm {0}',
  'Vous aviez l’intention de vous lever': 'You intended to get up',
  'Le sommeil l’a emporté ? Votre intention compte déjà. Ce soir est une nouvelle nuit.':
    'Sleep won? Your intention already counts. Tonight is a new night.',
  'Intention posée pour cette nuit. Qu’Allah vous facilite.': 'Intention set for tonight. May Allah make it easy for you.',
  'Ce soir, j’ai l’intention de me lever': 'Tonight, I intend to get up',
  'Jusqu’à ‘Isha (': 'Until ‘Isha (',
  '). Même si le sommeil l’emporte, l’intention est déjà récompensée.': '). Even if sleep wins, the intention is already rewarded.',
  'RAMADAN ·': 'RAMADAN ·',
  'Nuit impaire : peut-être Laylat al-Qadr': 'Odd night: perhaps Laylat al-Qadr',
  'Les dix dernières nuits': 'The last ten nights',
  'Le mois des nuits debout': 'The month of standing at night',
  'Encore': 'Still',
  'avant les dix dernières. Prier la nuit avec le suhoor, c’est une seule montée.':
    'before the last ten. Praying at night with suhoor is a single climb.',
  'Suhoor jusqu’à Fajr,': 'Suhoor until Fajr,',
  '{0}/10 nuits priées · les nuits impaires sont en or': '{0}/10 nights prayed · odd nights are in gold',

  // ----- Alarm ---------------------------------------------------------------------------------------
  'Heure du coucher': 'Bedtime',
  'Selon le nombre de cycles de sommeil choisi ci-dessus': 'Based on the number of sleep cycles chosen above',
  'Rappel du soir': 'Evening reminder',
  '45 min après ‘Isha, pour formuler l’intention': '45 min after ‘Isha, to make the intention',
  'Le dernier tiers commence bientôt': 'The last third starts soon',
  '15 minutes avant': '15 minutes before',
  'Le dernier tiers commence maintenant': 'The last third starts now',
  'Au début exact du dernier tiers': 'At the exact start of the last third',
  'Fajr approche': 'Fajr is near',
  '30 minutes avant Fajr, pour le Witr': '30 minutes before Fajr, for the Witr',
  'Notifications désactivées': 'Notifications turned off',
  'Autorisez les notifications d’OUMMAH pour être réveillé.': 'Allow OUMMAH notifications to be woken up.',
  'Plus tard': 'Later',
  'Réglages': 'Settings',
  'Mon réveil': 'My alarm',
  'Réveil du téléphone': 'Phone alarm',
  'Impossible d’ouvrir l’application Horloge sur ce téléphone.': 'Unable to open the Clock app on this phone.',
  'Me réveiller pour prier la nuit': 'Wake me up to pray at night',
  'Chaque nuit, recalculé selon vos horaires.': 'Every night, recalculated from your prayer times.',
  'cette nuit': 'tonight',
  'désactivé': 'off',
  'Quand me réveiller': 'When to wake me up',
  'Ma nuit': 'My night',
  'pour prier, du réveil à Fajr (': 'to pray, from waking up to Fajr (',
  'Après une prière d’environ 30 min,': 'After a prayer of about 30 min,',
  'pour vous recoucher avant Fajr': 'to go back to bed before Fajr',
  'Se coucher à': 'Go to bed at',
  'Cycles de sommeil complets (≈ 1 h 30) : on se réveille plus facilement. Touchez un horaire pour être prévenu chaque soir.':
    'Full sleep cycles (≈ 1 h 30): waking up is easier. Tap a time to be reminded every evening.',
  'de sommeil': 'of sleep',
  'Ajouter au réveil du téléphone': 'Add to the phone alarm',
  'Une vraie sonnerie à': 'A real alarm at',
  ', même en mode silencieux.': ', even in silent mode.',
  'Sur iPhone, OUMMAH vous réveille par une notification : gardez le son activé, ou ajoutez aussi une alarme dans l’app Horloge.':
    'On iPhone, OUMMAH wakes you up with a notification: keep the sound on, or also add an alarm in the Clock app.',
  'Notifications': 'Notifications',
  'Tout peut être désactivé à tout moment. Une nuit enregistrée ne reçoit plus de rappel.':
    'Everything can be turned off at any time. A logged night gets no more reminders.',
  'Début du dernier tiers': 'Start of the last third',
  '30 minutes après le début': '30 minutes after the start',
  '1 heure après le début': '1 hour after the start',
  '30 minutes avant Fajr': '30 minutes before Fajr',
  'Heure personnalisée': 'Custom time',

  // ----- Guided prayer (awake) -----------------------------------------------------------------------
  'Réveil': 'Waking up',
  'Ablutions': 'Wudu',
  'Intention': 'Intention',
  'Prière': 'Prayer',
  'Invocations': 'Supplications',
  'Fin': 'End',
  'Bismillah, vous êtes debout.': 'Bismillah, you are up.',
  'Passez la main sur le visage pour chasser le sommeil, puis dites :': 'Wipe your hand over your face to drive sleep away, then say:',
  'Les ablutions': 'Wudu',
  'Le sommeil annule les ablutions : faites un wudu complet, calmement, à l’eau fraîche pour vous réveiller.':
    'Sleep breaks wudu: make a complete wudu, calmly, with cool water to wake yourself up.',
  'L’intention': 'The intention',
  'Dans votre cœur : prier la prière de la nuit, pour Allah seul. Nul besoin de la prononcer. Mettez votre téléphone de côté, cet écran restera allumé.':
    'In your heart: to pray the night prayer, for Allah alone. No need to say it aloud. Put your phone aside, this screen will stay on.',
  'Priez deux par deux': 'Pray two by two',
  'Commencez par deux rak‘at légères, puis à votre rythme. Touchez le bouton après chaque salam.':
    'Start with two light rak‘at, then at your own pace. Tap the button after each salam.',
  'Retirer deux rak‘at': 'Remove two rak‘at',
  'Ajouter deux rak‘at': 'Add two rak‘at',
  'rak‘at · touchez + 2': 'rak‘at · tap + 2',
  'Que réciter dans ma prière ?': 'What to recite in my prayer?',
  'Le moment des invocations': 'Time for supplications',
  'Dans la prosternation ou après la prière, demandez à Allah ce dont vous avez besoin, dans votre langue.':
    'In prostration or after the prayer, ask Allah for what you need, in your own language.',
  'Ce que vous avez préparé pour cette nuit': 'What you prepared for tonight',
  'Préparer mes duas de la nuit': 'Prepare my night duas',
  'Terminer par le Witr': 'End with the Witr',
  'Une ou trois rak‘at pour clore la prière de la nuit. Vous pouvez aussi le garder pour avant Fajr.':
    'One or three rak‘at to close the night prayer. You can also keep it for before Fajr.',
  'rak‘a': 'rak‘a',
  'Votre nuit est enregistrée. Reposez-vous jusqu’à Fajr': 'Your night is logged. Rest until Fajr',
  'Terminer': 'Finish',
  'Al-hamdu lillah.': 'Al-hamdu lillah.',
  '{0} rak‘at': '{0} rak‘at',
  'Votre prière': 'Your prayer',
  'et {0} de Witr': 'and {0} of Witr',
  '. Enregistrez votre nuit pour votre régularité.': '. Log your night to keep track of your regularity.',
  'Nuit déjà enregistrée': 'Night already logged',
  'J’ai prié cette nuit': 'I prayed tonight',
  'Fermer': 'Close',
  'Fajr dans': 'Fajr in',
  'Suivant': 'Next',
  'Nuit accomplie': 'Night completed',
  'Qu’Allah accepte votre prière et exauce vos invocations.': 'May Allah accept your prayer and answer your supplications.',
  'nuits de suite': 'nights in a row',
  'Une seule validation par nuit. Elle reste sur ce téléphone et nourrit votre suivi.':
    'One log per night. It stays on this phone and feeds your tracking.',
  'J’ai aussi prié le Witr': 'I also prayed the Witr',
  'Facultatif': 'Optional',
  'Enregistrer ma nuit': 'Log my night',

  // ----- Statistics ------------------------------------------------------------------------------------
  'Semaine': 'Week',
  'Mois': 'Month',
  'Année': 'Year',
  '7 nuits': '7 nights',
  'Une semaine pour prendre le rythme': 'A week to get into the rhythm',
  '10 nuits': '10 nights',
  'Comme les dix dernières nuits': 'Like the last ten nights',
  '30 nuits': '30 nights',
  'Un mois avec la nuit': 'A month with the night',
  '40 nuits': '40 nights',
  'Ancrer l’habitude': 'Anchor the habit',
  'Ramadan': 'Ramadan',
  'Les 30 nuits du mois béni': 'The 30 nights of the blessed month',
  'Mes statistiques': 'My statistics',
  'régularité': 'regularity',
  'cette semaine': 'this week',
  'ce mois-ci': 'this month',
  'cette année': 'this year',
  'série actuelle': 'current streak',
  'meilleure série': 'best streak',
  'nuits au total': 'nights in total',
  'Calendrier': 'Calendar',
  'Nuit priée': 'Night prayed',
  'En pause': 'Paused',
  'Mettre ma série en pause': 'Pause my streak',
  'Règles, maladie, voyage : ces nuits ne cassent pas la série.': 'Period, illness, travel: these nights don’t break the streak.',
  'Mon défi': 'My challenge',
  'Défi accompli': 'Challenge completed',
  'Qu’Allah fasse de cette habitude une constance.': 'May Allah make this habit a lasting one.',
  '{0} nuit pour y arriver. Les nuits n’ont pas besoin d’être consécutives.': '{0} night to go. The nights don’t need to be consecutive.',
  '{0} nuits pour y arriver. Les nuits n’ont pas besoin d’être consécutives.': '{0} nights to go. The nights don’t need to be consecutive.',
  'Choisir un nouveau défi': 'Choose a new challenge',
  'Arrêter ce défi': 'Stop this challenge',
  'Mon défi personnalisé': 'My custom challenge',
  'Nombre de nuits': 'Number of nights',
  '{0} nuits': '{0} nights',
  'Commencer': 'Start',
  'Un défi personnel, entre vous et Allah : aucun classement, aucune comparaison.':
    'A personal challenge, between you and Allah: no ranking, no comparison.',

  // ----- Duas of the night -------------------------------------------------------------------------------
  'Pour cette nuit': 'For tonight',
  'Journal': 'Journal',
  'Mes duas de la nuit': 'My night duas',
  'Cette nuit, je demande à Allah…': 'Tonight, I ask Allah…',
  'La guérison de ma mère, un travail, le pardon…': 'My mother’s healing, a job, forgiveness…',
  'invoquée': 'made',
  'Gardée pour les prochaines nuits': 'Kept for the next nights',
  'Garder pour les prochaines nuits': 'Keep for the next nights',
  'Invocations de la nuit': 'Night supplications',
  'Toutes les duas d’OUMMAH': 'All OUMMAH duas',
  'Cette nuit, je souhaite invoquer Allah pour…': 'Tonight, I want to ask Allah for…',
  'Mon intention pour cette nuit': 'My intention for tonight',
  'Mes notes': 'My notes',
  'Ce que j’ai ressenti, ce que je retiens…': 'What I felt, what I take away…',
  'Jamais publié. Enregistré automatiquement sur ce téléphone.': 'Never published. Saved automatically on this phone.',
  'Mes nuits précédentes': 'My previous nights',

  // ----- Community ----------------------------------------------------------------------------------------
  'Une dua partagée ici': 'One dua shared here',
  '{0} duas partagées ici': '{0} duas shared here',
  'Zone d’environ 30 km · 14 derniers jours': 'Area of about 30 km · last 14 days',
  'Exaucée': 'Answered',
  'réponse': 'reply',
  'Lire et répondre': 'Read and reply',
  'La Oummah cette nuit': 'The Ummah tonight',
  'Communauté': 'Community',
  'Vous ne priez pas seul : la Oummah est éveillée.': 'You are not praying alone: the Ummah is awake.',
  'EN DIRECT · 12 DERNIÈRES HEURES': 'LIVE · LAST 12 HOURS',
  'réveillé': 'awake',
  'pour prier la nuit': 'to pray at night',
  'prié': 'prayed',
  'Membres réveillés (3 min. par zone)': 'Members awake (3 min. per area)',
  'Duas partagées · touchez pour lire': 'Shared duas · tap to read',
  'Et vous ?': 'And you?',
  'Connectez-vous pour être compté avec la Oummah.': 'Sign in to be counted with the Ummah.',
  'Se connecter': 'Sign in',
  'Un pseudo suffit pour rejoindre la communauté. Tout reste volontaire.': 'A username is enough to join the community. Everything stays optional.',
  'Créer mon profil OUMMAH': 'Create my OUMMAH profile',
  'Revenez cette nuit, après ‘Isha': 'Come back tonight, after ‘Isha',
  '(dernier tiers vers {0})': '(last third around {0})',
  'Votre nuit est comptée : vous avez prié.': 'Your night is counted: you prayed.',
  'Vous êtes compté parmi les réveillés.': 'You are counted among those awake.',
  'Me retirer pour cette nuit': 'Remove me for tonight',
  'Je suis réveillé pour prier': 'I am awake to pray',
  'Vous avez choisi de ne pas apparaître. Modifiable dans votre profil.': 'You chose not to appear. You can change this in your profile.',
  'Mes amis cette nuit': 'My friends tonight',
  '{0} ami éveillé': '{0} friend awake',
  '{0} amis éveillés': '{0} friends awake',
  ', dont {0} a prié': ', {0} of whom prayed',
  ', dont {0} ont prié': ', {0} of whom prayed',
  'Voir et encourager vos amis, selon leurs réglages.': 'See and encourage your friends, according to their settings.',
  '· confidentialité': '· privacy',
  'Uniquement de vraies déclarations OUMMAH. Aucune position précise n’est envoyée ni affichée.':
    'Only real OUMMAH declarations. No precise location is sent or shown.',

  // ----- Dua wall --------------------------------------------------------------------------------------------
  'Amine 🤲': 'Ameen 🤲',
  'Qu’Allah t’exauce': 'May Allah answer you',
  'Je fais dua pour toi': 'I am making dua for you',
  'Qu’Allah te facilite': 'May Allah make it easy for you',
  'Amine': 'Ameen',
  'Créez votre profil OUMMAH pour dire Amine.': 'Create your OUMMAH profile to say Ameen.',
  'Réponse': 'Reply',
  'Signaler': 'Report',
  'La réponse a été signalée.': 'The reply has been reported.',
  'Dua': 'Dua',
  'La dua a été signalée. Elle sera masquée si plusieurs membres la signalent.': 'The dua has been reported. It will be hidden if several members report it.',
  'Retour': 'Back',
  'Mur des duas': 'Dua wall',
  'Cette dua n’est plus disponible.': 'This dua is no longer available.',
  'Voir le Mur des duas': 'See the Dua wall',
  'Allah l’a exaucée': 'Allah answered it',
  'Gratitude': 'Gratitude',
  'Anonyme': 'Anonymous',
  '{0} réponse': '{0} reply',
  '{0} réponses': '{0} replies',
  'Aucune réponse pour l’instant': 'No replies yet',
  'Vous': 'You',
  'Membre': 'Member',
  'Appui long sur une réponse pour la signaler.': 'Long press a reply to report it.',
  'Réponse bienveillante uniquement : une dua, un encouragement. Pas de jugement ni de conseil non demandé.':
    'Kind replies only: a dua, an encouragement. No judgement and no unrequested advice.',
  'Écrire une réponse bienveillante…': 'Write a kind reply…',
  'caractères restants': 'characters left',
  'Créez votre profil OUMMAH pour répondre': 'Create your OUMMAH profile to reply',
  'Connectez-vous pour répondre': 'Sign in to reply',
  'Récentes': 'Recent',
  'Exaucées': 'Answered',
  'Les miennes': 'Mine',
  'Ma dua': 'My dua',
  'Allah m’a exaucé': 'Allah answered me',
  'En attente de validation': 'Awaiting approval',
  'Répondre': 'Reply',
  'Al-hamdu lillah. Un mot de gratitude pour encourager les autres ? (facultatif)': 'Al-hamdu lillah. A word of gratitude to encourage others? (optional)',
  'Ce qu’Allah m’a accordé…': 'What Allah granted me…',
  'Partager ma gratitude': 'Share my gratitude',
  'Dua publiée': 'Dua published',
  'Votre dua est sur le Mur. Qu’Allah l’exauce.': 'Your dua is on the Wall. May Allah answer it.',
  'Faites dua les uns pour les autres et dites Amine. Votre dua est publiée tout de suite.':
    'Make dua for one another and say Ameen. Your dua is published right away.',
  'Partager une dua': 'Share a dua',
  'Les duas exaucées apparaîtront ici, avec la gratitude de leurs auteurs.': 'Answered duas will appear here, with their authors’ gratitude.',
  'Aucune dua pour le moment. Soyez le premier à en partager une.': 'No duas yet. Be the first to share one.',
  'Voir plus': 'See more',
  'Demandez à vos frères et sœurs de faire dua pour vous. Restez bienveillant.': 'Ask your brothers and sisters to make dua for you. Stay kind.',
  'Faites dua pour…': 'Make dua for…',
  'Publier anonymement': 'Publish anonymously',
  'Votre pseudo ne sera pas affiché.': 'Your username will not be shown.',
  'Signé « {0} ».': 'Signed “{0}”.',
  'Validée par la modération avant publication. Pas de malédiction contre une personne, pas d’informations permettant d’identifier quelqu’un.':
    'Approved by moderation before publication. No curses against anyone, no information that could identify someone.',
  'Envoyer': 'Send',
  'Connectez-vous pour participer au Mur des duas.': 'Sign in to take part in the Dua wall.',
  'Créez votre profil OUMMAH (un pseudo suffit) pour participer.': 'Create your OUMMAH profile (a username is enough) to take part.',
  'Ce texte contient des mots qui ne sont pas acceptés sur le Mur des duas.': 'This text contains words that are not accepted on the Dua wall.',
  'Vous avez atteint la limite pour aujourd’hui. Réessayez demain.': 'You have reached today’s limit. Try again tomorrow.',
  'Action impossible pour le moment.': 'This action is not possible right now.',
  'il y a {0} min': '{0} min ago',
  'il y a {0} jours': '{0} days ago',

  // ----- Friends, chat and groups ------------------------------------------------------------------------------
  'Activité privée': 'Private activity',
  'A prié cette nuit': 'Prayed tonight',
  'Réveillé pour prier': 'Awake to pray',
  'Pas encore cette nuit': 'Not yet tonight',
  'Encouragement envoyé': 'Encouragement sent',
  '{0} va recevoir votre message. Qu’Allah vous récompense.': '{0} will receive your message. May Allah reward you.',
  'Encourager': 'Encourage',
  'Choisissez un message. Votre ami le reçoit en notification.': 'Choose a message. Your friend receives it as a notification.',
  'Amis': 'Friends',
  'Retirer de mes amis': 'Remove from my friends',
  'Bloquer': 'Block',
  'Bloquer {0} ?': 'Block {0}?',
  'Il ne pourra plus vous trouver, vous écrire ni vous encourager. Vous pourrez le débloquer plus tard.':
    'They will no longer be able to find you, write to you or encourage you. You can unblock them later.',
  'Signaler {0}': 'Report {0}',
  'Pourquoi signalez-vous ce membre ?': 'Why are you reporting this member?',
  'Pseudo inapproprié': 'Inappropriate username',
  'Harcèlement': 'Harassment',
  'Comportement suspect': 'Suspicious behaviour',
  'Le signalement a été transmis à l’équipe OUMMAH.': 'The report has been sent to the OUMMAH team.',
  'Mes amis': 'My friends',
  'Se réveiller ensemble, s’encourager, sans classement ni comparaison.': 'Wake up together, encourage each other, with no ranking or comparison.',
  'Ajouter un ami par son pseudo': 'Add a friend by username',
  'Aucun membre avec ce pseudo.': 'No member with this username.',
  'Ajouter': 'Add',
  'Accepter': 'Accept',
  'Demande envoyée': 'Request sent',
  '{0} ami éveillé cette nuit': '{0} friend awake tonight',
  '{0} amis éveillés cette nuit': '{0} friends awake tonight',
  'Aucun ami éveillé pour l’instant. Envoyez-leur un encouragement.': 'No friends awake yet. Send them an encouragement.',
  'Mes groupes': 'My groups',
  'Créer': 'Create',
  'Créez un groupe avec vos amis pour vous parler et vous programmer des rappels (prière de la nuit, lecture, Witr…).':
    'Create a group with your friends to talk and schedule reminders (night prayer, reading, Witr…).',
  '{0} membre': '{0} member',
  '{0} membres': '{0} members',
  'Encouragements reçus': 'Encouragements received',
  '• nouveau': '• new',
  'Demandes reçues': 'Requests received',
  'Refuser': 'Decline',
  'Pas encore d’amis': 'No friends yet',
  'Cherchez le pseudo d’un proche ci-dessus. Vous verrez ses nuits seulement s’il l’autorise.':
    'Search for a loved one’s username above. You will only see their nights if they allow it.',
  'Vous :': 'You:',
  'Demandes envoyées': 'Requests sent',
  'Membres bloqués (': 'Blocked members (',
  'Débloquer': 'Unblock',
  'Ce que mes amis voient · confidentialité': 'What my friends see · privacy',
  'Pas de classement ni de comparaison : on s’encourage, Allah seul compte les nuits.':
    'No ranking or comparison: we encourage each other, only Allah counts the nights.',
  'On se réveille pour prier cette nuit ?': 'Shall we wake up to pray tonight?',
  'Qu’Allah te facilite ta nuit.': 'May Allah make your night easy for you.',
  'J’ai fait dua pour toi cette nuit.': 'I made dua for you tonight.',
  'Barak Allahou fik, continue comme ça !': 'Barak Allahu fik, keep it up!',
  'Ma sha Allah, qu’Allah t’accorde la constance.': 'Ma sha Allah, may Allah grant you steadfastness.',
  'Connectez-vous pour retrouver vos amis.': 'Sign in to find your friends.',
  'Créez votre profil OUMMAH (un pseudo suffit).': 'Create your OUMMAH profile (a username is enough).',
  'Ce membre n’est pas disponible.': 'This member is not available.',
  'Ce membre n’accepte pas de demandes d’ami pour le moment.': 'This member is not accepting friend requests at the moment.',
  'Vous n’êtes plus amis avec ce membre.': 'You are no longer friends with this member.',
  'Ce membre ne reçoit pas de messages pour le moment.': 'This member is not receiving messages at the moment.',
  'Ce message contient des mots qui ne sont pas acceptés.': 'This message contains words that are not accepted.',
  'Vous l’avez déjà encouragé il y a peu. Réessayez dans quelques heures.': 'You encouraged them a short while ago. Try again in a few hours.',
  'Ami': 'Friend',
  'Message': 'Message',
  'Mon message': 'My message',
  'Le supprimer pour vous deux ?': 'Delete it for both of you?',
  'Annuler': 'Cancel',
  'Supprimer': 'Delete',
  'Signaler ce message': 'Report this message',
  'Merci': 'Thank you',
  'Le message a été signalé à l’équipe OUMMAH.': 'The message has been reported to the OUMMAH team.',
  'Signalement': 'Report',
  'Message privé · entre amis': 'Private message · between friends',
  'As-salamu ‘alaykum': 'As-salamu ‘alaykum',
  'Commencez la conversation avec {0}. Restez bienveillant : les messages peuvent être signalés.':
    'Start the conversation with {0}. Stay kind: messages can be reported.',
  '· Vu': '· Seen',
  '· Envoyé': '· Sent',
  'Envoi…': 'Sending…',
  'Aujourd’hui': 'Today',
  'Hier': 'Yesterday',
  'Votre message…': 'Your message…',
  'Groupe': 'Group',
  'Infos': 'Info',
  'Quitter le groupe ?': 'Leave the group?',
  'Vous ne recevrez plus ses messages ni ses rappels.': 'You will no longer receive its messages or reminders.',
  'Quitter': 'Leave',
  'Nom du groupe': 'Group name',
  'Renommer': 'Rename',
  'Notifications du groupe': 'Group notifications',
  'Messages et rappels, avec le son OUMMAH.': 'Messages and reminders, with the OUMMAH sound.',
  'Rappels programmés': 'Scheduled reminders',
  'Aucun rappel. Utilisez le réveil dans la discussion pour en programmer un.': 'No reminders. Use the alarm in the chat to schedule one.',
  '· par': '· by',
  'Membres ·': 'Members ·',
  '{0} (vous)': '{0} (you)',
  'Créateur': 'Creator',
  'Retirer {0} ?': 'Remove {0}?',
  'Retirer': 'Remove',
  'Ajouter mes amis': 'Add my friends',
  'Tous vos amis sont déjà dans ce groupe.': 'All your friends are already in this group.',
  'Ajouter des amis': 'Add friends',
  'Quitter le groupe': 'Leave the group',
  'Les lève-tôt': 'The early risers',
  'Famille': 'Family',
  'Frères de la mosquée': 'Brothers from the mosque',
  'Sœurs du dernier tiers': 'Sisters of the last third',
  'Nouveau groupe': 'New group',
  'Donnez un nom à votre groupe': 'Give your group a name',
  'Idées :': 'Ideas:',
  'Ajoutez d’abord des amis OUMMAH. Vous pouvez aussi créer le groupe maintenant et les inviter plus tard.':
    'Add OUMMAH friends first. You can also create the group now and invite them later.',
  'Création…': 'Creating…',
  'Créer le groupe': 'Create the group',
  'Seuls vos amis peuvent être ajoutés. Chacun peut quitter le groupe ou couper ses notifications.':
    'Only your friends can be added. Everyone can leave the group or mute its notifications.',
  'Debout pour la prière de la nuit': 'Up for the night prayer',
  'Lecture de sourate Al-Mulk': 'Reading Surah Al-Mulk',
  'Witr avant de dormir': 'Witr before sleeping',
  'Dua du dernier tiers': 'Dua of the last third',
  'Rappel pour le groupe': 'Reminder for the group',
  'Chaque membre reçoit une notification à l’heure choisie.': 'Each member receives a notification at the chosen time.',
  'Texte du rappel': 'Reminder text',
  'Heure': 'Time',
  'Chaque jour': 'Every day',
  'Heure invalide (format HH:MM)': 'Invalid time (HH:MM format)',
  'Programmation…': 'Scheduling…',
  'Programmer le rappel': 'Schedule the reminder',
  'Rappel': 'Reminder',
  'Annuler le rappel': 'Cancel the reminder',
  '{0} membre · touchez pour les infos': '{0} member · tap for info',
  '{0} membres · touchez pour les infos': '{0} members · tap for info',
  'Bismillah': 'Bismillah',
  'Lancez la discussion, ou programmez un rappel pour tout le groupe avec le réveil.': 'Start the conversation, or schedule a reminder for the whole group with the alarm.',
  'Programmer un rappel': 'Schedule a reminder',
  'Rappel envoyé': 'Reminder sent',
  'Chaque jour à {0}': 'Every day at {0}',
  'Aujourd’hui à {0}': 'Today at {0}',
  'Demain à {0}': 'Tomorrow at {0}',
  '{0} à {1}': '{0} at {1}',
  'Connectez-vous pour retrouver vos groupes.': 'Sign in to find your groups.',
  'Vous ne faites plus partie de ce groupe.': 'You are no longer part of this group.',
  'Seul le créateur du groupe peut faire cela.': 'Only the group creator can do this.',
  'Ce texte contient des mots qui ne sont pas acceptés.': 'This text contains words that are not accepted.',
  'Limite atteinte pour le moment. Réessayez plus tard.': 'Limit reached for now. Try again later.',
  'Vérifiez le texte et l’heure.': 'Check the text and the time.',
  'Messages OUMMAH': 'OUMMAH messages',
  'Messages privés et de groupe, rappels de groupe.': 'Private and group messages, group reminders.',

  // ----- Wake-up buddy -------------------------------------------------------------------------------------------
  'Déjà réveillé': 'Already woken up',
  '{0} a réveillé {1} avant vous. Barak Allahou fik.': '{0} woke {1} up before you. Barak Allahu fik.',
  'Réveiller': 'Wake up',
  'Ils comptent sur vous cette nuit': 'They are counting on you tonight',
  'Réveillé par vous 🤍': 'Woken up by you 🤍',
  'Souhaite se lever vers {0}': 'Wants to get up around {0}',
  'Souhaite se lever pour prier': 'Wants to get up to pray',
  'Qui peut vous réveiller ?': 'Who can wake you up?',
  'Ils reçoivent une notification. Le premier debout vous réveille avec le son OUMMAH.': 'They receive a notification. The first one up wakes you with the OUMMAH sound.',
  'Un groupe': 'A group',
  'Des amis': 'Friends',
  'Ajoutez d’abord des amis OUMMAH dans « Amis ».': 'Add OUMMAH friends first in “Friends”.',
  'Demander à être réveillé': 'Ask to be woken up',
  '{0} ami prévenu. Le premier debout vous réveillera.': '{0} friend notified. The first one up will wake you.',
  '{0} amis prévenus. Le premier debout vous réveillera.': '{0} friends notified. The first one up will wake you.',
  'Binôme de réveil': 'Wake-up buddy',
  '{0} vous a réveillé': '{0} woke you up',
  '{0} ami prêt à vous réveiller': '{0} friend ready to wake you',
  '{0} amis prêts à vous réveiller': '{0} friends ready to wake you',
  'à {0} · qu’Allah le récompense': 'at {0} · may Allah reward them',
  'Demandez à un ami ou à un groupe de vous réveiller cette nuit.': 'Ask a friend or a group to wake you up tonight.',
  'Connectez-vous pour utiliser le binôme de réveil.': 'Sign in to use the wake-up buddy.',
  'Choisissez au moins un ami.': 'Choose at least one friend.',
  'Cette demande n’est plus disponible.': 'This request is no longer available.',

  // ----- Profile ---------------------------------------------------------------------------------------------------
  'Profil': 'Profile',
  'Ce pseudo est déjà pris. Choisissez-en un autre.': 'This username is already taken. Choose another one.',
  'Le pseudo est définitif et ne peut pas être modifié.': 'The username is permanent and cannot be changed.',
  'Le pseudo doit faire de 3 à 24 caractères (lettres, chiffres, espace, point, tiret).':
    'The username must be 3 to 24 characters (letters, numbers, space, dot, hyphen).',
  'Impossible d’enregistrer le profil pour le moment.': 'Unable to save the profile right now.',
  'Mon profil OUMMAH': 'My OUMMAH profile',
  'Connectez-vous pour rejoindre la communauté Qiyam al-Layl.': 'Sign in to join the Qiyam al-Layl community.',
  'Créer mon profil': 'Create my profile',
  'Votre pseudo': 'Your username',
  'Pseudo': 'Username',
  'Ex. : Abdallah, Oum Yasmine…': 'E.g. Abdallah, Umm Yasmine…',
  'Votre pseudo est unique et lié à votre compte : il ne peut plus être modifié.': 'Your username is unique and linked to your account: it can no longer be changed.',
  'Unique et définitif : il ne pourra plus être modifié. Visible des autres membres, évitez votre nom complet.':
    'Unique and permanent: it can never be changed. Visible to other members, avoid your full name.',
  'Avatar': 'Avatar',
  'Confidentialité': 'Privacy',
  'Apparaître dans « La Oummah cette nuit »': 'Appear in “The Ummah tonight”',
  'Compté quand vous déclarez être réveillé ou validez votre nuit. Toujours anonyme.': 'Counted when you say you are awake or log your night. Always anonymous.',
  'Ma zone sur la carte': 'My area on the map',
  'Une zone d’environ 30 km : vos nuits (visibles à partir de 3 membres) et l’icône de vos duas. Jamais votre adresse.':
    'An area of about 30 km: your nights (visible from 3 members) and the icon of your duas. Never your address.',
  'Mes amis voient mes nuits': 'My friends see my nights',
  'Réveillé ou a prié cette nuit, et le nombre de nuits sur 7 jours. Rien d’autre.': 'Awake or prayed tonight, and the number of nights over 7 days. Nothing else.',
  'Recevoir des demandes d’ami': 'Receive friend requests',
  'Désactivez pour ne plus recevoir de nouvelles demandes.': 'Turn off to stop receiving new requests.',
  'Recevoir des messages': 'Receive messages',
  'Uniquement de vos amis. Désactivez pour ne plus en recevoir.': 'Only from your friends. Turn off to stop receiving them.',
  'Enregistrement…': 'Saving…',
  'Enregistrer': 'Save',

  // ----- Notifications ---------------------------------------------------------------------------------------------
  'Qiyam al-Layl · OUMMAH': 'Qiyam al-Layl · OUMMAH',
  'Ce soir, Qiyam al-Layl 🌙': 'Tonight, Qiyam al-Layl 🌙',
  'Dernier tiers de {0}. Une intention, un réveil, et Allah fait le reste.': 'Last third from {0}. An intention, an alarm, and Allah does the rest.',
  'Dans 15 minutes, à {0}.': 'In 15 minutes, at {0}.',
  'Il est l’heure de dormir 🌙': 'It is time to sleep 🌙',
  'Couché maintenant : {0} de sommeil avant {1} à {2}.': 'In bed now: {0} of sleep before {1} at {2}.',
  'votre réveil': 'your alarm',
  'le dernier tiers': 'the last third',
  'C’est l’heure de prier la nuit': 'It is time for the night prayer',
  'Le Seigneur descend au ciel de ce bas monde. Fajr à {0} · {1} devant soi.': 'The Lord descends to the lowest heaven. Fajr at {0} · {1} ahead.',
  '« Qui M’invoque, que Je lui réponde ? » Jusqu’à Fajr, {0}.': '“Is there anyone to invoke Me, so that I may respond to invocation?” Until Fajr, {0}.',
  'Fajr à {0} : encore 30 minutes pour le Witr et les invocations.': 'Fajr at {0}: 30 more minutes for the Witr and supplications.',
  // ----- Counts ----------------------------------------------------------------------------------------
  'membre réveillé pour prier la nuit': 'member awake to pray at night',
  'membres réveillés pour prier la nuit': 'members awake to pray at night',
  'dont {0} a prié': '{0} of whom prayed',
  'dont {0} ont prié': '{0} of whom prayed',
  '{0} nuit / 7 jours': '{0} night / 7 days',
  '{0} nuits / 7 jours': '{0} nights / 7 days',
  'nuit': 'night',
  'nuits': 'nights',
  'RAMADAN · NUIT {0}': 'RAMADAN · NIGHT {0}',
  'Encore {0} nuit avant les dix dernières. Prier la nuit avec le suhoor, c’est une seule montée.': '{0} more night before the last ten. Praying at night with suhoor is a single climb.',
  'Encore {0} nuits avant les dix dernières. Prier la nuit avec le suhoor, c’est une seule montée.': '{0} more nights before the last ten. Praying at night with suhoor is a single climb.',
  'jusqu’à Fajr ({0}), après ‘Isha': 'until Fajr ({0}), after ‘Isha',
  'Dhikr, Coran': 'Dhikr, Quran',
  'Duas': 'Duas',
  'Mur · dire Amine': 'Wall · say Ameen',
  'Voir la carte de la nuit': 'See the map of the night',
  'Nuit du {0} au {1}': 'Night of {0} to {1}',
  'Une seule validation par nuit. Elle est enregistrée sur ce téléphone pour votre suivi ; vos amis ou la communauté ne la voient que si vous l’avez autorisé.': 'One record per night. It is saved on this phone for your tracking; your friends or the community only see it if you have allowed it.',
  'Facultatif · pour votre suivi': 'Optional · for your tracking',
  'Cercle doré : la nuit que vous pouvez encore enregistrer.': 'Gold ring: the night you can still record.',
};
