import type { SirahAssertion, SirahPeriod } from "./sirahTypes";

const q = (id: string, text: string, reference: string): SirahAssertion => ({ id, text, certainty: "QURAN", sources: [{ kind: "QURAN", label: "Coran", reference }] });
const h = (id: string, text: string, reference: string, ..._ignored: string[]): SirahAssertion => ({ id, text, certainty: "AUTHENTIC_HADITH", sources: [{ kind: "AUTHENTIC_HADITH", label: "Hadith authentique", reference }] });
const s = (id: string, text: string, reference: string, certainty: "SIRA" | "HISTORY" | "DISCUSSED" | "NOT_ESTABLISHED" = "SIRA"): SirahAssertion => ({ id, text, certainty, sources: [{ kind: certainty, label: certainty === "DISCUSSED" ? "Chronologie discutée" : certainty === "NOT_ESTABLISHED" ? "Non établi" : "Sîra / histoire", reference }] });
const chapter = (id: string, title: string, assertions: SirahAssertion[], lessons: string[], importance?: "major" | "ordinary"): SirahPeriod["chapters"][number] => ({ id, title, assertions, lessons, importance });

export const SIRAH_PERIODS: SirahPeriod[] = [
  { id: "pre-revelation", title: "Avant la révélation", subtitle: "Une société, une famille et une réputation de vérité", era: "pre-revelation", chapters: [
    chapter("lineage-birth", "La naissance à La Mecque", [s("birth-date", "Les sources anciennes situent sa naissance à La Mecque dans l’année connue comme l’Année de l’Éléphant, mais la date civile précise n’est pas établie avec certitude.", "Ibn Hishâm, Sîra, début du récit", "DISCUSSED"), s("lineage", "Il appartient aux Banû Hâshim, clan qurayshite auquel se rattache la lignée de ‘Abd al-Muttalib.", "Ibn Hishâm, Sîra")], ["La connaissance historique exige de distinguer les faits assurés des datations discutées."]),
    chapter("childhood", "Enfance et protection", [s("milk-family", "Les récits de la sîra rapportent qu’il fut confié, selon la coutume, à une nourrice bédouine durant ses premières années.", "Ibn Hishâm, Sîra"), s("orphanhood", "Après la mort de sa mère puis de son grand-père, la protection de son oncle Abû Tâlib devint déterminante.", "Ibn Hishâm, Sîra")], ["La fragilité des débuts n’empêche pas une mission immense."]),
    chapter("character", "Al-Amîn avant la mission", [s("trust", "Avant la révélation, il était connu pour sa sincérité et sa fiabilité ; les récits de La Mecque le désignent comme al-Amîn.", "Ibn Hishâm, Sîra"), s("khadija", "Son activité commerciale et son mariage avec Khadîja رضي الله عنها constituent un tournant familial et moral avant la révélation.", "Ibn Hishâm, Sîra")], ["La confiance se construit avant même que la parole publique ne commence."]),
    chapter("kaaba-hira", "La Kaaba et la retraite à Hirâ’", [q("kaaba", "La Kaaba est présentée par le Coran comme une Maison ancienne consacrée à l’adoration d’Allah.", "Coran 2:125-127"), h("hira", "La première révélation survient alors qu’il se retirait dans la grotte de Hirâ’.", "Sahîh al-Bukhârî, 3")], ["La révélation s’inscrit dans une histoire sacrée déjà connue, tout en appelant à la purifier."]),
  ]},
  { id: "meccan", title: "La période mecquoise", subtitle: "Révélation, patience et appel", era: "meccan", chapters: [
    chapter("first-revelation", "La première révélation", [h("iqra", "L’ange vient à lui et lui ordonne de lire ; les premiers versets de la sourate al-‘Alaq sont alors révélés.", "Sahîh al-Bukhârî, 3"), h("waraqa", "Khadîja le conduit auprès de Waraqa ibn Nawfal, qui reconnaît dans l’événement le modèle des révélations antérieures.", "Sahîh al-Bukhârî, 3")], ["La mission commence par la connaissance et l’adoration, non par la recherche du pouvoir."]),
    chapter("early-call", "L’appel discret puis public", [q("warning", "Le Coran ordonne de se lever pour avertir et d’appeler d’abord les proches.", "Coran 74:1-7 ; 26:214"), q("public", "L’ordre d’annoncer publiquement ce qui lui est commandé marque une nouvelle étape de l’appel.", "Coran 15:94")], ["La progression de l’appel tient compte des personnes et des circonstances."]),
    chapter("persecution", "Opposition et persécutions", [q("patience", "Le Coran rappelle les épreuves des croyants et leur demande la patience et la constance.", "Coran 16:106-110"), s("pressure", "Les premiers croyants subissent une opposition sociale et parfois physique ; les détails de chaque épisode varient selon les récits de sîra.", "Ibn Hishâm, Sîra", "HISTORY")], ["La fidélité ne se mesure pas à l’absence d’épreuve."]),
    chapter("abyssinia", "Les départs vers l’Abyssinie", [s("najashi", "Une partie des croyants se réfugie auprès du Négus, souverain chrétien auquel les sources attribuent une attitude protectrice.", "Ibn Hishâm, Sîra"), s("maryam", "Les récits de sîra associent le dialogue avec le Négus à la récitation de passages sur Maryam et ‘Îsâ ; le Coran fournit le passage récité, pas le détail de cette scène historique.", "Ibn Hishâm, Sîra ; Coran 19:16-36", "HISTORY")], ["La justice peut être reconnue même au-delà des frontières religieuses."]),
    chapter("boycott", "Le boycott et l’endurance", [s("boycott", "Le boycott visant les Banû Hâshim et leurs alliés est rapporté par les sources de sîra ; sa durée exacte et certains détails documentaires sont discutés.", "Ibn Hishâm, Sîra", "DISCUSSED")], ["L’épreuve collective appelle solidarité et patience."]),
    chapter("isra", "Al-Isrâ’ et l’ascension", [q("night-journey", "Allah mentionne le voyage nocturne de la Mosquée sacrée à la Mosquée la plus éloignée.", "Coran 17:1"), h("miraj", "Les hadiths authentiques détaillent l’ascension et la rencontre avec plusieurs prophètes.", "Sahîh Muslim, 162")], ["Les signes extraordinaires ne remplacent pas l’obéissance quotidienne."]),
    chapter("taif-before-hijra", "Tâ’if — l’appel avant la Hijra", [s("taif", "Après une période de pertes et de rejet à La Mecque, il se rend à Tâ’if pour proposer l’appel ; les récits divergent sur plusieurs détails de la rencontre.", "Ibn Hishâm, Sîra", "HISTORY"), h("angel-mountains", "Le hadith rapporte qu’il refuse la vengeance immédiate et espère une descendance qui adorera Allah.", "Sahîh al-Bukhârî, 3231")], ["La miséricorde peut demeurer présente au cœur d’un rejet profond."]),
    chapter("aqaba", "Les engagements d’al-‘Aqaba", [s("aqaba", "Des habitants de Yathrib prêtent des engagements successifs et ouvrent la voie à l’accueil de la communauté.", "Musnad Ahmad ; Ibn Hishâm, Sîra"), s("musab", "Mus‘ab ibn ‘Umayr est envoyé pour enseigner le Coran et accompagner la nouvelle communauté.", "Ibn Hishâm, Sîra")], ["Une migration se prépare par la foi, la confiance et la transmission."]),
  ]},
  { id: "hijra", title: "La Hijra", subtitle: "Le pivot du chemin de lumière", era: "hijra", chapters: [
    chapter("hijra", "La Hijra — de La Mecque à Médine", [q("cave", "Le Coran rappelle la scène de la grotte et l’assurance donnée au compagnon : Allah est avec eux.", "Coran 9:40"), h("route", "Le récit authentique rapporte le départ avec Abû Bakr, le séjour dans la grotte de Thawr et le recours à un guide.", "Sahîh al-Bukhârî, 3905"), s("arrival", "Les récits de Sîra rapportent ensuite l’arrivée à Médine et l’accueil de la communauté médinoise.", "Ibn Hishâm, Sîra", "HISTORY"), s("calendar", "La Hijra devient ensuite le repère du calendrier musulman sous ‘Umar ; l’événement lui-même est antérieur à cette formalisation.", "Ibn Kathîr, al-Bidâya wa-n-Nihâya, récit de la formalisation", "HISTORY")], ["Quitter pour Allah peut devenir une fondation, pas une fuite.", "La communauté se construit autour d’une orientation et d’une responsabilité communes."], "major"),
  ]},
  { id: "medinan", title: "La période médinoise", subtitle: "Communauté, traités, épreuves et victoire", era: "medinan", chapters: [
    chapter("medina", "Médine et la communauté", [h("brotherhood", "Les liens entre Muhâjirûn et Ansâr sont présentés comme un modèle de fraternité et de solidarité.", "Sahîh al-Bukhârî, 3780"), q("community", "Le Coran encadre les relations, la justice et la solidarité au sein de la communauté.", "Coran 49:10-13")], ["Une communauté se définit par des devoirs réciproques."]),
    chapter("qibla", "La qibla et les prescriptions", [q("qibla", "La direction de prière est orientée vers la Mosquée sacrée après une période tournée vers la première qibla.", "Coran 2:142-150"), q("ramadan", "Le jeûne de Ramadan est prescrit et encadré par le Coran.", "Coran 2:183-187")], ["Les prescriptions forment une discipline spirituelle et collective."]),
    chapter("badr", "Badr", [q("badr", "Selon le récit coranique, Badr est une victoire accordée alors que les croyants étaient en infériorité numérique.", "Coran 3:123-127 ; 8:5-19"), h("angels", "Les hadiths authentiques mentionnent le mérite particulier des participants à Badr.", "Sahîh al-Bukhârî, 3983")], ["La victoire ne se réduit ni aux nombres ni aux moyens visibles."]),
    chapter("uhud", "Uhud et la discipline", [q("uhud", "Le Coran analyse Uhud, les erreurs, l’épreuve et la nécessité de l’obéissance.", "Coran 3:121-175"), h("martyrs", "Le hadith rapporte que deux martyrs d’Uhud furent enveloppés dans un même linceul ; celui qui connaissait davantage le Coran fut placé en premier dans la tombe, sans lavage ni prière funéraire.", "Sahîh al-Bukhârî, 4079")], ["Une défaite peut devenir une école de responsabilité."]),
    chapter("ahzab", "Al-Ahzâb et le fossé", [q("khandaq", "Le Coran décrit la coalition, la peur et le secours divin lors de la bataille des Coalisés.", "Coran 33:9-27"), s("salman", "Les récits historiques attribuent généralement la proposition du fossé à Salmân al-Fârisî ; cette attribution relève de la Sîra et de l’histoire.", "Ibn Hishâm, Sîra", "HISTORY")], ["La consultation et l’adaptation sont compatibles avec la confiance en Allah."]),
    chapter("hudaybiyya", "Al-Hudaybiyya", [q("pledge", "Le Coran évoque le pacte d’allégeance sous l’arbre et annonce l’ouverture qui en découle.", "Coran 48:18-29"), h("treaty", "Le traité est rapporté avec ses clauses et les réactions des Compagnons dans les recueils authentiques.", "Sahîh al-Bukhârî, 2731-2732")], ["Une concession apparente peut ouvrir une victoire durable."]),
    chapter("letters", "Les lettres aux dirigeants", [s("letters", "L’envoi de lettres à plusieurs dirigeants est attesté par des sources de sîra et des hadiths ; l’ordre exact et la datation de certaines lettres restent discutés.", "Ibn Hishâm, Sîra ; Sahîh Muslim, 1774", "DISCUSSED")], ["La transmission s’adresse aux personnes et aux peuples avec clarté, sans prétendre à une précision historique inexistante."]),
    chapter("khaybar", "Khaybar", [h("banner", "Le hadith rapporte l’annonce de l’étendard à un homme qui aime Allah et Son Messager et qu’Allah aime.", "Sahîh al-Bukhârî, 3009"), s("khaybar", "Les récits de Khaybar comprennent la campagne, l’issue du conflit et les arrangements consécutifs ; plusieurs détails relèvent de l’histoire de la sîra.", "Ibn Hishâm, Sîra", "HISTORY")], ["Le courage est lié à la justice et à la responsabilité."]),
    chapter("conquest", "La conquête de La Mecque", [q("conquest", "Le Coran annonce une victoire et l’entrée des gens dans la religion par groupes.", "Coran 110:1-3"), h("entry", "Le hadith décrit l’organisation de l’entrée vers La Mecque, les étendards et les itinéraires empruntés.", "Sahîh al-Bukhârî, 4280"), s("mercy", "Les récits de protection et de pardon accordés à certains habitants doivent être étudiés séparément dans leurs propres références historiques ou hadithiques.", "Sources de Sîra et récits associés", "HISTORY")], ["La force maîtrisée par le pardon peut transformer une victoire en réconciliation."]),
    chapter("hunayn", "Hunayn", [q("hunayn", "Le Coran rappelle Hunayn et avertit que le nombre ne suffit pas lorsque les cœurs s’appuient sur lui.", "Coran 9:25-27"), h("return", "Le hadith rapporte que le Prophète ﷺ ne fuit pas à Hunayn : il est sur sa mule blanche et Abû Sufyân tient ses rênes.", "Sahîh al-Bukhârî, 2864")], ["La confiance doit rester attachée à Allah dans l’aisance comme dans le danger."]),
    chapter("taif-after-hunayn", "Tâ’if — après Hunayn", [s("siege", "Après Hunayn, le déplacement vers Tâ’if et le siège sont rapportés par les sources de sîra ; la durée et plusieurs détails tactiques ne sont pas uniformes.", "Ibn Hishâm, Sîra", "HISTORY"), s("dua-taif", "Un récit attribué à cet épisode présente une demande de guidée plutôt qu’une demande de destruction immédiate ; son degré doit être distingué du récit historique du siège.", "Sunan Abî Dâwûd, 2689", "DISCUSSED")], ["Ne pas confondre l’épisode de Tâ’if avant la Hijra avec celui qui suit Hunayn."]),
    chapter("delegations", "Les délégations", [q("delegations", "Le Coran mentionne l’entrée de groupes dans l’Islam et appelle à la glorification et au repentir.", "Coran 110:1-3"), s("year-delegations", "Les sources de sîra regroupent de nombreuses délégations dans les dernières années médinoises, sans fournir toujours une chronologie uniforme.", "Ibn Hishâm, Sîra", "HISTORY")], ["L’expansion d’une communauté exige accueil, enseignement et discernement."]),
    chapter("tabuk", "Tabûk", [q("tabuk", "Le Coran traite de l’épreuve de Tabûk, des excuses, de la sincérité et du repentir.", "Coran 9:38-118"), h("three", "Le récit des trois Compagnons laissés en attente puis pardonnés est rapporté dans un hadith authentique.", "Sahîh al-Bukhârî, 4418")], ["La sincérité finit par trouver une issue, même après une longue attente."]),
    chapter("farewell-pilgrimage", "Le pèlerinage d’adieu", [q("pilgrimage", "Le Coran énonce l’achèvement de la religion et rappelle les règles du pèlerinage.", "Coran 5:3 ; 22:27-29"), h("rites", "Les hadiths authentiques décrivent séparément les rites accomplis lors du pèlerinage d’adieu.", "Sahîh Muslim, 1218")], ["Les rites transmis doivent être appris avec précision et humilité."]),
    chapter("farewell-sermons", "Les sermons d’adieu", [h("sermon-arafat", "Le sermon rapporté à ‘Arafât doit être étudié à partir des narrations qui le transmettent, sans le reconstruire en un discours unique à partir de fragments distincts.", "Sahîh Muslim, 1218"), s("sermon-mina", "D’autres paroles sont rapportées à Minâ et dans d’autres étapes ; elles restent attachées à leurs propres chaînes et contextes, et ne doivent pas être fusionnées avec le sermon de ‘Arafât.", "Sunan at-Tirmidhî, 1628", "DISCUSSED")], ["La fidélité aux sources impose de conserver les contextes séparés."]),
  ]},
  { id: "final-days", title: "Les derniers jours", subtitle: "Maladie, prière et départ", era: "final", chapters: [
    chapter("illness", "La maladie et les dernières prières", [h("abu-bakr-prayer", "Durant sa maladie, il demande à Abû Bakr de diriger la prière, selon les récits authentiques.", "Sahîh al-Bukhârî, 664"), h("last-moments", "Dans ses derniers instants, le hadith rapporte l’usage du siwâk, la mention des souffrances de l’agonie, l’expression « le Compagnon le plus élevé » et son décès.", "Sahîh al-Bukhârî, 4449")], ["La responsabilité se transmet avec clarté même dans la faiblesse physique."]),
    chapter("death", "Le décès à Médine", [q("death", "Le Coran rappelle que Muhammad ﷺ n’est qu’un messager et que les messagers sont passés avant lui.", "Coran 3:144"), h("abu-bakr-speech", "Abû Bakr récite ce verset pour aider la communauté à comprendre la réalité du décès.", "Sahîh al-Bukhârî, 4452"), h("burial", "Le hadith rapporte que le Prophète ﷺ est décédé chez ‘Â’ishah رضي الله عنها et y a été enterré.", "Sahîh al-Bukhârî, 1389")], ["La vérité révélée soutient la communauté au moment du choc."]),
  ]},
  { id: "legacy", title: "L’héritage", subtitle: "Une transmission vivante", era: "legacy", chapters: [
    chapter("quran-sunna", "Le Coran et la Sunna", [q("mission", "Le Coran présente le Messager comme une miséricorde et un modèle pour les croyants.", "Coran 21:107 ; 33:21"), h("transmission", "Les Compagnons transmettent ses paroles et ses actes avec des chaînes étudiées par la science du hadith.", "Sahîh Muslim, introduction")], ["L’héritage se reçoit par l’étude, la vérification et la mise en pratique."]),
    chapter("mercy-justice", "Miséricorde, justice et équilibre", [q("justice", "Le Coran ordonne la justice, la bienfaisance et la solidarité.", "Coran 16:90"), h("character", "Les hadiths décrivent le bon comportement comme une dimension centrale de la foi.", "Sahîh al-Bukhârî, 6029")], ["La Sîra devient féconde lorsqu’elle transforme le caractère."]),
    chapter("living-sirah", "Lire la Sîra aujourd’hui", [s("method", "Les récits doivent être hiérarchisés : Coran, hadith authentique, puis sources de sîra et d’histoire avec leur degré de solidité.", "Méthode de lecture des sources"), s("uncertain", "Les détails non établis ne doivent pas être présentés comme des certitudes religieuses.", "Principe de prudence historique", "NOT_ESTABLISHED")], ["Aimer la Sîra implique aussi de respecter la vérité de ses sources."]),
  ]},
];

export const SIRAH_COUNTS = {
  periods: SIRAH_PERIODS.length,
  chapters: SIRAH_PERIODS.reduce((n, period) => n + period.chapters.length, 0),
  assertions: SIRAH_PERIODS.flatMap((period) => period.chapters.flatMap((item) => item.assertions)),
};

export const SIRAH_DISCUSSION_IDS = ["lineage-birth", "boycott", "letters", "taif-after-hunayn", "living-sirah"];
