import type { Companion, CompanionCategory, CompanionSource } from "./companionsTypes";

const hadith = (label: string, reference: string, grade = "Authentique"): CompanionSource => ({ kind: "HADITH", label, reference, grade });
const quran = (reference: string, note?: string): CompanionSource => ({ kind: "QURAN", label: "Coran", reference, note });
const history = (label: string, reference: string, note?: string): CompanionSource => ({ kind: "HISTORY", label, reference, note });

const period = (id: string, title: string, paragraphs: string[], sources?: CompanionSource[], dateLabel?: string) => ({ id, title, paragraphs, sources });

export const COMPANIONS: Companion[] = [
  {
    id: "abu-bakr", name: "Abû Bakr as-Siddîq", arabicName: "أبو بكر الصدّيق", shortTitle: "Premier calife bien guidé", categories: ["all", "caliphs", "promised"],
    summary: "Compagnon proche, premier adulte à embrasser l’Islam selon les récits classiques et premier calife de la communauté.",
    periods: [
      period("before", "Avant l’Islam et la conversion", ["Abû Bakr ibn Abî Quhâfa appartenait aux Quraysh et était connu à La Mecque pour son activité commerciale et sa connaissance des généalogies. Les sources de sîra le décrivent comme un homme estimé et fiable.", "Il embrassa l’Islam dès les débuts de la mission du Prophète ﷺ. Le récit de sa conversion est transmis dans les ouvrages de sîra ; les détails varient selon les chaînes et doivent être lus comme un récit historique, non comme un hadith au même degré que les deux Sahîh."], [history("Sîra", "Ibn Hishâm, Sîra, passages sur les premiers convertis")]),
      period("with-prophet", "Auprès du Prophète ﷺ", ["Il accompagna le Prophète ﷺ dans l’émigration et fut son compagnon dans la grotte. Le Coran rappelle cet épisode en mentionnant le réconfort adressé au compagnon de l’Envoyé d’Allah.", "Il participa aux grandes étapes de la communauté et fut chargé de diriger la prière pendant la maladie finale du Prophète ﷺ. Son lien avec lui fut à la fois familial, politique et spirituel."], [quran("At-Tawbah 9:40"), hadith("La maladie finale", "Sahîh al-Bukhârî 664–665")]),
      period("caliphate", "Le califat", ["Après la mort du Prophète ﷺ, les Compagnons lui prêtèrent allégeance. Son gouvernement fut bref et marqué par la nécessité de préserver l’unité de la communauté.", "Il fit face aux refus de l’impôt légal et aux mouvements de rupture, soutint l’envoi de l’armée préparée par le Prophète ﷺ et lança la collecte écrite du Coran après les pertes subies par les récitateurs.", "Son administration s’appuya sur la consultation, la fermeté sur les obligations établies et la continuité de la mission prophétique."], [hadith("La direction de la prière", "Sahîh al-Bukhârî 678"), history("Histoire", "At-Tabarî, événements de l’an 11–13 de l’Hégire")], "11–13 H"),
      period("legacy", "Fin de vie et héritage", ["Abû Bakr mourut à Médine en 13 H selon la chronologie historique classique. Il fut enterré auprès du Prophète ﷺ.", "Son héritage est celui d’une fidélité constante, d’une décision rapide dans la crise et d’un effort pour maintenir la communauté attachée aux obligations et à la révélation."], [history("Chronologie", "Ibn Kathîr, Al-Bidâya wa-n-Nihâya, année 13 H")]),
    ],
  },
  {
    id: "umar", name: "‘Umar ibn al-Khattâb", arabicName: "عمر بن الخطاب", shortTitle: "Deuxième calife bien guidé", categories: ["all", "caliphs", "promised"],
    summary: "Compagnon de premier plan et deuxième calife bien guidé, associé à une gouvernance exigeante et structurée.",
    periods: [
      period("conversion", "Une conversion qui fortifie la communauté", ["‘Umar appartenait aux Quraysh et fut d’abord opposé au message. Les récits de sîra racontent une conversion qui transforma profondément son rapport à l’Islam ; les détails précis ne sont pas tous de même solidité.", "Après sa conversion, il devint un défenseur public des musulmans à La Mecque et un compagnon proche du Prophète ﷺ."], [history("Récit de sîra", "Ibn Hishâm, Sîra, récit de la conversion de ‘Umar")]),
      period("with-prophet", "Auprès du Prophète ﷺ", ["Il participa à la vie militaire, politique et judiciaire de Médine. Plusieurs révélations et décisions furent mises en relation avec ses avis dans les recueils de hadith, sans que cela signifie qu’il se substituait à la révélation.", "Le Prophète ﷺ a décrit ses mérites dans plusieurs hadiths authentiques et a souligné sa force de discernement."], [hadith("Mérites de ‘Umar", "Sahîh al-Bukhârî 3689"), hadith("Le rêve et le vêtement", "Sahîh Muslim 2390")]),
      period("caliphate", "Le califat", ["‘Umar succéda à Abû Bakr en 13 H. La communauté s’étendait rapidement et devait organiser ses territoires, ses finances, sa justice et ses relations avec les populations conquises.", "Il structura les provinces, institua des registres et une allocation publique, nomma des gouverneurs et exigea d’eux une reddition de comptes. Les récits historiques rapportent aussi son attention à la justice des juges et à la protection des personnes vulnérables.", "Les conquêtes de Syrie, d’Irak, d’Égypte et de Perse eurent lieu sous son califat, mais leur récit détaillé provient principalement des sources historiques et doit être distingué des hadiths.", "Il mourut après avoir été poignardé pendant la prière et la consultation fut organisée pour la succession."], [history("Gouvernement", "At-Tabarî, événements de l’an 13–23 H"), hadith("Le mérite et la guidance", "Sahîh al-Bukhârî 3689")], "13–23 H"),
      period("legacy", "Héritage", ["‘Umar est resté une référence de justice, de responsabilité publique et de sobriété personnelle. Les détails anecdotiques doivent toutefois être vérifiés récit par récit, car les ouvrages historiques contiennent des niveaux de fiabilité différents."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
    ],
  },
  {
    id: "uthman", name: "‘Uthmân ibn ‘Affân", arabicName: "عثمان بن عفان", shortTitle: "Troisième calife bien guidé", categories: ["all", "caliphs", "promised"],
    summary: "Compagnon généreux, deux fois gendre du Prophète ﷺ et troisième calife bien guidé.",
    periods: [
      period("early", "Les débuts et les épreuves", ["‘Uthmân appartenait aux Banû Umayya et faisait partie des premiers musulmans. Il émigra en Abyssinie puis à Médine avec son épouse Ruqayya, fille du Prophète ﷺ.", "Après la mort de Ruqayya, il épousa Umm Kulthûm, également fille du Prophète ﷺ. C’est pour cette raison que les sources lui donnent le titre de Dhû an-Nûrayn, l’homme des deux lumières."], [history("Sîra", "Ibn Hishâm, passages sur les émigrations"), hadith("Mérites de ‘Uthmân", "Sahîh al-Bukhârî 3674")]),
      period("with-prophet", "Générosité et service", ["Il participa aux campagnes et contribua financièrement à plusieurs besoins de la communauté. Le hadith de l’équipement de l’armée de Tabûk est rapporté dans les sources de mérites.", "Le Prophète ﷺ lui annonça le Paradis malgré une épreuve qui le toucherait, selon un hadith authentique."], [hadith("L’équipement de l’armée", "Jâmi‘ at-Tirmidhî 3701", "Hasan selon l’édition citée"), hadith("L’épreuve à venir", "Sahîh Muslim 2403")]),
      period("caliphate", "Le califat", ["‘Uthmân fut choisi par le conseil institué après la mort de ‘Umar. Son califat connut une forte expansion et une croissance de la communauté.", "La recension et la diffusion d’exemplaires concordants du muṣḥaf sont associées à son gouvernement, afin de limiter les divergences de lecture entre régions. Les détails administratifs sont documentés dans les sources historiques.", "La fin de son califat fut marquée par des contestations et un siège à Médine. Les causes, acteurs et récits précis font l’objet de versions historiques divergentes : il faut distinguer les faits largement établis des reconstructions polémiques ou tardives.", "‘Uthmân fut tué dans sa maison en 35 H. Les sources s’accordent sur le meurtre, mais divergent sur le détail de la chaîne des événements et des responsabilités."], [hadith("La compilation du muṣḥaf", "Sahîh al-Bukhârî 4987"), history("Fitna", "At-Tabarî, événements de l’an 35 H", "Récit historique à comparer avec d’autres sources")], "23–35 H"),
      period("legacy", "Héritage", ["Son héritage associe générosité, pudeur, service du texte coranique et une crise politique dont l’étude exige de ne pas transformer les récits tardifs en certitudes."], [hadith("Pudeur de ‘Uthmân", "Sahîh Muslim 2401")]),
    ],
  },
  {
    id: "ali", name: "‘Alî ibn Abî Tâlib", arabicName: "علي بن أبي طالب", shortTitle: "Quatrième calife bien guidé", categories: ["all", "caliphs", "promised"],
    summary: "Cousin et gendre du Prophète ﷺ, savant parmi les Compagnons et quatrième calife bien guidé.",
    periods: [
      period("early", "Dans la maison du Prophète ﷺ", ["‘Alî grandit dans la maison du Prophète ﷺ et embrassa l’Islam très jeune. Les sources de sîra le présentent comme l’un des premiers croyants.", "Il épousa Fâtima, fille du Prophète ﷺ, et fut le père d’al-Hasan et d’al-Husayn. Les liens familiaux et les mérites de la famille prophétique sont établis par de nombreux textes, tandis que certaines formulations populaires doivent être vérifiées dans leur chaîne."], [hadith("Mérites de ‘Alî", "Sahîh Muslim 2404"), history("Sîra", "Ibn Hishâm, passages sur les débuts de l’Islam")]),
      period("service", "Auprès du Prophète ﷺ", ["Il participa aux expéditions et reçut des responsabilités militaires et judiciaires. Le Prophète ﷺ lui confia notamment l’étendard à Khaybar selon un hadith authentique.", "Il transmit des jugements, des paroles et des enseignements. Sa proximité ne doit pas conduire à attribuer automatiquement à son autorité des récits sans chaîne vérifiable."], [hadith("Khaybar", "Sahîh al-Bukhârî 4210"), hadith("Position auprès du Prophète", "Sahîh Muslim 2404")]),
      period("caliphate", "Le califat et la Fitna", ["‘Alî fut reconnu comme calife après le meurtre de ‘Uthmân, dans une communauté profondément divisée. Son gouvernement dut gérer la recherche des responsables, les revendications de justice et l’éclatement politique.", "Les affrontements de Jamal et de Siffîn sont des faits historiques largement établis, mais les récits détaillés, les intentions attribuées aux acteurs et les discours rapportés ne sont pas tous au même niveau. Les présenter exige de signaler les divergences plutôt que de choisir une narration partisane.", "L’arbitrage lié à Siffîn, l’émergence des Khârijites et les décisions politiques de la fin de son règne sont principalement étudiés dans les sources historiques. Le module séparera les chroniques des hadiths authentiques.", "‘Alî fut assassiné à Kûfa en 40 H selon la chronologie historique classique."], [history("Fitna", "At-Tabarî, événements des années 35–40 H", "Récit historique divergent"), hadith("Al-Hasan et al-Husayn", "Sahîh al-Bukhârî 3748")], "35–40 H"),
      period("legacy", "Héritage", ["Son héritage est celui d’un savoir transmis, d’un courage reconnu et d’une période politique que les savants abordent avec prudence. Les mérites établis sont distingués des récits polémiques apparus dans les conflits ultérieurs."], [hadith("La ville du savoir", "Jâmi‘ at-Tirmidhî 3723", "Récit discuté selon les spécialistes")]),
    ],
  },
];

const additional = (id: string, name: string, arabicName: string, shortTitle: string, summary: string, periods: Companion["periods"], categories: CompanionCategory[] = ["all"]): Companion => ({ id, name, arabicName, shortTitle, summary, periods, categories });

COMPANIONS.push(
  additional("hamza", "Hamza ibn ‘Abd al-Muttalib", "حمزة بن عبد المطلب", "Oncle du Prophète ﷺ", "Oncle du Prophète ﷺ et martyr de Uhud.", [
    period("conversion", "Conversion et défense de la vérité", ["Hamza appartenait aux Banû Hâshim et était connu pour sa force et son courage. Il embrassa l’Islam à La Mecque après un épisode d’opposition publique à l’encontre du Prophète ﷺ ; le détail de la scène relève principalement de la sîra.", "Sa conversion renforça la protection sociale du Prophète ﷺ dans une période où les croyants subissaient les pressions de Quraysh."], [history("Sîra", "Ibn Hishâm, récit de la conversion de Hamza")]),
    period("uhud", "Uhud et le martyre", ["Hamza participa aux grandes expéditions. Il fut tué à Uhud en 3 H, événement largement établi dans les sources de sîra.", "Les récits détaillés de son assassinat et de la mutilation de son corps sont rapportés dans des chaînes et des formulations de force variable ; ils doivent être présentés avec retenue."], [history("Uhud", "Ibn Hishâm, récit de la bataille de Uhud"), hadith("Le maître des martyrs", "Sunan Ibn Mâjah 1513", "Hasan selon plusieurs spécialistes")]),
    period("legacy", "Héritage", ["Hamza reste associé au courage, au sacrifice et à la défense des opprimés. Son statut de martyr est un élément central de la mémoire musulmane."], [hadith("Mérites des martyrs", "Sahîh al-Bukhârî 2817")]),
  ]),
  additional("bilal", "Bilâl ibn Rabâh", "بلال بن رباح", "Le muezzin de l’Islam", "Compagnon abyssinien, éprouvé à La Mecque puis muezzin de la communauté.", [
    period("early", "Épreuve et libération", ["Bilâl était un homme esclave à La Mecque lorsqu’il embrassa l’Islam. Les sources de sîra rapportent les tortures qu’il subit et l’intervention d’Abû Bakr pour l’affranchir.", "La formule « un seul, un seul » est célèbre dans les récits de son épreuve ; elle doit être reliée à ses sources plutôt que présentée sans référence."], [history("Sîra", "Ibn Hishâm, récit de Bilâl à La Mecque")]),
    period("medina", "Auprès du Prophète ﷺ", ["À Médine, Bilâl fut choisi comme muezzin et accompagna le Prophète ﷺ dans plusieurs événements. Son parcours montre que la dignité dans la communauté ne dépend pas de l’origine sociale."], [hadith("L’appel à la prière", "Sahîh al-Bukhârî 604"), hadith("Les pas au Paradis", "Sahîh al-Bukhârî 1149")]),
    period("later", "Après la mort du Prophète ﷺ", ["Les récits divergent sur la durée exacte de son séjour à Médine et sur certains détails de ses voyages. Il mourut en Syrie selon la chronologie historique généralement retenue, mais la date exacte fait l’objet de variantes."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ", "Chronologie discutée")]),
  ]),
  additional("salman", "Salmân al-Fârisî", "سلمان الفارسي", "Le chercheur de vérité", "Compagnon venu de Perse après une longue recherche spirituelle.", [
    period("search", "Une recherche de vérité", ["Salmân était originaire de Perse. Les récits de sa vie avant l’Islam décrivent une recherche religieuse passant par plusieurs maîtres ; ces détails proviennent surtout de récits biographiques et ne sont pas tous de même solidité.", "Il finit par rejoindre Médine et reconnut les signes qu’il associait au dernier Prophète ﷺ."], [history("Récit biographique", "Ibn Hishâm, histoire de Salmân", "Récit de sîra à distinguer du hadith")]),
    period("medina", "La communauté de Médine", ["Salmân participa à la bataille du Fossé. La proposition de creuser la tranchée est largement connue dans les sources de sîra, tandis que certains détails de dialogue doivent être vérifiés séparément.", "Le Prophète ﷺ a souligné la place de Salmân parmi les gens de sa maison dans un récit souvent cité ; sa formulation et son degré doivent être examinés selon la source."], [history("Al-Khandaq", "Ibn Hishâm, récit de la bataille du Fossé"), hadith("Salmân", "Jâmi‘ at-Tirmidhî 3774", "Récit discuté selon la chaîne")]),
    period("legacy", "Transmission et fin de vie", ["Salmân fut associé à la sobriété, au savoir et à la sagesse. Les récits sur sa fonction en al-Madâ’in et sur sa mort sont principalement historiques et comportent des variantes."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
  ]),
  additional("abu-ubayda", "Abû ‘Ubayda ibn al-Jarrâh", "أبو عبيدة بن الجراح", "Gardien de la confiance", "Compagnon parmi les premiers croyants et commandant reconnu en Syrie.", [
    period("early", "Conversion et émigration", ["Abû ‘Ubayda embrassa l’Islam à La Mecque et émigra à Médine. Il participa aux grandes expéditions de la communauté.", "Les sources de mérites le décrivent comme digne de confiance ; les détails biographiques précis sont surtout conservés dans les ouvrages de sîra."], [hadith("Digne de confiance", "Sahîh al-Bukhârî 3744")]),
    period("syria", "Responsabilité en Syrie", ["Après la mort du Prophète ﷺ, Abû ‘Ubayda exerça un commandement en Syrie. Les chroniques rapportent son rôle dans les campagnes et son comportement envers les populations, avec des différences de détail selon les auteurs.", "Il mourut lors de l’épidémie de ‘Amwâs en 18 H selon la chronologie historique classique."], [history("Conquête de Syrie", "At-Tabarî, événements des années 13–18 H"), history("‘Amwâs", "Ibn Kathîr, Al-Bidâya wa-n-Nihâya")]),
    period("legacy", "Héritage", ["Son héritage associe confiance, commandement et détachement de la gloire personnelle."], [hadith("Les meilleurs Compagnons", "Sahîh Muslim 2419")]),
  ], ["all", "promised"]),
  additional("sad", "Sa‘d ibn Abî Waqqâs", "سعد بن أبي وقاص", "Compagnon et commandant", "Parmi les premiers musulmans et commandant de la conquête de l’Irak.", [
    period("conversion", "Parmi les premiers musulmans", ["Sa‘d appartenait aux Banû Zuhra et embrassa l’Islam à La Mecque. Il fut parmi les premiers croyants et subit les tensions familiales liées à sa conversion.", "Il participa à l’émigration et aux expéditions avec le Prophète ﷺ."], [hadith("Mérites de Sa‘d", "Sahîh al-Bukhârî 3723")]),
    period("command", "Commandement et Qâdisiyya", ["Sa‘d commanda l’armée musulmane lors de la bataille de Qâdisiyya selon les sources historiques. La conquête de l’Irak et la fondation de Kûfa sont rapportées dans les chroniques, avec des variantes de détail.", "‘Umar le nomma gouverneur de Kûfa puis le retira après des plaintes dont les récits ne doivent pas être surinterprétés."], [history("Qâdisiyya", "At-Tabarî, événements des années 14–17 H")]),
    period("later", "Retrait et héritage", ["Sa‘d se retira des affrontements de la première Fitna et mourut à al-‘Aqîq selon la chronologie classique. Il figure parmi les Compagnons auxquels les traditions attribuent une place éminente."], [hadith("Les dix promis", "Jâmi‘ at-Tirmidhî 3747", "Hasan selon plusieurs spécialistes"), history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
  ], ["all", "promised"]),
  additional("khalid", "Khâlid ibn al-Walîd", "خالد بن الوليد", "L’épée d’Allah", "Commandant majeur de l’époque prophétique et des premières conquêtes.", [
    period("conversion", "De l’opposition à l’Islam", ["Khâlid appartenait aux Quraysh et participa à Uhud du côté mecquois avant sa conversion. Il embrassa l’Islam avant la conquête de La Mecque, selon la sîra.", "Le Prophète ﷺ lui confia ensuite des responsabilités militaires."], [history("Sîra", "Ibn Hishâm, conversion de Khâlid")]),
    period("campaigns", "Commandement", ["Il participa à Mu’ta et reçut le titre d’épée d’Allah dans un hadith authentique. Les récits de ses campagnes doivent être lus selon les sources et les contextes précis.", "Sous Abû Bakr puis ‘Umar, il commanda plusieurs opérations en Arabie, en Irak et au Levant. Les chroniques diffèrent sur les effectifs et certains épisodes."], [hadith("L’épée d’Allah", "Sahîh al-Bukhârî 4262"), history("Campagnes", "At-Tabarî, chroniques des premières conquêtes")]),
    period("later", "Fin de vie", ["‘Umar le releva du commandement suprême sans nier ses mérites, afin que la victoire ne soit pas attribuée à un homme plutôt qu’à Allah. Khâlid mourut à Homs selon la tradition historique dominante."], [history("Biographie", "Ibn Kathîr, Al-Bidâya wa-n-Nihâya")]),
  ]),
  additional("abd-rahman", "‘Abd al-Rahmân ibn ‘Awf", "عبد الرحمن بن عوف", "Marchand et donateur", "Compagnon parmi les premiers croyants, marchand prospère et généreux.", [
    period("early", "Conversion et émigration", ["Il embrassa l’Islam à La Mecque, émigra en Abyssinie puis à Médine et y reconstruisit son activité commerciale.", "Le Prophète ﷺ établit une fraternité entre lui et un Ansârî ; le récit souligne son refus de dépendre durablement d’un don et son désir de travailler."], [hadith("La fraternité à Médine", "Sahîh al-Bukhârî 2048")]),
    period("service", "Service et consultation", ["Il participa aux expéditions et fut membre du conseil chargé de choisir le successeur de ‘Umar. Sa richesse fut régulièrement orientée vers les besoins de la communauté.", "Les détails sur ses donations sont nombreux mais doivent être reliés à des sources précises plutôt qu’à des montants légendaires."], [hadith("Les dix promis", "Jâmi‘ at-Tirmidhî 3747", "Hasan selon plusieurs spécialistes")]),
    period("legacy", "Mort et héritage", ["Il mourut à Médine en 32 H selon la chronologie classique. Son héritage associe commerce licite, générosité et responsabilité collective."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
  ], ["all", "promised"]),
  additional("talha", "Talha ibn ‘Ubaydillâh", "طلحة بن عبيد الله", "Compagnon de Uhud", "Parmi les premiers musulmans et les dix promis au Paradis selon un hadith rapporté.", [
    period("early", "Premiers pas", ["Talha embrassa l’Islam à La Mecque et subit les pressions de Quraysh. Il émigra et participa à la vie de Médine.", "Les récits de sa conversion sont principalement biographiques et doivent être distingués des textes de hadith authentique."], [history("Sîra", "Ibn Hishâm, passages sur les premiers convertis")]),
    period("uhud", "Uhud et service", ["Il participa aux campagnes et fut gravement blessé à Uhud en protégeant le Prophète ﷺ selon des récits transmis dans les recueils de hadith et de sîra.", "Il était reconnu pour sa générosité et sa place dans la consultation des Compagnons."], [hadith("Mérites de Talha", "Jâmi‘ at-Tirmidhî 3744", "Hasan selon plusieurs spécialistes")]),
    period("legacy", "Fin de vie", ["Talha mourut lors des troubles de la première Fitna. Les circonstances exactes et les responsabilités individuelles doivent être rapportées avec prudence et en distinguant les chroniques divergentes."], [history("Jamâl", "At-Tabarî, événements de l’an 36 H", "Récit historique divergent")]),
  ], ["all", "promised"]),
  additional("zubayr", "az-Zubayr ibn al-‘Awwâm", "الزبير بن العوام", "Compagnon et défenseur", "Cousin du Prophète ﷺ, parmi les premiers musulmans et les dix promis au Paradis selon un hadith.", [
    period("early", "Un des premiers croyants", ["Az-Zubayr appartenait aux Quraysh et embrassa l’Islam très tôt. Les sources rapportent les persécutions subies par les premiers musulmans.", "Il émigra et participa aux campagnes avec le Prophète ﷺ."], [history("Sîra", "Ibn Hishâm, premiers musulmans")]),
    period("service", "Auprès du Prophète ﷺ", ["Il fut présent dans plusieurs expéditions et était connu pour son courage. Les textes de mérites le comptent parmi les dix promis au Paradis dans un hadith rapporté par les recueils de Sunan."], [hadith("Les dix promis", "Jâmi‘ at-Tirmidhî 3747", "Hasan selon plusieurs spécialistes")]),
    period("legacy", "Fin de vie", ["Il se retira du conflit après avoir compris la gravité de la situation, puis fut tué après la bataille du Chameau selon les chroniques. Les détails des échanges sont historiques et discutés."], [history("Jamâl", "At-Tabarî, événements de l’an 36 H", "Récit historique divergent")]),
  ], ["all", "promised"]),
  additional("ibn-abbas", "‘Abd Allâh ibn ‘Abbâs", "عبد الله بن عباس", "Le savant de la communauté", "Cousin du Prophète ﷺ et grand transmetteur de tafsîr et de hadith.", [
    period("youth", "Enfance auprès du Prophète ﷺ", ["Ibn ‘Abbâs était encore jeune lorsque le Prophète ﷺ mourut. Il bénéficia de sa proximité familiale et transmit des invocations et des enseignements rapportés dans les hadiths.", "Le Prophète ﷺ invoqua pour lui la compréhension de la religion dans un hadith authentique."], [hadith("Invocation pour la compréhension", "Sahîh al-Bukhârî 75")]),
    period("knowledge", "Savoir et enseignement", ["Après la mort du Prophète ﷺ, il interrogea les Compagnons et enseigna à La Mecque puis dans le monde musulman. Il est une source majeure des explications transmises sur le Coran.", "Les attributions de tafsîr doivent toutefois être vérifiées : tout commentaire appelé ‘tafsîr d’Ibn ‘Abbâs’ n’a pas nécessairement une chaîne authentique jusqu’à lui."], [hadith("Mérites d’Ibn ‘Abbâs", "Sahîh al-Bukhârî 7270")]),
    period("legacy", "Héritage", ["Il mourut à Tâ’if en 68 H selon la chronologie classique. Son héritage est lié à la science, à la transmission et à la méthode consistant à revenir aux Compagnons et à la langue arabe."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
  ]),
  additional("ibn-masud", "‘Abd Allâh ibn Mas‘ûd", "عبد الله بن مسعود", "Compagnon du Coran", "Lecteur du Coran, proche serviteur du Prophète ﷺ et enseignant à Kûfa.", [
    period("early", "Conversion et proximité", ["Ibn Mas‘ûd travaillait comme berger avant son entrée dans l’Islam. Il devint l’un des premiers croyants et servit le Prophète ﷺ, notamment dans les tâches quotidiennes.", "Le Prophète ﷺ encouragea les Compagnons à apprendre le Coran de plusieurs maîtres dont Ibn Mas‘ûd selon un hadith authentique."], [hadith("Apprendre le Coran", "Sahîh al-Bukhârî 4999")]),
    period("teaching", "Enseigner à Kûfa", ["‘Umar l’envoya enseigner à Kûfa. Il transmit la récitation, le droit et les pratiques apprises auprès du Prophète ﷺ.", "Les divergences de récitation doivent être étudiées à partir des transmissions reconnues et non d’anecdotes isolées."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
    period("legacy", "Fin de vie", ["Il mourut à Médine après le califat de ‘Uthmân selon les chronologies classiques. Son héritage est particulièrement important pour la récitation et la compréhension du Coran."], [hadith("Mérites d’Ibn Mas‘ûd", "Sahîh al-Bukhârî 3760")]),
  ]),
  additional("abu-hurayra", "Abû Hurayra", "أبو هريرة", "Grand transmetteur de hadith", "Compagnon connu pour le nombre de hadiths qu’il transmit.", [
    period("conversion", "Arrivée dans l’Islam", ["Abû Hurayra appartenait à la tribu de Daws au Yémen. Il vint à Médine et embrassa l’Islam dans les dernières années de la vie du Prophète ﷺ, traditionnellement situé lors de l’expédition de Khaybar.", "Il demeura auprès du Prophète ﷺ avec une attention particulière à l’apprentissage et à la mémorisation."], [history("Biographie", "Ibn Hajar, Al-Isâba, notice d’Abû Hurayra")]),
    period("transmission", "Mémoire et enseignement", ["Il transmit un très grand nombre de hadiths. Cette abondance s’explique notamment par son attention constante aux assemblées du Prophète ﷺ et par les années durant lesquelles il enseigna après sa mort.", "Il fut gouverneur de Bahreïn pendant une période sous ‘Umar selon les récits historiques, puis vécut à Médine et transmit jusqu’à sa mort."], [hadith("La mémorisation", "Sahîh al-Bukhârî 119")]),
    period("legacy", "Héritage", ["Il mourut à Médine en 57 ou 58 H selon les chronologies. Son héritage est celui d’une transmission abondante, à contrôler hadith par hadith selon les recueils et les degrés d’authenticité."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ", "Année de décès discutée")]),
  ]),
  additional("anas", "Anas ibn Mâlik", "أنس بن مالك", "Serviteur et transmetteur", "Compagnon qui servit le Prophète ﷺ à Médine et transmit de nombreux enseignements.", [
    period("medina", "Auprès du Prophète ﷺ", ["Anas fut présenté au Prophète ﷺ par sa mère alors qu’il était jeune et le servit à Médine. Il décrivit son comportement avec les enfants et les serviteurs dans plusieurs hadiths authentiques.", "Son témoignage est précieux pour la vie quotidienne du Prophète ﷺ, tout en restant limité à ce qu’il a effectivement observé ou entendu."], [hadith("Le comportement du Prophète ﷺ", "Sahîh Muslim 2310")]),
    period("later", "Après 632", ["Après la mort du Prophète ﷺ, Anas participa aux campagnes puis s’installa à Bassora, où il enseigna. Il transmit des hadiths à plusieurs générations de disciples.", "Les récits de sa longévité et de ses invocations sont nombreux ; ils doivent être distingués des formulations tardives non vérifiées."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
    period("legacy", "Fin de vie", ["Anas mourut à Bassora en 93 H environ selon la chronologie généralement retenue. Il est souvent présenté comme le dernier Compagnon à y mourir, affirmation à rattacher aux sources historiques utilisées."], [history("Chronologie", "Ibn Hajar, Al-Isâba", "Date approximative")]),
  ]),
  additional("said-ibn-zayd", "Sa‘îd ibn Zayd", "سعيد بن زيد", "Parmi les dix promis", "Compagnon des premiers temps, connu pour sa foi, sa patience et son attachement à la vérité.", [
    period("family", "Une famille des débuts", ["Sa‘îd ibn Zayd appartenait aux Quraysh. Son père, Zayd ibn ‘Amr, rejetait le polythéisme et recherchait la religion d’Ibrâhîm ; les détails de sa biographie avant l’Islam proviennent principalement des ouvrages de sîra.", "Sa‘îd épousa Fâtima bint al-Khattâb. Tous deux embrassèrent l’Islam avant ‘Umar ; le récit de cette conversion familiale est rapporté dans les sources biographiques avec des variantes de détail."], [history("Premiers temps", "Ibn Hishâm, Sîra, récit de la conversion de ‘Umar")]),
    period("service", "Émigration et service", ["Il émigra avec les premiers musulmans et servit la communauté. Il fut absent de Badr dans une mission confiée par le Prophète ﷺ, puis participa aux événements militaires ultérieurs selon les notices biographiques.", "Le hadith qui énumère les dix promis au Paradis le cite explicitement parmi eux ; cette attribution est distincte des récits historiques sur les détails de sa vie."], [hadith("Les dix promis au Paradis", "Jâmi‘ at-Tirmidhî 3747", "Hasan selon plusieurs spécialistes")]),
    period("later", "Après le Prophète ﷺ", ["Après 632, Sa‘îd demeura un Compagnon engagé sans rechercher une fonction centrale. Les sources historiques le rattachent aux premières campagnes et à la vie de la communauté sous les Califes, avec des détails qui ne sont pas tous également établis.", "Il mourut pendant la période omeyyade selon des chronologies divergentes. Son héritage est celui d’un croyant précoce et d’un témoin de la première génération, dont les mérites sont à distinguer des récits tardifs."], [history("Biographie", "Ibn Sa‘d, At-Tabaqât al-Kubrâ", "Chronologie de la mort discutée")]),
  ], ["all", "promised"]),
);

const addCaliphateTimeline = (id: string, extra: Companion["periods"]) => {
  const companion = COMPANIONS.find((item) => item.id === id);
  if (companion) companion.periods.splice(2, 0, ...extra);
};

addCaliphateTimeline("abu-bakr", [
  period("succession", "Saqîfa et accession", ["La succession fut discutée à Saqîfa dans l’urgence créée par la mort du Prophète ﷺ. Les récits s’accordent sur l’allégeance finalement donnée à Abû Bakr, mais divergent sur les échanges et la portée politique de chaque prise de parole."], [history("Saqîfa", "At-Tabarî, événements de l’an 11 H", "Récit historique à comparer")]),
  period("usama", "L’armée d’Usâma", ["Abû Bakr maintint l’expédition qu’Usâma ibn Zayd avait été chargé de conduire par le Prophète ﷺ. Les sources historiques présentent cette décision comme un choix de continuité malgré la fragilité de la situation à Médine."], [history("Expédition d’Usâma", "Ibn Sa‘d, At-Tabaqât al-Kubrâ", "Chronique historique")]),
  period("ridda", "Ridda et obligation de la zakât", ["Il refusa de distinguer entre la prière et la zakât lorsque des groupes voulurent rompre cette obligation. Les campagnes contre les mouvements de révolte furent conduites par plusieurs commandants ; les détails militaires sont à lire dans les chroniques."], [hadith("La zakât", "Sahîh al-Bukhârî 1400"), history("Guerres de Ridda", "At-Tabarî, événements des années 11–12 H")]),
  period("quran-collection", "La collecte du Coran", ["Après les pertes de récitateurs à Yamâma, ‘Umar proposa de rassembler les fragments et témoignages écrits. Abû Bakr confia ce travail à Zayd ibn Thâbit, selon le récit authentique rapporté par al-Bukhârî."], [hadith("Collecte du Coran", "Sahîh al-Bukhârî 4986")]),
  period("administration", "Administration et fronts", ["Son gouvernement conserva Médine comme centre de décision et ouvrit des fronts en Irak et au Shâm. Les éléments précis concernant le Bayt al-Mâl et l’organisation provinciale relèvent principalement des sources historiques, avec des variantes."], [history("Administration", "At-Tabarî, années 11–13 H")]),
]);
addCaliphateTimeline("umar", [
  period("accession", "Accession et consultation", ["Avant sa mort, Abû Bakr désigna ‘Umar après consultation des Compagnons. L’allégeance fut ensuite donnée à ‘Umar, dans une communauté qui devait administrer une expansion rapide."], [history("Succession", "At-Tabarî, année 13 H")]),
  period("diwan", "Registres, provinces et finances", ["Les chroniques attribuent à ‘Umar la structuration du dîwân, des allocations publiques et du gouvernement provincial. Ces récits historiques documentent une administration en formation ; ils ne doivent pas être confondus avec des paroles prophétiques."], [history("Dîwân et provinces", "Abû Yûsuf, Kitâb al-Kharâj", "Source administrative postérieure")]),
  period("justice", "Justice et responsabilité", ["Il nomma des gouverneurs et des juges, surveilla leur conduite et exigea une responsabilité publique. Les anecdotes individuelles doivent être vérifiées séparément, car leur force varie selon les chaînes historiques."], [history("Gouvernement", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
  period("expansion", "Expansion et commandement", ["La Syrie, l’Irak, l’Égypte et une partie de la Perse furent intégrés à l’État musulman durant son règne. Les chroniques divergent sur certains effectifs, itinéraires et discours, tandis que l’expansion générale est largement établie."], [history("Conquêtes", "At-Tabarî, années 13–23 H", "Récit historique")]),
]);
addCaliphateTimeline("uthman", [
  period("council", "Élection par le conseil", ["Après la mort de ‘Umar, un conseil de six Compagnons consulta la communauté et ‘Uthmân fut choisi. Le principe du conseil est établi par les récits transmis ; les détails des échanges doivent être distingués selon les sources."], [history("Conseil", "At-Tabarî, année 23 H")]),
  period("expansion", "Expansion et administration", ["Son règne vit l’extension des territoires et la consolidation de provinces éloignées. Les nominations de gouverneurs et les critiques formulées contre certaines administrations sont rapportées dans des chroniques de force inégale."], [history("Provinces", "Al-Balâdhurî, Futûh al-Buldân", "Récit historique")]),
  period("mushaf", "Unification des muṣḥaf", ["À la suite de divergences de récitation signalées entre régions, ‘Uthmân demanda une copie de référence et en fit envoyer des exemplaires. Le récit de Hudhayfa, du comité et de la diffusion est rapporté dans Sahîh al-Bukhârî."], [hadith("Les muṣḥaf", "Sahîh al-Bukhârî 4987")]),
  period("crisis", "Crise politique et fin du règne", ["Les protestations, le siège puis le meurtre de ‘Uthmân sont largement attestés. Les causes précises, les responsabilités individuelles et de nombreux discours sont en revanche des récits historiques divergents ; aucune version discutée ne doit être présentée comme certaine."], [history("Fitna", "At-Tabarî, année 35 H", "Récit historique divergent")]),
]);
addCaliphateTimeline("ali", [
  period("accession", "Accession dans la crise", ["‘Alî fut reconnu après le meurtre de ‘Uthmân, alors que Médine et les provinces étaient divisées. La question de la priorité entre stabilisation politique et jugement des meurtriers traversa immédiatement son gouvernement."], [history("Accession", "At-Tabarî, année 35 H", "Chronique à comparer")]),
  period("jamal", "Jamal", ["L’affrontement du Chameau est un événement historique largement établi. Les intentions attribuées aux Compagnons, les dialogues et les responsabilités précises appartiennent à des récits de force variable et sont présentés ici comme discutés."], [history("Jamal", "At-Tabarî, année 36 H", "Récit historique divergent")]),
  period("siffin", "Siffîn et arbitrage", ["Le conflit avec Mu‘âwiya à Siffîn, puis l’arbitrage et la sortie des Khârijites, structurèrent la fin de son règne. Les détails narratifs et les formulations de l’arbitrage varient selon les chroniques ; ils ne sont pas assimilés à des hadiths authentiques."], [history("Siffîn", "At-Tabarî, année 37 H", "Récit historique divergent")]),
  period("governance", "Gouverner une communauté divisée", ["Son gouvernement dut déplacer son centre de décision et administrer des provinces en conflit. Les décisions particulières et les accusations réciproques doivent être étudiées dans leur contexte et sans narration partisane."], [history("Gouvernement de ‘Alî", "Ibn Sa‘d, At-Tabaqât al-Kubrâ")]),
]);

export const COMPANION_CATEGORIES = [
  { id: "all", label: "Tous" },
  { id: "caliphs", label: "Califes bien guidés" },
  { id: "promised", label: "Dix promis au Paradis" },
] as const;
