import { Ionicons } from "@expo/vector-icons";
import { StyleSheet, View } from "react-native";
import { colors } from "../../../theme/colors";

const icons: Record<string, keyof typeof Ionicons.glyphMap> = {
  "prayer-foundations": "sparkles-outline",
  "prayer-times-qibla": "compass-outline",
  "prayer-entry-recitation": "book-outline",
  "prayer-bowing-prostration": "swap-vertical-outline",
  "prayer-seated-ending": "remove-outline",
  "prayer-special-situations": "trail-sign-outline",
  "prayer-corrections": "refresh-outline",
  "prayer-collective-friday": "people-outline",
  "prayer-funeral": "leaf-outline",
  "purification-water": "water-outline",
  "purification-ablutions": "hand-left-outline",
  "purification-khuff": "footsteps-outline",
  "purification-ghusl": "water-outline",
  "purification-tayammum": "layers-outline",
  "purification-menstruation": "calendar-outline",
  "purification-doubt": "help-circle-outline",
  "purification-soiled-clothing": "shirt-outline",
  "fasting-foundations": "moon-outline",
  "fasting-month-start": "calendar-outline",
  "fasting-daily-rhythm": "sunny-outline",
  "fasting-invalidations": "warning-outline",
  "fasting-excuses": "medkit-outline",
  "fasting-voluntary": "sparkles-outline",
  "fasting-special-days": "calendar-number-outline",
  "fasting-qadr": "star-outline",
  "zakat-foundations": "leaf-outline",
  "zakat-beneficiaries": "people-outline",
  "zakat-thresholds": "scale-outline",
  "zakat-livestock": "paw-outline",
  "zakat-crops-rikaz": "nutrition-outline",
  "zakat-fitr": "gift-outline",
  "hajj-foundations": "location-outline",
  "hajj-ihram": "shirt-outline",
  "hajj-tawaf-sai": "sync-outline",
  "hajj-arafah-mina": "map-outline",
  "hajj-jamarat": "trail-sign-outline",
  "hajj-ifada-farewell": "exit-outline",
  "hajj-types": "git-branch-outline",
  "hajj-special-cases": "help-buoy-outline",
  "funerals-death": "heart-outline",
  "funerals-washing": "water-outline",
  "funerals-shroud": "layers-outline",
  "funerals-prayer": "book-outline",
  "funerals-burial": "leaf-outline",
  "funerals-condolences": "people-outline",
  "family-marriage": "heart-circle-outline",
  "family-wali-mahr": "ribbon-outline",
  "family-spouses": "home-outline",
  "family-separation": "git-branch-outline",
  "family-children": "people-circle-outline",
  "transactions-foundations": "document-text-outline",
  "transactions-sales": "cart-outline",
  "transactions-debt": "receipt-outline",
  "transactions-riba": "swap-horizontal-outline",
  "transactions-rental": "key-outline",
  "transactions-partnerships": "people-outline",
  "food-basics": "restaurant-outline",
  "food-slaughter": "cut-outline",
  "food-sacrifice": "calendar-outline",
  "food-aqiqah": "gift-outline",
  "oaths": "hand-left-outline",
  "vows": "ribbon-outline",
  "expiations": "refresh-outline",
  "clothing-basics": "shirt-outline",
  "clothing-adornment": "diamond-outline",
  "clothing-appearance": "sparkles-outline",
  "daily-cleanliness": "water-outline",
  "daily-social": "people-outline",
  "daily-travel": "navigate-outline",
  "daily-public": "business-outline",
  "justice-evidence": "document-text-outline",
  "justice-disputes": "chatbubbles-outline",
  "justice-property": "briefcase-outline",
  "wills": "document-outline",
  "inheritance-estate": "folder-open-outline",
  "inheritance-heirs": "people-outline",
  "inheritance-cases": "git-branch-outline",
  "hunting": "compass-outline",
  "animals": "paw-outline",
  "animals-products": "cube-outline",
  "siyar-principles": "shield-checkmark-outline",
  "siyar-relations": "people-outline",
  "siyar-historical": "library-outline",
};
export function FiqhChapterMark({ chapterId, compact = false }: { chapterId: string; compact?: boolean }) {
  return (
    <View style={[styles.mark, compact && styles.markCompact]}>
      <Ionicons name={icons[chapterId] ?? "book-outline"} size={compact ? 17 : 21} color={colors.goldLight} />
    </View>
  );
}

const styles = StyleSheet.create({
  mark: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.goldDark,
    marginBottom: 10,
  },
  markCompact: {
    width: 34,
    height: 34,
    borderRadius: 17,
    marginBottom: 0,
    backgroundColor: "rgba(29, 18, 43, 0.92)",
  },
});
