import type { FiqhSource } from "../fiqhTypes";

const B = (n: string, scope: string): FiqhSource => ({ id: `bukhari-${n}`, kind: "hadith", reference: `Sahîh al-Bukhârî, ${n}`, canonicalReference: n, authenticity: "Sahîh", scope });
const M = (n: string, scope: string): FiqhSource => ({ id: `muslim-${n}`, kind: "hadith", reference: `Sahîh Muslim, ${n}`, canonicalReference: n, authenticity: "Sahîh", scope });
const AD = (n: string, scope: string, grade = "Sahîh selon al-Albânî"): FiqhSource => ({ id: `abudawud-${n}`, kind: "hadith", reference: `Sunan Abî Dâwûd, ${n}`, canonicalReference: n, authenticity: grade, scope });
const T = (n: string, scope: string, grade = "Sahîh selon al-Albânî"): FiqhSource => ({ id: `tirmidhi-${n}`, kind: "hadith", reference: `Jâmi‘ at-Tirmidhî, ${n}`, canonicalReference: n, authenticity: grade, scope });
const IM = (n: string, scope: string, grade = "Sahîh selon al-Albânî"): FiqhSource => ({ id: `ibnmajah-${n}`, kind: "hadith", reference: `Sunan Ibn Mâjah, ${n}`, canonicalReference: n, authenticity: grade, scope });
const Q = (s: number, v: number, scope: string): FiqhSource => ({ id: `quran-${s}-${v}`, kind: "quran", reference: `Coran ${s}:${v}`, scope });

/**
 * Sources added with the hand-written lessons (2026 rewrite).
 * Each one is listed in the review file sent to the scholar.
 */
export const LESSON_SOURCES: FiqhSource[] = [
  // Purification
  M("223", "« La purification est la moitié de la foi »"),
  M("224", "aucune prière n’est acceptée sans purification"),
  B("157", "le Prophète ﷺ a fait ses ablutions en lavant chaque membre une fois"),
  B("158", "le Prophète ﷺ a fait ses ablutions en lavant chaque membre deux fois"),
  B("168", "le Prophète ﷺ aimait commencer par la droite, notamment dans sa purification"),
  B("185", "description des ablutions par ‘Abdullah ibn Zayd : essuyage de la tête de l’avant vers l’arrière puis retour"),
  B("60", "« Malheur aux talons [négligés], du Feu »"),
  M("241", "« Malheur aux talons [négligés], du Feu » : les pieds doivent être entièrement lavés"),
  M("234", "attestation de foi prononcée après les ablutions et sa récompense"),
  M("243", "un homme avait laissé sur son pied une partie sèche de la taille d’un ongle : « Retourne et fais bien tes ablutions »"),
  AD("175", "l’homme qui avait laissé une partie sèche sur son pied reçut l’ordre de refaire ablutions et prière"),
  AD("142", "bien faire les ablutions, passer l’eau entre les doigts et bien aspirer l’eau sauf en jeûnant"),
  B("201", "ablutions avec un mudd d’eau et ghusl avec un sâ‘ à cinq mudd"),
  B("887", "« Si ce n’était pas pénible pour ma communauté, je leur aurais ordonné le siwâk à chaque prière »"),
  B("269", "le madhy impose le wudû’ et le lavage de la partie intime, sans ghusl"),
  M("360", "question sur la viande de chameau : « Oui, faites les ablutions »"),
  B("137", "celui qui doute en prière ne la quitte pas avant d’entendre un son ou de sentir une odeur"),
  M("362", "celui qui ressent quelque chose dans son ventre et doute ne quitte pas la mosquée sans certitude"),
  M("330", "Umm Salama n’a pas à défaire ses tresses pour le ghusl : trois poignées d’eau sur la tête suffisent"),
  B("249", "description du ghusl du Prophète ﷺ par Maymûna"),
  B("877", "« Quand l’un de vous vient au vendredi, qu’il fasse le ghusl »"),
  B("879", "« Le ghusl du vendredi est un devoir pour tout pubère »"),
  B("282", "la femme qui a un rêve érotique fait le ghusl si elle voit le liquide"),
  AD("355", "Qays ibn ‘Âsim reçut l’ordre de faire le ghusl en embrassant l’islam"),
  B("335", "la terre a été rendue pour le Prophète ﷺ lieu de prière et moyen de purification"),
  AD("338", "deux hommes ont prié avec le tayammum puis trouvé l’eau dans le temps : l’un a refait, l’autre non, et tous deux ont été approuvés"),
  AD("162", "‘Alî : l’essuyage se fait sur le dessus des khuff"),
  T("96", "Safwân ibn ‘Assâl : on garde les khuff trois jours en voyage, sauf en cas de janâba"),
  B("305", "‘Â’isha, ayant ses règles pendant le Hajj : « Fais tout ce que fait le pèlerin, sauf le tawâf »"),
  B("304", "la femme qui a ses règles ne prie pas et ne jeûne pas"),
  M("302", "« Faites tout, sauf le rapport » avec l’épouse qui a ses règles"),
  B("228", "Fâtima bint Abî Hubaysh : la femme en istihâda fait le wudû’ pour chaque prière"),
  B("1926", "le Prophète ﷺ se levait en état de janâba à l’aube, faisait le ghusl et jeûnait"),
  B("223", "urine d’un nourrisson garçon : de l’eau aspergée sur le vêtement"),
  B("218", "deux hommes punis dans leur tombe, dont l’un ne se préservait pas de l’urine"),
  AD("650", "le Prophète ﷺ a retiré ses sandales pendant la prière en apprenant qu’elles étaient souillées, et a poursuivi"),
  Q(6, 145, "la bête morte, le sang répandu et la viande de porc sont une souillure (rijs)"),
  M("366", "« Quand la peau est tannée, elle devient pure »"),
  M("288", "‘Â’isha grattait le sperme du vêtement du Prophète ﷺ qui priait avec"),
  B("283", "« Le croyant ne devient pas impur »"),
  B("194", "le Prophète ﷺ a versé l’eau de ses ablutions sur Jâbir malade"),

  // Prayer
  M("82", "« Entre l’homme et le polythéisme et la mécréance, il y a l’abandon de la prière »"),
  M("610a", "les cinq prières dans le récit de Jibrîl"),
  AD("495", "« Ordonnez la prière à vos enfants à sept ans »", "Hasan sahîh selon al-Albânî"),
  Q(7, 31, "« Prenez votre parure en tout lieu de prière »"),
  AD("641", "Allah n’accepte pas la prière d’une femme pubère sans voile"),
  B("359", "que personne ne prie dans un seul vêtement sans rien sur les épaules"),
  B("611", "« Quand vous entendez l’appel, dites comme le muezzin »"),
  M("384", "répéter l’appel, prier sur le Prophète ﷺ puis demander pour lui al-wasîla"),
  M("385", "répondre « lâ ḥawla wa lâ quwwata illâ billâh » à « ḥayya ‘ala-ṣ-ṣalâh » et « ḥayya ‘ala-l-falâḥ »"),
  B("614", "l’invocation après l’adhân et l’intercession promise"),
  AD("499", "les formules de l’adhân et de l’iqâma vues en rêve par ‘Abdullah ibn Zayd", "Hasan sahîh selon al-Albânî"),
  M("612", "les limites de chaque temps de prière enseignées par le Prophète ﷺ"),
  B("527", "l’acte le plus aimé d’Allah : la prière à son heure"),
  T("342", "« Ce qui est entre l’est et l’ouest est qibla » (pour les gens de Médine)"),
  B("400", "prière surérogatoire sur la monture dans sa direction, descente pour l’obligatoire"),
  AD("61", "« La clé de la prière est la purification ; on y entre par le takbîr et on en sort par le taslîm »", "Hasan sahîh selon al-Albânî"),
  B("735", "lever les mains au takbîr d’ouverture, avant et après le rukû‘"),
  B("740", "poser la main droite sur l’avant-bras gauche"),
  B("744", "invocation d’ouverture : « Allâhumma bâ‘id baynî wa bayna khaṭâyâya… »"),
  M("772", "« Subḥâna rabbiya-l-‘aẓîm » au rukû‘ et « Subḥâna rabbiya-l-a‘lâ » au sujûd"),
  B("796", "l’imam dit « Sami‘a-llâhu liman ḥamidah », les fidèles « Allâhumma rabbanâ laka-l-ḥamd »"),
  B("812", "la prosternation sur sept os : front et nez, mains, genoux, pointes des pieds"),
  M("494", "« Quand tu te prosternes, pose tes paumes et lève tes coudes »"),
  IM("897", "« Rabbi-ghfir lî, rabbi-ghfir lî » entre les deux prosternations"),
  B("828", "description de la prière par Abû Humayd : le dos droit au rukû‘, l’assise"),
  B("780", "« Quand l’imam dit Âmîn, dites Âmîn »"),
  B("776", "al-Fâtiha et une sourate dans les deux premières rak‘ât, al-Fâtiha seule dans les deux dernières"),
  B("3370", "la prière sur le Prophète ﷺ (aṣ-ṣalât al-ibrâhîmiyya)"),
  M("588", "demander refuge contre quatre choses avant le salut"),
  Q(2, 286, "« Allah n’impose à aucune âme une charge supérieure à sa capacité »"),
  Q(64, 16, "« Craignez Allah autant que vous le pouvez »"),
  B("597", "« Celui qui oublie une prière, qu’il la fasse dès qu’il s’en souvient »"),
  M("684", "celui qui oublie une prière ou s’endort la fait dès qu’il s’en souvient"),
  B("596", "à la bataille du Fossé, le Prophète ﷺ a prié ‘Asr après le coucher du soleil, puis Maghrib"),
  B("586", "pas de prière après ‘Asr jusqu’au coucher du soleil, ni après Fajr jusqu’au lever"),
  M("831", "trois moments où le Prophète ﷺ interdisait de prier : lever, zénith, coucher du soleil"),
  B("645", "la prière en groupe dépasse de vingt-sept degrés la prière seul"),
  M("653", "l’aveugle qui entend l’appel doit y répondre"),
  B("900", "« N’empêchez pas les servantes d’Allah d’aller aux mosquées d’Allah »"),
  B("723", "« Alignez vos rangs, cela fait partie de l’accomplissement de la prière »"),
  M("673", "« Que dirige le groupe celui qui récite le mieux le Livre d’Allah »"),
  B("691", "mise en garde contre celui qui lève la tête avant l’imam"),
  B("703", "« Celui qui dirige les gens, qu’il allège »"),
  M("440", "les meilleurs rangs des hommes sont les premiers, ceux des femmes les derniers"),
  B("699", "Ibn ‘Abbâs placé à droite du Prophète ﷺ quand il priait seul avec lui"),
  M("591", "après le salut : « Astaghfiru-llâh » trois fois et « Allâhumma anta-s-salâm… »"),
  M("597", "trente-trois tasbîh, tahmîd et takbîr après chaque prière"),
  B("844", "« Lâ ilâha illa-llâhu waḥdahu… Allâhumma lâ mâni‘a limâ a‘ṭayt… »"),
  B("998", "« Faites du witr votre dernière prière de la nuit »"),
  M("752", "le witr est une rak‘a à la fin de la nuit"),
  M("755", "celui qui craint de ne pas se lever fait le witr en début de nuit"),
  M("728", "douze rak‘ât surérogatoires par jour : une maison au Paradis"),
  B("1180", "Ibn ‘Umar : dix rak‘ât retenues du Prophète ﷺ autour des prières"),
  M("725", "« Les deux rak‘ât de l’aube valent mieux que le monde et ce qu’il contient »"),
  B("1147", "le Prophète ﷺ ne dépassait pas onze rak‘ât la nuit, en Ramadan comme en dehors"),
  B("2009", "« Celui qui prie les nuits de Ramadan avec foi et espérance… »"),
  M("1163", "la meilleure prière après l’obligatoire est la prière de la nuit"),
  B("990", "« La prière de la nuit se fait deux par deux »"),
  B("444", "« Quand l’un de vous entre à la mosquée, qu’il prie deux rak‘ât avant de s’asseoir »"),
  M("720", "deux rak‘ât de duḥâ valent l’aumône due pour chaque articulation"),
  AD("1067", "le vendredi est un devoir pour tout musulman, sauf l’esclave, la femme, l’enfant et le malade"),
  B("883", "le ghusl, le parfum et le silence pendant le sermon du vendredi"),
  B("935", "le vendredi contient une heure où l’invocation est exaucée"),
  B("934", "dire « tais-toi » pendant le sermon est une parole vaine"),
  AD("1052", "celui qui délaisse trois vendredis par négligence, Allah scelle son cœur", "Hasan sahîh selon al-Albânî"),
  M("881", "quatre rak‘ât après le vendredi"),
  B("937", "Ibn ‘Umar : deux rak‘ât chez soi après le vendredi"),
  AD("1151", "sept takbîr dans la première rak‘a de l’Aïd et cinq dans la seconde", "Hasan selon al-Albânî"),
  B("974", "les femmes, même celles qui ont leurs règles, sortent le jour de l’Aïd"),
  B("953", "manger quelques dattes en nombre impair avant la prière de l’Aïd al-Fitr"),
  B("986", "revenir de l’Aïd par un autre chemin"),
  B("1325", "un qîrât de récompense pour la prière funéraire, deux pour l’enterrement"),

  // Fasting
  AD("2454", "pas de jeûne pour celui qui ne l’a pas résolu avant l’aube"),
  M("1154", "le Prophète ﷺ décidait de jeûner dans la journée quand il n’y avait rien à manger (jeûne surérogatoire)"),
  B("1903", "« Celui qui ne délaisse pas la parole mensongère et l’agir selon elle, Allah n’a pas besoin qu’il délaisse sa nourriture et sa boisson »"),
  B("1914", "ne pas devancer Ramadan d’un ou deux jours de jeûne"),
  B("1916", "le fil blanc et le fil noir : la clarté du jour et l’obscurité de la nuit"),
  B("1918", "« Bilâl appelle de nuit : mangez et buvez jusqu’à l’appel d’Ibn Umm Maktûm »"),
  B("1921", "entre le suhûr et la prière de l’aube, le temps de réciter cinquante versets"),
  B("1954", "quand la nuit arrive, que le jour s’en va et que le soleil s’est couché, le jeûneur rompt"),
  AD("2356", "rompre le jeûne avec des dattes fraîches, sinon sèches, sinon de l’eau", "Hasan sahîh selon al-Albânî"),
  AD("2357", "« Dhahaba-ẓ-ẓama’, wa-btallati-l-‘urûq, wa thabata-l-ajru in shâ’a-llâh »", "Hasan selon al-Albânî"),
  T("807", "celui qui donne à manger à un jeûneur obtient une récompense égale à la sienne"),
  B("1927", "le Prophète ﷺ embrassait son épouse en jeûnant, étant le plus maître de son désir"),
  AD("2380", "celui que le vomissement surprend n’a rien à rattraper ; celui qui se fait vomir rattrape"),
  B("1938", "le Prophète ﷺ s’est fait poser des ventouses en jeûnant"),
  B("1943", "à Hamza al-Aslamî : « Jeûne si tu veux, romps si tu veux » en voyage"),
  B("1946", "« Ce n’est pas de la piété de jeûner en voyage » (pour celui que le jeûne épuise)"),
  B("1950", "‘Â’isha rattrapait ses jours de Ramadan en Sha‘bân"),
  B("1952", "« Celui qui meurt en devant des jours de jeûne, son proche jeûne pour lui »"),
  B("4505", "Ibn ‘Abbâs : le vieillard et la vieille femme qui ne peuvent jeûner nourrissent un pauvre par jour"),
  AD("2408", "Allah a allégé le jeûne pour le voyageur, la femme enceinte et celle qui allaite", "Hasan sahîh selon al-Albânî"),
  M("1134", "« Si je vis jusqu’à l’an prochain, je jeûnerai le neuvième » (‘Âshûrâ’)"),
  B("1988", "le Prophète ﷺ a bu du lait à ‘Arafa, devant les gens : il ne jeûnait pas ce jour-là"),
  B("1997", "pas de jeûne les jours de Tashrîq, sauf pour le pèlerin qui n’a pas trouvé de bête à sacrifier"),
  B("1985", "ne pas jeûner le vendredi seul, sans un jour avant ou après"),
  B("1981", "trois jours de jeûne chaque mois, conseillés à Abû Hurayra"),
  M("1159", "le meilleur jeûne est celui de Dâwûd : un jour sur deux"),
  T("747", "les œuvres sont présentées le lundi et le jeudi ; le Prophète ﷺ aimait jeûner ces jours-là"),
  B("2026", "le Prophète ﷺ faisait la retraite (i‘tikâf) les dix dernières nuits de Ramadan jusqu’à sa mort"),
  Q(97, 3, "« La Nuit du Destin vaut mieux que mille mois »"),
  T("3513", "invocation de la Nuit du Destin : « Allâhumma innaka ‘afuwwun tuḥibbu-l-‘afwa fa‘fu ‘annî »"),
];

export { B, M, AD, T, IM, Q };
