import type { FiqhSource } from "../fiqhTypes";

const B = (n: string, scope: string): FiqhSource => ({ id: `bukhari-${n}`, kind: "hadith", reference: `Sahîh al-Bukhârî, ${n}`, canonicalReference: n, authenticity: "Sahîh", scope });
const M = (n: string, scope: string): FiqhSource => ({ id: `muslim-${n}`, kind: "hadith", reference: `Sahîh Muslim, ${n}`, canonicalReference: n, authenticity: "Sahîh", scope });
const AD = (n: string, scope: string, grade = "Sahîh selon al-Albânî"): FiqhSource => ({ id: `abudawud-${n}`, kind: "hadith", reference: `Sunan Abî Dâwûd, ${n}`, canonicalReference: n, authenticity: grade, scope });
const T = (n: string, scope: string, grade = "Sahîh selon al-Albânî"): FiqhSource => ({ id: `tirmidhi-${n}`, kind: "hadith", reference: `Jâmi‘ at-Tirmidhî, ${n}`, canonicalReference: n, authenticity: grade, scope });
const IM = (n: string, scope: string, grade = "Sahîh selon al-Albânî"): FiqhSource => ({ id: `ibnmajah-${n}`, kind: "hadith", reference: `Sunan Ibn Mâjah, ${n}`, canonicalReference: n, authenticity: grade, scope });
const Q = (s: number, v: number, scope: string): FiqhSource => ({ id: `quran-${s}-${v}`, kind: "quran", reference: `Coran ${s}:${v}`, scope });

/**
 * Sources added with the hand-written lessons (2026 rewrite).
 * Each one is listed in the review file sent to the scholar.
 */
export const LESSON_SOURCES: FiqhSource[] = [
  {
    id: "contemporary-estimates",
    kind: "scholar",
    author: "Savants contemporains, dont Ibn ‘Uthaymîn et le Comité permanent (al-Lajna ad-Dâ’ima)",
    reference: "Estimations contemporaines des mesures anciennes",
    scope: "conversion approximative des mesures des textes : sâ‘ (environ 2,7 litres), dinar et dirham (seuil d’environ 85 g d’or et 595 g d’argent), awsuq, distance du voyage (environ 80 km)",
    limits: "Ce sont des estimations : les textes donnent des mesures anciennes, et les savants proposent des équivalences qui varient légèrement. Le poids d’un sâ‘ dépend de la denrée.",
  },
  { id: "uthaymin-liqa-zakat", kind: "scholar", author: "Shaykh Muhammad ibn Sâlih al-‘Uthaymîn", reference: "Ibn ‘Uthaymîn — Liqâ’ al-Bâb al-Maftûh (al-Maktaba ash-Shâmila, livre 7687, p. 4153)", scope: "l’or et l’argent sont soumis à la zakât « en toutes circonstances », bijoux compris ; les biens destinés au commerce ; seuil de 85 g d’or et 595 g d’argent ; on ne complète pas l’or par l’argent" },
  { id: "uthaymin-sa", kind: "scholar", author: "Shaykh Muhammad ibn Sâlih al-‘Uthaymîn", reference: "Ibn ‘Uthaymîn — réponse sur la mesure du sâ‘ prophétique (enregistrement, alathar.net)", scope: "le sâ‘ prophétique pesé en bon blé : 2,040 kg ; le poids change selon la denrée, et il faut augmenter le poids pour une denrée plus lourde" },
  { id: "binbaz-zakat-savings", kind: "scholar", author: "Shaykh ‘Abd al-‘Azîz ibn Bâz", reference: "Ibn Bâz — Majmû‘ al-Fatâwâ, 14/129", scope: "l’argent épargné, pour le mariage, une maison ou autre, est soumis à la zakât s’il atteint le seuil et qu’une année est passée, qu’il soit en or, en argent ou en monnaie papier" },
  { id: "binbaz-zakat-fitr-sa", kind: "scholar", author: "Shaykh ‘Abd al-‘Azîz ibn Bâz", reference: "Ibn Bâz — « Zakât al-fitr : un sâ‘ de l’aliment de base du pays » (binbaz.org.sa, article 169)", scope: "un sâ‘ par personne, de toutes les denrées : quatre poignées des deux mains moyennes remplies, soit environ 3 kg" },
  { id: "abudawud-1564", kind: "hadith", reference: "Sunan Abî Dâwûd, 1564", authenticity: "Hasan selon al-Albânî", scope: "Umm Salama portait des bijoux en or : Ce dont la zakât est payée n’est pas un trésor (kanz)" },
  { id: "abudawud-1565", kind: "hadith", reference: "Sunan Abî Dâwûd, 1565", authenticity: "Sahîh selon al-Albânî", scope: "‘Â’isha portait des bagues en argent sans en payer la zakât : « Cela suffit pour te mener au Feu »" },
  { id: "abudawud-1811", kind: "hadith", reference: "Sunan Abî Dâwûd, 1811", authenticity: "Sahîh selon al-Albânî", scope: "l’homme qui faisait la talbiya pour Shubruma : « Accomplis d’abord le hajj pour toi-même, puis fais-le pour Shubrumah »" },
  { id: "abudawud-1985", kind: "hadith", reference: "Sunan Abî Dâwûd, 1985", authenticity: "Sahîh selon al-Albânî", scope: "« Le rasage n’est pas une obligation pour les femmes ; seule la coupe des cheveux leur est demandée »" },
  { id: "bukhari-1536", kind: "hadith", reference: "Sahîh al-Bukhârî, 1536", authenticity: "Sahîh", scope: "l’homme entré en ihrâm parfumé et vêtu d’un manteau : « Lave le parfum de ton corps trois fois, enlève le manteau »" },
  { id: "bukhari-1685", kind: "hadith", reference: "Sahîh al-Bukhârî, 1685", authenticity: "Sahîh", scope: "al-Fadl rapporte que le Prophète ﷺ a continué la talbiya jusqu’à la lapidation de Jamrat al-‘Aqaba" },
  { id: "abudawud-365", kind: "hadith", reference: "Sunan Abî Dâwûd, 365", authenticity: "Sahîh selon al-Albânî", scope: "Khawla bint Yasâr : « Il te suffit de laver le sang, la trace ne te fera aucun mal »" },
  { id: "abudawud-376", kind: "hadith", reference: "Sunan Abî Dâwûd, 376", authenticity: "Sahîh selon al-Albânî", scope: "« Seule l’urine d’une fille doit être lavée ; celle d’un garçon doit être simplement aspergée d’eau »" },
  // Purification
  M("223", "La purification est la moitié de la foi"),
  M("224", "aucune prière n’est acceptée sans purification"),
  B("157", "le Prophète ﷺ a fait ses ablutions en lavant chaque membre une fois"),
  B("158", "le Prophète ﷺ a fait ses ablutions en lavant chaque membre deux fois"),
  B("168", "le Prophète ﷺ aimait commencer par la droite, notamment dans sa purification"),
  B("185", "description des ablutions par ‘Abdullah ibn Zayd : essuyage de la tête de l’avant vers l’arrière puis retour"),
  B("60", "Malheur aux talons [négligés], du Feu"),
  M("241", "Malheur aux talons [négligés], du Feu : les pieds doivent être entièrement lavés"),
  M("234", "attestation de foi prononcée après les ablutions et sa récompense"),
  M("243", "un homme avait laissé sur son pied une partie sèche de la taille d’un ongle : « Retourne et fais bien tes ablutions »"),
  AD("175", "l’homme qui avait laissé une partie sèche sur son pied reçut l’ordre de refaire ablutions et prière"),
  AD("142", "bien faire les ablutions, passer l’eau entre les doigts et bien aspirer l’eau sauf en jeûnant"),
  B("201", "ablutions avec un mudd d’eau et ghusl avec un sâ‘ à cinq mudd"),
  B("887", "Si ce n’était pas pénible pour ma communauté, je leur aurais ordonné le siwâk à chaque prière"),
  B("269", "le madhy impose le wudû’ et le lavage de la partie intime, sans ghusl"),
  M("360", "question sur la viande de chameau : Oui, faites les ablutions"),
  B("137", "celui qui doute en prière ne la quitte pas avant d’entendre un son ou de sentir une odeur"),
  M("362", "celui qui ressent quelque chose dans son ventre et doute ne quitte pas la mosquée sans certitude"),
  M("330", "Umm Salama n’a pas à défaire ses tresses pour le ghusl : trois poignées d’eau sur la tête suffisent"),
  B("249", "description du ghusl du Prophète ﷺ par Maymûna"),
  B("877", "Quand l’un de vous vient au vendredi, qu’il fasse le ghusl"),
  B("879", "Le ghusl du vendredi est un devoir pour tout pubère"),
  B("282", "la femme qui a un rêve érotique fait le ghusl si elle voit le liquide"),
  AD("355", "Qays ibn ‘Âsim reçut l’ordre de faire le ghusl en embrassant l’islam"),
  B("335", "la terre a été rendue pour le Prophète ﷺ lieu de prière et moyen de purification"),
  AD("338", "deux hommes ont prié avec le tayammum puis trouvé l’eau dans le temps : l’un a refait, l’autre non, et tous deux ont été approuvés"),
  AD("162", "‘Alî : l’essuyage se fait sur le dessus des khuff"),
  T("96", "Safwân ibn ‘Assâl : on garde les khuff trois jours en voyage, sauf en cas de janâba"),
  B("305", "‘Â’isha, ayant ses règles pendant le Hajj : Fais tout ce que fait le pèlerin, sauf le tawâf"),
  B("304", "la femme qui a ses règles ne prie pas et ne jeûne pas"),
  M("302", "Faites tout, sauf le rapport avec l’épouse qui a ses règles"),
  B("228", "Fâtima bint Abî Hubaysh : la femme en istihâda fait le wudû’ pour chaque prière"),
  B("1926", "le Prophète ﷺ se levait en état de janâba à l’aube, faisait le ghusl et jeûnait"),
  B("223", "urine d’un nourrisson garçon : de l’eau aspergée sur le vêtement"),
  B("218", "deux hommes punis dans leur tombe, dont l’un ne se préservait pas de l’urine"),
  AD("650", "le Prophète ﷺ a retiré ses sandales pendant la prière en apprenant qu’elles étaient souillées, et a poursuivi"),
  Q(6, 145, "la bête morte, le sang répandu et la viande de porc sont une souillure (rijs)"),
  M("366", "« Quand la peau est tannée, elle devient pure »"),
  M("288", "‘Â’isha grattait le sperme du vêtement du Prophète ﷺ qui priait avec"),
  B("283", "Le croyant ne devient pas impur"),
  B("194", "le Prophète ﷺ a versé l’eau de ses ablutions sur Jâbir malade"),

  // Prayer
  M("82", "Entre l’homme et le polythéisme et la mécréance, il y a l’abandon de la prière"),
  M("610a", "les cinq prières dans le récit de Jibrîl"),
  AD("495", "Ordonnez la prière à vos enfants à sept ans", "Hasan sahîh selon al-Albânî"),
  Q(7, 31, "« dans chaque lieu de Salât portez votre parure (vos habits) »"),
  AD("641", "Allah n’accepte pas la prière d’une femme pubère sans voile"),
  B("359", "que personne ne prie dans un seul vêtement sans rien sur les épaules"),
  B("611", "Quand vous entendez l’appel, dites comme le muezzin"),
  M("384", "répéter l’appel, prier sur le Prophète ﷺ puis demander pour lui al-wasîla"),
  M("385", "répondre « lâ ḥawla wa lâ quwwata illâ billâh » à « ḥayya ‘ala-ṣ-ṣalâh » et « ḥayya ‘ala-l-falâḥ »"),
  B("614", "l’invocation après l’adhân et l’intercession promise"),
  AD("499", "les formules de l’adhân et de l’iqâma vues en rêve par ‘Abdullah ibn Zayd", "Hasan sahîh selon al-Albânî"),
  M("612", "les limites de chaque temps de prière enseignées par le Prophète ﷺ"),
  B("527", "l’acte le plus aimé d’Allah : la prière à son heure"),
  T("342", "« Ce qui est entre l’est et l’ouest est qibla » (pour les gens de Médine)"),
  B("400", "prière surérogatoire sur la monture dans sa direction, descente pour l’obligatoire"),
  AD("61", "La clé de la prière est la purification ; on y entre par le takbîr et on en sort par le taslîm", "Hasan sahîh selon al-Albânî"),
  B("735", "lever les mains au takbîr d’ouverture, avant et après le rukû‘"),
  B("740", "poser la main droite sur l’avant-bras gauche"),
  B("744", "invocation d’ouverture : « Allâhumma bâ‘id baynî wa bayna khaṭâyâya… »"),
  M("772", "« Subḥâna rabbiya-l-‘aẓîm » au rukû‘ et « Subḥâna rabbiya-l-a‘lâ » au sujûd"),
  B("796", "l’imam dit « Sami‘a-llâhu liman ḥamidah », les fidèles « Allâhumma rabbanâ laka-l-ḥamd »"),
  B("812", "la prosternation sur sept os : front et nez, mains, genoux, pointes des pieds"),
  M("494", "Quand tu te prosternes, pose tes paumes et lève tes coudes"),
  IM("897", "« Rabbi-ghfir lî, rabbi-ghfir lî » entre les deux prosternations"),
  B("828", "description de la prière par Abû Humayd : le dos droit au rukû‘, l’assise"),
  B("780", "Quand l’imam dit Âmîn, dites Âmîn"),
  B("776", "al-Fâtiha et une sourate dans les deux premières rak‘ât, al-Fâtiha seule dans les deux dernières"),
  B("3370", "la prière sur le Prophète ﷺ (aṣ-ṣalât al-ibrâhîmiyya)"),
  M("588", "demander refuge contre quatre choses avant le salut"),
  Q(2, 286, "« Allah n’impose à aucune âme une charge supérieure à sa capacité »"),
  Q(64, 16, "« Craignez Allah, donc autant que vous pouvez »"),
  B("597", "Celui qui oublie une prière, qu’il la fasse dès qu’il s’en souvient"),
  M("684", "celui qui oublie une prière ou s’endort la fait dès qu’il s’en souvient"),
  B("596", "à la bataille du Fossé, le Prophète ﷺ a prié ‘Asr après le coucher du soleil, puis Maghrib"),
  B("586", "pas de prière après ‘Asr jusqu’au coucher du soleil, ni après Fajr jusqu’au lever"),
  M("831", "trois moments où le Prophète ﷺ interdisait de prier : lever, zénith, coucher du soleil"),
  B("645", "la prière en groupe dépasse de vingt-sept degrés la prière seul"),
  M("653", "l’aveugle qui entend l’appel doit y répondre"),
  B("900", "N’empêchez pas les servantes d’Allah d’aller aux mosquées d’Allah"),
  B("723", "Alignez vos rangs, cela fait partie de l’accomplissement de la prière"),
  M("673", "Que dirige le groupe celui qui récite le mieux le Livre d’Allah"),
  B("691", "mise en garde contre celui qui lève la tête avant l’imam"),
  B("703", "Celui qui dirige les gens, qu’il allège"),
  M("440", "les meilleurs rangs des hommes sont les premiers, ceux des femmes les derniers"),
  B("699", "Ibn ‘Abbâs placé à droite du Prophète ﷺ quand il priait seul avec lui"),
  M("591", "après le salut : « Astaghfiru-llâh » trois fois et « Allâhumma anta-s-salâm… »"),
  M("597", "trente-trois tasbîh, tahmîd et takbîr après chaque prière"),
  B("844", "« Lâ ilâha illa-llâhu waḥdahu… Allâhumma lâ mâni‘a limâ a‘ṭayt… »"),
  B("998", "« Faites du witr votre dernière prière de la nuit »"),
  M("752", "le witr est une rak‘a à la fin de la nuit"),
  M("755", "celui qui craint de ne pas se lever fait le witr en début de nuit"),
  M("728", "douze rak‘ât surérogatoires par jour : une maison au Paradis"),
  B("1180", "Ibn ‘Umar : dix rak‘ât retenues du Prophète ﷺ autour des prières"),
  M("725", "Les deux rak‘ât de l’aube valent mieux que le monde et ce qu’il contient"),
  B("1147", "le Prophète ﷺ ne dépassait pas onze rak‘ât la nuit, en Ramadan comme en dehors"),
  B("2009", "Celui qui prie les nuits de Ramadan avec foi et espérance…"),
  M("1163", "la meilleure prière après l’obligatoire est la prière de la nuit"),
  B("990", "La prière de la nuit se fait deux par deux"),
  B("444", "Quand l’un de vous entre à la mosquée, qu’il prie deux rak‘ât avant de s’asseoir"),
  M("720", "deux rak‘ât de duḥâ valent l’aumône due pour chaque articulation"),
  AD("1067", "le vendredi est un devoir pour tout musulman, sauf l’esclave, la femme, l’enfant et le malade"),
  B("883", "le ghusl, le parfum et le silence pendant le sermon du vendredi"),
  B("935", "le vendredi contient une heure où l’invocation est exaucée"),
  B("934", "dire « tais-toi » pendant le sermon est une parole vaine"),
  AD("1052", "celui qui délaisse trois vendredis par négligence, Allah scelle son cœur", "Hasan sahîh selon al-Albânî"),
  M("881", "quatre rak‘ât après le vendredi"),
  B("937", "Ibn ‘Umar : deux rak‘ât chez soi après le vendredi"),
  AD("1151", "sept takbîr dans la première rak‘a de l’Aïd et cinq dans la seconde", "Hasan selon al-Albânî"),
  B("974", "les femmes, même celles qui ont leurs règles, sortent le jour de l’Aïd"),
  B("953", "manger quelques dattes en nombre impair avant la prière de l’Aïd al-Fitr"),
  B("986", "revenir de l’Aïd par un autre chemin"),
  B("1325", "un qîrât de récompense pour la prière funéraire, deux pour l’enterrement"),

  // Fasting
  AD("2454", "pas de jeûne pour celui qui ne l’a pas résolu avant l’aube"),
  M("1154", "le Prophète ﷺ décidait de jeûner dans la journée quand il n’y avait rien à manger (jeûne surérogatoire)"),
  B("1903", "Celui qui ne délaisse pas la parole mensongère et l’agir selon elle, Allah n’a pas besoin qu’il délaisse sa nourriture et sa boisson"),
  B("1914", "ne pas devancer Ramadan d’un ou deux jours de jeûne"),
  B("1916", "le fil blanc et le fil noir : la clarté du jour et l’obscurité de la nuit"),
  B("1918", "Bilâl appelle de nuit : mangez et buvez jusqu’à l’appel d’Ibn Umm Maktûm"),
  B("1921", "entre le suhûr et la prière de l’aube, le temps de réciter cinquante versets"),
  B("1954", "quand la nuit arrive, que le jour s’en va et que le soleil s’est couché, le jeûneur rompt"),
  AD("2356", "rompre le jeûne avec des dattes fraîches, sinon sèches, sinon de l’eau", "Hasan sahîh selon al-Albânî"),
  AD("2357", "« Dhahaba-ẓ-ẓama’, wa-btallati-l-‘urûq, wa thabata-l-ajru in shâ’a-llâh »", "Hasan selon al-Albânî"),
  T("807", "celui qui donne à manger à un jeûneur obtient une récompense égale à la sienne"),
  B("1927", "le Prophète ﷺ embrassait son épouse en jeûnant, étant le plus maître de son désir"),
  AD("2380", "celui que le vomissement surprend n’a rien à rattraper ; celui qui se fait vomir rattrape"),
  B("1938", "le Prophète ﷺ s’est fait poser des ventouses en jeûnant"),
  B("1943", "à Hamza al-Aslamî : Jeûne si tu veux, romps si tu veux en voyage"),
  B("1946", "Ce n’est pas de la piété de jeûner en voyage (pour celui que le jeûne épuise)"),
  B("1950", "‘Â’isha rattrapait ses jours de Ramadan en Sha‘bân"),
  B("1952", "Celui qui meurt en devant des jours de jeûne, son proche jeûne pour lui"),
  B("4505", "Ibn ‘Abbâs : le vieillard et la vieille femme qui ne peuvent jeûner nourrissent un pauvre par jour"),
  AD("2408", "Allah a allégé le jeûne pour le voyageur, la femme enceinte et celle qui allaite", "Hasan sahîh selon al-Albânî"),
  M("1134", "Si je vis jusqu’à l’an prochain, je jeûnerai le neuvième (‘Âshûrâ’)"),
  B("1988", "le Prophète ﷺ a bu du lait à ‘Arafa, devant les gens : il ne jeûnait pas ce jour-là"),
  B("1997", "pas de jeûne les jours de Tashrîq, sauf pour le pèlerin qui n’a pas trouvé de bête à sacrifier"),
  B("1985", "ne pas jeûner le vendredi seul, sans un jour avant ou après"),
  B("1981", "trois jours de jeûne chaque mois, conseillés à Abû Hurayra"),
  M("1159", "le meilleur jeûne est celui de Dâwûd : un jour sur deux"),
  T("747", "les œuvres sont présentées le lundi et le jeudi ; le Prophète ﷺ aimait jeûner ces jours-là"),
  B("2026", "le Prophète ﷺ faisait la retraite (i‘tikâf) les dix dernières nuits de Ramadan jusqu’à sa mort"),
  Q(97, 3, "« La nuit d’Al-Qadr est meilleure que mille mois »"),
  T("3513", "invocation de la Nuit du Destin : « Allâhumma innaka ‘afuwwun tuḥibbu-l-‘afwa fa‘fu ‘annî »"),

  // Zakât
  B("1395", "Mu‘âdh envoyé au Yémen : une aumône prise de leurs riches et rendue à leurs pauvres"),
  B("1403", "celui qui ne paie pas la zakât de ses biens les verra changés en serpent le Jour de la Résurrection"),
  Q(9, 34, "menace contre ceux qui thésaurisent l’or et l’argent sans les dépenser dans le sentier d’Allah"),
  M("2588", "L’aumône ne diminue en rien les biens"),
  B("1463", "pas de zakât pour le musulman sur son esclave ni sur son cheval"),
  M("1072", "l’aumône ne convient pas à la famille de Muhammad ﷺ"),
  AD("1633", "pas de part dans la zakât pour le riche ni pour l’homme fort capable de gagner sa vie"),
  B("1466", "Zaynab, épouse d’Ibn Mas‘ûd : donner à ses proches vaut deux récompenses"),
  T("623", "Mu‘âdh : un veau d’un an pour trente bovins, une vache de deux ans pour quarante"),
  Q(6, 141, "« acquittez-en les droits le jour de la récolte »"),
  B("1506", "Abû Sa‘îd : un sâ‘ de nourriture, d’orge, de dattes, de fromage séché ou de raisins secs"),
  B("1511", "les Compagnons donnaient la zakât al-fitr un ou deux jours avant l’Aïd"),
  AD("1609", "la zakât al-fitr purifie le jeûneur et nourrit les pauvres ; acceptée si donnée avant la prière", "Hasan selon al-Albânî"),

  // Hajj & ‘Umra
  B("1521", "celui qui fait le Hajj sans obscénité ni perversité revient comme au jour de sa naissance"),
  B("1773", "d’une ‘Umra à l’autre, expiation ; le Hajj accepté n’a d’autre récompense que le Paradis"),
  B("1862", "la femme ne voyage qu’avec un mahram ; un homme inscrit pour une expédition part faire le Hajj avec son épouse"),
  Q(2, 196, "« Et accomplissez pour Allah le pèlerinage et l’Umra » ; compensation du rasage par jeûne, aumône ou sacrifice"),
  Q(2, 197, "le Hajj a lieu en des mois connus ; ni rapports, ni perversité, ni dispute"),
  B("1542", "ce que le muhrim ne porte pas : chemise, turban, pantalon, burnous, khuff, vêtement parfumé"),
  B("1838", "la femme en ihrâm ne porte ni niqâb ni gants"),
  M("1409", "le muhrim ne se marie pas et ne marie personne"),
  Q(5, 95, "interdiction de tuer le gibier en état d’ihrâm"),
  B("1814", "Ka‘b ibn ‘Ujra : rasage pour une gêne, compensé par trois jours de jeûne, six pauvres nourris ou un mouton"),
  M("1209", "Asmâ’ bint ‘Umays, en lochies, fit le ghusl et entra en ihrâm"),
  B("1736", "le jour du sacrifice, à ceux qui avaient interverti les rites : Fais, il n’y a pas de mal"),
  B("1681", "Sawda a demandé à quitter Muzdalifa avant les gens, ce qui lui fut permis"),
  B("1755", "les gens reçurent l’ordre que leur dernier acte soit à la Maison, sauf la femme en règles"),
  B("1782", "une ‘Umra en Ramadan équivaut à un Hajj"),

  // Funérailles
  B("1294", "N’est pas des nôtres celui qui se frappe les joues et déchire ses habits"),
  B("1280", "pas de deuil au-delà de trois jours, sauf pour l’épouse : quatre mois et dix jours"),
  AD("3132", "Préparez de la nourriture pour la famille de Ja‘far, car il leur est arrivé ce qui les occupe", "Hasan selon al-Albânî"),
  B("1278", "Umm ‘Atiyya : il nous fut interdit de suivre les convois funèbres, sans insistance"),
  B("1343", "les martyrs de Uhud furent enterrés dans leur sang, sans être lavés"),

  // Mariage & famille
  B("5065", "Ô jeunes gens, que celui qui en a les moyens se marie"),
  B("5090", "on épouse une femme pour quatre raisons : choisis celle qui a la religion"),
  M("1424", "« Va la regarder » : voir la future épouse avant le mariage"),
  M("1425", "Cherche, ne serait-ce qu’une bague en fer comme mahr"),
  AD("2083", "le mariage de la femme sans l’accord de son tuteur est nul"),
  B("5167", "Donne un repas de noces, ne serait-ce qu’avec un mouton"),
  T("3895", "« Le meilleur d’entre vous est le meilleur envers sa famille »"),
  Q(65, 7, "« Que celui qui est aisé dépense de sa fortune »"),
  B("5364", "Hind : Prends de quoi te suffire, toi et ton enfant, convenablement"),
  B("5193", "l’épouse qui refuse sans raison l’appel de son mari au lit"),
  Q(2, 230, "après le troisième divorce, la femme n’est plus licite pour lui avant d’avoir épousé un autre"),
  B("5251", "Ibn ‘Umar avait divorcé pendant les règles : ordre de la reprendre"),
  B("5273", "l’épouse de Thâbit ibn Qays rend le jardin et obtient la séparation (khul‘)"),
  Q(2, 234, "la veuve observe quatre mois et dix jours"),
  Q(65, 4, "le délai de la femme enceinte prend fin à l’accouchement"),
  AD("2276", "Tu y as plus droit tant que tu ne te remaries pas (garde de l’enfant)", "Hasan selon al-Albânî"),
  M("1452", "cinq tétées connues rendent l’allaitement interdisant"),
  B("2645", "l’allaitement rend interdit ce que rend interdit la parenté"),
  Q(4, 23, "les femmes qu’il est interdit d’épouser"),

  // Transactions
  AD("3503", "Ne vends pas ce que tu n’as pas"),
  M("102", "Celui qui nous trompe n’est pas des nôtres"),
  IM("2246", "il n’est pas permis de vendre un bien en cachant son défaut"),
  B("2117", "à l’homme souvent trompé : Dis : pas de tromperie"),
  B("2076", "Qu’Allah fasse miséricorde à l’homme facile quand il vend, achète et réclame"),
  M("1598", "malédiction de celui qui consomme l’intérêt, le donne, l’écrit et en témoigne"),
  B("2240", "le salam : mesure connue, poids connu, terme connu"),
  B("2287", "Le retard de paiement du riche est une injustice"),
  B("2387", "celui qui emprunte en voulant rendre, Allah l’aide à rendre"),
  T("1078", "l’âme du croyant reste suspendue à sa dette jusqu’à son règlement"),
  M("1600", "Les meilleurs d’entre vous sont ceux qui remboursent le mieux"),
  Q(2, 283, "le gage remis en garantie d’une dette en voyage"),
  B("2068", "le Prophète ﷺ a mis sa cotte de mailles en gage chez un juif"),
  Q(12, 72, "« Et j’en suis garant »"),
  IM("2443", "Donnez au salarié son salaire avant que sa sueur ne sèche"),
  B("2227", "Allah est l’adversaire de celui qui emploie un salarié sans lui payer son salaire"),
  Q(65, 6, "« donnez-leur leurs salaires » pour l’allaitement"),
  Q(38, 24, "beaucoup d’associés se font du tort, sauf ceux qui croient"),
  M("1551", "Khaybar laissée aux exploitants contre la moitié de la récolte"),
  B("3642", "‘Urwa chargé d’acheter un mouton pour le Prophète ﷺ"),

  // Alimentation & sacrifices
  B("52", "Le licite est clair et l’illicite est clair ; entre les deux, des choses ambiguës"),
  Q(5, 5, "la nourriture des gens du Livre est licite"),
  Q(5, 90, "le vin, les jeux de hasard sont une souillure de l’œuvre du Diable"),
  M("1933", "les animaux à crocs parmi les fauves sont illicites"),
  M("1934", "interdiction des fauves à crocs et des oiseaux à serres"),
  M("1941", "les ânes domestiques interdits, les chevaux permis"),
  B("5495", "les Compagnons mangeaient des sauterelles avec le Prophète ﷺ"),
  M("2003", "Tout enivrant est khamr, et tout khamr est illicite"),
  B("5376", "Mentionne le nom d’Allah, mange de la main droite et devant toi"),
  B("2488", "ce qui fait couler le sang avec le nom d’Allah se mange, sauf la dent et l’ongle"),
  B("5507", "viande dont on ignore si le nom d’Allah a été prononcé : Nommez Allah et mangez"),
  M("1966", "deux béliers sacrifiés de sa main, avec la basmala et le takbîr"),
  M("1961", "ce qui est égorgé avant la prière de l’Aïd n’est que de la viande"),
  M("1977", "celui qui veut sacrifier ne coupe ni cheveux ni ongles dès le début de Dhul-Hijja"),
  M("1963", "N’égorgez qu’une bête d’âge requis (musinna)"),
  AD("2802", "quatre défauts rendent la bête impropre au sacrifice"),
  Q(22, 36, "« mangez-en, et nourrissez-en le besogneux discret et le mendiant »"),
  B("5472", "Avec le garçon, une ‘aqîqa : versez pour lui le sang"),
  AD("2838", "l’enfant est lié à sa ‘aqîqa, égorgée le septième jour ; on le rase et on le nomme"),
  T("1513", "deux moutons pour le garçon, un pour la fille"),

  // Serments & vœux
  B("2679", "Que celui qui jure jure par Allah ou se taise"),
  AD("3251", "Celui qui jure par autre qu’Allah a commis du polythéisme"),
  Q(2, 225, "Allah ne vous tient pas rigueur des serments irréfléchis"),
  Q(66, 2, "Allah vous a prescrit de vous délier de vos serments (par l’expiation)"),
  B("6622", "si tu vois mieux que ton serment, fais le mieux et expie ton serment"),
  B("6675", "le faux serment délibéré fait partie des grands péchés"),
  T("1532", "celui qui jure en disant « in shâ’ Allah » n’est pas parjure"),
  B("6608", "le vœu n’apporte rien ; il extrait seulement quelque chose de l’avare"),
  B("6698", "Sa‘d accomplit le vœu de sa mère défunte"),
  M("1645", "L’expiation du vœu est l’expiation du serment"),

  // Vêtements & parure
  AD("4057", "la soie et l’or sont interdits aux hommes de ma communauté, permis aux femmes"),
  B("5787", "ce qui descend sous les chevilles du vêtement (par orgueil) est dans le Feu"),
  B("5885", "malédiction des hommes qui imitent les femmes et des femmes qui imitent les hommes"),
  M("91", "Allah est beau et aime la beauté ; l’orgueil, c’est refuser la vérité et mépriser les gens"),
  B("5889", "cinq actes de la fitra : circoncision, rasage du pubis, moustache, ongles, aisselles"),
  M("261", "dix actes de la fitra, dont laisser la barbe et le siwâk"),
  B("5892", "Laissez pousser la barbe et taillez la moustache"),
  M("2102", "Changez ce blanc, et évitez le noir"),
  B("5921", "interdiction du qaza‘ : raser une partie de la tête et en laisser une autre"),

  // Vie quotidienne
  B("142", "invocation en entrant aux toilettes : « Allâhumma innî a‘ûdhu bika mina-l-khubuthi wa-l-khabâ’ith »"),
  T("7", "en sortant des toilettes : « Ghufrânak »"),
  B("153", "ne pas se nettoyer de la main droite"),
  B("6320", "épousseter son lit avant de dormir"),
  M("54", "Répandez le salâm entre vous"),
  B("6232", "le monté salue le piéton, le passant celui qui est assis, le petit groupe le grand"),
  B("6224", "l’éternuement : « Al-ḥamdu li-llâh », « Yarḥamuka-llâh », « Yahdîkumu-llâh… »"),
  B("6245", "demander la permission trois fois, puis repartir"),
  B("6018", "Que celui qui croit en Allah et au Jour dernier honore son voisin"),
  M("1342", "l’invocation du voyage"),
  AD("2608", "à trois en voyage, qu’ils désignent l’un d’eux comme chef", "Hasan sahîh selon al-Albânî"),
  B("1797", "au retour : « Âyibûna tâ’ibûna ‘âbidûna li-rabbinâ ḥâmidûn »"),
  B("6269", "ne pas faire lever quelqu’un pour prendre sa place"),
  B("6288", "deux ne conversent pas à l’écart du troisième"),
  T("3433", "l’expiation de l’assemblée : « Subḥânaka-llâhumma wa bi-ḥamdik… »"),

  // Justice & droits
  M("1711", "si on donnait aux gens selon leurs prétentions… ; le serment incombe au défendeur"),
  M("1712", "le Prophète ﷺ a jugé avec un témoin et un serment"),
  B("7158", "le juge ne juge pas entre deux personnes alors qu’il est en colère"),
  B("7169", "Je ne suis qu’un humain ; certains sont plus habiles à plaider"),
  AD("3594", "la conciliation est permise entre musulmans, sauf celle qui rend licite l’illicite", "Hasan sahîh selon al-Albânî"),
  B("2654", "le faux témoignage parmi les plus grands péchés"),
  Q(65, 2, "« prenez deux hommes intègres parmi vous comme témoins »"),
  M("1722", "le bien trouvé s’annonce un an ; si son propriétaire vient, on le lui rend"),
  IM("2340", "Ni dommage ni représaille préjudiciable"),
  B("5225", "un plat cassé remplacé par un plat"),

  // Héritage & testaments
  Q(4, 7, "aux hommes et aux femmes revient une part de ce que laissent les parents et les proches"),
  B("2738", "le musulman qui a de quoi léguer ne passe pas deux nuits sans testament écrit"),
  AD("2870", "Pas de testament en faveur d’un héritier", "Hasan sahîh selon al-Albânî"),
  T("2094", "‘Alî : la dette est réglée avant le testament", "Hasan selon al-Albânî"),
  T("2109", "le meurtrier n’hérite pas"),

  // Chasse & animaux
  Q(5, 96, "le gibier de mer est permis ; le gibier de terre est interdit en ihrâm"),
  B("5476", "gibier atteint par la pointe : on mange ; par le plat : il est assommé"),
  M("1929", "la chasse au chien dressé avec la mention du nom d’Allah"),
  M("1931", "le gibier retrouvé après plusieurs jours se mange s’il n’est pas avarié"),
  B("2322", "garder un chien sans nécessité (chasse, troupeau, champ) diminue les œuvres d’un qîrât chaque jour"),
  B("3482", "une femme est entrée en Enfer à cause d’une chatte qu’elle avait enfermée"),
  M("1957", "malédiction de celui qui prend un être vivant pour cible"),
  M("2117", "interdiction de frapper ou de marquer au visage"),
  B("3314", "cinq nuisibles que l’on tue même dans l’enceinte sacrée"),

  // Siyar & relations
  Q(17, 34, "« Et remplissez l’engagement, car on sera interrogé au sujet des engagements »"),
  Q(60, 8, "Allah n’interdit pas d’être bon et juste envers ceux qui ne vous combattent pas"),
  B("3179", "la protection accordée par les musulmans est une, le plus humble d’entre eux peut l’accorder"),
  M("1731", "consignes aux armées : ne pas trahir, ne pas mutiler, ne pas tuer d’enfant"),
  M("1787", "Nous respectons leur pacte (Hudhayfa et son père)"),
];

export { B, M, AD, T, IM, Q };
