-- OUMMAH Scan: first provenance-backed scientific seed.
-- This migration does not alter the health score or the scan verdict.
alter table public.food_additive_science
  add column if not exists adi_display text,
  add column if not exists adi_authority text,
  add column if not exists health_effects jsonb not null default '[]'::jsonb,
  add column if not exists exposure_assessment jsonb not null default '{}'::jsonb,
  add column if not exists assessment_history jsonb not null default '[]'::jsonb;

insert into public.food_additive_science (
  code, canonical_name, function_classes, regulatory_status, eu_authorized, eu_conditions,
  adi_value, adi_unit, adi_display, adi_authority, severity, evidence_strength,
  exposure_concern, scientific_classification, scientific_summary, health_effects,
  sensitive_populations, exposure_assessment, assessment_history, sources,
  regulatory_source_updated_at, scientific_reviewed_at, needs_scientific_review, data_version
)
values
('E150D', 'Caramel au sulfite d’ammonium', '["colour"]'::jsonb, null, null, '{}'::jsonb,
 null, null, null, null, 'none', 'strong', 'unlikely', 'no_particular_signal',
 'Les évaluations officielles intégrées sont rassurantes dans les conditions autorisées. La quantité présente dans ce produit n’est pas mesurée.', '[]'::jsonb, '[]'::jsonb,
 '{"exposureConclusion":"Les données intégrées ne montrent pas de signal particulier dans les conditions autorisées ; l’exposition individuelle du produit n’est pas mesurée.","sourceIds":["e150d-efsa-colours","e150d-efsa-2012"]}'::jsonb,
 '[{"organisation":"EFSA","date":"2012-12-19","conclusion":"Exposition des consommateurs estimée inférieure aux estimations précédentes pour les caramels évalués.","sourceId":"e150d-efsa-2012"}]'::jsonb,
 '[{"sourceId":"e150d-eu-database","organisation":"European Commission","sourceType":"regulation","title":"Food additives database","url":"https://food.ec.europa.eu/food-safety/food-improvement-agents/additives/database_en","retrievedAt":"2026-09-16","fieldsSupported":["regulatory_status","eu_authorized"]},{"sourceId":"e150d-efsa-colours","organisation":"EFSA","sourceType":"official_information","title":"Food colours","url":"https://www.efsa.europa.eu/en/topics/topic/food-colours","publishedAt":"2026-09-15","retrievedAt":"2026-09-16","fieldsSupported":["scientific_summary","severity","evidence_strength","exposure_concern"]},{"sourceId":"e150d-efsa-2012","organisation":"EFSA","sourceType":"scientific_opinion","title":"Caramel colours: consumer exposure lower than previously estimated","url":"https://www.efsa.europa.eu/en/press/news/121219","publishedAt":"2012-12-19","retrievedAt":"2026-09-16","fieldsSupported":["exposure_concern","assessment_history"]}]'::jsonb,
 '2026-09-15', '2026-09-15', false, '1.0'),
('E331', 'Citrates de sodium', '["acidity_regulator","sequestrant"]'::jsonb, null, null, '{}'::jsonb,
 null, null, null, null, 'none', 'insufficient', 'unknown', 'insufficient_data',
 'Le code E331 regroupe des formes de citrate. Les données intégrées ici ne permettent pas de conclure sur une exposition ou un effet spécifique au produit.', '[]'::jsonb, '[]'::jsonb,
 '{"exposureConclusion":"Exposition et forme précise non déterminées avec les données disponibles.","sourceIds":["e331-efsa-call"]}'::jsonb, '[]'::jsonb,
 '[{"sourceId":"e331-eu-database","organisation":"European Commission","sourceType":"regulation","title":"Food additives database","url":"https://food.ec.europa.eu/food-safety/food-improvement-agents/additives/database_en","retrievedAt":"2026-09-16","fieldsSupported":["regulatory_status","eu_authorized"]},{"sourceId":"e331-efsa-call","organisation":"EFSA","sourceType":"official_information","title":"Open call for food additives analytical data and use levels","url":"https://www.efsa.europa.eu/en/call/open-call-food-additives-analytical-data-and-use-levels-food-and-beverages-intended-human","retrievedAt":"2026-09-16","fieldsSupported":["scientific_summary","exposure_concern"]}]'::jsonb,
 '2026-09-16', '2026-09-16', true, '1.0'),
('E338', 'Acide phosphorique', '["acidity_regulator"]'::jsonb, 'Autorisé dans l’Union européenne sous les conditions applicables de la liste de l’Union', true, '{}'::jsonb,
 40, 'mg de phosphore/kg de poids corporel/jour', '40 mg de phosphore/kg de poids corporel/jour', 'EFSA', 'moderate', 'strong', 'possible', 'limited_concern',
 'L’EFSA a établi une DJA groupée pour les phosphates. Elle concerne l’exposition totale et ne permet pas de conclure que ce produit dépasse la DJA, car sa quantité réelle d’additif est inconnue.', '[]'::jsonb, '[]'::jsonb,
 '{"adiValue":40,"adiUnit":"mg de phosphore/kg de poids corporel/jour","adiDisplay":"40 mg de phosphore/kg de poids corporel/jour","exposureConclusion":"La DJA concerne l’exposition totale aux phosphates ; la dose de ce produit est inconnue.","sourceIds":["e338-efsa-2019"]}'::jsonb,
 '[{"organisation":"EFSA","date":"2019-06-04","conclusion":"DJA groupée de 40 mg de phosphore/kg de poids corporel/jour pour les phosphates.","sourceId":"e338-efsa-2019"}]'::jsonb,
 '[{"sourceId":"e338-eu-database","organisation":"European Commission","sourceType":"regulation","title":"Food additives database","url":"https://food.ec.europa.eu/food-safety/food-improvement-agents/additives/database_en","retrievedAt":"2026-09-16","fieldsSupported":["regulatory_status","eu_authorized"]},{"sourceId":"e338-efsa-2019","organisation":"EFSA","sourceType":"scientific_opinion","title":"Re-evaluation of phosphoric acid–phosphates","url":"https://doi.org/10.2903/j.efsa.2019.5674","publishedAt":"2019-06-04","retrievedAt":"2026-09-16","fieldsSupported":["adi_value","adi_unit","adi_authority","exposure_concern","assessment_history"]},{"sourceId":"e338-efsa-press-2019","organisation":"EFSA","sourceType":"scientific_opinion","title":"Nouvel avis scientifique de l’EFSA sur les phosphates","url":"https://www.efsa.europa.eu/fr/press/news/190612","publishedAt":"2019-06-12","retrievedAt":"2026-09-16","fieldsSupported":["scientific_summary","exposure_concern"]}]'::jsonb,
 '2019-06-04', '2019-06-04', false, '1.0'),
('E950', 'Acésulfame-K', '["sweetener"]'::jsonb, 'Autorisé dans l’Union européenne sous les conditions applicables de la liste de l’Union', true, '{}'::jsonb,
 15, 'mg/kg de poids corporel/jour', '15 mg/kg de poids corporel/jour', 'EFSA', 'low', 'strong', 'unknown', 'no_particular_signal',
 'L’EFSA a réévalué l’acésulfame-K et établi une DJA. Le scan ne mesure pas l’exposition individuelle du produit.', '[]'::jsonb, '[]'::jsonb,
 '{"adiValue":15,"adiUnit":"mg/kg de poids corporel/jour","adiDisplay":"15 mg/kg de poids corporel/jour","exposureConclusion":"DJA officielle disponible ; l’exposition individuelle du produit n’est pas mesurée.","sourceIds":["e950-efsa-2025"]}'::jsonb,
 '[{"organisation":"EFSA","date":"2025-04-30","conclusion":"Réévaluation officielle de l’acésulfame-K et DJA de 15 mg/kg de poids corporel/jour.","sourceId":"e950-efsa-2025"}]'::jsonb,
 '[{"sourceId":"e950-eu-database","organisation":"European Commission","sourceType":"regulation","title":"Food additives database","url":"https://food.ec.europa.eu/food-safety/food-improvement-agents/additives/database_en","retrievedAt":"2026-09-16","fieldsSupported":["regulatory_status","eu_authorized"]},{"sourceId":"e950-efsa-2025","organisation":"EFSA","sourceType":"scientific_opinion","title":"Réévaluation de l’acésulfame K (E950)","url":"https://www.efsa.europa.eu/fr/plain-language-summary/re-evaluation-acesulfame-k-e-950-food-additive","publishedAt":"2025-04-30","retrievedAt":"2026-09-16","fieldsSupported":["adi_value","adi_unit","adi_authority","scientific_summary","assessment_history"]},{"sourceId":"e950-efsa-sweeteners","organisation":"EFSA","sourceType":"official_information","title":"Sweeteners","url":"https://www.efsa.europa.eu/en/topics/topic/sweeteners","retrievedAt":"2026-09-16","fieldsSupported":["scientific_summary"]}]'::jsonb,
 '2025-04-30', '2025-04-30', false, '1.0'),
('E951', 'Aspartame', '["sweetener"]'::jsonb, 'Autorisé dans l’Union européenne sous les conditions applicables de la liste de l’Union', true, '{}'::jsonb,
 null, 'mg/kg de poids corporel/jour', '0 à 40 mg/kg de poids corporel/jour', 'JECFA', 'serious', 'limited', 'unknown', 'limited_concern',
 'Le CIRC a signalé un danger potentiel avec des indices limités. Le JECFA a maintenu une DJA ; ces éléments ne mesurent pas le risque pour ce produit particulier.', '[{"category":"carcinogenicity","effect":"Peut-être cancérogène, groupe 2B, sur la base d’indices limités.","severity":"serious","evidenceStrength":"limited_evidence","sourceIds":["e951-who-2023"]}]'::jsonb, '["Personnes atteintes de phénylcétonurie"]'::jsonb,
 '{"adiDisplay":"0 à 40 mg/kg de poids corporel/jour","exposureConclusion":"DJA JECFA disponible ; l’exposition individuelle du produit n’est pas mesurée.","sourceIds":["e951-jecfa-2023"]}'::jsonb,
 '[{"organisation":"JECFA","date":"2023-07-14","conclusion":"DJA de 0 à 40 mg/kg de poids corporel/jour maintenue.","sourceId":"e951-jecfa-2023"},{"organisation":"CIRC","date":"2023-07-14","conclusion":"Classification groupe 2B, indices limités.","sourceId":"e951-who-2023"}]'::jsonb,
 '[{"sourceId":"e951-eu-database","organisation":"European Commission","sourceType":"regulation","title":"Food additives database","url":"https://food.ec.europa.eu/food-safety/food-improvement-agents/additives/database_en","retrievedAt":"2026-09-16","fieldsSupported":["regulatory_status","eu_authorized"]},{"sourceId":"e951-who-2023","organisation":"OMS / CIRC / JECFA","sourceType":"international_agency","title":"Aspartame hazard and risk assessment results released","url":"https://www.who.int/news/item/14-07-2023-aspartame-hazard-and-risk-assessment-results-released","publishedAt":"2023-07-14","retrievedAt":"2026-09-16","fieldsSupported":["health_effects","severity","evidence_strength"]},{"sourceId":"e951-jecfa-2023","organisation":"OMS / JECFA","sourceType":"international_agency","title":"JECFA — Aspartame","url":"https://apps.who.int/food-additives-contaminants-jecfa-database/Home/Chemical/62","publishedAt":"2023","retrievedAt":"2026-09-16","fieldsSupported":["adi_display","adi_authority","exposure_concern"]},{"sourceId":"e951-efsa-topic","organisation":"EFSA","sourceType":"official_information","title":"Aspartame","url":"https://www.efsa.europa.eu/en/topics/topic/aspartame","retrievedAt":"2026-09-16","fieldsSupported":["scientific_summary"]}]'::jsonb,
 '2023-07-14', '2023-07-14', false, '1.0')
on conflict (code) do update set
  canonical_name = excluded.canonical_name,
  function_classes = excluded.function_classes,
  regulatory_status = excluded.regulatory_status,
  eu_authorized = excluded.eu_authorized,
  eu_conditions = excluded.eu_conditions,
  adi_value = excluded.adi_value,
  adi_unit = excluded.adi_unit,
  adi_display = excluded.adi_display,
  adi_authority = excluded.adi_authority,
  severity = excluded.severity,
  evidence_strength = excluded.evidence_strength,
  exposure_concern = excluded.exposure_concern,
  scientific_classification = excluded.scientific_classification,
  scientific_summary = excluded.scientific_summary,
  health_effects = excluded.health_effects,
  sensitive_populations = excluded.sensitive_populations,
  exposure_assessment = excluded.exposure_assessment,
  assessment_history = excluded.assessment_history,
  sources = excluded.sources,
  regulatory_source_updated_at = excluded.regulatory_source_updated_at,
  scientific_reviewed_at = excluded.scientific_reviewed_at,
  needs_scientific_review = excluded.needs_scientific_review,
  data_version = excluded.data_version,
  updated_at = now();
