-- OUMMAH Scan — grille de critères des organismes halal + repères religieux.
-- Règles éditoriales (validées) :
--  * la grille ne note pas les organismes : chaque critère vaut « yes » (déclaré/vérifié), « partial »,
--    « no » (uniquement si l'organisme l'indique lui-même) ou « unknown » (non documenté) ;
--  * les repères religieux sont rédigés par sujet (Coran, Sunna, Compagnons, savants retenus : Ibn Bâz,
--    Al-Albânî, Ibn ‘Uthaymîn, Al-Fawzân) et ne mentionnent jamais un organisme ;
--  * fatwas du Comité permanent : attribuées au Comité, avec la mention des signataires.

alter table public.halal_certification_bodies add column if not exists criteria jsonb not null default '{}'::jsonb;

-- Grille : uniquement ce que les pages officielles consultées le 03/10/2026 indiquent ------------------
update public.halal_certification_bodies set criteria = $j${
  "noStunning": {"status": "yes", "value": "Aucun procédé d’assommage accepté, pour tous les animaux (ovins, bovins, volailles) ; l’organisme garantit que l’animal est vivant au moment de l’égorgement.", "sourceStatus": "declared_by_body", "sources": [{"title": "AVS et l’interdiction de l’assommage", "organisation": "AVS", "url": "https://avs.fr/avs-et-linterdiction-de-lassommage/"}]},
  "permanentControl": {"status": "yes", "value": "Présence permanente et continue des contrôleurs sur tous les sites de production et de transformation ; aucune certification sans leur présence.", "sourceStatus": "declared_by_body", "sources": [{"title": "Les procédés de certification utilisés par AVS", "organisation": "AVS", "url": "https://avs.fr/les-procedes-de-certification-utilise-par-avs-pour-garantir-le-caractere-halal-des-viandes/"}, {"title": "FAQ", "organisation": "AVS", "url": "https://avs.fr/faq/"}]},
  "traceability": {"status": "yes", "value": "Contrôleurs présents de l’abattage jusqu’à l’emballage ; matériel d’authentification personnalisé, toujours en possession des contrôleurs.", "sourceStatus": "declared_by_body", "sources": [{"title": "FAQ", "organisation": "AVS", "url": "https://avs.fr/faq/"}]}
}$j$::jsonb where id = 'avs';

update public.halal_certification_bodies set criteria = $j${
  "noStunning": {"status": "partial", "value": "Bovins : abattage rituel « garanti sans étourdissement ante ou post mortem ». Volailles : la page consultée décrit l’électronarcose sans préciser la règle appliquée par l’organisme.", "sourceStatus": "declared_by_body", "sources": [{"title": "Halal meat certification", "organisation": "ARGML", "url": "https://argml.com/en/halal-certification/meat/"}]},
  "permanentControl": {"status": "yes", "value": "Contrôleurs rituels salariés de l’association, affectés en permanence aux sites pendant les productions halal, du sacrifice jusqu’au conditionnement final.", "sourceStatus": "declared_by_body", "sources": [{"title": "The ARGML", "organisation": "ARGML", "url": "https://argml.com/en/the-argml/"}]},
  "traceability": {"status": "yes", "value": "Les matières premières carnées arrivent sous scellé ARGML pour une continuité permanente de la traçabilité.", "sourceStatus": "declared_by_body", "sources": [{"title": "Meat products", "organisation": "ARGML", "url": "https://argml.com/en/halal-certification/meat-products/"}]},
  "ingredients": {"status": "yes", "value": "Contrôle des ingrédients, additifs, auxiliaires de fabrication, gélatines et alcool dans les produits transformés.", "sourceStatus": "declared_by_body", "sources": [{"title": "Processed products", "organisation": "ARGML", "url": "https://argml.com/en/halal-certification/processed-products/"}]}
}$j$::jsonb where id = 'argml';

update public.halal_certification_bodies set criteria = $j${
  "slaughterer": {"status": "yes", "value": "Abattage effectué par un musulman pratiquant et doué de raison.", "sourceStatus": "declared_by_body", "sources": [{"title": "L’association Achahada", "organisation": "Achahada", "url": "https://achahada.com/lassociation-achahada/"}]},
  "tasmiya": {"status": "yes", "value": "Invocation de la basmala par le préposé au sacrifice, avant la saignée, sur chaque bête.", "sourceStatus": "declared_by_body", "sources": [{"title": "L’association Achahada", "organisation": "Achahada", "url": "https://achahada.com/lassociation-achahada/"}]},
  "noStunning": {"status": "yes", "value": "Sans étourdissement préalable et sans électronarcose avant ou après la saignée.", "sourceStatus": "declared_by_body", "sources": [{"title": "L’association Achahada", "organisation": "Achahada", "url": "https://achahada.com/lassociation-achahada/"}]},
  "permanentControl": {"status": "partial", "value": "Contrôle journalier, 7 jours sur 7 ; le sacrifice est fait par un préposé de l’association ou sous son contrôle. La présence continue sur toute la chaîne n’est pas précisée.", "sourceStatus": "declared_by_body", "sources": [{"title": "L’association Achahada", "organisation": "Achahada", "url": "https://achahada.com/lassociation-achahada/"}]},
  "traceability": {"status": "yes", "value": "Étiquetage des barquettes par les contrôleurs ; aucun matériel d’estampillage laissé sur site sans eux.", "sourceStatus": "declared_by_body", "sources": [{"title": "Traçabilité", "organisation": "Achahada", "url": "https://achahada.com/tracabilite/"}]},
  "noMSM": {"status": "yes", "value": "Cahier des charges : pas de VSM (viande séparée mécaniquement).", "sourceStatus": "declared_by_body", "sources": [{"title": "L’association Achahada", "organisation": "Achahada", "url": "https://achahada.com/lassociation-achahada/"}]}
}$j$::jsonb where id = 'achahada';

update public.halal_certification_bodies set criteria = $j${
  "ingredients": {"status": "yes", "value": "Le contrôle porte sur les produits agroalimentaires afin d’identifier toute substance ou additif non conforme.", "sourceStatus": "declared_by_body", "sources": [{"title": "Certification halal", "organisation": "SFCVH", "url": "https://www.sfcvh.com/certification_halal/"}]}
}$j$::jsonb where id = 'sfcvh';

-- Repères religieux ------------------------------------------------------------------------------------
create table if not exists public.halal_religious_guides (
  id text primary key,
  sort_order integer not null default 0,
  title text not null,
  question text not null,
  quran jsonb not null default '[]'::jsonb,
  sunnah jsonb not null default '[]'::jsonb,
  companions jsonb not null default '[]'::jsonb,
  scholars jsonb not null default '[]'::jsonb,
  agreement text,
  divergence text,
  reading text,
  last_verified_at date not null,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.halal_religious_guides enable row level security;
drop policy if exists "Public can read halal religious guides" on public.halal_religious_guides;
create policy "Public can read halal religious guides"
  on public.halal_religious_guides for select to anon, authenticated using (is_active);
grant select on public.halal_religious_guides to anon, authenticated;

insert into public.halal_religious_guides (id, sort_order, title, question, quran, sunnah, companions, scholars, agreement, divergence, reading, last_verified_at)
values
('stunning', 1, 'Étourdissement / électronarcose', 'L’animal étourdi avant l’égorgement est-il licite ?',
 $j$[{"reference": "Al-Mâ’ida 5:3", "text": "Sens : vous sont interdites la bête morte, le sang, la viande de porc, […] la bête étouffée, la bête assommée (al-mawqûdha) […], sauf celle que vous avez égorgée (avant sa mort)."}]$j$::jsonb,
 $j$[{"reference": "Muslim 1955 (Shaddâd ibn Aws)", "text": "« Allah a prescrit l’excellence en toute chose […] Lorsque vous égorgez, égorgez de la meilleure façon : que chacun aiguise sa lame et soulage sa bête. »", "sources": [{"title": "Sahîh Muslim, chapitre de l’ordre de bien égorger", "organisation": "Sahîh Muslim (bibliothèque Islamweb)", "url": "https://www.islamweb.net/ar/library/content/1/3687/"}]}]$j$::jsonb,
 $j$[{"name": "‘Abdullâh ibn ‘Umar", "text": "À propos du gibier tué par une boulette (al-bunduqa) : « C’est la mawqûdha » (la bête assommée).", "reference": "Rapporté par Al-Bukhârî (ta‘lîq), Livre des sacrifices et de la chasse, chapitre du gibier tué par le plat de la flèche", "sources": [{"title": "Sahîh al-Bukhârî, 7/243 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3573"}]}]$j$::jsonb,
 $j$[
  {"scholar": "Ibn Bâz", "position": "La bête morte de l’étourdissement est interdite (comme la bête assommée ou étouffée) ; « ce qui a été étourdi ou frappé, puis trouvé vivant et égorgé selon la règle, est licite ».", "reference": "Majmû‘ Fatâwâ Ibn Bâz 8/428 — revue Al-Islâh n° 90, dhû al-qa‘da 1405 H", "sources": [{"title": "حكم الحيوان المذبوح بالصعق الكهربائي", "organisation": "Site officiel d’Ibn Bâz", "url": "https://binbaz.org.sa/articles/156/%D8%AD%D9%83%D9%85-%D8%A7%D9%84%D8%AD%D9%8A%D9%88%D8%A7%D9%86-%D8%A7%D9%84%D9%85%D8%B0%D8%A8%D9%88%D8%AD-%D8%A8%D8%A7%D9%84%D8%B5%D8%B9%D9%82-%D8%A7%D9%84%D9%83%D9%87%D8%B1%D8%A8%D8%A7%D9%89%D9%8A"}]},
  {"scholar": "Comité permanent (fatwa signée par Ibn Bâz)", "position": "Fatwa n° 1665 : morte de l’étourdissement, la bête est interdite (consensus rapporté) ; rattrapée vivante et égorgée, elle est licite. L’acte d’étourdir est lui-même interdit car il fait souffrir l’animal, sauf s’il est impossible de l’égorger autrement.", "reference": "Fatâwâ al-Lajna ad-Dâ’ima, 1re série, tome 22", "sources": [{"title": "صعق الحيوان بالكهرباء قبل ذبحه", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17241"}]},
  {"scholar": "Comité permanent (fatwas signées par Al-Fawzân et Ibn Bâz)", "position": "Fatwa n° 18476 : étourdie puis égorgée vivante, la bête est licite ; morte de l’étourdissement, elle est interdite. Fatwa n° 17924 : l’anesthésie avant l’égorgement n’est pas permise car elle peut tuer la bête ; si celle-ci est égorgée vivante, elle reste licite.", "reference": "Fatâwâ al-Lajna ad-Dâ’ima, 1re série, tome 22", "sources": [{"title": "تخدير الحيوانات قبل الذبح", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17302"}, {"title": "الإحسان في الذبيحة", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17261"}]},
  {"scholar": "Ibn ‘Uthaymîn", "position": "Une bête étourdie dont on fait couler le sang avant sa mort est licite. Face à ce qui se dit des abattoirs étrangers, « le scrupule (al-wara‘) est de s’en abstenir », sans péché pour qui en mange.", "reference": "Majmû‘ Fatâwâ wa Rasâ’il 15/442 (question 1182) ; Fatâwâ Nûr ‘alâ ad-Darb 20/2", "sources": [{"title": "Majmû‘ Fatâwâ wa Rasâ’il 15/442", "organisation": "Ibn ‘Uthaymîn", "url": "https://shamela.ws/book/12293/5962"}, {"title": "Fatâwâ Nûr ‘alâ ad-Darb 20/2", "organisation": "Ibn ‘Uthaymîn", "url": "https://shamela.ws/book/2300/5897"}]},
  {"scholar": "Al-Albânî", "position": "Si l’étourdissement ne tue pas et que la bête est égorgée vivante, sa viande reste licite ; mais étourdir est un péché car c’est une souffrance, et l’on ne peut pas garantir que l’étourdissement ne tue pas. Il a refusé que des musulmans avalisent comme « halal » une chaîne de volailles étourdies par bain électrique.", "reference": "Fatâwâ ‘abr al-hâtif wa as-sayyâra, cassette 152 ; Silsilat al-Hudâ wan-Nûr, cassette 327", "sources": [{"title": "حكم أكل لحم الخروف إذا كانت طريقة ذبحه تتضمن الصعق", "organisation": "Enregistrements d’Al-Albânî (transcription)", "url": "https://www.al-albany.com/audios/content/147242/"}, {"title": "حكم ذبح الدجاج بالآلات الأوتوماتيكية وهي تمر على صعق كهربائي", "organisation": "Enregistrements d’Al-Albânî (transcription)", "url": "https://www.al-albany.com/audios/content/10742/"}]}
 ]$j$::jsonb,
 'Tous s’accordent : une bête morte de l’étourdissement avant d’être égorgée est interdite ; une bête étourdie puis égorgée encore vivante est licite.',
 'Sur l’acte d’étourdir : le Comité permanent l’interdit sauf nécessité et Al-Albânî le considère comme un péché ; Ibn ‘Uthaymîn ne le condamne pas explicitement dans les textes retenus. Sur l’attitude à adopter face au doute : scrupule recommandé (Ibn ‘Uthaymîn), abstention (Al-Albânî).',
 'Un organisme qui refuse tout étourdissement écarte le risque d’une bête morte avant l’égorgement. Un organisme qui l’accepte dépend de la garantie que l’étourdissement ne tue pas, garantie que plusieurs savants jugent difficile à apporter. Cela ne rend pas, à lui seul, un produit « non halal ».',
 '2026-10-03'),

('tasmiya', 2, 'Invocation lors de l’abattage', 'Faut-il prononcer le nom d’Allah sur chaque bête, et que se passe-t-il en cas d’oubli ?',
 $j$[{"reference": "Al-An‘âm 6:121", "text": "Sens : ne mangez pas de ce sur quoi le nom d’Allah n’a pas été prononcé, car ce serait une perversité."}, {"reference": "Al-An‘âm 6:118", "text": "Sens : mangez de ce sur quoi le nom d’Allah a été prononcé, si vous croyez en Ses versets."}]$j$::jsonb,
 $j$[{"reference": "Al-Bukhârî et Muslim 1968 (Râfi‘ ibn Khadîj)", "text": "« Ce qui fait couler le sang et sur quoi le nom d’Allah a été mentionné, mangez-en, sauf la dent et l’ongle. »", "sources": [{"title": "Sahîh al-Bukhârî, 7/265 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3595"}]}, {"reference": "Al-Bukhârî (‘Â’isha), Livre des sacrifices", "text": "Des gens dirent : « Des personnes nous apportent de la viande et nous ne savons pas si le nom d’Allah a été mentionné dessus. » Il ﷺ dit : « Mentionnez-le, vous, et mangez-en. » Elle précisa : ils étaient nouvellement sortis de la mécréance.", "sources": [{"title": "Sahîh al-Bukhârî, 7/263 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3593"}]}]$j$::jsonb,
 $j$[{"name": "‘Abdullâh ibn ‘Abbâs", "text": "« Celui qui oublie, il n’y a pas de mal. » Al-Bukhârî ajoute : l’oublieux n’est pas appelé pervers (fâsiq), en référence à 6:121.", "reference": "Rapporté par Al-Bukhârî (ta‘lîq), chapitre de l’invocation sur la bête égorgée et de celui qui la délaisse volontairement", "sources": [{"title": "Sahîh al-Bukhârî, 7/257 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3587"}]}]$j$::jsonb,
 $j$[
  {"scholar": "Ibn Bâz", "position": "En cas d’oubli, la bête est licite ; l’ignorant est aussi excusé. L’omission volontaire, en connaissant la règle, rend la bête interdite selon l’avis le plus juste.", "reference": "Programme Nûr ‘alâ ad-Darb", "sources": [{"title": "حكم نسيان التسمية عند الذبح", "organisation": "Site officiel d’Ibn Bâz", "url": "https://binbaz.org.sa/fatwas/12153/%D8%AD%D9%83%D9%85-%D9%86%D8%B3%D9%8A%D8%A7%D9%86-%D8%A7%D9%84%D8%AA%D8%B3%D9%85%D9%8A%D8%A9-%D8%B9%D9%86%D8%AF-%D8%A7%D9%84%D8%B0%D8%A8%D8%AD"}]},
  {"scholar": "Comité permanent (fatwas signées par Ibn Bâz)", "position": "Fatwa n° 11490 : la bête dont l’invocation a été oubliée est licite (avis rapporté d’Ibn ‘Abbâs). Fatwa n° 11967 : l’invocation doit venir de l’égorgeur, pas d’un appareil enregistreur.", "reference": "Fatâwâ al-Lajna ad-Dâ’ima, 1re série, tome 22", "sources": [{"title": "الأكل من الذبيحة إذا نسي الذابح التسمية عليها", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17311"}, {"title": "استعمال جهاز تسجيل لتكرار التسمية", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17309"}]},
  {"scholar": "Al-Fawzân", "position": "Quatrième condition de l’abattage : que l’égorgeur dise « bismillâh » au moment du geste ; le takbîr est recommandé avec elle. Comité permanent, fatwa n° 15666 (signée par Al-Fawzân et Ibn Bâz) : l’invocation se fait sur chaque bête, une invocation collective sur un troupeau ne suffit pas.", "reference": "Al-Mulakhkhas al-Fiqhî 2/591 ; Fatâwâ al-Lajna ad-Dâ’ima, 1re série, tome 22", "sources": [{"title": "Al-Mulakhkhas al-Fiqhî 2/591", "organisation": "Al-Fawzân", "url": "https://shamela.ws/book/11811/1005"}, {"title": "التسمية على كامل القطيع", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17303"}]},
  {"scholar": "Ibn ‘Uthaymîn", "position": "L’invocation est une condition qui ne tombe ni par oubli ni par ignorance : celui qui l’oublie n’a pas péché, mais on ne mange pas la bête. Elle doit être prononcée par l’égorgeur lui-même.", "reference": "Al-Sharh al-Mumti‘ 15/86-87", "sources": [{"title": "Al-Sharh al-Mumti‘ 15/86", "organisation": "Ibn ‘Uthaymîn", "url": "https://shamela.ws/book/10649/6314"}]},
  {"scholar": "Al-Albânî", "position": "Le hadith d’‘Â’isha concerne l’invocation, pas la méthode d’abattage : dire « bismillâh » en mangeant ne rend pas licite une bête tuée sans être égorgée. Formule : « bismillâh ».", "reference": "Silsilat al-Hudâ wan-Nûr, cassettes 131 et 731", "sources": [{"title": "ما حكم أكل اللحوم المستوردة من بلغارية وتركيا", "organisation": "Enregistrements d’Al-Albânî (transcription)", "url": "https://www.al-albany.com/audios/content/10674/"}]}
 ]$j$::jsonb,
 'Tous s’accordent : l’invocation est exigée, prononcée par l’égorgeur lui-même, et ni un enregistrement ni une basmala écrite ne la remplacent.',
 'Sur l’oubli : la bête reste licite pour Ibn Bâz et le Comité permanent (avis d’Ibn ‘Abbâs) ; elle ne l’est pas pour Ibn ‘Uthaymîn. Aucun avis d’Al-Albânî sur l’oubli n’a été retrouvé dans une source vérifiable.',
 'Un organisme qui déclare imposer l’invocation sur chaque bête répond à l’exigence commune. Cela ne permet pas, à lui seul, de trancher le cas d’un oubli ponctuel.',
 '2026-10-03'),

('slaughterer', 3, 'Conditions concernant l’abatteur', 'Qui peut égorger une bête dont la viande est licite ?',
 $j$[{"reference": "Al-Mâ’ida 5:5", "text": "Sens : la nourriture de ceux à qui le Livre a été donné vous est permise, et votre nourriture leur est permise."}]$j$::jsonb,
 $j$[{"reference": "Al-Bukhârî 391 (Anas ibn Mâlik)", "text": "« Quiconque prie notre prière, s’oriente vers notre qibla et mange notre bête égorgée, celui-là est le musulman. »", "sources": []}]$j$::jsonb,
 $j$[{"name": "‘Abdullâh ibn ‘Abbâs", "text": "« Leur nourriture : ce sont leurs bêtes égorgées » (à propos de 5:5).", "reference": "Rapporté par Al-Bukhârî (ta‘lîq), chapitre des bêtes égorgées par les Gens du Livre", "sources": [{"title": "Sahîh al-Bukhârî, 7/264 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3594"}]}]$j$::jsonb,
 $j$[
  {"scholar": "Al-Fawzân", "position": "L’égorgeur doit être sain d’esprit, musulman ou des Gens du Livre (juif ou chrétien). Ne sont pas licites les bêtes égorgées par le païen, le mazdéen, l’apostat, ni par celui qui invoque les morts dans les mausolées.", "reference": "Al-Mulakhkhas al-Fiqhî 2/588-589", "sources": [{"title": "Al-Mulakhkhas al-Fiqhî 2/588", "organisation": "Al-Fawzân", "url": "https://shamela.ws/book/11811/1002"}]},
  {"scholar": "Ibn ‘Uthaymîn", "position": "Cinq cas : on sait, ou l’on pense fortement, que l’égorgeur est musulman ou des Gens du Livre : licite ; on doute, ou l’on pense fortement, ou l’on sait qu’il ne l’est pas : interdit. Les chrétiens d’aujourd’hui restent des Gens du Livre tant qu’ils se réclament de leur religion ; on n’a pas à demander comment ils ont égorgé.", "reference": "Majmû‘ Fatâwâ wa Rasâ’il 15/442 (question 1182) ; Al-Sharh al-Mumti‘ 15/62-63 ; Fatâwâ Nûr ‘alâ ad-Darb 20/2", "sources": [{"title": "Majmû‘ Fatâwâ wa Rasâ’il 15/442", "organisation": "Ibn ‘Uthaymîn", "url": "https://shamela.ws/book/12293/5961"}, {"title": "Al-Sharh al-Mumti‘ 15/62", "organisation": "Ibn ‘Uthaymîn", "url": "https://shamela.ws/book/10649/6290"}]},
  {"scholar": "Ibn Bâz", "position": "Viande des pays des Gens du Livre : licite par principe, sauf si l’on sait qu’elle a été tuée par étranglement ou par un coup. Viande des pays non scripturaires : interdite par principe, sauf si l’on sait qu’un musulman ou un homme du Livre l’a égorgée.", "reference": "Programme Nûr ‘alâ ad-Darb", "sources": [{"title": "تفصيل الحكم في اللحوم المستوردة", "organisation": "Site officiel d’Ibn Bâz", "url": "https://binbaz.org.sa/fatwas/5995/%D8%AA%D9%81%D8%B5%D9%8A%D9%84-%D8%A7%D9%84%D8%AD%D9%83%D9%85-%D9%81%D9%8A-%D8%A7%D9%84%D9%84%D8%AD%D9%88%D9%85-%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D9%88%D8%B1%D8%AF%D8%A9"}]},
  {"scholar": "Comité permanent (fatwa signée par Ibn Bâz)", "position": "Fatwa n° 2340 : lorsque les bêtes d’égorgeurs dont l’abattage est valide et d’autres dont il ne l’est pas sont mêlées sans pouvoir être distinguées, elles sont toutes interdites ; il est recommandé de choisir soi-même ses égorgeurs.", "reference": "Fatâwâ al-Lajna ad-Dâ’ima, 1re série, tome 22", "sources": [{"title": "ذبائح البلاد التي اختلط فيها المسلمون والنصارى والوثنيون", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17233"}]},
  {"scholar": "Al-Albânî", "position": "Deux conditions pour la viande des Gens du Livre : l’égorgeur est juif ou chrétien, et la bête est réellement égorgée et non tuée. Trois cas : on sait que c’est licite, on sait que c’est interdit, ou l’on ne sait pas, et alors « laisse ce qui te fait douter ».", "reference": "Silsilat al-Hudâ wan-Nûr, cassettes 253 et 131", "sources": [{"title": "ما حكم اللحوم الذي تأتي من بلاد الكفر كبلغاريا", "organisation": "Enregistrements d’Al-Albânî (transcription)", "url": "https://www.al-albany.com/audios/content/10693/"}, {"title": "ما حكم أكل اللحوم المستوردة من بلغارية وتركيا", "organisation": "Enregistrements d’Al-Albânî (transcription)", "url": "https://www.al-albany.com/audios/content/10674/"}]}
 ]$j$::jsonb,
 'Tous s’accordent : seule est licite la bête égorgée par un musulman ou par un juif ou un chrétien ; celle d’un païen, d’un mazdéen ou d’un apostat ne l’est pas.',
 'Sur la présomption pour la viande des pays occidentaux : licite par principe pour Ibn Bâz et Ibn ‘Uthaymîn (qui recommande toutefois le scrupule) ; Al-Albânî, personnellement convaincu que l’abattage y est rarement conforme, prône l’abstention en cas de doute.',
 'Exiger un sacrificateur musulman va au-delà de la condition de validité commune (musulman ou Gens du Livre) : c’est une précaution supplémentaire.',
 '2026-10-03'),

('mechanical', 4, 'Abattage mécanique', 'Une machine peut-elle égorger, et comment se fait l’invocation ?',
 '[]'::jsonb,
 $j$[{"reference": "Al-Bukhârî et Muslim 1968 (Râfi‘ ibn Khadîj)", "text": "« Ce qui fait couler le sang et sur quoi le nom d’Allah a été mentionné, mangez-en. »", "sources": [{"title": "Sahîh al-Bukhârî, 7/265 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3595"}]}, {"reference": "Muslim 1955 (Shaddâd ibn Aws)", "text": "« Que chacun aiguise sa lame et soulage sa bête. »", "sources": [{"title": "Sahîh Muslim, chapitre de l’ordre de bien égorger", "organisation": "Sahîh Muslim (bibliothèque Islamweb)", "url": "https://www.islamweb.net/ar/library/content/1/3687/"}]}]$j$::jsonb,
 $j$[{"name": "‘Abdullâh ibn ‘Abbâs", "text": "« L’égorgement se fait à la gorge et à la base du cou (al-halq wa al-labba). »", "reference": "Rapporté par Al-Bukhârî (ta‘lîq), chapitre de l’égorgement", "sources": [{"title": "Sahîh al-Bukhârî, 7/266 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3596"}]}, {"name": "Ibn ‘Umar, Ibn ‘Abbâs et Anas ibn Mâlik", "text": "« Si la tête est tranchée, il n’y a pas de mal. »", "reference": "Rapporté par Al-Bukhârî (ta‘lîq), chapitre de l’égorgement", "sources": [{"title": "Sahîh al-Bukhârî, 7/266 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3596"}]}, {"name": "‘Abdullâh ibn ‘Umar", "text": "Il interdisait de trancher jusqu’à la moelle (an-nakh‘) : « on coupe ce qui est en deçà de l’os, puis on laisse la bête jusqu’à ce qu’elle meure » (rapporté par Nâfi‘).", "reference": "Rapporté par Al-Bukhârî (ta‘lîq), chapitre de l’égorgement", "sources": [{"title": "Sahîh al-Bukhârî, 7/266 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3596"}]}]$j$::jsonb,
 $j$[
  {"scholar": "Ibn Bâz", "position": "Interrogé sur l’abattage avec une machine électrique : « oui, si elle est tranchante ».", "reference": "Fatâwâ ad-Durûs", "sources": [{"title": "ما حكم الذبح بالآلة الكهربائية؟", "organisation": "Site officiel d’Ibn Bâz", "url": "https://binbaz.org.sa/fatwas/24016/%D9%85%D8%A7-%D8%AD%D9%83%D9%85-%D8%A7%D9%84%D8%B0%D8%A8%D8%AD-%D8%A8%D8%A7%D9%84%D8%A7%D9%84%D8%A9-%D8%A7%D9%84%D9%83%D9%87%D8%B1%D8%A8%D8%A7%D9%89%D9%8A%D8%A9"}]},
  {"scholar": "Comité permanent (fatwas signées par Ibn Bâz et/ou Al-Fawzân)", "position": "N° 9677 (Ibn Bâz) : la machine automatique est permise ; une seule invocation suffit, prononcée par celui qui la met en marche, s’il est musulman ou des Gens du Livre. N° 21165 (Al-Fawzân) : la lame doit être tranchante et couper la trachée et l’œsophage ; en abattage à la main, une invocation par bête. N° 20738 (Al-Fawzân et Ibn Bâz) : si la machine égorge lot après lot, une invocation à chaque mise en marche ; la basmala écrite sur la lame ne suffit pas.", "reference": "Fatâwâ al-Lajna ad-Dâ’ima, 1re série, tome 22", "sources": [{"title": "الذبح بالآلة الأوتوماتيكية والتسمية عند تشغيل الماكينة", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17249"}, {"title": "هل يكفي كتابة البسملة على الآلة", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17304"}]},
  {"scholar": "Ibn ‘Uthaymîn", "position": "Une invocation sur une série déterminée suffit (par exemple mille volailles accrochées, « bismillâh » au lancement de la machine). Une seule invocation au début pour toute la journée ne vaut pas ; la basmala écrite au mur sans être prononcée relève de l’ignorance.", "reference": "Liqâ’ al-Bâb al-Maftûh, séance n° 35 (enregistrement)", "sources": [{"title": "Liqâ’ al-Bâb al-Maftûh 35", "organisation": "Enregistrements d’Ibn ‘Uthaymîn", "url": "https://alathar.net/home/esound/index.php?op=codevi&coid=61964"}]},
  {"scholar": "Al-Albânî", "position": "Aucun avis vérifiable trouvé sur la lame mécanique elle-même ; ses réserves sur les chaînes automatiques portent sur l’étourdissement (voir le repère « Étourdissement »).", "reference": "—", "sources": []}
 ]$j$::jsonb,
 'Les savants retenus admettent la machine si sa lame tranche la gorge et que l’invocation est prononcée par un musulman ou un homme du Livre qui la met en marche.',
 'Faible : Ibn ‘Uthaymîn exige explicitement une invocation par série déterminée et rejette l’invocation unique pour toute une journée.',
 'L’abattage manuel n’est pas une condition de validité ; c’est une précaution qui facilite l’invocation sur chaque bête et le contrôle de l’égorgement.',
 '2026-10-03'),

('contamination', 5, 'Contamination et chaîne de production', 'Que dit la règle sur le contact avec le porc et le mélange des viandes ?',
 $j$[{"reference": "Al-Baqara 2:173", "text": "Sens : Il vous a seulement interdit la bête morte, le sang, la viande de porc et ce sur quoi on a invoqué un autre nom qu’Allah."}, {"reference": "Al-An‘âm 6:145", "text": "Sens : […] ou la viande de porc, car c’est une souillure."}]$j$::jsonb,
 $j$[{"reference": "Al-Bukhârî et Muslim 1930 (Abû Tha‘laba al-Khushanî)", "text": "« Ne mangez pas dans leurs récipients, sauf si vous n’en trouvez pas d’autres ; alors lavez-les et mangez-y. »", "sources": [{"title": "Sahîh al-Bukhârî, chapitre des récipients des mazdéens et de la bête morte, 7/256 (éd. Ta’sîl)", "organisation": "Sahîh al-Bukhârî", "url": "https://shamela.ws/book/1284/3586"}]}, {"reference": "Al-Bukhârî 52 et Muslim 1599 (An-Nu‘mân ibn Bashîr)", "text": "« Le licite est clair et l’illicite est clair ; entre les deux se trouvent des choses ambiguës […] Celui qui s’en préserve protège sa religion et son honneur. »", "sources": []}, {"reference": "At-Tirmidhî 2518 (Al-Hasan ibn ‘Alî), authentifié par Al-Albânî", "text": "« Laisse ce qui te fait douter pour ce qui ne te fait pas douter. »", "sources": [{"title": "Jâmi‘ at-Tirmidhî, livre de la description du Jour dernier", "organisation": "Jâmi‘ at-Tirmidhî (bibliothèque Islamweb)", "url": "https://www.islamweb.net/ar/library/content/2/2442/"}]}]$j$::jsonb,
 '[]'::jsonb,
 $j$[
  {"scholar": "Comité permanent (fatwa signée par Ibn Bâz)", "position": "Fatwa n° 5442 : les ustensiles ayant servi au porc ou au vin ne s’utilisent qu’après avoir été lavés. Fatwa n° 2340 : des viandes d’abattages valides et non valides mêlées sans distinction sont toutes interdites.", "reference": "Fatâwâ al-Lajna ad-Dâ’ima, 1re série, tome 22", "sources": [{"title": "الأكل في مطاعم الكفار وأوانيهم تتلوث بلحوم الخنازير", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17237"}, {"title": "ذبائح البلاد التي اختلط فيها المسلمون والنصارى والوثنيون", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17233"}]},
  {"scholar": "Comité permanent (fatwa signée par Al-Fawzân)", "position": "Fatwa n° 21341 : la nourriture préparée par des non-musulmans est permise, sauf si l’on sait qu’elle contient du porc ou un de ses dérivés, ou une viande non abattue selon la règle.", "reference": "Fatâwâ al-Lajna ad-Dâ’ima, 1re série, tome 22", "sources": [{"title": "حكم اكل الميتة ولحم الخنزير", "organisation": "Fatâwâ al-Lajna ad-Dâ’ima", "url": "https://shamela.ws/book/8381/17235"}]},
  {"scholar": "Ibn ‘Uthaymîn", "position": "Les récipients des non-musulmans se lavent avant usage, même s’ils sont purs, afin de s’en distinguer.", "reference": "Majmû‘ Fatâwâ wa Rasâ’il 15/441 (question 1181)", "sources": [{"title": "Majmû‘ Fatâwâ wa Rasâ’il 15/441", "organisation": "Ibn ‘Uthaymîn", "url": "https://shamela.ws/book/12293/5960"}]},
  {"scholar": "Al-Albânî", "position": "Conserves de viande, beurre, fromage produits en Occident : si l’on sait qu’ils sont licites, on en mange ; si l’on sait qu’ils contiennent des graisses interdites, non ; si l’on ne sait pas, on s’abstient (« laisse ce qui te fait douter »).", "reference": "Sharh al-Adab al-Mufrad, cassette 19", "sources": [{"title": "أمثلة عن أمور مشتبهات", "organisation": "Enregistrements d’Al-Albânî (transcription)", "url": "https://www.al-albany.com/audios/content/152181/"}]}
 ]$j$::jsonb,
 'Le porc et ses dérivés sont interdits ; un ustensile souillé se lave avant usage ; des viandes valides et non valides mêlées sans distinction sont toutes interdites.',
 'Aucune fatwa des savants retenus n’a été trouvée sur une chaîne industrielle partagée entre halal et non-halal : OUMMAH n’en tire aucune conclusion.',
 'Refuser les sites qui manipulent du porc, contrôler les ingrédients et assurer la traçabilité sont des précautions contre le mélange et la contamination ; leur absence n’est pas, à elle seule, une preuve de contamination.',
 '2026-10-03')
on conflict (id) do update set sort_order = excluded.sort_order, title = excluded.title, question = excluded.question, quran = excluded.quran, sunnah = excluded.sunnah, companions = excluded.companions, scholars = excluded.scholars, agreement = excluded.agreement, divergence = excluded.divergence, reading = excluded.reading, last_verified_at = excluded.last_verified_at, updated_at = now();
