-- OUMMAH Boycott — scanner réactif + cache produits scannés + extension catalogue.
-- Périmètre strict : module Boycott uniquement.
-- boycott_scanned_products est un cache d'identification/scan ; boycott_entities reste la source canonique du statut rouge.

create table if not exists public.boycott_scanned_products (
  barcode text primary key,
  product_name text,
  brand text,
  image_url text,
  last_result text not null default 'unknown',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  scan_count bigint not null default 1,
  constraint boycott_scanned_products_barcode_valid check (barcode ~ '^[0-9]{8,14}$'),
  constraint boycott_scanned_products_result_allowed check (last_result in ('boycott','ok','unknown'))
);

alter table public.boycott_scanned_products enable row level security;

drop policy if exists "boycott scanned products public read" on public.boycott_scanned_products;
create policy "boycott scanned products public read"
on public.boycott_scanned_products
for select
to anon, authenticated
using (true);

create or replace function public.record_boycott_scanned_product(
  p_barcode text,
  p_product_name text default null,
  p_brand text default null,
  p_image_url text default null,
  p_last_result text default 'unknown'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_barcode is null or p_barcode !~ '^[0-9]{8,14}$' then
    return;
  end if;

  insert into public.boycott_scanned_products
    (barcode, product_name, brand, image_url, last_result, first_seen_at, last_seen_at, scan_count)
  values
    (
      p_barcode,
      nullif(btrim(p_product_name), ''),
      nullif(btrim(p_brand), ''),
      nullif(btrim(p_image_url), ''),
      case when p_last_result in ('boycott','ok','unknown') then p_last_result else 'unknown' end,
      now(),
      now(),
      1
    )
  on conflict (barcode) do update set
    product_name = coalesce(excluded.product_name, boycott_scanned_products.product_name),
    brand = coalesce(excluded.brand, boycott_scanned_products.brand),
    image_url = coalesce(excluded.image_url, boycott_scanned_products.image_url),
    last_result = excluded.last_result,
    last_seen_at = now(),
    scan_count = boycott_scanned_products.scan_count + 1;
end;
$$;

revoke all on function public.record_boycott_scanned_product(text,text,text,text,text) from public;
grant execute on function public.record_boycott_scanned_product(text,text,text,text,text) to anon, authenticated;

insert into public.boycott_entities
  (slug, name, aliases, category, parent_group, summary, evidence_kind, sources, barcode_prefixes, product_barcodes, alternative_ids, last_verified_at, is_active)
values
('nestle', 'Nestlé', ARRAY['Nestle']::text[], 'food', null, 'Nestlé est l’unique actionnaire d’Osem-Nestlé depuis 2016. OUMMAH classe le groupe à boycotter selon sa règle interne fondée sur ce lien économique documenté avec une importante entreprise israélienne.', 'occupation_economy', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('l-oreal-groupe', 'L''Oréal Groupe', ARRAY['L''Oréal','Loreal','L''Oreal']::text[], 'other', null, 'BDS a documenté historiquement les investissements et activités de L’Oréal en Israël. OUMMAH conserve ce lien documenté dans son classement et l’étend aux marques actuelles du groupe en indiquant qu’il s’agit d’un héritage de groupe.', 'occupation_economy', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('restaurant-brands-international', 'Restaurant Brands International', ARRAY['RBI']::text[], 'restaurant', null, 'Restaurant Brands International est la maison mère de Burger King. Burger King figure parmi les campagnes populaires de boycott soutenues par BDS ; OUMMAH applique sa règle d’héritage de groupe.', 'parent_group', '[{"label":"BDS — Burger King parmi les campagnes populaires soutenues","url":"https://www.bdsmovement.net/ar/Guide-to-BDS-Boycott"},{"label":"Restaurant Brands International — marques officielles","url":"https://www.rbi.com/English/brands/default.aspx"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('tim-hortons', 'Tim Hortons', '{}'::text[], 'restaurant', 'Restaurant Brands International', 'Tim Hortons appartient à Restaurant Brands International, également maison mère de Burger King. OUMMAH applique le statut rouge par héritage du groupe ; cela ne signifie pas que Tim Hortons a fourni directement un soutien militaire.', 'parent_group', '[{"label":"BDS — Burger King parmi les campagnes populaires soutenues","url":"https://www.bdsmovement.net/ar/Guide-to-BDS-Boycott"},{"label":"Restaurant Brands International — marques officielles","url":"https://www.rbi.com/English/brands/default.aspx"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('popeyes', 'Popeyes', '{}'::text[], 'restaurant', 'Restaurant Brands International', 'Popeyes appartient à Restaurant Brands International, également maison mère de Burger King. OUMMAH applique le statut rouge par héritage du groupe ; cela ne signifie pas que Popeyes a fourni directement un soutien militaire.', 'parent_group', '[{"label":"BDS — Burger King parmi les campagnes populaires soutenues","url":"https://www.bdsmovement.net/ar/Guide-to-BDS-Boycott"},{"label":"Restaurant Brands International — marques officielles","url":"https://www.rbi.com/English/brands/default.aspx"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('firehouse-subs', 'Firehouse Subs', '{}'::text[], 'restaurant', 'Restaurant Brands International', 'Firehouse Subs appartient à Restaurant Brands International, également maison mère de Burger King. OUMMAH applique le statut rouge par héritage du groupe ; cela ne signifie pas que Firehouse Subs a fourni directement un soutien militaire.', 'parent_group', '[{"label":"BDS — Burger King parmi les campagnes populaires soutenues","url":"https://www.bdsmovement.net/ar/Guide-to-BDS-Boycott"},{"label":"Restaurant Brands International — marques officielles","url":"https://www.rbi.com/English/brands/default.aspx"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('osem', 'Osem', '{}'::text[], 'food', 'Nestlé', 'Osem fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('bamba', 'Bamba', '{}'::text[], 'food', 'Nestlé', 'Bamba fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('bissli', 'Bissli', '{}'::text[], 'food', 'Nestlé', 'Bissli fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('tivall', 'Tivall', '{}'::text[], 'food', 'Nestlé', 'Tivall fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('materna', 'Materna', '{}'::text[], 'food', 'Nestlé', 'Materna fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('tzabar', 'Tzabar', '{}'::text[], 'food', 'Nestlé', 'Tzabar fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('bonjour', 'Bonjour', '{}'::text[], 'food', 'Nestlé', 'Bonjour fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('perfecto', 'Perfecto', '{}'::text[], 'food', 'Nestlé', 'Perfecto fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nescafe', 'Nescafé', '{}'::text[], 'beverage', 'Nestlé', 'Nescafé fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nespresso', 'Nespresso', '{}'::text[], 'beverage', 'Nestlé', 'Nespresso fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('kitkat', 'KitKat', '{}'::text[], 'food', 'Nestlé', 'KitKat fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('smarties', 'Smarties', '{}'::text[], 'food', 'Nestlé', 'Smarties fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('aero', 'Aero', '{}'::text[], 'food', 'Nestlé', 'Aero fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('lion', 'Lion', '{}'::text[], 'food', 'Nestlé', 'Lion fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('quality-street', 'Quality Street', '{}'::text[], 'food', 'Nestlé', 'Quality Street fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('after-eight', 'After Eight', '{}'::text[], 'food', 'Nestlé', 'After Eight fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('milkybar', 'Milkybar', '{}'::text[], 'food', 'Nestlé', 'Milkybar fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nesquik', 'Nesquik', '{}'::text[], 'food', 'Nestlé', 'Nesquik fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('maggi', 'Maggi', '{}'::text[], 'food', 'Nestlé', 'Maggi fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('thomy', 'Thomy', '{}'::text[], 'food', 'Nestlé', 'Thomy fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('garden-gourmet', 'Garden Gourmet', '{}'::text[], 'food', 'Nestlé', 'Garden Gourmet fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('halsans-kok', 'Hälsans Kök', '{}'::text[], 'food', 'Nestlé', 'Hälsans Kök fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('buitoni', 'Buitoni', '{}'::text[], 'food', 'Nestlé', 'Buitoni fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('wagner', 'Wagner', '{}'::text[], 'food', 'Nestlé', 'Wagner fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('stouffer-s', 'Stouffer''s', '{}'::text[], 'food', 'Nestlé', 'Stouffer''s fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('hot-pockets', 'Hot Pockets', '{}'::text[], 'food', 'Nestlé', 'Hot Pockets fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('lean-cuisine', 'Lean Cuisine', '{}'::text[], 'food', 'Nestlé', 'Lean Cuisine fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('digiorno', 'DiGiorno', '{}'::text[], 'food', 'Nestlé', 'DiGiorno fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('toll-house', 'Toll House', '{}'::text[], 'food', 'Nestlé', 'Toll House fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('coffee-mate', 'Coffee mate', '{}'::text[], 'beverage', 'Nestlé', 'Coffee mate fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('carnation', 'Carnation', '{}'::text[], 'food', 'Nestlé', 'Carnation fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('milo', 'Milo', '{}'::text[], 'beverage', 'Nestlé', 'Milo fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('cerelac', 'Cerelac', '{}'::text[], 'food', 'Nestlé', 'Cerelac fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('gerber', 'Gerber', '{}'::text[], 'food', 'Nestlé', 'Gerber fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('sma-nutrition', 'SMA Nutrition', '{}'::text[], 'food', 'Nestlé', 'SMA Nutrition fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nestle-nan', 'Nestlé NAN', '{}'::text[], 'food', 'Nestlé', 'Nestlé NAN fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nestle-fitness', 'Nestlé Fitness', '{}'::text[], 'food', 'Nestlé', 'Nestlé Fitness fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('chocapic', 'Chocapic', '{}'::text[], 'food', 'Nestlé', 'Chocapic fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('cookie-crisp', 'Cookie Crisp', '{}'::text[], 'food', 'Nestlé', 'Cookie Crisp fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('cini-minis', 'Cini Minis', '{}'::text[], 'food', 'Nestlé', 'Cini Minis fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('golden-grahams', 'Golden Grahams', '{}'::text[], 'food', 'Nestlé', 'Golden Grahams fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('cheerios', 'Cheerios', '{}'::text[], 'food', 'Nestlé', 'Cheerios fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('shreddies', 'Shreddies', '{}'::text[], 'food', 'Nestlé', 'Shreddies fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('lion-cereals', 'Lion Cereals', '{}'::text[], 'food', 'Nestlé', 'Lion Cereals fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nesquik-cereal', 'Nesquik Cereal', '{}'::text[], 'food', 'Nestlé', 'Nesquik Cereal fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nestle-dessert', 'Nestlé Dessert', '{}'::text[], 'food', 'Nestlé', 'Nestlé Dessert fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('la-laitiere', 'La Laitière', '{}'::text[], 'food', 'Nestlé', 'La Laitière fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('herta', 'Herta', '{}'::text[], 'food', 'Nestlé', 'Herta fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('mousline', 'Mousline', '{}'::text[], 'food', 'Nestlé', 'Mousline fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('purina', 'Purina', '{}'::text[], 'food', 'Nestlé', 'Purina fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('purina-one', 'Purina ONE', '{}'::text[], 'food', 'Nestlé', 'Purina ONE fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('purina-pro-plan', 'Purina Pro Plan', '{}'::text[], 'food', 'Nestlé', 'Purina Pro Plan fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('friskies', 'Friskies', '{}'::text[], 'food', 'Nestlé', 'Friskies fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('felix', 'Felix', '{}'::text[], 'food', 'Nestlé', 'Felix fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('gourmet', 'Gourmet', '{}'::text[], 'food', 'Nestlé', 'Gourmet fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('fancy-feast', 'Fancy Feast', '{}'::text[], 'food', 'Nestlé', 'Fancy Feast fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('beneful', 'Beneful', '{}'::text[], 'food', 'Nestlé', 'Beneful fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('dog-chow', 'Dog Chow', '{}'::text[], 'food', 'Nestlé', 'Dog Chow fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('cat-chow', 'Cat Chow', '{}'::text[], 'food', 'Nestlé', 'Cat Chow fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('tidy-cats', 'Tidy Cats', '{}'::text[], 'food', 'Nestlé', 'Tidy Cats fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('dentalife', 'Dentalife', '{}'::text[], 'food', 'Nestlé', 'Dentalife fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('beyond-pet-food', 'Beyond Pet Food', '{}'::text[], 'food', 'Nestlé', 'Beyond Pet Food fait partie du portefeuille Nestlé ou d’une activité contrôlée par Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('perrier', 'Perrier', '{}'::text[], 'beverage', 'Nestlé', 'Perrier fait partie du portefeuille Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('s-pellegrino', 'S.Pellegrino', '{}'::text[], 'beverage', 'Nestlé', 'S.Pellegrino fait partie du portefeuille Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('acqua-panna', 'Acqua Panna', '{}'::text[], 'beverage', 'Nestlé', 'Acqua Panna fait partie du portefeuille Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('vittel', 'Vittel', '{}'::text[], 'beverage', 'Nestlé', 'Vittel fait partie du portefeuille Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('contrex', 'Contrex', '{}'::text[], 'beverage', 'Nestlé', 'Contrex fait partie du portefeuille Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('hepar', 'Hépar', '{}'::text[], 'beverage', 'Nestlé', 'Hépar fait partie du portefeuille Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nestea', 'Nestea', '{}'::text[], 'beverage', 'Nestlé', 'Nestea fait partie du portefeuille Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nescafe-dolce-gusto', 'Nescafé Dolce Gusto', '{}'::text[], 'beverage', 'Nestlé', 'Nescafé Dolce Gusto fait partie du portefeuille Nestlé. OUMMAH applique le statut rouge par héritage du groupe en raison du lien documenté Nestlé–Osem-Nestlé ; cela ne constitue pas une affirmation de financement militaire direct par cette marque.', 'parent_group', '[{"label":"Osem-Nestlé — historique et propriété","url":"https://www.osem-nestle.co.il/history"},{"label":"Nestlé — portefeuille officiel de marques","url":"https://www.nestle.com/brands"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('l-oreal-paris', 'L''Oréal Paris', '{}'::text[], 'other', 'L''Oréal Groupe', 'L''Oréal Paris appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('garnier', 'Garnier', '{}'::text[], 'other', 'L''Oréal Groupe', 'Garnier appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('maybelline-new-york', 'Maybelline New York', '{}'::text[], 'other', 'L''Oréal Groupe', 'Maybelline New York appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('nyx-professional-makeup', 'NYX Professional Makeup', '{}'::text[], 'other', 'L''Oréal Groupe', 'NYX Professional Makeup appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('essie', 'Essie', '{}'::text[], 'other', 'L''Oréal Groupe', 'Essie appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('mixa', 'Mixa', '{}'::text[], 'other', 'L''Oréal Groupe', 'Mixa appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('3ce', '3CE', '{}'::text[], 'other', 'L''Oréal Groupe', '3CE appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('lancome', 'Lancôme', '{}'::text[], 'other', 'L''Oréal Groupe', 'Lancôme appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('yves-saint-laurent-beaute', 'Yves Saint Laurent Beauté', '{}'::text[], 'other', 'L''Oréal Groupe', 'Yves Saint Laurent Beauté appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('giorgio-armani-beauty', 'Giorgio Armani Beauty', '{}'::text[], 'other', 'L''Oréal Groupe', 'Giorgio Armani Beauty appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('kiehl-s', 'Kiehl''s', '{}'::text[], 'other', 'L''Oréal Groupe', 'Kiehl''s appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('biotherm', 'Biotherm', '{}'::text[], 'other', 'L''Oréal Groupe', 'Biotherm appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('helena-rubinstein', 'Helena Rubinstein', '{}'::text[], 'other', 'L''Oréal Groupe', 'Helena Rubinstein appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('mugler', 'Mugler', '{}'::text[], 'other', 'L''Oréal Groupe', 'Mugler appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('azzaro', 'Azzaro', '{}'::text[], 'other', 'L''Oréal Groupe', 'Azzaro appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('valentino-beauty', 'Valentino Beauty', '{}'::text[], 'other', 'L''Oréal Groupe', 'Valentino Beauty appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('prada-beauty', 'Prada Beauty', '{}'::text[], 'other', 'L''Oréal Groupe', 'Prada Beauty appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('ralph-lauren-fragrances', 'Ralph Lauren Fragrances', '{}'::text[], 'other', 'L''Oréal Groupe', 'Ralph Lauren Fragrances appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('viktor-rolf', 'Viktor&Rolf', '{}'::text[], 'other', 'L''Oréal Groupe', 'Viktor&Rolf appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('maison-margiela-fragrances', 'Maison Margiela Fragrances', '{}'::text[], 'other', 'L''Oréal Groupe', 'Maison Margiela Fragrances appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('youth-to-the-people', 'Youth To The People', '{}'::text[], 'other', 'L''Oréal Groupe', 'Youth To The People appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('takami', 'Takami', '{}'::text[], 'other', 'L''Oréal Groupe', 'Takami appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('shu-uemura', 'Shu Uemura', '{}'::text[], 'other', 'L''Oréal Groupe', 'Shu Uemura appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('l-oreal-professionnel', 'L''Oréal Professionnel', '{}'::text[], 'other', 'L''Oréal Groupe', 'L''Oréal Professionnel appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('kerastase', 'Kérastase', '{}'::text[], 'other', 'L''Oréal Groupe', 'Kérastase appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('redken', 'Redken', '{}'::text[], 'other', 'L''Oréal Groupe', 'Redken appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('matrix', 'Matrix', '{}'::text[], 'other', 'L''Oréal Groupe', 'Matrix appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('biolage', 'Biolage', '{}'::text[], 'other', 'L''Oréal Groupe', 'Biolage appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('pureology', 'Pureology', '{}'::text[], 'other', 'L''Oréal Groupe', 'Pureology appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('mizani', 'Mizani', '{}'::text[], 'other', 'L''Oréal Groupe', 'Mizani appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('pulp-riot', 'Pulp Riot', '{}'::text[], 'other', 'L''Oréal Groupe', 'Pulp Riot appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('shu-uemura-art-of-hair', 'Shu Uemura Art of Hair', '{}'::text[], 'other', 'L''Oréal Groupe', 'Shu Uemura Art of Hair appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('color-wow', 'Color Wow', '{}'::text[], 'other', 'L''Oréal Groupe', 'Color Wow appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('cerave', 'CeraVe', '{}'::text[], 'other', 'L''Oréal Groupe', 'CeraVe appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('la-roche-posay', 'La Roche-Posay', '{}'::text[], 'other', 'L''Oréal Groupe', 'La Roche-Posay appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('vichy', 'Vichy', '{}'::text[], 'other', 'L''Oréal Groupe', 'Vichy appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('skinceuticals', 'SkinCeuticals', '{}'::text[], 'other', 'L''Oréal Groupe', 'SkinCeuticals appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('skinbetter-science', 'Skinbetter Science', '{}'::text[], 'other', 'L''Oréal Groupe', 'Skinbetter Science appartient au portefeuille L’Oréal Groupe. OUMMAH applique le statut rouge par héritage du groupe à partir d’un lien historique documenté par BDS ; la fiche ne prétend pas que cette marque finance directement l’armée israélienne.', 'parent_group', '[{"label":"BDS — appel au boycott de L’Oréal (historique documenté)","url":"https://www.bdsmovement.net/news/l%25E2%2580%2599oreal-makeup-israeli-apartheid-0"},{"label":"L’Oréal Groupe — portefeuille officiel","url":"https://www.loreal.com/en/our-global-brands-portfolio/"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('israel-aerospace-industries', 'Israel Aerospace Industries', '{}'::text[], 'other', null, 'Israel Aerospace Industries est rattachée à une entreprise ou un secteur explicitement cité dans les priorités actuelles de BDS. OUMMAH l’inclut en rouge selon sa politique interne de liens documentés.', 'occupation_economy', '[{"label":"BDS — priorités de pression / entreprises israéliennes","url":"https://bdsmovement.net/Get-involved-divestment"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('wix-com', 'Wix.com', '{}'::text[], 'technology', null, 'Wix.com est rattachée à une entreprise ou un secteur explicitement cité dans les priorités actuelles de BDS. OUMMAH l’inclut en rouge selon sa politique interne de liens documentés.', 'occupation_economy', '[{"label":"BDS — priorités de pression / entreprises israéliennes","url":"https://bdsmovement.net/Get-involved-divestment"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('paz-oil-company', 'Paz Oil Company', '{}'::text[], 'energy', null, 'Paz Oil Company est rattachée à une entreprise ou un secteur explicitement cité dans les priorités actuelles de BDS. OUMMAH l’inclut en rouge selon sa politique interne de liens documentés.', 'occupation_economy', '[{"label":"BDS — priorités de pression / entreprises israéliennes","url":"https://bdsmovement.net/Get-involved-divestment"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('icl-group', 'ICL Group', '{}'::text[], 'other', null, 'ICL Group est rattachée à une entreprise ou un secteur explicitement cité dans les priorités actuelles de BDS. OUMMAH l’inclut en rouge selon sa politique interne de liens documentés.', 'occupation_economy', '[{"label":"BDS — priorités de pression / entreprises israéliennes","url":"https://bdsmovement.net/Get-involved-divestment"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true),
  ('osem-nestle', 'Osem-Nestlé', '{}'::text[], 'food', null, 'Osem-Nestlé est rattachée à une entreprise ou un secteur explicitement cité dans les priorités actuelles de BDS. OUMMAH l’inclut en rouge selon sa politique interne de liens documentés.', 'occupation_economy', '[{"label":"BDS — priorités de pression / entreprises israéliennes","url":"https://bdsmovement.net/Get-involved-divestment"}]'::jsonb, '{}'::text[], '{}'::text[], '{}'::text[], '2026-09-04T00:00:00Z'::timestamptz, true)
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  category = excluded.category,
  parent_group = excluded.parent_group,
  summary = excluded.summary,
  evidence_kind = excluded.evidence_kind,
  sources = excluded.sources,
  last_verified_at = excluded.last_verified_at,
  is_active = excluded.is_active,
  updated_at = now();
