import { boycottSummary, type BoycottEntity, type BoycottSource } from './domain/BoycottEntity';
import { localizedRecord, translate } from '../../i18n/translate';

export type ControversyCategory = 'israel_palestine' | 'uyghurs' | 'africa' | 'forced_labour' | 'workers_rights' | 'sanctions' | 'environment' | 'boycott_campaign' | 'other';
export type InvolvementType = 'direct_operation' | 'subsidiary' | 'parent_company' | 'investment' | 'supplier_relationship' | 'partnership' | 'public_statement' | 'government_contract' | 'documented_campaign' | 'allegation' | 'legal_finding' | 'sanction';
export type InformationStatus = 'confirmed' | 'documented' | 'disputed' | 'allegation' | 'historical' | 'outdated';
export type ControversySource = BoycottSource & { publisher: string; sourceType: 'official' | 'institutional' | 'ngo' | 'media' | 'campaign' };
export type BrandControversy = { id: string; brandId: string; brandName: string; category: ControversyCategory; title: string; summary: string; involvementType: InvolvementType; status: InformationStatus; severity: 'informational' | 'attention'; sources: ControversySource[]; updatedAt: string };

const involvementLabels: Record<BoycottEntity['evidenceKind'], { category: ControversyCategory; type: InvolvementType }> = { military_supply: { category: 'israel_palestine', type: 'supplier_relationship' }, government_contract: { category: 'other', type: 'government_contract' }, material_support: { category: 'israel_palestine', type: 'partnership' }, parent_group: { category: 'other', type: 'parent_company' }, subsidiary_or_franchise: { category: 'other', type: 'subsidiary' }, occupation_economy: { category: 'israel_palestine', type: 'direct_operation' }, financial_link: { category: 'other', type: 'investment' }, other_documented_link: { category: 'other', type: 'documented_campaign' } };
function sourceType(source: BoycottSource): ControversySource['sourceType'] { const value = `${source.label} ${source.url}`.toLowerCase(); if (source.label.toLowerCase().startsWith('bds') || value.includes('/guide-to-bds-boycott') || value.includes('/get-involved-boycott')) return 'campaign'; if (value.includes('dbio') || value.includes('dontbuyintooccupation')) return 'ngo'; if (value.includes('aspi') || value.includes('sheffield') || value.includes('shu.ac.uk')) return 'ngo'; if (value.includes('reuters')) return 'media'; if (value.includes('.gov') || value.includes('un.org') || value.includes('europa.eu')) return 'institutional'; return 'official'; }
export function getBrandControversyDossier(entity?: BoycottEntity): BrandControversy | null { if (!entity || !entity.sources.length || !entity.summary.trim()) return null; const mapped = involvementLabels[entity.evidenceKind]; const sources = entity.sources.filter((source, index, all) => Boolean(source.url) && all.findIndex((candidate) => candidate.url === source.url) === index).map((source) => ({ ...source, publisher: source.label.split(' — ')[0] ?? source.label, sourceType: sourceType(source) })); if (!sources.length) return null; const campaignOnly = sources.every((source) => source.sourceType === 'campaign'); return { id: `dossier-${entity.id}`, brandId: entity.id, brandName: entity.name, category: campaignOnly ? 'boycott_campaign' : mapped.category, title: campaignOnly ? translate('controversy.campaign') : translate('controversy.dossier'), summary: campaignOnly ? translate('controversy.campaignSummary', { brand: entity.name }) : boycottSummary(entity), involvementType: campaignOnly ? 'documented_campaign' : mapped.type, status: 'documented', severity: 'attention', sources, updatedAt: entity.lastVerifiedAt }; }
export const CONTROVERSY_CATEGORY_LABELS: Record<ControversyCategory, string> = localizedRecord({ israel_palestine: 'controversy.israelPalestine', uyghurs: 'controversy.uyghurs', africa: 'controversy.africa', forced_labour: 'controversy.forcedLabour', workers_rights: 'controversy.workersRights', sanctions: 'controversy.sanctions', environment: 'controversy.environment', boycott_campaign: 'controversy.campaign', other: 'controversy.other' });
export const INVOLVEMENT_LABELS: Record<InvolvementType, string> = localizedRecord({ direct_operation: 'involvement.direct', subsidiary: 'involvement.subsidiary', parent_company: 'involvement.parent', investment: 'involvement.investment', supplier_relationship: 'involvement.supplier', partnership: 'involvement.partnership', public_statement: 'involvement.statement', government_contract: 'involvement.government', documented_campaign: 'involvement.campaign', allegation: 'involvement.allegation', legal_finding: 'involvement.legal', sanction: 'involvement.sanction' });
export const STATUS_LABELS: Record<InformationStatus, string> = localizedRecord({ confirmed: 'infoStatus.confirmed', documented: 'infoStatus.documented', disputed: 'infoStatus.disputed', allegation: 'infoStatus.allegation', historical: 'infoStatus.historical', outdated: 'infoStatus.outdated' });
