export type HalalCertifierNoticeType = 'partnership_ended' | 'recognition_changed' | 'accreditation_scope_changed' | 'certification_expired' | 'warning' | 'dispute' | 'clarification' | 'historical_notice' | 'official_information' | 'methodology' | 'recognition' | 'non_recognition' | 'historical_information' | 'organisation_statement';
export type HalalCertifierNoticeStatus = 'active' | 'historical' | 'resolved' | 'disputed' | 'documented' | 'contested';
export type HalalCertifierSource = { title: string; organisation: string; publishedAt?: string; url: string };
export type HalalCertifierNotice = { id: string; certifierId?: string; type: HalalCertifierNoticeType; title: string; summary: string; scope?: string; status: HalalCertifierNoticeStatus; issuedBy: string; publishedAt?: string; validFrom?: string; validUntil?: string; sourceUrl: string; sources?: HalalCertifierSource[] };
export type HalalCertifier = { id: string; name: string; aliases: string[]; country: string; website?: string; description?: string; verificationStatus: 'identified' | 'documented' | 'insufficient_data'; notices: HalalCertifierNotice[]; sources: HalalCertifierSource[]; lastVerifiedAt: string };

const VERIFIED_AT = '2026-09-15';
const SFCVH_SOURCE = 'https://www.grandemosqueedeparis.fr/post/communiqu%C3%A9-certification-de-lic%C3%A9it%C3%A9-halal-rupture-du-partenariat-avec-la-soci%C3%A9t%C3%A9-sfcvh';
const CERTIFIERS: HalalCertifier[] = [
  { id: 'avs', name: 'AVS', aliases: ['A Votre Service', 'Association À Votre Service'], country: 'France', website: 'https://www.halal-avs.com', verificationStatus: 'identified', notices: [], sources: [], lastVerifiedAt: VERIFIED_AT },
  { id: 'argml', name: 'ARGML', aliases: ['Association Rituelle de la Grande Mosquée de Lyon', 'Grande Mosquée de Lyon'], country: 'France', website: 'https://argml.com', description: 'Association rituelle de la Grande Mosquée de Lyon, qui présente sur son site ses activités de contrôle et de certification halal.', verificationStatus: 'documented', notices: [{ id: 'argml-methodology', type: 'methodology', title: 'Méthode de contrôle présentée par l’organisme', summary: 'L’ARGML indique que ses contrôleurs interviennent aux différentes étapes de la chaîne de production et de distribution selon ses procédures de certification.', status: 'documented', issuedBy: 'ARGML', sourceUrl: 'https://argml.com/' }], sources: [{ title: 'ARGML — Organisme de certification halal', organisation: 'ARGML', url: 'https://argml.com/' }, { title: 'The ARGML — Halal certification body of reference', organisation: 'ARGML', url: 'https://argml.com/en/the-argml/' }], lastVerifiedAt: VERIFIED_AT },
  { id: 'achahada', name: 'Achahada', aliases: ['ACHAHADA'], country: 'France', verificationStatus: 'identified', notices: [], sources: [], lastVerifiedAt: VERIFIED_AT },
  { id: 'halal-services', name: 'Halal Services', aliases: ['Halal Service', 'Halal Services France'], country: 'France', verificationStatus: 'identified', notices: [], sources: [], lastVerifiedAt: VERIFIED_AT },
  { id: 'sfcvh', name: 'SFCVH', aliases: ['Société Française de Contrôle de Viande Halal'], country: 'France', website: 'https://www.sfcvh.com', verificationStatus: 'documented', notices: [{ id: 'sfcvh-gmp-partnership-ended', type: 'partnership_ended', title: 'Fin du partenariat avec la Grande Mosquée de Paris', summary: 'La Grande Mosquée de Paris indique que son partenariat avec la SFCVH a pris fin le 1er juin 2022 et que l’ancien logo commun est devenu caduc. Cette notice concerne cette relation historique et ne qualifie pas l’organisme dans son ensemble.', scope: 'Certification commune Grande Mosquée de Paris / SFCVH', status: 'historical', issuedBy: 'Grande Mosquée de Paris', publishedAt: '2022-06-15', validUntil: '2022-06-01', sourceUrl: SFCVH_SOURCE, sources: [{ title: 'Communiqué — rupture du partenariat avec la SFCVH', organisation: 'Grande Mosquée de Paris', publishedAt: '2022-06-15', url: SFCVH_SOURCE }] }], sources: [], lastVerifiedAt: VERIFIED_AT },
  { id: 'hqc-france', name: 'HQC France', aliases: ['HQC', 'Halal Quality Control France'], country: 'France', website: 'https://www.hqceurope.com/hqc-france', verificationStatus: 'documented', notices: [{ id: 'hqc-scope-clarification-2026', type: 'accreditation_scope_changed', title: 'Clarification sur la portée des accréditations', summary: 'Une formulation publique concernant la portée des accréditations a été corrigée. Les accréditations peuvent dépendre du pays, du bureau et du périmètre concerné ; la certification du produit doit être vérifiée dans son contexte.', scope: 'Pays, bureau et périmètre d’accréditation', status: 'active', issuedBy: 'Documentation publique KFC France / HQC Europe', publishedAt: '2026-08-27', sourceUrl: 'https://www.kfc.fr/faq-kfc', sources: [{ title: 'FAQ KFC France', organisation: 'KFC France', url: 'https://www.kfc.fr/faq-kfc' }, { title: 'HQC Europe France', organisation: 'HQC Europe', url: 'https://www.hqceurope.com/hqc-france' }] }], sources: [{ title: 'HQC Europe France', organisation: 'HQC Europe', url: 'https://www.hqceurope.com/hqc-france' }], lastVerifiedAt: VERIFIED_AT },
];

function normalize(value: string) { return value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase().trim(); }
export function getHalalCertifier(name?: string): HalalCertifier | null { if (!name) return null; const normalized = normalize(name); return CERTIFIERS.find((certifier) => [certifier.name, ...certifier.aliases].some((value) => normalized.includes(normalize(value)))) ?? null; }
export function getActiveHalalCertifierNotices(certifier?: HalalCertifier | null) { return certifier?.notices.filter((notice) => notice.status === 'active' || notice.status === 'disputed') ?? []; }
export function getHalalCertifierNoticeTypeLabel(type: HalalCertifierNoticeType) { const labels: Record<HalalCertifierNoticeType, string> = { partnership_ended: 'Partenariat terminé', recognition_changed: 'Reconnaissance modifiée', accreditation_scope_changed: 'Portée d’accréditation', certification_expired: 'Certification à revérifier', warning: 'Mise en garde publiée', dispute: 'Information contestée', clarification: 'Clarification', historical_notice: 'Notice historique', official_information: 'Information officielle', methodology: 'Méthodologie', recognition: 'Reconnaissance', non_recognition: 'Non-reconnaissance', historical_information: 'Information historique', organisation_statement: 'Déclaration de l’organisme' }; return labels[type]; }
