import { Ionicons } from '@expo/vector-icons';
import { Linking, Modal, Pressable, ScrollView, StyleSheet, Text as NativeText, View } from 'react-native';
import type { ComponentProps, ReactNode } from 'react';
import type { BrandControversy } from '../../features/boycott/brandControversyRepository';
import { CONTROVERSY_CATEGORY_LABELS, INVOLVEMENT_LABELS, STATUS_LABELS } from '../../features/boycott/brandControversyRepository';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';

function repairLegacyText(value: string) { return value.replace(/\u00c3\u00a9/g, '\u00e9').replace(/\u00c3\u00a8/g, '\u00e8').replace(/\u00c3\u00aa/g, '\u00ea').replace(/\u00c3\u0080/g, '\u00c0').replace(/\u00c3\u00a0/g, '\u00e0').replace(/\u00c3\u00a7/g, '\u00e7').replace(/\u00c2\u00a0/g, ' ').replace(/\u00c2/g, '').replace(/\u00e2\u0080\u0099/g, '\u2019').replace(/\u00e2\u0080\u0093/g, '\u2013').replace(/\u00e2\u0080\u00a2/g, '\u2022').replace(/\u00e2\u009c\u0093/g, '\u2713').replace(/\u00e2\u0080\u00a6/g, '\u2026'); }
function Text(props: ComponentProps<typeof NativeText>) { const children: ReactNode = typeof props.children === 'string' ? repairLegacyText(props.children) : props.children; return <NativeText {...props}>{children}</NativeText>; }

export function BrandControversyDetailSheet({ dossier, onClose }: { dossier: BrandControversy | null; onClose: () => void }) {
  if (!dossier) return null;
  return <Modal transparent animationType="slide" visible onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><View style={styles.headerCopy}><Text style={styles.kicker}>DOSSIER DOCUMENTAIRE</Text><Text style={styles.name}>{dossier.brandName}</Text></View><Pressable accessibilityLabel="Fermer le dossier" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.text} /></Pressable></View><ScrollView showsVerticalScrollIndicator={false}><Text style={styles.topic}>{CONTROVERSY_CATEGORY_LABELS[dossier.category]}</Text><Text style={styles.title}>Pourquoi cette marque est mentionnée ?</Text><Text style={styles.body}>{dossier.summary}</Text><Text style={styles.title}>Type d’implication</Text><Text style={styles.body}>{INVOLVEMENT_LABELS[dossier.involvementType]}</Text><Text style={styles.title}>Statut de l’information</Text><Text style={styles.body}>{STATUS_LABELS[dossier.status]}</Text><Text style={styles.title}>Dernière vérification</Text><Text style={styles.body}>{dossier.updatedAt}</Text><Text style={styles.title}>Sources</Text>{dossier.sources.map((source) => <Pressable key={source.url} onPress={() => void Linking.openURL(source.url)} style={styles.source}><Text style={styles.sourceTitle}>{source.publisher}</Text><Text style={styles.body}>{source.label}{source.publishedAt ? ` · ${source.publishedAt}` : ''}</Text><Text style={styles.link}>Ouvrir la source</Text></Pressable>)}</ScrollView></View></View></Modal>;
}

const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(4,3,9,0.78)' }, sheet: { maxHeight: '84%', padding: 22, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: colors.backgroundSecondary, borderTopWidth: 1, borderColor: colors.borderSoft }, header: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, headerCopy: { flex: 1, minWidth: 0 }, kicker: { color: colors.goldLight, fontFamily: typography.sans, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, name: { marginTop: 5, color: colors.text, fontFamily: typography.serifSemibold, fontSize: 23, flexShrink: 1 }, close: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, topic: { alignSelf: 'flex-start', marginTop: 18, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 12, color: colors.goldLight, backgroundColor: colors.surface, fontFamily: typography.sans, fontSize: 12 }, title: { marginTop: 20, color: colors.goldLight, fontFamily: typography.sans, fontSize: 12, fontWeight: '800' }, body: { marginTop: 8, color: colors.textSecondary, fontFamily: typography.sans, fontSize: 13, lineHeight: 19 }, source: { marginTop: 12, padding: 12, borderRadius: 14, backgroundColor: colors.surface }, sourceTitle: { color: colors.text, fontFamily: typography.sans, fontSize: 12, fontWeight: '800', flexShrink: 1 }, link: { marginTop: 6, color: colors.goldLight, fontFamily: typography.sans, fontSize: 11, fontWeight: '800' } });
