import { Ionicons } from '@expo/vector-icons';
import { Linking, Modal, Pressable, ScrollView, StyleSheet, Text as NativeText, View } from 'react-native';
import type { ComponentProps, ReactNode } from 'react';
import type { HalalCertifier } from '../../features/boycott/halalCertifierRepository';
import { getHalalCertifierNoticeTypeLabel } from '../../features/boycott/halalCertifierRepository';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';

function repairLegacyText(value: string) { return value.replace(/\u00c3\u00a9/g, '\u00e9').replace(/\u00c3\u00a8/g, '\u00e8').replace(/\u00c3\u00aa/g, '\u00ea').replace(/\u00c3\u0080/g, '\u00c0').replace(/\u00c3\u00a0/g, '\u00e0').replace(/\u00c3\u00a7/g, '\u00e7').replace(/\u00c2\u00a0/g, ' ').replace(/\u00c2/g, '').replace(/\u00e2\u0080\u0099/g, '\u2019').replace(/\u00e2\u0080\u0093/g, '\u2013').replace(/\u00e2\u0080\u00a2/g, '\u2022').replace(/\u00e2\u009c\u0093/g, '\u2713').replace(/\u00e2\u0080\u00a6/g, '\u2026'); }
function Text(props: ComponentProps<typeof NativeText>) { const children: ReactNode = typeof props.children === 'string' ? repairLegacyText(props.children) : props.children; return <NativeText {...props}>{children}</NativeText>; }

export function HalalCertifierDetailSheet({ certifier, onClose }: { certifier: HalalCertifier | null; onClose: () => void }) {
  if (!certifier) return null;
  const hasDocumentation = certifier.verificationStatus === 'documented';
  return <Modal transparent animationType="slide" visible onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><View style={styles.headerCopy}><Text style={styles.kicker}>CERTIFICATION HALAL</Text><Text style={styles.name}>{certifier.name}</Text></View><Pressable accessibilityLabel="Fermer la fiche du certificateur" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.text} /></Pressable></View><ScrollView showsVerticalScrollIndicator={false}><Text style={styles.status}>✓ Organisme identifié</Text><Text style={styles.documentation}>{hasDocumentation ? '✓ Documentation disponible' : 'Documentation indépendante : non disponible actuellement'}</Text><Text style={styles.title}>Pays</Text><Text style={styles.body}>{certifier.country}</Text>{certifier.description ? <><Text style={styles.title}>À propos</Text><Text style={styles.body}>{certifier.description}</Text></> : null}<Text style={styles.title}>Informations à connaître</Text>{certifier.notices.length ? certifier.notices.map((notice) => <View key={notice.id} style={styles.notice}><Text style={styles.noticeType}>{getHalalCertifierNoticeTypeLabel(notice.type)}</Text><Text style={styles.noticeTitle}>{notice.title}</Text><Text style={styles.body}>{notice.summary}</Text><Text style={styles.meta}>{notice.publishedAt ? `Publié le ${notice.publishedAt} · ` : ''}{notice.issuedBy}</Text><Pressable onPress={() => void Linking.openURL(notice.sourceUrl)}><Text style={styles.link}>Voir la source</Text></Pressable></View>) : <Text style={styles.body}>Aucune notice particulière suffisamment documentée n’est intégrée pour le moment.</Text>}<Text style={styles.title}>Sources</Text>{certifier.sources.length ? certifier.sources.map((source) => <Pressable key={source.url} onPress={() => void Linking.openURL(source.url)} style={styles.source}><Text style={styles.sourceTitle}>{source.organisation} — {source.title}</Text><Text style={styles.link}>Ouvrir la source</Text></Pressable>) : <Text style={styles.body}>Aucune source primaire accessible n’est intégrée pour le moment.</Text>}<Text style={styles.verified}>Vérifié le {certifier.lastVerifiedAt}</Text></ScrollView></View></View></Modal>;
}

const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(4,3,9,0.78)' }, sheet: { maxHeight: '82%', padding: 22, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: colors.backgroundSecondary, borderTopWidth: 1, borderColor: colors.borderSoft }, header: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, headerCopy: { flex: 1, minWidth: 0 }, kicker: { color: colors.goldLight, fontFamily: typography.sans, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, name: { marginTop: 5, color: colors.text, fontFamily: typography.serifSemibold, fontSize: 23, flexShrink: 1 }, close: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, status: { alignSelf: 'flex-start', marginTop: 18, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 12, color: colors.goldLight, backgroundColor: colors.surface, fontFamily: typography.sans, fontSize: 12, fontWeight: '800' }, documentation: { marginTop: 10, color: colors.textSecondary, fontFamily: typography.sans, fontSize: 12, lineHeight: 18 }, title: { marginTop: 20, color: colors.goldLight, fontFamily: typography.sans, fontSize: 12, fontWeight: '800' }, body: { marginTop: 8, color: colors.textSecondary, fontFamily: typography.sans, fontSize: 13, lineHeight: 19 }, notice: { marginTop: 12, padding: 12, borderRadius: 16, backgroundColor: colors.surface }, noticeType: { color: colors.goldLight, fontFamily: typography.sans, fontSize: 11, fontWeight: '800' }, noticeTitle: { marginTop: 6, color: colors.text, fontFamily: typography.sans, fontSize: 13, fontWeight: '800' }, meta: { marginTop: 7, color: colors.textMuted, fontFamily: typography.sans, fontSize: 11, lineHeight: 16 }, link: { marginTop: 8, color: colors.goldLight, fontFamily: typography.sans, fontSize: 12, fontWeight: '800' }, source: { marginTop: 10, padding: 12, borderRadius: 14, backgroundColor: colors.surface }, sourceTitle: { color: colors.text, fontFamily: typography.sans, fontSize: 13, lineHeight: 18, flexShrink: 1 }, verified: { marginTop: 20, marginBottom: 12, color: colors.textMuted, fontFamily: typography.sans, fontSize: 11 } });
